### YamlMime:PowershellCmdlet
summary: |-
  This cmdlet is available only in the Exchange Online PowerShell module version 3.2.0 or later. For more information, see [About the Exchange Online PowerShell module](https://aka.ms/exov3-module).

  Use the Get-DefaultTenantMyAnalyticsFeatureConfig cmdlet to view the availability and status of Viva Insights features for the cloud-based organization: digest email, add-in, dashboard, meeting effectiveness survey, and schedule send suggestions.

  For information about the parameter sets in the Syntax section below, see [Exchange cmdlet syntax](https://learn.microsoft.com/powershell/exchange/exchange-cmdlet-syntax).
module: ExchangePowerShell
notes: ""
links:
- text: Deploy personal insights
  href: https://learn.microsoft.com/viva/insights/personal/setup/deployment-guide
syntaxes:
- Get-DefaultTenantMyAnalyticsFeatureConfig [-ResultSize <Unlimited>] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    Get-DefaultTenantMyAnalyticsFeatureConfig
  description: |-
    This example returns the default opt-in or opt-out information for the various Viva Insights settings.
  summary: ""
parameters:
- type: <xref href="Unlimited" data-throw-if-not-resolved="False" />
  name: ResultSize
  description: |+
    This parameter is reserved for internal Microsoft use.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Exchange Online
  parameterValueGroup: ""
applicable:
- Exchange Online
uid: ExchangePowerShell.Get-DefaultTenantMyAnalyticsFeatureConfig
name: Get-DefaultTenantMyAnalyticsFeatureConfig
description: |-
  This cmdlet requires the .NET Framework 4.7.2 or later.

  To run this cmdlet, you need to be a member of one of the following directory role groups in the destination organization:

  - Global Administrator
  - Exchange Administrator
  - Insights Administrator

  For more information, see [Microsoft Entra built-in roles](https://learn.microsoft.com/entra/identity/role-based-access-control/permissions-reference).
metadata:
  external help file: Microsoft.Exchange.Management.RestApiClient.dll-Help.xml
  Module Name: ExchangeOnlineManagement
  online version: https://learn.microsoft.com/powershell/module/exchange/get-defaulttenantmyanalyticsfeatureconfig
  applicable: Exchange Online
  title: Get-DefaultTenantMyAnalyticsFeatureConfig
  schema: 2.0.0
  author: chrisda
  ms.author: chrisda
  ms.reviewer: ""
