### YamlMime:PowershellCmdlet
summary: |-
  This cmdlet is available only in the cloud-based service.

  Use the Get-RecordReviewNotificationTemplateConfig cmdlet to view the record review notification and reminder settings.

  For information about the parameter sets in the Syntax section below, see [Exchange cmdlet syntax](https://learn.microsoft.com/powershell/exchange/exchange-cmdlet-syntax).
module: ExchangePowerShell
notes: ""
syntaxes:
- Get-RecordReviewNotificationTemplateConfig [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    Get-RecordReviewNotificationTemplateConfig
  description: |-
    This example shows detailed information about the record review notification template configuration.
  summary: ""
applicable:
- Security & Compliance
uid: ExchangePowerShell.Get-RecordReviewNotificationTemplateConfig
name: Get-RecordReviewNotificationTemplateConfig
description: |-
  To use this cmdlet in Security & Compliance PowerShell, you need to be assigned permissions. For more information, see [Permissions in the Microsoft Purview compliance portal](https://learn.microsoft.com/purview/microsoft-365-compliance-center-permissions).
metadata:
  external help file: Microsoft.Exchange.TransportMailflow-Help.xml
  online version: https://learn.microsoft.com/powershell/module/exchange/get-recordreviewnotificationtemplateconfig
  applicable: Security & Compliance
  title: Get-RecordReviewNotificationTemplateConfig
  schema: 2.0.0
  author: chrisda
  ms.author: chrisda
  ms.reviewer: ""
