### YamlMime:PowershellCmdlet
summary: |-
  This cmdlet is available only in Security & Compliance PowerShell. For more information, see [Security & Compliance PowerShell](https://learn.microsoft.com/powershell/exchange/scc-powershell).

  Use the Get-PolicyConfig cmdlet to view the endpoint restrictions that are configured in the organization.

  For information about the parameter sets in the Syntax section below, see [Exchange cmdlet syntax](https://learn.microsoft.com/powershell/exchange/exchange-cmdlet-syntax).
module: ExchangePowerShell
notes: ""
syntaxes:
- Get-PolicyConfig [[-Identity] <OrganizationIdParameter>] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    Get-PolicyConfig
  description: |-
    This example returns the endpoint restrictions that are available in the organization.
  summary: ""
parameters:
- type: <xref href="OrganizationIdParameter" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    You don't need to use this parameter. The only endpoint restrictions object in the organization is named Settings.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: ""
applicable:
- Security & Compliance
uid: ExchangePowerShell.Get-PolicyConfig
name: Get-PolicyConfig
description: |-
  To use this cmdlet in Security & Compliance PowerShell, you need to be assigned permissions. For more information, see [Permissions in the Microsoft Purview compliance portal](https://learn.microsoft.com/purview/microsoft-365-compliance-center-permissions).
metadata:
  external help file: Microsoft.Exchange.TransportMailflow-Help.xml
  online version: https://learn.microsoft.com/powershell/module/exchange/get-policyconfig
  applicable: Security & Compliance
  title: Get-PolicyConfig
  schema: 2.0.0
  author: chrisda
  ms.author: chrisda
  ms.reviewer: ""
