### YamlMime:PowershellCmdlet
summary: |-
  This cmdlet is functional only in the cloud-based service.

  Use the Get-OnlineMeetingConfiguration cmdlet to view status and usage information about Skype Meetings and Skype for Business Online for mailboxes. Skype Meetings automatically includes Skype for Business Online conference join information in Exchange Online meeting invitations.

  For information about the parameter sets in the Syntax section below, see [Exchange cmdlet syntax](https://learn.microsoft.com/powershell/exchange/exchange-cmdlet-syntax).
module: ExchangePowerShell
notes: ""
syntaxes:
- >-
  Get-OnlineMeetingConfiguration [-Identity] <MailboxIdParameter>

   [-DomainController <Fqdn>]

   [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    Get-OnlineMeetingConfiguration -Identity carlam@fourthcoffee.com
  description: |-
    This example gets the Skype Meetings configuration for the specified mailbox.
  summary: ""
parameters:
- type: <xref href="Fqdn" data-throw-if-not-resolved="False" />
  name: DomainController
  description: |+
    This parameter is reserved for internal Microsoft use.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Exchange Server 2016
  - Exchange Server 2019
  parameterValueGroup: ""
- type: <xref href="MailboxIdParameter" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    The Identity parameter specifies the mailbox that you want to view. You can use any value that uniquely identifies the mailbox. For example:

    - Name
    - Alias
    - Distinguished name (DN)
    - Canonical DN
    - Domain\\Username
    - Email address
    - GUID
    - LegacyExchangeDN
    - SamAccountName
    - User ID or user principal name (UPN)

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  applicable:
  - Exchange Server 2016
  - Exchange Server 2019
  - Exchange Online
  parameterValueGroup: ""
applicable:
- Exchange Server 2016
- Exchange Server 2019
- Exchange Online
uid: ExchangePowerShell.Get-OnlineMeetingConfiguration
name: Get-OnlineMeetingConfiguration
description: |-
  Exchange Online maintains a per-user cache of Skype for Business Online meeting information that's updated every 24 hours. The Get-OnlineMeetingConfiguration cmdlet provides the following information about the Skype Meetings configuration and the Skype for Business Online meeting information for the user:

  - IsAutoOnlineMeetingEnabled: Indicates if Skype Meetings is enabled for the mailbox.
  - OnlineMeetingInfo: Skype for Business Online meeting coordinates.
  - LastSyncTime: The last time Exchange Online successfully synchronized meeting coordinates from Skype for Business Online.
  - LastSuccessfulSyncTime: The last time Exchange Online successfully cleaned the cached of used Skype for Business Online meeting coordinates.

  You need to be assigned permissions before you can run this cmdlet. Although this topic lists all parameters for the cmdlet, you may not have access to some parameters if they're not included in the permissions assigned to you. To find the permissions required to run any cmdlet or parameter in your organization, see [Find the permissions required to run any Exchange cmdlet](https://learn.microsoft.com/powershell/exchange/find-exchange-cmdlet-permissions).
metadata:
  external help file: Microsoft.Exchange.CalendarsAndGroups-Help.xml
  online version: https://learn.microsoft.com/powershell/module/exchange/get-onlinemeetingconfiguration
  applicable: Exchange Server 2016, Exchange Server 2019, Exchange Online
  title: Get-OnlineMeetingConfiguration
  schema: 2.0.0
  author: chrisda
  ms.author: chrisda
  ms.reviewer: ""
