### YamlMime:PowershellCmdlet
summary: |-
  This cmdlet is available in on-premises Exchange and in the cloud-based service. Some parameters and settings may be exclusive to one environment or the other.

  Use the Get-PolicyTipConfig cmdlet to view the data loss prevention (DLP) Policy Tips in your organization.

  For information about the parameter sets in the Syntax section below, see [Exchange cmdlet syntax](https://learn.microsoft.com/powershell/exchange/exchange-cmdlet-syntax).
module: ExchangePowerShell
notes: ""
inputs:
- name: <xref href="Input types" data-throw-if-not-resolved="False" />
  description: |-
    To see the input types that this cmdlet accepts, see [Cmdlet Input and Output Types](https://go.microsoft.com/fwlink/p/?linkId=616387). If the Input Type field for a cmdlet is blank, the cmdlet doesn't accept input data.
outputs:
- name: <xref href="Output types" data-throw-if-not-resolved="False" />
  description: |-
    To see the return types, which are also known as output types, that this cmdlet accepts, see [Cmdlet Input and Output Types](https://go.microsoft.com/fwlink/p/?linkId=616387). If the Output Type field is blank, the cmdlet doesn't return data.
syntaxes:
- >-
  Get-PolicyTipConfig [-Action <PolicyTipMessageConfigAction>]

   [-Locale <CultureInfo>]

   [-Original]

   [-DomainController <Fqdn>]

   [<CommonParameters>]
- >-
  Get-PolicyTipConfig [[-Identity] <PolicyTipConfigIdParameter>]

   [-DomainController <Fqdn>]

   [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    Get-PolicyTipConfig -Action NotifyOnly
  description: |-
    This example returns a summary list of the custom Policy Tips in all languages that have the action value NotifyOnly.
  summary: ""
- title: Example 2
  code: |-
    Get-PolicyTipConfig -Original -Locale fr
  description: |-
    This example returns a summary list of all built-in French Policy Tips.
  summary: ""
- title: Example 3
  code: |-
    Get-PolicyTipConfig en\RejectOverride | Format-List
  description: |-
    This example returns details about the custom English Policy Tip for the action value RejectOverride.
  summary: ""
parameters:
- type: <xref href="PolicyTipMessageConfigAction" data-throw-if-not-resolved="False" />
  name: Action
  description: |+
    The Action parameter filters the Policy Tips by action. Valid values for this parameter are:

    - NotifyOnly
    - RejectOverride
    - Reject

    You can't use the value Url with the Action parameter. Instead, use command: Get-PolicyTipConfig Url.

    You can't use the Action parameter with the Identity parameter.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Exchange Server 2013
  - Exchange Server 2016
  - Exchange Server 2019
  - Exchange Online
  parameterValueGroup: ""
- type: <xref href="Fqdn" data-throw-if-not-resolved="False" />
  name: DomainController
  description: |+
    This parameter is available only in on-premises Exchange.

    The DomainController parameter specifies the domain controller that's used by this cmdlet to read data from or write data to Active Directory. You identify the domain controller by its fully qualified domain name (FQDN). For example, dc01.contoso.com.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Exchange Server 2013
  - Exchange Server 2016
  - Exchange Server 2019
  parameterValueGroup: ""
- type: <xref href="PolicyTipConfigIdParameter" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    The Identity parameter specifies the custom Policy Tip you want to view. You can use any value that uniquely identifies the custom Policy Tip. For example:

    - `Locale\Action`: Locale is a supported locale code. For example, en for English or fr for French. For more information about supported locales, see [Supported languages for NDRs](https://learn.microsoft.com/Exchange/mail-flow/non-delivery-reports-and-bounce-messages/ndr-procedures#supported-languages-for-ndrs). Action is one of the following Policy Tip actions: NotifyOnly, RejectOverride or Reject.
    - The value Url
    - GUID
    - Distinguished name (DN)

    You can't use the Identity parameter with the Action, Locale or Original parameters.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  applicable:
  - Exchange Server 2013
  - Exchange Server 2016
  - Exchange Server 2019
  - Exchange Online
  parameterValueGroup: ""
- type: <xref href="CultureInfo" data-throw-if-not-resolved="False" />
  name: Locale
  description: |+
    The Locale parameter specifies a locale-specific version of the Policy Tip.

    Valid values for this parameter are supported locale codes. For example, en for English or fr for French. For more information about supported locales, see [Supported languages for NDRs](https://learn.microsoft.com/Exchange/mail-flow/non-delivery-reports-and-bounce-messages/ndr-procedures#supported-languages-for-ndrs).

    You can't use the Locale parameter with the Identity parameter.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Exchange Server 2013
  - Exchange Server 2016
  - Exchange Server 2019
  - Exchange Online
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Original
  description: |+
    The Original switch specifies whether to include built-in Policy Tips in the results. You don't need to specify a value with this switch.

    You can't use the Original switch with the Identity parameter.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Exchange Server 2013
  - Exchange Server 2016
  - Exchange Server 2019
  - Exchange Online
  parameterValueGroup: ""
applicable:
- Exchange Server 2013
- Exchange Server 2016
- Exchange Server 2019
- Exchange Online
uid: ExchangePowerShell.Get-PolicyTipConfig
name: Get-PolicyTipConfig
description: |-
  You need to be assigned permissions before you can run this cmdlet. Although this topic lists all parameters for the cmdlet, you may not have access to some parameters if they're not included in the permissions assigned to you. To find the permissions required to run any cmdlet or parameter in your organization, see [Find the permissions required to run any Exchange cmdlet](https://learn.microsoft.com/powershell/exchange/find-exchange-cmdlet-permissions).
metadata:
  external help file: Microsoft.Exchange.TransportMailflow-Help.xml
  online version: https://learn.microsoft.com/powershell/module/exchange/get-policytipconfig
  applicable: Exchange Server 2013, Exchange Server 2016, Exchange Server 2019, Exchange Online
  title: Get-PolicyTipConfig
  schema: 2.0.0
  author: chrisda
  ms.author: chrisda
  ms.reviewer: ""
