### YamlMime:PowershellCmdlet
summary: |-
  This cmdlet is available only in the cloud-based service.

  Use the Get-EventsFromEmailConfiguration cmdlet to view the events from email settings on a mailbox. These settings define whether Outlook or Outlook on the web (formerly known as Outlook Web App) automatically discovers events from email messages and adds them to the user's calendar.

  For information about the parameter sets in the Syntax section below, see [Exchange cmdlet syntax](https://learn.microsoft.com/powershell/exchange/exchange-cmdlet-syntax).
module: ExchangePowerShell
notes: ""
syntaxes:
- >-
  Get-EventsFromEmailConfiguration [-Identity] <RecipientIdParameter>

   [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    Get-EventsFromEmailConfiguration -Identity peter@contoso.com
  description: |-
    This example retrieves all events from email settings for peter@contoso.com's mailbox.
  summary: ""
parameters:
- type: <xref href="RecipientIdParameter" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    The Identity parameter specifies the mailbox that you want to view. You identify the mailbox by email address.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  applicable:
  - Exchange Online
  parameterValueGroup: ""
applicable:
- Exchange Online
uid: ExchangePowerShell.Get-EventsFromEmailConfiguration
name: Get-EventsFromEmailConfiguration
description: |-
  **Note**: The following output properties have been deprecated: EventReservationProcessingLevel, FoodEstablishmentReservationProcessingLevel, InvoiceProcessingLevel, and ServiceReservationProcessingLevel.

  You need to be assigned permissions before you can run this cmdlet. Although this topic lists all parameters for the cmdlet, you may not have access to some parameters if they're not included in the permissions assigned to you. To find the permissions required to run any cmdlet or parameter in your organization, see [Find the permissions required to run any Exchange cmdlet](https://learn.microsoft.com/powershell/exchange/find-exchange-cmdlet-permissions).
metadata:
  external help file: Microsoft.Exchange.RolesAndAccess-Help.xml
  online version: https://learn.microsoft.com/powershell/module/exchange/get-eventsfromemailconfiguration
  applicable: Exchange Online
  title: Get-EventsFromEmailConfiguration
  schema: 2.0.0
  author: chrisda
  ms.author: chrisda
  ms.reviewer: ""
