### YamlMime:PowershellCmdlet
summary: |-
  This cmdlet is available only in the cloud-based service.

  Use the Get-ApplicationAccessPolicy cmdlet to view the list of application access policies.

  For information about the parameter sets in the Syntax section below, see [Exchange cmdlet syntax](https://learn.microsoft.com/powershell/exchange/exchange-cmdlet-syntax).
module: ExchangePowerShell
notes: ""
syntaxes:
- >-
  Get-ApplicationAccessPolicy [[-Identity] <ApplicationAccessPolicyIdParameter>]

   [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    Get-ApplicationAccessPolicy | Format-Table -Auto Description,ScopeName,AccessRight
  description: |-
    This example returns a summary list of all application access policies in the organization.
  summary: ""
- title: Example 2
  code: |-
    Get-ApplicationAccessPolicy -Identity "596ade3a-1abe-4c5b-b7d5-a169c4b05d4a\7a774f0c-7a6f-11e0-85ad-07fb4824019b:S-1-5-21-724521725-2336880675-2689004279-1821338;8b6ce428-cca2-459a-ac50-d38bcc932258"
  description: |-
    This example returns detailed information for the specified application access policy.
  summary: ""
parameters:
- type: <xref href="ApplicationAccessPolicyIdParameter" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    The Identity parameter specifies the application access policy that you want to view. To find the Identity value for the policy, run the command Get-ApplicationAccessPolicy | Format-List Identity,Description,ScopeName,AccessRight,AppID.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  applicable:
  - Exchange Online
  - Exchange Online Protection
  parameterValueGroup: ""
applicable:
- Exchange Online
- Exchange Online Protection
uid: ExchangePowerShell.Get-ApplicationAccessPolicy
name: Get-ApplicationAccessPolicy
description: |-
  This feature applies only to apps connecting to the Microsoft Graph API for Outlook resources.

  You need to be assigned permissions before you can run this cmdlet. Although this topic lists all parameters for the cmdlet, you may not have access to some parameters if they're not included in the permissions assigned to you. To find the permissions required to run any cmdlet or parameter in your organization, see [Find the permissions required to run any Exchange cmdlet](https://learn.microsoft.com/powershell/exchange/find-exchange-cmdlet-permissions).
metadata:
  external help file: Microsoft.Exchange.ServerStatus-Help.xml
  online version: https://learn.microsoft.com/powershell/module/exchange/get-applicationaccesspolicy
  applicable: Exchange Online, Exchange Online Protection
  title: Get-ApplicationAccessPolicy
  schema: 2.0.0
  author: chrisda
  ms.author: chrisda
  ms.reviewer: ""
