### YamlMime:PowershellCmdlet
summary: |-
  This cmdlet is available only in on-premises Exchange.

  Use the Get-UMCallRouterSettings cmdlet to view the settings of the Microsoft Exchange Unified Messaging Call Router service. This service exists on Exchange servers that have the Client Access server role installed, and is used by telephony clients to connect to Exchange.

  For information about the parameter sets in the Syntax section below, see [Exchange cmdlet syntax](https://learn.microsoft.com/powershell/exchange/exchange-cmdlet-syntax).
module: ExchangePowerShell
notes: ""
inputs:
- name: <xref href="Input types" data-throw-if-not-resolved="False" />
  description: |-
    To see the input types that this cmdlet accepts, see [Cmdlet Input and Output Types](https://go.microsoft.com/fwlink/p/?linkId=616387). If the Input Type field for a cmdlet is blank, the cmdlet doesn't accept input data.
outputs:
- name: <xref href="Output types" data-throw-if-not-resolved="False" />
  description: |-
    To see the return types, which are also known as output types, that this cmdlet accepts, see [Cmdlet Input and Output Types](https://go.microsoft.com/fwlink/p/?linkId=616387). If the Output Type field is blank, the cmdlet doesn't return data.
syntaxes:
- >-
  Get-UMCallRouterSettings [[-Server] <ServerIdParameter>]

   [-DomainController <Fqdn>]

   [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    Get-UMCallRouterSettings
  description: |-
    This example displays a summary list of the Microsoft Exchange Unified Messaging Call Router service settings on all Exchange servers in the Active Directory forest.
  summary: ""
- title: Example 2
  code: |-
    Get-UMCallRouterSettings -Server EXCH01 | Format-List
  description: |-
    This example displays detailed information for the Microsoft Exchange Unified Messaging Call Router service that's running on the server named EXCH01.
  summary: ""
parameters:
- type: <xref href="Fqdn" data-throw-if-not-resolved="False" />
  name: DomainController
  description: |+
    The DomainController parameter specifies the domain controller that's used by this cmdlet to read data from or write data to Active Directory. You identify the domain controller by its fully qualified domain name (FQDN). For example, dc01.contoso.com.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Exchange Server 2013
  - Exchange Server 2016
  parameterValueGroup: ""
- type: <xref href="ServerIdParameter" data-throw-if-not-resolved="False" />
  name: Server
  description: |+
    The Server parameter specifies the Exchange server where you want to run this command. You can use any value that uniquely identifies the server. For example:

    - Name
    - FQDN
    - Distinguished name (DN)
    - Exchange Legacy DN

    If you don't use this parameter, the command is run on the local server.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  applicable:
  - Exchange Server 2013
  - Exchange Server 2016
  parameterValueGroup: ""
applicable:
- Exchange Server 2013
- Exchange Server 2016
uid: ExchangePowerShell.Get-UMCallRouterSettings
name: Get-UMCallRouterSettings
description: |-
  When the cmdlet is used for a single server, it returns the UM call router properties including MaxCalls, MaxFaxCalls and UMDialPlans. The properties and their values are stored in the Unified Messaging section of the Microsoft Exchange configuration object in Active Directory.

  You need to be assigned permissions before you can run this cmdlet. Although this topic lists all parameters for the cmdlet, you may not have access to some parameters if they're not included in the permissions assigned to you. To find the permissions required to run any cmdlet or parameter in your organization, see [Find the permissions required to run any Exchange cmdlet](https://learn.microsoft.com/powershell/exchange/find-exchange-cmdlet-permissions).
metadata:
  external help file: Microsoft.Exchange.RemoteConnections-Help.xml
  online version: https://learn.microsoft.com/powershell/module/exchange/get-umcallroutersettings
  applicable: Exchange Server 2013, Exchange Server 2016
  title: Get-UMCallRouterSettings
  schema: 2.0.0
  author: chrisda
  ms.author: chrisda
  ms.reviewer: ""
