### YamlMime:PowershellCmdlet
summary: |-
  This cmdlet is available only in the cloud-based service.

  Use the Get-EmailTenantSettings cmdlet to view whether priority account protection is enabled or disabled in your Microsoft Defender for Office 365 organization. For more information about priority accounts, see [Manage and monitor priority accounts](https://learn.microsoft.com/microsoft-365/admin/setup/priority-accounts).

  For information about the parameter sets in the Syntax section below, see [Exchange cmdlet syntax](https://learn.microsoft.com/powershell/exchange/exchange-cmdlet-syntax).
module: ExchangePowerShell
notes: ""
syntaxes:
- Get-EmailTenantSettings [[-Identity] <EmailTenantSettingsIdParameter>] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    Get-EmailTenantSettings | Format-List Identity,EnablePriorityAccountProtection
  description: |-
    This example shows whether priority account protection is enabled or disabled in the organization.
  summary: ""
parameters:
- type: <xref href="EmailTenantSettingsIdParameter" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    The Identity parameter specifies the settings object that you want to view. The only settings object in the organization is named Default.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  applicable:
  - Exchange Online
  parameterValueGroup: ""
applicable:
- Exchange Online
uid: ExchangePowerShell.Get-EmailTenantSettings
name: Get-EmailTenantSettings
description: |-
  You need to be assigned permissions before you can run this cmdlet. Although this topic lists all parameters for the cmdlet, you may not have access to some parameters if they're not included in the permissions assigned to you. To find the permissions required to run any cmdlet or parameter in your organization, see [Find the permissions required to run any Exchange cmdlet](https://learn.microsoft.com/powershell/exchange/find-exchange-cmdlet-permissions).
metadata:
  external help file: Microsoft.Exchange.TransportMailflow-Help.xml
  online version: https://learn.microsoft.com/powershell/module/exchange/get-emailtenantsettings
  applicable: Exchange Online
  title: Get-EmailTenantSettings
  schema: 2.0.0
  author: chrisda
  ms.author: chrisda
  ms.reviewer: ""
