### YamlMime:PowershellCmdlet
summary: |-
  This cmdlet is available only in the cloud-based service.

  Use the Get-OMEConfiguration cmdlet to view Microsoft Purview Message Encryption configurations.

  For information about the parameter sets in the Syntax section below, see [Exchange cmdlet syntax](https://learn.microsoft.com/powershell/exchange/exchange-cmdlet-syntax).
module: ExchangePowerShell
notes: ""
inputs:
- name: <xref href="Input types" data-throw-if-not-resolved="False" />
  description: |-
    To see the input types that this cmdlet accepts, see [Cmdlet Input and Output Types](https://go.microsoft.com/fwlink/p/?linkId=616387). If the Input Type field for a cmdlet is blank, the cmdlet doesn't accept input data.
outputs:
- name: <xref href="Output types" data-throw-if-not-resolved="False" />
  description: |-
    To see the return types, which are also known as output types, that this cmdlet accepts, see [Cmdlet Input and Output Types](https://go.microsoft.com/fwlink/p/?linkId=616387). If the Output Type field is blank, the cmdlet doesn't return data.
syntaxes:
- >-
  Get-OMEConfiguration [[-Identity] <OMEConfigurationIdParameter>]

   [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    Get-OMEConfiguration
  description: |-
    This example returns a summary list of all OME configurations in the organization.
  summary: ""
- title: Example 2
  code: |-
    Get-OMEConfiguration | Format-List
  description: |-
    This example returns detailed information for all OME configurations in the organization.
  summary: ""
parameters:
- type: <xref href="OMEConfigurationIdParameter" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    The Identity parameter specifies the OME configuration that you want to get. The default OME configuration has the Identity value "OME Configuration".

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  applicable:
  - Exchange Online
  - Exchange Online Protection
  parameterValueGroup: ""
applicable:
- Exchange Online
- Exchange Online Protection
uid: ExchangePowerShell.Get-OMEConfiguration
name: Get-OMEConfiguration
description: |-
  You need to be assigned permissions before you can run this cmdlet. Although this topic lists all parameters for the cmdlet, you may not have access to some parameters if they're not included in the permissions assigned to you. To find the permissions required to run any cmdlet or parameter in your organization, see [Find the permissions required to run any Exchange cmdlet](https://learn.microsoft.com/powershell/exchange/find-exchange-cmdlet-permissions).
metadata:
  external help file: Microsoft.Exchange.WebClient-Help.xml
  online version: https://learn.microsoft.com/powershell/module/exchange/get-omeconfiguration
  applicable: Exchange Online, Exchange Online Protection
  title: Get-OMEConfiguration
  schema: 2.0.0
  author: chrisda
  ms.author: chrisda
  ms.reviewer: ""
