### YamlMime:PowershellCmdlet
summary: |-
  This cmdlet is available only in the Exchange Online PowerShell module. For more information, see [About the Exchange Online PowerShell module](https://aka.ms/exov3-module).

  Use the Get-UserBriefingConfig cmdlet to get the current state of the Briefing email flag for the specified user. For more details about configuring the Briefing email, see [Configure Briefing email](https://learn.microsoft.com/Briefing/be-admin).

  For information about the parameter sets in the Syntax section below, see [Exchange cmdlet syntax](https://learn.microsoft.com/powershell/exchange/exchange-cmdlet-syntax).
module: ExchangePowerShell
notes: ""
links:
- text: Configure Briefing email
  href: https://learn.microsoft.com/Briefing/be-admin
syntaxes:
- >-
  Get-UserBriefingConfig -Identity <String>

   [-ResultSize <Unlimited>]
examples:
- title: Example 1
  code: |-
    Get-UserBriefingConfig -Identity lila@contoso.com
  description: |-
    This example returns the Briefing configuration for the user lila@contoso.com.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    The Identity parameter specifies the user that you want to view (for example, lila@contoso.com).

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Exchange Online
  parameterValueGroup: ""
- type: <xref href="Unlimited" data-throw-if-not-resolved="False" />
  name: ResultSize
  description: |+
    This parameter is reserved for internal Microsoft use.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Exchange Online
  parameterValueGroup: ""
applicable:
- Exchange Online
uid: ExchangePowerShell.Get-UserBriefingConfig
name: Get-UserBriefingConfig
description: |-
  This cmdlet requires the .NET Framework 4.7.2 or later. To run this cmdlet, you need to be a member of one of the following directory role groups in the destination organization:

  - Global Administrator
  - Exchange Administrator
  - Insights Administrator

  To learn more about administrator role permissions in Microsoft Entra ID, see [Role template IDs](https://learn.microsoft.com/entra/identity/role-based-access-control/permissions-reference#role-template-ids).
metadata:
  external help file: Microsoft.Exchange.Management.RestApiClient.dll-Help.xml
  Module Name: ExchangeOnlineManagement
  online version: https://learn.microsoft.com/powershell/module/exchange/get-userbriefingconfig
  applicable: Exchange Online
  title: Get-UserBriefingConfig
  schema: 2.0.0
  author: chrisda
  ms.author: chrisda
