### YamlMime:PowershellCmdlet
summary: |-
  This cmdlet is functional only in Security & Compliance PowerShell. For more information, see [Security & Compliance PowerShell](https://learn.microsoft.com/powershell/exchange/scc-powershell).

  Use the Get-AuditConfigurationPolicy cmdlet to view audit configuration policies.

  For information about the parameter sets in the Syntax section below, see [Exchange cmdlet syntax](https://learn.microsoft.com/powershell/exchange/exchange-cmdlet-syntax).
module: ExchangePowerShell
notes: ""
syntaxes:
- >-
  Get-AuditConfigurationPolicy [[-Identity] <PolicyIdParameter>]

   [-DomainController <Fqdn>]

   [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    Get-AuditConfigurationPolicy | Format-List Name,Enabled,Workload,Priority,*Location
  description: |-
    This example lists summary information about all audit configuration policies.
  summary: ""
- title: Example 2
  code: |-
    Get-AuditConfigurationPolicy -Identity 8d4d2060-ee8e-46a8-8d72-24922956fba5
  description: |-
    This examples lists details about the audit configuration policy named 8d4d2060-ee8e-46a8-8d72-24922956fba5.
  summary: ""
parameters:
- type: <xref href="Fqdn" data-throw-if-not-resolved="False" />
  name: DomainController
  description: |+
    This parameter is reserved for internal Microsoft use.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: ""
- type: <xref href="PolicyIdParameter" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    The Identity parameter specifies the audit configuration policy that you want to view. The name of the policy is a GUID value. For example, 8d4d2060-ee8e-46a8-8d72-24922956fba5.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  applicable:
  - Exchange Online
  - Security & Compliance
  parameterValueGroup: ""
applicable:
- Exchange Online
- Security & Compliance
uid: ExchangePowerShell.Get-AuditConfigurationPolicy
name: Get-AuditConfigurationPolicy
description: |-
  To use this cmdlet in Security & Compliance PowerShell, you need to be assigned permissions. For more information, see [Permissions in the Microsoft Purview compliance portal](https://learn.microsoft.com/purview/microsoft-365-compliance-center-permissions).
metadata:
  external help file: Microsoft.Exchange.TransportMailflow-Help.xml
  online version: https://learn.microsoft.com/powershell/module/exchange/get-auditconfigurationpolicy
  applicable: Exchange Online, Security & Compliance
  title: Get-AuditConfigurationPolicy
  schema: 2.0.0
  author: chrisda
  ms.author: chrisda
  ms.reviewer: ""
