### YamlMime:PowershellCmdlet
summary: |-
  This cmdlet is available only in the Exchange Online PowerShell module. For more information, see [About the Exchange Online PowerShell module](https://aka.ms/exov3-module).

  Use the Get-MyAnalyticsFeatureConfig cmdlet to view the availability and feature status of MyAnalytics for the specified user.

  **Note**: This cmdlet replaces the Get-UserAnalyticsConfig cmdlet.

  For information about the parameter sets in the Syntax section below, see [Exchange cmdlet syntax](https://learn.microsoft.com/powershell/exchange/exchange-cmdlet-syntax).
module: ExchangePowerShell
notes: ""
syntaxes:
- >-
  Get-MyAnalyticsFeatureConfig -Identity <String>

   [-ResultSize <unlimited>]

   [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    c:\users\vikram Get-MyAnalyticsFeatureConfig -Identity vikram@contoso.com

    UserId : vikram@contoso.com
    PrivacyMode : opt-in
    IsDashboardEnabled : true
    IsAddInEnabled : true
    IsDigestEmailEnabled : false
  description: |-
    This example and the corresponding output shows the MyAnalytics configuration for the user vikram@contoso.com. MyAnalytics is available to Vikram (the PrivacyMode property value is opt-in). The only feature that's disabled is digest email messages.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    The Identity parameter specifies the user you want to view. You identify the user by their email address.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Exchange Online
  parameterValueGroup: ""
- type: <xref href="Unlimited" data-throw-if-not-resolved="False" />
  name: ResultSize
  description: |+
    This parameter is reserved for internal Microsoft use.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Exchange Online
  parameterValueGroup: ""
applicable:
- Exchange Online
uid: ExchangePowerShell.Get-MyAnalyticsFeatureConfig
name: Get-MyAnalyticsFeatureConfig
description: |-
  This cmdlet requires the .NET Framework 4.7.2 or later. To run this cmdlet, you need to be a member of one of the following directory role groups in the destination organization:

  - Global Administrator
  - Exchange Administrator
  - Insights Administrator

  To learn more about administrator role permissions in Microsoft Entra ID, see [Role template IDs](https://learn.microsoft.com/entra/identity/role-based-access-control/permissions-reference#role-template-ids).
metadata:
  external help file: Microsoft.Exchange.Management.RestApiClient.dll-Help.xml
  Module Name: ExchangeOnlineManagement
  online version: https://learn.microsoft.com/powershell/module/exchange/get-myanalyticsfeatureconfig
  applicable: Exchange Online
  title: Get-MyAnalyticsFeatureConfig
  schema: 2.0.0
  author: chrisda
  ms.author: chrisda
