### YamlMime:PowershellCmdlet
summary: |-
  This cmdlet is available only in Security & Compliance PowerShell. For more information, see [Security & Compliance PowerShell](https://learn.microsoft.com/powershell/exchange/scc-powershell).

  Use the Get-InformationBarrierPoliciesApplicationStatus cmdlet to view the application status of information barrier policies.

  For information about the parameter sets in the Syntax section below, see [Exchange cmdlet syntax](https://learn.microsoft.com/powershell/exchange/exchange-cmdlet-syntax).
module: ExchangePowerShell
notes: ""
links:
- text: Define policies for information barriers
  href: https://learn.microsoft.com/purview/information-barriers-policies
syntaxes:
- >-
  Get-InformationBarrierPoliciesApplicationStatus [-All]

   [<CommonParameters>]
- >-
  Get-InformationBarrierPoliciesApplicationStatus [[-Identity] <PolicyIdParameter>]

   [-All]

   [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    Get-InformationBarrierPoliciesApplicationStatus
  description: |-
    This example returns the most recent application of information barrier policies by the Start-InformationBarrierPoliciesApplication cmdlet.
  summary: ""
- title: Example 2
  code: |-
    Get-InformationBarrierPoliciesApplicationStatus -All
  description: |-
    This example returns all applications of information barrier policies by the Start-InformationBarrierPoliciesApplication cmdlet.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: All
  description: |+
    The All switch specifies whether to include all applications of information barrier policies in the results. You don't need to specify a value with this switch.

    If you don't use this switch, the command only returns the most recent policy application.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: ""
- type: <xref href="PolicyIdParameter" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    The Identity parameter specifies the information barrier policy application that you want to view. This value is a GUID that's displayed when you run the Start-InformationBarrierPoliciesApplication cmdlet (for example, a0551cee-db3d-4002-9fa0-94358035fdf2). You can also find the Identity value by running the command Get-InformationBarrierPoliciesApplicationStatus -All.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: ""
applicable:
- Security & Compliance
uid: ExchangePowerShell.Get-InformationBarrierPoliciesApplicationStatus
name: Get-InformationBarrierPoliciesApplicationStatus
description: |-
  For more information, see [View status of information barrier policy application](https://learn.microsoft.com/purview/information-barriers-policies#view-status-of-user-accounts-segments-policies-or-policy-application).

  To use this cmdlet in Security & Compliance PowerShell, you need to be assigned permissions. For more information, see [Permissions in the Microsoft Purview compliance portal](https://learn.microsoft.com/purview/microsoft-365-compliance-center-permissions).
metadata:
  external help file: Microsoft.Exchange.TransportMailflow-Help.xml
  online version: https://learn.microsoft.com/powershell/module/exchange/get-informationbarrierpoliciesapplicationstatus
  applicable: Security & Compliance
  title: Get-InformationBarrierPoliciesApplicationStatus
  schema: 2.0.0
  author: chrisda
  ms.author: chrisda
  ms.reviewer: ""
