### YamlMime:PowershellCmdlet
summary: |-
  This cmdlet is available only in Security & Compliance PowerShell. For more information, see [Security & Compliance PowerShell](https://learn.microsoft.com/powershell/exchange/scc-powershell).

  Use the New-AuditConfigurationRule cmdlet to create audit configuration rules.

  For information about the parameter sets in the Syntax section below, see [Exchange cmdlet syntax](https://learn.microsoft.com/powershell/exchange/exchange-cmdlet-syntax).
module: ExchangePowerShell
notes: ""
syntaxes:
- >-
  New-AuditConfigurationRule -AuditOperation <MultiValuedProperty> -Workload <Workload>

   [-Confirm]

   [-DomainController <Fqdn>]

   [-WhatIf]

   [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    New-AuditConfigurationRule -Workload SharePoint -AuditOperation Delete
  description: |-
    This example creates a new audit configuration rule for Microsoft SharePoint Online that audits delete operations.
  summary: ""
parameters:
- type: <xref href="MultiValuedProperty" data-throw-if-not-resolved="False" />
  name: AuditOperation
  isRequired: true
  description: |+
    The AuditOperation parameter specifies the operations that are audited by the rule. Valid values are:

    - Administrate
    - CheckIn
    - CheckOut
    - Count
    - CreateUpdate
    - Delete
    - Forward
    - MoveCopy
    - PermissionChange
    - ProfileChange
    - SchemaChange
    - Search
    - SendAsOthers
    - View
    - Workflow

    You can specify multiple values separated by commas.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    The Confirm switch specifies whether to show or hide the confirmation prompt. How this switch affects the cmdlet depends on if the cmdlet requires confirmation before proceeding.

    - Destructive cmdlets (for example, Remove-\* cmdlets) have a built-in pause that forces you to acknowledge the command before proceeding. For these cmdlets, you can skip the confirmation prompt by using this exact syntax: `-Confirm:$false`.
    - Most other cmdlets (for example, New-\* and Set-\* cmdlets) don't have a built-in pause. For these cmdlets, specifying the Confirm switch without a value introduces a pause that forces you acknowledge the command before proceeding.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Security & Compliance
  parameterValueGroup: ""
- type: <xref href="Fqdn" data-throw-if-not-resolved="False" />
  name: DomainController
  description: |+
    This parameter is reserved for internal Microsoft use.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    The WhatIf switch doesn't work in Security & Compliance PowerShell.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Security & Compliance
  parameterValueGroup: ""
- type: <xref href="Workload" data-throw-if-not-resolved="False" />
  name: Workload
  isRequired: true
  description: |+
    The Workload parameter specifies where the audit configuration policy applies. Valid values are:

    - Exchange
    - OneDriveForBusiness
    - SharePoint

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: ""
applicable:
- Security & Compliance
uid: ExchangePowerShell.New-AuditConfigurationRule
name: New-AuditConfigurationRule
description: |-
  To use this cmdlet in Security & Compliance PowerShell, you need to be assigned permissions. For more information, see [Permissions in the Microsoft Purview compliance portal](https://learn.microsoft.com/purview/microsoft-365-compliance-center-permissions).
metadata:
  external help file: Microsoft.Exchange.TransportMailflow-Help.xml
  online version: https://learn.microsoft.com/powershell/module/exchange/new-auditconfigurationrule
  applicable: Security & Compliance
  title: New-AuditConfigurationRule
  schema: 2.0.0
  author: chrisda
  ms.author: chrisda
  ms.reviewer: ""
