### YamlMime:PowershellCmdlet
summary: |-
  This cmdlet is available only in the cloud-based service.

  Use the Set-RecordReviewNotificationTemplateConfig cmdlet to set up the customized record review notification and reminder that's sent when an item requires review.

  For information about the parameter sets in the Syntax section below, see [Exchange cmdlet syntax](https://learn.microsoft.com/powershell/exchange/exchange-cmdlet-syntax).
module: ExchangePowerShell
notes: ""
syntaxes:
- >-
  Set-RecordReviewNotificationTemplateConfig -IsCustomizedNotificationTemplate <Boolean> -IsCustomizedReminderTemplate <Boolean>

   [-CustomizedNotificationDataString <String>]

   [-CustomizedReminderDataString <String>]

   [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    Set-RecordReviewNotificationTemplateConfig -IsCustomizedNotificationTemplate $true -CustomizedNotificationDataString "This is the Contoso notification" -IsCustomizedReminderTemplate $true -CustomizedReminderDataString "This is the Contoso reminder"
  description: |-
    This example configures customized review notification text and review reminder text.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: CustomizedNotificationDataString
  description: |+
    The CustomizedNotificationDataString parameter specifies the customized review notification text to use. If the value contains spaces, enclose the value in quotation marks (").

    The value of this parameter is meaningful only when the value of the IsCustomizedNotificationTemplate parameter is $true.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: CustomizedReminderDataString
  description: |+
    The CustomizedReminderDataString parameter specifies the customized review reminder text to use. If the value contains spaces, enclose the value in quotation marks (").

    The value of this parameter is meaningful only when the value of the IsCustomizedReminderTemplate parameter is $true.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: IsCustomizedNotificationTemplate
  isRequired: true
  description: |+
    The IsCustomizedNotificationTemplate switch specifies whether to use a customized review notification instead of the system default notification. Valid values are:

    - $true: Use a customized review notification. You specify the notification text using the CustomizedNotificationDataString parameter.
    - $false: Use the default system notification. This is the default value.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: IsCustomizedReminderTemplate
  isRequired: true
  description: |+
    The IsCustomizedReminderTemplate switch specifies whether to use a customized review reminder instead of the system default reminder:

    - $true: Use a customized review reminder. You specify the reminder text using the CustomizedReminderDataString parameter.
    - $false: Use the default system reminder. This is the default value.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: ""
applicable:
- Security & Compliance
uid: ExchangePowerShell.Set-RecordReviewNotificationTemplateConfig
name: Set-RecordReviewNotificationTemplateConfig
description: |-
  To use this cmdlet in Security & Compliance PowerShell, you need to be assigned permissions. For more information, see [Permissions in the Microsoft Purview compliance portal](https://learn.microsoft.com/purview/microsoft-365-compliance-center-permissions).
metadata:
  external help file: Microsoft.Exchange.TransportMailflow-Help.xml
  online version: https://learn.microsoft.com/powershell/module/exchange/set-recordreviewnotificationtemplateconfig
  applicable: Security & Compliance
  title: Set-RecordReviewNotificationTemplateConfig
  schema: 2.0.0
  author: chrisda
  ms.author: chrisda
  ms.reviewer: ""
