### YamlMime:PowershellCmdlet
summary: |-
  This cmdlet is available only in the Exchange Online PowerShell module version 3.2.0 or later. For more information, see [About the Exchange Online PowerShell module](https://aka.ms/exov3-module).

  Use the Set-DefaultTenantMyAnalyticsFeatureConfig cmdlet to update the availability and status of Viva Insights features for the cloud-based organization: digest email, add-in, dashboard, meeting effectiveness survey, and schedule send suggestions.

  For information about the parameter sets in the Syntax section below, see [Exchange cmdlet syntax](https://learn.microsoft.com/powershell/exchange/exchange-cmdlet-syntax).
module: ExchangePowerShell
notes: ""
links:
- text: Deploy personal insights
  href: https://learn.microsoft.com/viva/insights/personal/setup/deployment-guide
syntaxes:
- >-
  Set-DefaultTenantMyAnalyticsFeatureConfig

   [-Feature <String>]

   [-IsEnabled <Boolean>]

   [-ResultSize <Unlimited>]

   [-SamplingRate <Double>]

   [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    Set-DefaultTenantMyAnalyticsFeatureConfig -Feature All -IsEnabled $true
  description: |-
    This example enables all available Viva Insights features for the organization: add-in, dashboard, digest email, meeting effectiveness survey, schedule send suggestions.
  summary: ""
- title: Example 2
  code: |-
    Set-DefaultTenantMyAnalyticsFeatureConfig -Feature Add-in -IsEnabled $false
  description: |-
    This example disables Viva Insight add-in feature for the organization.
  summary: ""
- title: Example 3
  code: |-
    Set-DefaultTenantMyAnalyticsFeatureConfig -Feature Meeting-Effectiveness-Survey-Sampling-Rate -SamplingRate 0.2
  description: |-
    This example sets the meeting effectiveness survey sampling rate to 20%.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Feature
  description: |+
    The Feature parameter specifies the Viva Insights feature to enable or disable. Valid values are:

    - Add-in
    - Dashboard
    - Digest-email
    - Meeting-effectiveness-survey
    - Meeting-effectiveness-survey-sampling-rate
    - Schedule-send
    - All (all features)

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Exchange Online
  parameterValueGroup: Dashboard, Add-in, Digest-email, Meeting-effectiveness-survey, Scheduled-send, All
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: IsEnabled
  description: |+
    The IsEnabled parameter enables or disables the Viva Insights feature specified by the Feature parameter. Valid values are:

    - $true: The feature is enabled.
    - $false: The feature is disabled.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Exchange Online
  parameterValueGroup: ""
- type: <xref href="Unlimited" data-throw-if-not-resolved="False" />
  name: ResultSize
  description: |+
    This parameter is reserved for internal Microsoft use.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Exchange Online
  parameterValueGroup: ""
- type: <xref href="Double" data-throw-if-not-resolved="False" />
  name: SamplingRate
  description: |+
    This parameter is available only in version 3.2.0 or later.

    The SamplingRate parameter specifies the meeting effectiveness survey sampling rate. The percentage value is expressed a a decimal (for example, 0.1 indicates 10%). A valid value is from 0.1 to 0.7.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Exchange Online
  parameterValueGroup: ""
applicable:
- Exchange Online
uid: ExchangePowerShell.Set-DefaultTenantMyAnalyticsFeatureConfig
name: Set-DefaultTenantMyAnalyticsFeatureConfig
description: |-
  This cmdlet requires the .NET Framework 4.7.2 or later.

  To run this cmdlet, you need to be a member of one of the following directory role groups in the destination organization:

  - Global Administrator
  - Exchange Administrator
  - Insights Administrator

  For more information, see [Microsoft Entra built-in roles](https://learn.microsoft.com/entra/identity/role-based-access-control/permissions-reference).
metadata:
  external help file: Microsoft.Exchange.Management.RestApiClient.dll-Help.xml
  Module Name: ExchangeOnlineManagement
  online version: https://learn.microsoft.com/powershell/module/exchange/set-defaulttenantmyanalyticsfeatureconfig
  applicable: Exchange Online
  title: Set-DefaultTenantMyAnalyticsFeatureConfig
  schema: 2.0.0
  author: chrisda
  ms.author: chrisda
  ms.reviewer: ""
