### YamlMime:PowershellCmdlet
summary: |-
  This cmdlet is available only in Security & Compliance PowerShell. For more information, see [Security & Compliance PowerShell](https://learn.microsoft.com/powershell/exchange/scc-powershell).

  Use the Set-PolicyConfig cmdlet to modify the endpoint restrictions that are configured in the organization.

  For information about the parameter sets in the Syntax section below, see [Exchange cmdlet syntax](https://learn.microsoft.com/powershell/exchange/exchange-cmdlet-syntax).
module: ExchangePowerShell
notes: ""
syntaxes:
- >-
  Set-PolicyConfig [[-Identity] <OrganizationIdParameter>]

   [-CaseHoldPolicyLimit <Int32>]

   [-ClassificationScheme <ClassificationScheme>]

   [-ComplianceUrl <String>]

   [-Confirm]

   [-DlpAppGroups <PswsHashtable[]>]

   [-DlpAppGroupsPsws <PswsHashtable[]>]

   [-DlpNetworkShareGroups <PswsHashtable>]

   [-DlpPrinterGroups <PswsHashtable>]

   [-DlpRemovableMediaGroups <PswsHashtable>]

   [-DocumentIsUnsupportedSeverity <RuleSeverity>]

   [-EnableAdvancedRuleBuilder <Boolean>]

   [-EnableLabelCoauth <Boolean>]

   [-EnableSpoAipMigration <Boolean>]

   [-EndpointDlpGlobalSettings <PswsHashtable[]>]

   [-EndpointDlpGlobalSettingsPsws <PswsHashtable[]>]

   [-ExtendTeamsDlpPoliciesToSharePointOneDrive <Boolean>]

   [-InformationBarrierMode <InformationBarrierMode>]

   [-InformationBarrierPeopleSearchRestriction <InformationBarrierPeopleSearchRestriction>]

   [-IsDlpSimulationOptedIn <Boolean>]

   [-OnPremisesWorkload <Workload>]

   [-ProcessingLimitExceededSeverity <RuleSeverity>]

   [-PurviewLabelConsent <Boolean>]

   [-ReservedForFutureUse <Boolean>]

   [-RetentionForwardCrawl <Boolean>]

   [-RuleErrorAction <PolicyRuleErrorAction>]

   [-SenderAddressLocation <PolicySenderAddressLocation>]

   [-SiteGroups <PswsHashtable[]>]

   [-SiteGroupsPsws <PswsHashtable[]>]

   [-WhatIf]

   [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    {{ Add example code here }}
  description: |-
    {{ Add example description here }}
  summary: ""
parameters:
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: CaseHoldPolicyLimit
  description: |+
    {{ Fill CaseHoldPolicyLimit Description }}

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: ""
- type: <xref href="ClassificationScheme" data-throw-if-not-resolved="False" />
  name: ClassificationScheme
  description: |+
    {{ Fill ClassificationScheme Description }}

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: Default, V0_AggregatedOnly, V1_DetailedResults
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ComplianceUrl
  description: |+
    {{ Fill ComplianceUrl Description }}

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    The Confirm switch specifies whether to show or hide the confirmation prompt. How this switch affects the cmdlet depends on if the cmdlet requires confirmation before proceeding.

    - Destructive cmdlets (for example, Remove-\* cmdlets) have a built-in pause that forces you to acknowledge the command before proceeding. For these cmdlets, you can skip the confirmation prompt by using this exact syntax: -Confirm:$false.
    - Most other cmdlets (for example, New-\* and Set-\* cmdlets) don't have a built-in pause. For these cmdlets, specifying the Confirm switch without a value introduces a pause that forces you acknowledge the command before proceeding.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Security & Compliance
  parameterValueGroup: ""
- type: <xref href="PswsHashtable" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: DlpAppGroups
  description: |+
    {{ Fill DlpAppGroups Description }}

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: ""
- type: <xref href="PswsHashtable" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: DlpAppGroupsPsws
  description: |+
    {{ Fill DlpAppGroupsPsws Description }}

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: ""
- type: <xref href="PswsHashtable" data-throw-if-not-resolved="False" />
  name: DlpNetworkShareGroups
  description: |+
    {{ Fill DlpNetworkShareGroups Description }}

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: ""
- type: <xref href="PswsHashtable" data-throw-if-not-resolved="False" />
  name: DlpPrinterGroups
  description: |+
    {{ Fill DlpPrinterGroups Description }}

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: ""
- type: <xref href="PswsHashtable" data-throw-if-not-resolved="False" />
  name: DlpRemovableMediaGroups
  description: |+
    {{ Fill DlpRemovableMediaGroups Description }}

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: ""
- type: <xref href="RuleSeverity" data-throw-if-not-resolved="False" />
  name: DocumentIsUnsupportedSeverity
  description: |+
    {{ Fill DocumentIsUnsupportedSeverity Description }}

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: Low, Medium, High, None, Informational, Information
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableAdvancedRuleBuilder
  description: |+
    {{ Fill EnableAdvancedRuleBuilder Description }}

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableLabelCoauth
  description: |+
    The EnableLabelCoauth parameter enables or disables co-authoring support in Office desktop apps for the entire organization. Valid value are:

    - $true: Co-authoring support in Office desktop apps is enabled. When documents are labeled and encrypted by sensitivity labels, multiple users can edit these documents at the same time. Labeling information for unencrypted files is no longer saved in custom properties. Don't enable co-authoring if you use any apps, services, scripts, or tools that read or write labeling metadata to the old location.
    - $false: Co-authoring support in Office desktop apps is disabled.

    Disabling co-authoring support in Office desktop apps in the organization has the following consequences:

    - For apps and services that support the new labeling metadata, they now revert to the original metadata format and location when labels are read or saved.
    - The new metadata format and location for Office documents that was used while the setting was enabled will not be copied to the original format and location. As a result, this labeling information for unencrypted Word, Excel, and PowerPoint files will be lost.
    - Co-authoring and AutoSave no longer work in your organization for labeled and encrypted documents.
    - Sensitivity labels remain enabled for Office files in OneDrive and SharePoint.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableSpoAipMigration
  description: |+
    The EnableSpoAipMigration parameter enables or disables built-in labeling for supported Office files in SharePoint and OneDrive. Valid values are:

    - $true: Users can apply your sensitivity labels in Office for the web. Users will see the Sensitivity button on the ribbon so they can apply labels, and see any applied label name on the status bar.
    - $false: Users can't apply your sensitivity labels in Office for the web.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: ""
- type: <xref href="PswsHashtable" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: EndpointDlpGlobalSettings
  description: |+
    The EndpointDlpGlobalSettings parameter specifies the global endpoints. This parameter uses the following syntax: `@(@{"Setting"="<Setting>"; "Value"="<Value>}",@{"Setting"="<Setting>"; "Value"="<Value>"},...)`.

    The value of `<Setting>` is one of the supported values.

    Example values:

    - `@{"Setting"="PathExclusion"; "Value"="C:\Windows";}`
    - `@{"Setting"="PathExclusion"; "Value"="%AppData%\Mozilla";}`
    - `@{"Setting"="PathExclusion"; "Value"="C:\Users\*\Desktop";}`
    - `@{"Setting"="UnallowedApp"="Notepad ++;"Executable"="notepad++"}`
    - `@{"Setting"="UnallowedApp"="Executable"="cmd"}`
    - `@{"Setting"="UnallowedBrowser"="Chrome";"Executable"="chrome"}`
    - `@{"Setting"="CloudAppRestrictions"="Allow"}`
    - `@{"Setting"="CloudAppRestrictionList"="1.1.2.2"}`
    - `@{"Setting"="CloudAppRestrictionList"="subdomain.com"}`
    - `@{"Setting"="CloudAppRestrictionList"="another.differentdomain.edu"}`
    - `@{"Setting"="ShowEndpointJustificationDropdown"; "True";}`

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: ""
- type: <xref href="PswsHashtable" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: EndpointDlpGlobalSettingsPsws
  description: |+
    {{ Fill EndpointDlpGlobalSettingsPsws Description }}

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: ExtendTeamsDlpPoliciesToSharePointOneDrive
  description: |+
    The ExtendTeamsDlpPoliciesToSharePointOneDrive parameter enables the Teams DLP Policy to automatically extend protection to the content stored in OneDrive shared in 1:1 chats and content stored in SharePoint associated with Teams teams shared through channel chats. Valid values are:

    - $true
    - $false

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: ""
- type: <xref href="OrganizationIdParameter" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    You don't need to use this parameter. The only endpoint restrictions object in the organization is named Settings.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: ""
- type: <xref href="InformationBarrierMode" data-throw-if-not-resolved="False" />
  name: InformationBarrierMode
  description: |+
    The InformationBarrierMode parameter specifies the mode that controls the total number of segments and how many segments a user can be part of. Valid values are:

    - SingleSegment: Users in the organization can have 5000 segments but can only be assigned to one segment.
    - MultiSegment: Users in the organization can have 5000 segments and can be assigned up to 10 segments. For more information, see [Use multi-segment support in information barriers](https://learn.microsoft.com/purview/information-barriers-multi-segment).

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: SingleSegment, MultiSegment
- type: <xref href="InformationBarrierPeopleSearchRestriction" data-throw-if-not-resolved="False" />
  name: InformationBarrierPeopleSearchRestriction
  description: |+
    {{ Fill InformationBarrierPeopleSearchRestriction Description }}

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: Enabled, Disabled
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: IsDlpSimulationOptedIn
  description: |+
    {{ Fill IsDlpSimulationOptedIn Description }}

  defaultValue: "False"
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: ""
- type: <xref href="Workload" data-throw-if-not-resolved="False" />
  name: OnPremisesWorkload
  description: |+
    {{ Fill OnPremisesWorkload Description }}

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: None, Exchange, SharePoint, Intune, OneDriveForBusiness, PublicFolder, SharePointOnPremises, ExchangeOnPremises, AuditAlerting, Skype, ModernGroup, DynamicScope, Teams, UnifiedAuditAzure, EndpointDevices, ThirdPartyApps, OnPremisesScanner
- type: <xref href="RuleSeverity" data-throw-if-not-resolved="False" />
  name: ProcessingLimitExceededSeverity
  description: |+
    {{ Fill ProcessingLimitExceededSeverity Description }}

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: Low, Medium, High, None, Informational, Information
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: PurviewLabelConsent
  description: |+
    {{ Fill PurviewLabelConsent Description }}

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: ReservedForFutureUse
  description: |+
    {{ Fill ReservedForFutureUse Description }}

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: RetentionForwardCrawl
  description: |+
    {{ Fill RetentionForwardCrawl Description }}

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: ""
- type: <xref href="PolicyRuleErrorAction" data-throw-if-not-resolved="False" />
  name: RuleErrorAction
  description: |+
    The RuleErrorAction parameter specifies what to do if an error is encountered during the evaluation of the rule. Valid values are:

    - Ignore
    - RetryThenBlock (This is the default value)

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: Ignore, RetryThenBlock
- type: <xref href="PolicySenderAddressLocation" data-throw-if-not-resolved="False" />
  name: SenderAddressLocation
  description: |+
    The SenderAddressLocation parameter specifies where to look for sender addresses in conditions and exceptions that examine sender email addresses. Valid values are:

    - Header: Only examine senders in the message headers (for example, the From, Sender, or Reply-To fields). This is the default value.
    - Envelope: Only examine senders from the message envelope (the MAIL FROM value that was used in the SMTP transmission, which is typically stored in the Return-Path field).
    - HeaderOrEnvelope: Examine senders in the message header and the message envelope.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: Header, Envelope, HeaderOrEnvelope
- type: <xref href="PswsHashtable" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: SiteGroups
  description: |+
    {{ Fill SiteGroups Description }}

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: ""
- type: <xref href="PswsHashtable" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: SiteGroupsPsws
  description: |+
    {{ Fill SiteGroupsPsws Description }}

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    The WhatIf switch doesn't work in Security & Compliance PowerShell.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Security & Compliance
  parameterValueGroup: ""
applicable:
- Security & Compliance
uid: ExchangePowerShell.Set-PolicyConfig
name: Set-PolicyConfig
description: |-
  To use this cmdlet in Security & Compliance PowerShell, you need to be assigned permissions. For more information, see [Permissions in the Microsoft Purview compliance portal](https://learn.microsoft.com/purview/microsoft-365-compliance-center-permissions).
metadata:
  external help file: Microsoft.Exchange.TransportMailflow-Help.xml
  online version: https://learn.microsoft.com/powershell/module/exchange/set-policyconfig
  applicable: Security & Compliance
  title: Set-PolicyConfig
  schema: 2.0.0
  author: chrisda
  ms.author: chrisda
  ms.reviewer: ""
