### YamlMime:PowershellCmdlet
summary: |-
  This cmdlet is available only in the Exchange Online PowerShell module. For more information, see [About the Exchange Online PowerShell module](https://aka.ms/exov3-module).

  Use the Set-MyAnalyticsFeatureConfig cmdlet to configure the availability and features of MyAnalytics for the specified user.

  **Note**: This cmdlet replaces the Set-UserAnalyticsConfig cmdlet.

  For information about the parameter sets in the Syntax section below, see [Exchange cmdlet syntax](https://learn.microsoft.com/powershell/exchange/exchange-cmdlet-syntax).
module: ExchangePowerShell
notes: ""
syntaxes:
- >-
  Set-MyAnalyticsFeatureConfig -Identity <String>

   [-Feature <String>]

   [-IsEnabled <Boolean>]

   [-PrivacyMode <String>]

   [-ResultSize <Unlimited>]

   [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    Set-MyAnalyticsFeatureConfig -Identity vikram@contoso.com -PrivacyMode opt-in
  description: |-
    This example makes MyAnalytics and all features available to Vikram.
  summary: ""
- title: Example 2
  code: |-
    Set-MyAnalyticsFeatureConfig -Identity swathy@contoso.com -PrivacyMode opt-in -Feature digest-email -IsEnabled $false
  description: |-
    This example makes MyAnalytics available to Swathy, but disables the digest email feature.
  summary: ""
- title: Example 3
  code: |-
    Set-MyAnalyticsFeatureConfig -Identity akshath@contoso.com -Feature digest-email -IsEnabled $false
  description: |-
    This example disables the digest email feature for Akshath.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Feature
  description: |+
    The Feature parameter specifies the MyAnalytics features to enable or disable for the user. Valid values are:

    - all (this is the default value)
    - add-in
    - dashboard
    - digest-email

    To actually enable or disable a feature that's specified by this parameter, use the IsEnabled parameter in the same command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Exchange Online
  parameterValueGroup: dashboard, add-in, digest-email, all
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    The Identity parameter specifies the user you want to view. You identify the user by their email address.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Exchange Online
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: IsEnabled
  description: |+
    The IsEnabled parameter specifies whether to enable or disable the feature that's specified by the Feature parameter. Valid values are:

    - $true: The specified feature is enabled.
    - $false: The specified feature is disabled.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Exchange Online
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: PrivacyMode
  description: |+
    The PrivacyMode parameter specifies whether to enable or disable MyAnalytics for the specified user. Valid values are:

    -opt-in: MyAnalytics is enabled for the user. Use the Feature and IsEnabled parameters to enable or disable specific MyAnalytics features.
    -opt-out: MyAnalytics is disabled for the user.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Exchange Online
  parameterValueGroup: opt-in, opt-out
- type: <xref href="Unlimited" data-throw-if-not-resolved="False" />
  name: ResultSize
  description: |+
    This parameter is reserved for internal Microsoft use.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Exchange Online
  parameterValueGroup: ""
applicable:
- Exchange Online
uid: ExchangePowerShell.Set-MyAnalyticsFeatureConfig
name: Set-MyAnalyticsFeatureConfig
description: |-
  This cmdlet requires the .NET Framework 4.7.2 or later. To run this cmdlet, you need to be a member of one of the following directory role groups in the destination organization:

  - Global Administrator
  - Exchange Administrator
  - Insights Administrator

  To learn more about administrator role permissions in Microsoft Entra ID, see [Role template IDs](https://learn.microsoft.com/entra/identity/role-based-access-control/permissions-reference#role-template-ids).
metadata:
  external help file: Microsoft.Exchange.Management.RestApiClient.dll-Help.xml
  Module Name: ExchangeOnlineManagement
  online version: https://learn.microsoft.com/powershell/module/exchange/set-myanalyticsfeatureconfig
  applicable: Exchange Online
  title: Set-MyAnalyticsFeatureConfig
  schema: 2.0.0
  author: chrisda
  ms.author: chrisda
