### YamlMime:PowershellCmdlet
summary: |-
  This cmdlet is available only in the Exchange Online PowerShell module. For more information, see [About the Exchange Online PowerShell module](https://aka.ms/exov3-module).

  **Note**: This cmdlet is available only in version 2.0.5 or later of the module.

  Use the Set-VivaInsightsSettings cmdlet to control user access to features in Viva Insights. Only users with provisioned Exchange Online mailboxes can access features within the Viva Insights app in Teams.

  For information about the parameter sets in the Syntax section below, see [Exchange cmdlet syntax](https://learn.microsoft.com/powershell/exchange/exchange-cmdlet-syntax).
module: ExchangePowerShell
notes: ""
syntaxes:
- >-
  Set-VivaInsightsSettings -Identity <String> -Enabled <Boolean> -Feature <String>

   [-ResultSize <Unlimited>]

   [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    Set-VivaInsightsSettings -Identity roy@contoso.onmicrosoft.com -Enabled $false -Feature headspace
  description: |-
    This example disables access to all the Headspace features in Microsoft Viva Insights in Microsoft Teams for the specified user.
  summary: ""
parameters:
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: Enabled
  isRequired: true
  description: |+
    The Enabled parameter enables or disables access to specific features of Microsoft Viva Insights in Microsoft Teams for the user. Valid values are:

    - $true: The specified features in Microsoft Viva Insights in Microsoft Teams are enabled for the user.
    - $false: The specified features in Microsoft Viva Insights in Microsoft Teams are disabled for the user.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Exchange Online
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Feature
  isRequired: true
  description: |+
    The Feature parameter specifies the feature of Microsoft Viva Insights in Microsoft Teams for the user. Valid values are:

    - Headspace: Represents all features of Headspace.
    - MeetingEffectivenessSurvey: This value is available only in version 2.0.6-Preview2 of the module as part of a Private Preview.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Exchange Online
  parameterValueGroup: headspace
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    The Identity parameter specifies the user that you want to modify. You identify the user by their User Principal Name (UPN) (for example, roy@contoso.onmicrosoft.com).

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Exchange Online
  parameterValueGroup: ""
- type: <xref href="Unlimited" data-throw-if-not-resolved="False" />
  name: ResultSize
  description: |+
    This parameter is reserved for internal Microsoft use.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Exchange Online
  parameterValueGroup: ""
applicable:
- Exchange Online
uid: ExchangePowerShell.Set-VivaInsightsSettings
name: Set-VivaInsightsSettings
description: |-
  This cmdlet requires the .NET Framework 4.7.2 or later. To run this cmdlet, you need to be a member of one of the following directory role groups in the destination organization:

  - Global Administrator
  - Exchange Administrator
  - Teams Administrator

  To learn more about administrator role permissions in Microsoft Entra ID, see [Role template IDs](https://learn.microsoft.com/entra/identity/role-based-access-control/permissions-reference#role-template-ids).
metadata:
  external help file: Microsoft.Exchange.Management.RestApiClient.dll-Help.xml
  Module Name: ExchangeOnlineManagement
  online version: https://learn.microsoft.com/powershell/module/exchange/set-vivainsightssettings
  applicable: Exchange Online
  title: Set-VivaInsightsSettings
  schema: 2.0.0
  author: chrisda
  ms.author: chrisda
