### YamlMime:PowershellCmdlet
summary: |-
  This cmdlet is available only in the cloud-based service.

  Use the Set-EventsFromEmailConfiguration cmdlet to modify the events from email settings on a mailbox. on Outlook clients and Outlook on the web. These settings define whether Outlook or Outlook on the web (formerly known as Outlook Web App) automatically discovers events from email messages and adds them to the user's calendar.

  For information about the parameter sets in the Syntax section below, see [Exchange cmdlet syntax](https://learn.microsoft.com/powershell/exchange/exchange-cmdlet-syntax).
module: ExchangePowerShell
notes: ""
syntaxes:
- >-
  Set-EventsFromEmailConfiguration [-Identity] <RecipientIdParameter>

   [-CreateEventsFromEmailAsPrivate <Boolean>]

   [-EventReservationProcessingLevel <String>]

   [-FlightReservationProcessingLevel <String>]

   [-FoodEstablishmentReservationProcessingLevel <String>]

   [-InvoiceProcessingLevel <String>]

   [-LodgingReservationProcessingLevel <String>]

   [-ParcelDeliveryProcessingLevel <String>]

   [-RentalCarReservationProcessingLevel <String>]

   [-ServiceReservationProcessingLevel <String>]

   [<CommonParameters>]
- >-
  Set-EventsFromEmailConfiguration [-Identity] <RecipientIdParameter>

   [-ResetSettings]

   [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    Set-EventsFromEmailConfiguration -Identity peter@contoso.com -InvoiceProgressingLevel Disabled
  description: |-
    This example disables the discovery of invoices from messages for the user.
  summary: ""
- title: Example 2
  code: |-
    Set-EventsFromEmailConfiguration -Identity peter@contoso.com -ServiceReservationProcessingLevel Calendar -CreateEventsFromEmailAsPrivate $true
  description: |-
    This example enables the discovery of service reservations, automatically adds them to the user's calendar, and makes these automatically added events private.
  summary: ""
- title: Example 3
  code: |-
    Set-EventsFromEmailConfiguration -Identity peter@contoso.com -ResetSettings
  description: |-
    This example resets Events from Email settings for the user.
  summary: ""
parameters:
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: CreateEventsFromEmailAsPrivate
  description: |+
    The CreateEventsFromEmailAsPrivate parameter specifies whether to create the events discovered from messages as normal or private events. Valid values are:

    - $true: The events are crated as private events. This is the default value.
    - $false: The events are created as normal events.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Exchange Online
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: EventReservationProcessingLevel
  description: |+
    This parameter has been deprecated and is no longer used.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Exchange Online
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: FlightReservationProcessingLevel
  description: |+
    The FlightReservationProcessingLevel parameter specifies whether flight reservations are automatically discovered from messages, and whether these reservations are automatically added to the user's calendar. Valid values are:

    - Disabled: Do not discover flight reservations from messages.
    - Email: Discover flight reservations from messages, but don't automatically add them to the user's calendar.
    - Calendar: Discover flight reservations from messages and automatically add them to the user's calendar. This is the default value.

    Note that these values are case sensitive.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Exchange Online
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: FoodEstablishmentReservationProcessingLevel
  description: |+
    This parameter has been deprecated and is no longer used.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Exchange Online
  parameterValueGroup: ""
- type: <xref href="RecipientIdParameter" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    The Identity parameter specifies the mailbox that you want to modify. You identify the mailbox by email address.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  applicable:
  - Exchange Online
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: InvoiceProcessingLevel
  description: |+
    This parameter has been deprecated and is no longer used.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Exchange Online
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: LodgingReservationProcessingLevel
  description: |+
    The LodgingReservationProcessingLevel parameter specifies whether lodging reservations are automatically discovered from messages, and whether these reservations are automatically added to the user's calendar. Valid values are:

    - Disabled: Do not discover lodging reservations from messages.
    - Email: Discover lodging reservations from messages however do not automatically add these to the user's calendar.
    - Calendar: Discover lodging reservations from messages and automatically add them to the user's calendar. This is the default value.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Exchange Online
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ParcelDeliveryProcessingLevel
  description: |+
    The ParcelDeliveryProcessingLevel parameter specifies whether parcel deliveries are automatically discovered from messages, and whether these reservations are automatically added to the user's calendar. Valid values are:

    - Disabled: Do not discover parcel deliveries from messages.
    - Email: Discover parcel deliveries from messages however do not automatically add these to the user's calendar.
    - Calendar: Discover parcel deliveries from messages and automatically add them to the user's calendar. This is the default value.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Exchange Online
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: RentalCarReservationProcessingLevel
  description: |+
    The RentalCarReservationProcessingLevel parameter specifies whether rental car reservations are automatically discovered from messages, and whether these reservations are automatically added to the user's calendar. Valid values are:

    - Disabled: Do not discover rental car reservations from messages.
    - Email: Discover rental car reservations from messages, but don't automatically add them to the user's calendar.
    - Calendar: Discover rental car reservations from messages and automatically add them to the user's calendar. This is the default value.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Exchange Online
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: ResetSettings
  isRequired: true
  description: |+
    The ResetSettings switch specifies whether to return all of the reservation discovery settings to their default values. You don't need to specify a value with this switch.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Exchange Online
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ServiceReservationProcessingLevel
  description: |+
    This parameter has been deprecated and is no longer used.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Exchange Online
  parameterValueGroup: ""
applicable:
- Exchange Online
uid: ExchangePowerShell.Set-EventsFromEmailConfiguration
name: Set-EventsFromEmailConfiguration
description: |-
  You need to be assigned permissions before you can run this cmdlet. Although this topic lists all parameters for the cmdlet, you may not have access to some parameters if they're not included in the permissions assigned to you. To find the permissions required to run any cmdlet or parameter in your organization, see [Find the permissions required to run any Exchange cmdlet](https://learn.microsoft.com/powershell/exchange/find-exchange-cmdlet-permissions).
metadata:
  external help file: Microsoft.Exchange.RolesAndAccess-Help.xml
  online version: https://learn.microsoft.com/powershell/module/exchange/set-eventsfromemailconfiguration
  applicable: Exchange Online
  title: Set-EventsFromEmailConfiguration
  schema: 2.0.0
  author: chrisda
  ms.author: chrisda
  ms.reviewer: ""
