### YamlMime:PowershellCmdlet
summary: |-
  This cmdlet is available only in the cloud-based service.

  Use the Set-ArcConfig cmdlet to modify the list of trusted Authenticated Received Chain (ARC) sealers that are configured in the cloud-based organization.

  For information about the parameter sets in the Syntax section below, see [Exchange cmdlet syntax](https://learn.microsoft.com/powershell/exchange/exchange-cmdlet-syntax).
module: ExchangePowerShell
notes: ""
syntaxes:
- >-
  Set-ArcConfig [-Identity] <HostedConnectionFilterPolicyIdParameter> -ArcTrustedSealers <String[]>

   [-Confirm]

   [-WhatIf]

   [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    Set-ArcConfig -Identity Default -ArcTrustedSealers fabrikam.com
  description: |-
    This example configures "fabrikam.com" as the only trusted ARC sealer in the organization.
  summary: ""
- title: Example 2
  code: |-
    $DomainsAdd = @(Get-ArcConfig | select -Expand ArcTrustedSealers)

    $DomainsAdd += "cohovineyard.com","tailspintoys.com"

    Set-ArcConfig -Identity Default -ArcTrustedSealers $DomainsAdd
  description: |-
    This example adds the trusted ARC sealers "cohovineyard.com" and "tailspintoys.com" without affecting the other trusted ARC sealer entries.
  summary: ""
- title: Example 3
  code: |-
    $x = @(Get-ArcConfig | select -Expand ArcTrustedSealers)

    $y = $x.Split(",")

    $DomainsRemove = [System.Collections.ArrayList]($y)

    $DomainsRemove

    $DomainsRemove.RemoveAt(6)

    Set-ArcConfig -Identity Default -ArcTrustedSealers $DomainsRemove
  description: |-
    This example modifies the trusted ARC sealers list by removing an existing ARC sealer without affecting other ARC sealers that are already specified.

    The first four commands return the existing list of ARC sealers. The first ARC sealer in the list has the index number 0, the second has the index number 1, and so on. Use the index number to specify the ARC sealer that you want to remove.

    The last two commands remove the seventh ARC sealer that's displayed in the list.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: ArcTrustedSealers
  isRequired: true
  description: |+
    The ArcTrustedSealers parameter specifies the domain name of the ARC sealers that you want to add.

    The domain name must match the domain that's shown in the `d` tag in the **ARC-Seal** and **ARC-Message-Signature** headers in affected email messages (for example, fabrikam.com). You can use Outlook to see these headers.

    To replace the existing list of ARC sealers with the values you specify, use the syntax `Domain1,Domain2,...DomainN`. To preserve existing values, be sure to include the file types that you want to keep along with the new values that you want to add.

    To add or remove file types without affecting the other file type entries, see the Examples section in this topic.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Exchange Online
  - Exchange Online Protection
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    The Confirm switch specifies whether to show or hide the confirmation prompt. How this switch affects the cmdlet depends on if the cmdlet requires confirmation before proceeding.

    - Destructive cmdlets (for example, Remove-\* cmdlets) have a built-in pause that forces you to acknowledge the command before proceeding. For these cmdlets, you can skip the confirmation prompt by using this exact syntax: `-Confirm:$false`.
    - Most other cmdlets (for example, New-\* and Set-\* cmdlets) don't have a built-in pause. For these cmdlets, specifying the Confirm switch without a value introduces a pause that forces you acknowledge the command before proceeding.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Exchange Online
  - Exchange Online Protection
  parameterValueGroup: ""
- type: <xref href="HostedConnectionFilterPolicyIdParameter" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    The Identity parameter specifies the trusted ARC sealers list that you want to modify. Use one of the following values:

    - Default for your own organization.
    - \<TenantID\>\Default for delegated organizations. The \<TenantID\> value is a GUID that's visible in many admin portal URLs in Microsoft 365 (the tid= value). For example, a32d39e2-3702-4ff5-9628-31358774c091.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  applicable:
  - Exchange Online
  - Exchange Online Protection
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    The WhatIf switch simulates the actions of the command. You can use this switch to view the changes that would occur without actually applying those changes. You don't need to specify a value with this switch.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Exchange Online
  - Exchange Online Protection
  parameterValueGroup: ""
applicable:
- Exchange Online
- Exchange Online Protection
uid: ExchangePowerShell.Set-ArcConfig
name: Set-ArcConfig
description: |-
  Services that modify message content in transit before delivery can invalidate DKIM email signatures and affect the authentication of the message. These services can use ARC to provide details of the original authentication before the modifications occurred. Your organization can then trust these details to help authenticate the message.

  You need to be assigned permissions before you can run this cmdlet. Although this topic lists all parameters for the cmdlet, you may not have access to some parameters if they're not included in the permissions assigned to you. To find the permissions required to run any cmdlet or parameter in your organization, see [Find the permissions required to run any Exchange cmdlet](https://learn.microsoft.com/powershell/exchange/find-exchange-cmdlet-permissions).
metadata:
  external help file: Microsoft.Exchange.TransportMailflow-Help.xml
  online version: https://learn.microsoft.com/powershell/module/exchange/set-arcconfig
  applicable: Exchange Online, Exchange Online Protection
  title: Set-ArcConfig
  schema: 2.0.0
  author: chrisda
  ms.author: chrisda
  ms.reviewer: ""
