### YamlMime:PowershellCmdlet
summary: |-
  Displays the Enhanced 9-1-1 (E9-1-1) Location Information service (LIS) configuration in XML format.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Management.Automation.PSCustomObject" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Publish-CsLisConfiguration
  href: Publish-CsLisConfiguration.yml
- text: Unpublish-CsLisConfiguration
  href: Unpublish-CsLisConfiguration.yml
- text: Import-CsLisConfiguration
  href: Import-CsLisConfiguration.yml
- text: Export-CsLisConfiguration
  href: Export-CsLisConfiguration.yml
- text: Test-CsLisConfiguration
  href: Test-CsLisConfiguration.yml
syntaxes:
- Debug-CsLisConfiguration [-Force] [-LocalStore] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Debug-CsLisConfiguration | Format-Table -Wrap
  description: |-
    Running this command will display the entire LIS configuration to the Skype for Business Server Management Shell window in XML format.
    By default, the output of the Debug-CsLisConfiguration cmdlet is displayed on one line, with an ellipsis (...) at the end of the line indicating that there's more than one line of data.
    Therefore, in this example we pipe the output to the Format-Table cmdlet, specifying the Wrap parameter, to display the full output wrapped to fit in the display window.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses any confirmation prompts that would otherwise be displayed before making changes.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: LocalStore
  description: |+
    Allows you to specify a domain controller.
    If no domain controller is specified, the first available will be used.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Debug-CsLisConfiguration
name: Debug-CsLisConfiguration
description: |-
  The LIS configuration for an Enterprise Voice E9-1-1 implementation is stored in compressed format.
  This cmdlet un-compresses the configuration and displays it in XML format.
  This can make it quicker to debug issues with a configuration.

  This cmdlet retrieves the location information from the Central Management store.
  When this information is created, it is stored in the location database; it does not move to the Central Management store until it is published with the Publish-CsLisConfiguration cmdlet.
  If the location information has not been published (or has been un-published with the Unpublish-CsLisConfiguration cmdlet), the Debug-CsLisConfiguration cmdlet will not return anything.

  Who can run this cmdlet: By default, members of the following groups are authorized to run the Debug-CsLisConfiguration cmdlet locally: RTCUniversalServerAdmins.
  To return a list of all the role-based access control (RBAC) roles this cmdlet has been assigned to (including any custom RBAC roles you have created yourself), run the following command from the Windows PowerShell prompt:

  `Get-CsAdminRole | Where-Object {$_.Cmdlets -match "Debug-CsLisConfiguration"}`
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/debug-cslisconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Debug-CsLisConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
