### YamlMime:PowershellCmdlet
summary: |-
  Exports an Enterprise Voice Enhanced 9-1-1 (E9-1-1) configuration to a file in compressed format for backup purposes.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Byte" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  description: |-
    Returns a byte array when the AsBytes parameter is used.
links:
- text: Import-CsLisConfiguration
  href: Import-CsLisConfiguration.yml
- text: Debug-CsLisConfiguration
  href: Debug-CsLisConfiguration.yml
- text: Publish-CsLisConfiguration
  href: Publish-CsLisConfiguration.yml
- text: Unpublish-CsLisConfiguration
  href: Unpublish-CsLisConfiguration.yml
- text: Test-CsLisConfiguration
  href: Test-CsLisConfiguration.yml
syntaxes:
- Export-CsLisConfiguration [-FileName] <String> [<CommonParameters>]
- Export-CsLisConfiguration [-AsBytes] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Export-CsLisConfiguration -FileName C:\E911Config.bak
  description: |-
    This example exports the entire E9-1-1 configuration from the Location Information Server (LIS) to the backup file named E911Config.bak.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    $lisconfig = Export-CsLisConfiguration -AsBytes
  description: |-
    In this example, the LIS configuration is stored as an array of bytes in a variable, $lisconfig.
  summary: ""
- title: '-------------------------- Example 3 --------------------------'
  code: |-
    $lisconfig = Export-CsLisConfiguration -AsBytes

    [System.IO.File]::WriteAllBytes('C:\E911Config.bak', $lisconfig)

    [System.IO.File]::ReadAllBytes('C:\E911Config.bak') | Import-CsLisConfiguration
  description: |-
    Example 3 is a more complete version of Example 2.
    The first line is the same, we call the Export-CsLisConfiguration cmdlet with the AsBytes parameter to store the LIS configuration as an array of bytes in the variable $lisconfig.
    The rest of this example shows how to save that configuration to a file and then import it back into the location configuration database.

    In line 2 we pipe the contents of $lisconfig, which is the byte array representing the LIS configuration, to the full path and file name of the file to which we want to save the configuration.

    Finally, in line 3 we import the configuration back into the location configuration database.
    First we retrieve the contents from the file.
    The contents of the file are then piped to the Import-CsLisConfiguration cmdlet, which imports the saved configuration into the location database.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AsBytes
  description: |+
    Returns the configuration as a byte array.
    The output of the command should be assigned to a variable for later import.
    (If you don't assign the output to a variable, the byte array representing the configuration will scroll down your Lync Server Management Shell window.) You cannot specify both the AsBytes parameter and the FileName parameter; you can use only one or the other for each call to this cmdlet.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: FileName
  isRequired: true
  description: |+
    The path and file name of the file to which you want to save the configuration.
    This cannot be the name of an existing file.

    If you supply a value to the AsBytes parameter, you cannot supply a value to the FileName parameter.
    If you're accessing this cmdlet remotely, you must use AsBytes rather than FileName.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Export-CsLisConfiguration
name: Export-CsLisConfiguration
description: |-
  Implementing E9-1-1 in an organization can, depending on the size of the organization, involve mapping thousands of subnets, ports, switches, and wireless access points (WAPs) to locations.
  An E9-1-1 configuration also includes information about web services provided by the E9-1-1 Network Routing Provider, and about locations and civic addresses and whether or not they've been validated.
  Given the volume of information and settings required to implement E9-1-1, it's recommended that you regularly back up the entire configuration.
  You can use this cmdlet to back up the E9-1-1 configuration to a file, which will save the entire configuration in compressed format.
  To recover the configuration, call the Import-CsLisConfiguration cmdlet.

  This cmdlet creates a new backup file; it will not overwrite an existing file.
  That means the file name that is specified in the call to this cmdlet cannot be the name of an existing file.

  By default, members of the following groups are authorized to run the Export-CsLisConfiguration cmdlet locally: RTCUniversalServerAdmins.
  To return a list of all the role-based access control (RBAC) roles this cmdlet has been assigned to (including any custom RBAC roles you have created yourself), run the following command from the Windows PowerShell prompt:

  `Get-CsAdminRole | Where-Object {$_.Cmdlets -match "Export-CsLisConfiguration"}`
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/export-cslisconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Export-CsLisConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
