### YamlMime:PowershellCmdlet
summary: |-
  Retrieves one or more trunk configurations, which describe the settings for a trunking peer entity such as a public switched telephone network (PSTN) gateway, IP-private branch exchange (PBX), or Session Border Controller (SBC) at the service provider.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Rtc.Management.WritableConfig.Settings.TrunkConfiguration.TrunkConfiguration" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-CsTrunkConfiguration
  href: New-CsTrunkConfiguration.yml
- text: Remove-CsTrunkConfiguration
  href: Remove-CsTrunkConfiguration.yml
- text: Set-CsTrunkConfiguration
  href: Set-CsTrunkConfiguration.yml
- text: Test-CsTrunkConfiguration
  href: Test-CsTrunkConfiguration.yml
syntaxes:
- Get-CsTrunkConfiguration [[-Identity] <XdsIdentity>] [-LocalStore] [<CommonParameters>]
- Get-CsTrunkConfiguration [-Filter <String>] [-LocalStore] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Get-CsTrunkConfiguration
  description: |-
    This example retrieves all trunk configurations for the Skype for Business Server deployment.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Get-CsTrunkConfiguration -Identity site:Redmond
  description: |-
    This example retrieves the trunk configuration with the Identity site:Redmond.
    Because identities are unique, this command will return at most one object.
  summary: ""
- title: '-------------------------- Example 3 --------------------------'
  code: |-
    Get-CsTrunkConfiguration -Filter site:*
  description: |-
    Example 3 retrieves all trunk configurations defined at the site level.
    The Get-CsTrunkConfiguration cmdlet uses the Filter parameter to retrieve all trunk configurations with an Identity beginning with site:, meaning all trunk configurations defined at the site level.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    This parameter accepts a wildcard string and returns all trunk configurations with identities matching that string.
    For example, a Filter value of site:* will return all trunk configurations defined at the site level.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    The unique identifier of the trunk configuration you want to retrieve.
    Trunk configurations can be defined at the Global scope, the Site scope, or at the Service scope for a PSTN Gateway service.
    For example, site:Redmond (for site) or PstnGateway:Redmond.litwareinc.com (for service).

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: LocalStore
  description: |+
    Retrieves the information from the local replica of the Central Management store, rather than the Central Management store itself.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Get-CsTrunkConfiguration
name: Get-CsTrunkConfiguration
description: |-
  Use this cmdlet to retrieve one or more trunking configurations applicable to PSTN gateway entities.
  Each configuration contains specific settings for a trunking peer entity such as a PSTN gateway, IP-PBX, or SBC at the service provider.
  These settings configure such things as whether media bypass is enabled on this trunk, whether real-time transport control protocol (RTCP) packets are sent under certain conditions, and whether to require secure real-time protocol (SRTP) encryption.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/get-cstrunkconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Get-CsTrunkConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
