### YamlMime:PowershellCmdlet
summary: |-
  Reports back the location of the Active Directory service control point for the Central Management store.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="String" data-throw-if-not-resolved="False" />
  description: |-
    The Get-CsConfigurationStoreLocation cmdlet reports back the location of the configuration store.
links:
- text: Remove-CsConfigurationStoreLocation
  href: Remove-CsConfigurationStoreLocation.yml
- text: Set-CsConfigurationStoreLocation
  href: Set-CsConfigurationStoreLocation.yml
syntaxes:
- >-
  Get-CsConfigurationStoreLocation [-GlobalSettingsDomainController <Fqdn>] [-Report <String>]

   [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Get-CsConfigurationStoreLocation
  description: |-
    The command shown in Example 1 returns the SQL Server path to the computer (or pool) hosting the Central Management store.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Get-CsConfigurationStoreLocation -Report "C:\Logs\ConfigurationStore.html"
  description: |-
    Example 2 is a variation of the command shown in Example 1; in this case, however, the Report parameter is included in order to specify a path for the report generated when you run the Get-CsConfigurationStoreLocation cmdlet.
  summary: ""
parameters:
- type: <xref href="Fqdn" data-throw-if-not-resolved="False" />
  name: GlobalSettingsDomainController
  description: |+
    Fully qualified domain name (FQDN) of a domain controller where global settings are stored.
    If global settings are stored in the Active Directory System container, then this parameter must point to the root domain controller.
    If global settings are stored in the Configuration container, then any domain controller can be used and this parameter can be omitted.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Report
  description: |+
    Enables you to specify a file path for the log file created when the cmdlet runs.
    For example: 

    `-Report "C:\Logs\ConfigurationStore.html"`

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Get-CsConfigurationStoreLocation
name: Get-CsConfigurationStoreLocation
description: |-
  Active Directory Domain Services uses service control points (SCP) to help computers locate services.
  For example, when you install Skype for Business Server, a service control point is created that provides location information for the Central Management store used to maintain Skype for Business Server data.
  Computers that need access to the database connect to Active Directory and use the information contained in the SCP to help them locate the correct computer and the correct instance of SQL Server.

  The Get-CsConfigurationStoreLocation cmdlet is used to report back the SQL Server path (for example, atl-sql-001.litwareinc.com/rtc) to the computer running the Central Management store.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/get-csconfigurationstorelocation
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Get-CsConfigurationStoreLocation
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
