### YamlMime:PowershellCmdlet
summary: |-
  Returns information about the User Services configuration settings in use in your organization.
  The User Services service helps maintain presence information and manage conferencing.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
    The Get-CsUserServicesConfiguration cmdlet does not accept pipelined input.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The Get-CsUserServicesConfiguration cmdlet returns instances of the Microsoft.Rtc.Management.WritableConfig.Settings.UserServices.UserServicesSettings object.
links:
- text: New-CsUserServicesConfiguration
  href: New-CsUserServicesConfiguration.yml
- text: Remove-CsUserServicesConfiguration
  href: Remove-CsUserServicesConfiguration.yml
- text: Set-CsUserServicesConfiguration
  href: Set-CsUserServicesConfiguration.yml
syntaxes:
- Get-CsUserServicesConfiguration [[-Identity] <XdsIdentity>] [-LocalStore] [<CommonParameters>]
- Get-CsUserServicesConfiguration [-Filter <String>] [-LocalStore] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Get-CsUserServicesConfiguration
  description: |-
    The command shown in Example 1 returns a collection of all the User Services configuration settings currently in use in the organization.
    This is achieved by calling the Get-CsUserServicesConfiguration cmdlet without any additional parameters.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Get-CsUserServicesConfiguration -Identity site:Redmond
  description: |-
    In Example 2, only one collection of User Services configuration settings is returned: the collection with the Identity site:Redmond.
    Because identities must be unique, this command can never return more than one item.
  summary: ""
- title: '-------------------------- Example 3 --------------------------'
  code: |-
    Get-CsUserServicesConfiguration -Filter "service:*"
  description: |-
    Example 3 returns a collection of all the User Services configuration settings that have been applied at the service scope.
    This is done by calling the Get-CsUserServicesConfiguration cmdlet along with the -Filter parameter; the filter value "service:*" limits the returned data to settings where the Identity begins with the characters "service:".
    By definition, those are settings configured at the service scope.
  summary: ""
- title: '-------------------------- Example 4 --------------------------'
  code: |-
    Get-CsUserServicesConfiguration | Where-Object {$_.MaxContacts -gt 250}
  description: |-
    Example 4 returns all the User Services configuration settings that allow users to have more than 250 contacts.
    To do this, the command first calls the Get-CsUserServicesConfiguration cmdlet without any additional parameters in order to return a collection of all the User Services configuration settings currently in use.
    That collection is then piped to the Where-Object cmdlet, which picks out only those settings where the MaxContacts property is greater than 250.
  summary: ""
- title: '-------------------------- Example 5 --------------------------'
  code: |-
    Get-CsUserServicesConfiguration | Where-Object {$_.AnonymousUserGracePeriod -gt "00:10:00"}
  description: |-
    In Example 5, information is reported for those User Services configuration settings where the anonymous user grace period is longer than 10 minutes.
    To carry out this task, the command first calls the Get-CsUserServicesConfiguration cmdlet without any additional parameters; this returns a collection of all the User Services configuration settings being used in the organization.
    The returned collection is then piped to the Where-Object cmdlet, which selects only the settings where the AnonymousUserGracePeriod property is greater than 10 minutes (00 hours: 10 minutes: 00 seconds).
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Enables you to use wildcards when retrieving one or more collections of User Services configuration settings.
    For example, to return all the settings configured at the site scope, use this syntax:

    `-Filter "site:*"`

    To return all the settings configured at the service scope, use this syntax:

    `-Filter "service:*"`



  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Unique identifier for the User Services configuration settings to be returned.
    To return the global settings, use this syntax:.

    `-Identity global`

    To return settings configured at the site scope, use syntax similar to this:

    `-Identity site:Redmond`

    To return settings at the service level, use syntax like this:

    `-Identity service:UserServer:atl-cs-001.litwareinc.com`

    If this parameter is omitted then the Get-CsUserServicesConfiguration cmdlet returns all the User Services configuration settings currently in use in your organization.



  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: LocalStore
  description: |+
    Retrieves the User Services configuration data from the local replica of the Central Management store rather than from the Central Management store itself.



  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Get-CsUserServicesConfiguration
name: Get-CsUserServicesConfiguration
description: |-
  Skype for Business Server relies on the User Services service to help maintain presence information for users and to manage meetings and conferences.
  In turn, the CsUserServicesConfiguration cmdlets are used to administer User Services settings at the global, site, and service scope.
  (Note that the only service that can host User Services configuration settings is the User Services itself.) These settings help determine such things as the number of contacts a user can have, the number of meetings a user can have scheduled at any one time, and the length of time that a given meeting can remain active.

  The Get-CsUserServicesConfiguration cmdlet provides a way for administrators to retrieve information about any (or all) of the User Services configuration settings currently in use.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/get-csuserservicesconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Get-CsUserServicesConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
