### YamlMime:PowershellCmdlet
summary: |-
  Retrieves a test scenario you can use to test phone numbers against specified routes and rules.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Returns one of more objects of type Microsoft.Rtc.Management.WritableConfig.Policy.Voice.TestConfiguration.
links:
- text: New-CsVoiceTestConfiguration
  href: New-CsVoiceTestConfiguration.yml
- text: Remove-CsVoiceTestConfiguration
  href: Remove-CsVoiceTestConfiguration.yml
- text: Set-CsVoiceTestConfiguration
  href: Set-CsVoiceTestConfiguration.yml
- text: Test-CsVoiceTestConfiguration
  href: Test-CsVoiceTestConfiguration.yml
syntaxes:
- Get-CsVoiceTestConfiguration [[-Identity] <XdsGlobalRelativeIdentity>] [-LocalStore] [<CommonParameters>]
- Get-CsVoiceTestConfiguration [-Filter <String>] [-LocalStore] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Get-CsVoiceTestConfiguration
  description: |-
    Retrieves all the voice test configuration settings.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Get-CsVoiceTestConfiguration | Select-Object Identity, DialedNumber, ExpectedTranslatedNumber
  description: |-
    This example retrieves all the voice test configuration settings, displaying only the Identity, DialedNumber, and ExpectedTranslatedNumber parameter of each.
    The settings returned by the Get-CsVoiceTestConfiguration cmdlet are piped to the Select-Object cmdlet, where the output is narrowed down to the Identity, DialedNumber, and ExpectedTranslatedNumber properties.
  summary: ""
- title: '-------------------------- Example 3 --------------------------'
  code: |-
    Get-CsVoiceTestConfiguration -Filter *test*
  description: |-
    This example uses the Filter parameter to retrieve all the voice test configuration settings with Identities that contain the string "test".
    The wildcard characters (*) at the beginning and end of the filter value indicate that the string "test" can be located anywhere within the Identity, with any characters before or after that string.
    For example, this command would return voice test configurations with names such as TestConfig, VoiceNumberTest, and VoiceTest1.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    This parameter provides a way to do a wildcard search of the defined voice test configurations.
    (For details, see the examples in this topic.)

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsGlobalRelativeIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    A string uniquely identifying the test configuration you want to retrieve.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: LocalStore
  description: |+
    Retrieves the voice test configuration from the local replica of the Central Management store, rather than the Central Management store itself.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Get-CsVoiceTestConfiguration
name: Get-CsVoiceTestConfiguration
description: |-
  This cmdlet retrieves the voice route, usage, dial plan, and voice policy against which to test a specified phone number.
  Before implementing voice routes and voice policies, it's a good idea to test them out on various phone numbers to ensure the results are what you're expecting.
  You can do this testing by retrieving a test configuration with this cmdlet, and then running that scenario with the Test-CsVoiceConfiguration cmdlet.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/get-csvoicetestconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Get-CsVoiceTestConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
