### YamlMime:PowershellCmdlet
summary: |-
  Returns information about the reporting configuration settings in use in the organization.
  Reporting configuration settings are used to specify the URL used for accessing Skype for Business Server Monitoring Reports.
  This cmdlet was introduced in Lync Server 2013.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Rtc.Management.WritableConfig.Settings.Reporting.ReportingConfiguration" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-CsReportingConfiguration
  href: New-CsReportingConfiguration.yml
- text: Remove-CsReportingConfiguration
  href: Remove-CsReportingConfiguration.yml
- text: Set-CsReportingConfiguration
  href: Set-CsReportingConfiguration.yml
syntaxes:
- Get-CsReportingConfiguration [-Filter <String>] [-LocalStore] [<CommonParameters>]
- Get-CsReportingConfiguration [[-Identity] <XdsIdentity>] [-LocalStore] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Get-CsReportingConfiguration
  description: |-
    The command shown in Example 1 returns information for all the reporting configuration settings currently in use in the organization.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Get-CsReportingConfiguration -Identity "Service:MonitoringDatabase:atl-sql-001.litwareinc.com"
  description: |-
    In Example 2, information is returned for a single collection of reporting configuration settings: the settings with the Identity "Service:MonitoringDatabase:atl-sql-001.litwareinc.com".
  summary: ""
- title: '-------------------------- Example 3 --------------------------'
  code: |-
    Get-CsReportingConfiguration -Filter "*.litwareinc.com"
  description: |-
    In Example 3, information is returned for all the reporting configuration settings that have an Identity that ends in ".litwareinc.com".
    To do this, the command uses the Filter parameter and the filter value "*.litwareinc.com".
  summary: ""
- title: '-------------------------- Example 4 --------------------------'
  code: |-
    Get-CsReportingConfiguration | Where-Object {$_.ReportingUrl -like "*_ARCHINST*"}
  description: |-
    Example 4 returns information for all the reporting configuration settings that include the string value "_ARCHINST" somewhere in their reporting URL.
    To do this the command first uses the Get-CsReportingConfiguration cmdlet to return a collection of all the reporting configuration settings currently in use.
    This collection is then piped to the Where-Object cmdlet, which picks out only those settings where the ReportingUrl includes (-like) the string value "_ARCHINST".
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Enables you to use wildcard characters when specifying the reporting configuration settings to be returned.
    For example, this syntax returns all the settings configured at the service scope:

    `-Filter "service:*"`

    Note that you cannot use both the Filter and the Identity parameters in the same command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Service Identity of the monitoring database associated with the reporting configuration settings.
    For example:

    `-Identity "Service:MonitoringDatabase:atl-sql-001.litwareinc.com"`

    If you do not include either the Identity parameter or the Filter parameter in your command, then the Get-CsReportingConfiguration cmdlet will return all the reporting configuration settings in use in your organization.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: LocalStore
  description: |+
    Retrieves the reporting configuration data from the local replica of the Central Management store rather than from the Central Management store itself.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Get-CsReportingConfiguration
name: Get-CsReportingConfiguration
description: |-
  Reporting configuration settings are used to specify the home page for the Skype for Business Server Monitoring Reports; if you are not using Monitoring Reports then there is no reason for you to modify the reporting configuration settings.

  The functions carried out by the Get-CsReportingConfiguration cmdlet are not available in the Skype for Business Server Control Panel.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/get-csreportingconfiguration
  applicable: Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Get-CsReportingConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
