### YamlMime:PowershellCmdlet
summary: |-
  Retrieves one or more collections of Quality of Experience (QoE) settings.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Rtc.Management.WritableConfig.Settings.QoE.QoESettings" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-CsQoEConfiguration
  href: New-CsQoEConfiguration.yml
- text: Remove-CsQoEConfiguration
  href: Remove-CsQoEConfiguration.yml
- text: Set-CsQoEConfiguration
  href: Set-CsQoEConfiguration.yml
syntaxes:
- Get-CsQoEConfiguration [[-Identity] <XdsIdentity>] [-LocalStore] [<CommonParameters>]
- Get-CsQoEConfiguration [-Filter <String>] [-LocalStore] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Get-CsQoEConfiguration
  description: |-
    This example uses the Get-CsQoEConfiguration cmdlet to return a collection of all the QoE settings configured for use in your organization.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Get-CsQoEConfiguration -Identity site:Redmond
  description: |-
    Example 2 uses the Identity parameter to ensure that the Get-CsQoEConfiguration cmdlet returns only the QoE settings with the Identity site:Redmond.
  summary: ""
- title: '-------------------------- Example 3 --------------------------'
  code: |-
    Get-CsQoEConfiguration -Filter site:*
  description: |-
    In Example 3 the Filter parameter is used to return all the QoE settings that have been configured at the site scope.
    The wildcard "site:*" returns all the QoE settings that have an Identity beginning with the string value site:.
    Settings that meet those criteria are settings that have been configured at the site scope.
  summary: ""
- title: '-------------------------- Example 4 --------------------------'
  code: |-
    Get-CsQoEConfiguration | Where-Object {$_.KeepQoEDataForDays -lt 30}
  description: |-
    Example 4 returns a collection of all the QoE settings where the KeepQoEDataForDays property is less than 30 days.
    To do this, the command first uses the Get-CsQoEConfiguration cmdlet to return a collection of all the QoE settings configured in the organization.
    That collection is then piped to the Where-Object cmdlet, which applies a filter that limits the returned data to those settings that have a KeepQoEDataForDays value of less than 30 days.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Enables you to use wildcard characters in order to return a collection (or multiple collections) of QoE configuration settings.
    To return a collection of all the settings configured at the site scope, use this syntax:

    `-Filter site:*`

    To return a collection of all the settings that have the string value "Western" somewhere in their Identity (the only property you can filter on) use this syntax:

    `-Filter *Western*`

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    The unique identifier of the settings you want to retrieve.
    Possible values are global and site:\<site name\>, where \<site name\> is the name of the site in your Skype for Business Server deployment to which you want to apply the changes.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: LocalStore
  description: |+
    Retrieves the settings from the local replica of the Central Management store.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Get-CsQoEConfiguration
name: Get-CsQoEConfiguration
description: |-
  QoE metrics track the quality of audio and video calls made in your organization, including such things as the number of network packets lost, background noise, and the amount of "jitter" (differences in packet delay).
  These metrics are stored in a database apart from other data (such as call detail records), which allows you to enable and disable QoE independent of other data recording.
  Use this cmdlet to retrieve settings that configure QoE at the global or site level.

  QoE is part of the Monitoring Server role; therefore Monitoring Server must be deployed on your Skype for Business Server 2015 installation before QoE recording takes effect or any QoE data can be collected.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/get-csqoeconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Get-CsQoEConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
