### YamlMime:PowershellCmdlet
summary: |-
  Returns information about the server applications in use in your organization.
  Server applications are applications that are hosted by Skype for Business Server.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Rtc.Management.WritableConfig.Settings.ServerApplication.Application" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-CsServerApplication
  href: New-CsServerApplication.yml
- text: Remove-CsServerApplication
  href: Remove-CsServerApplication.yml
- text: Set-CsServerApplication
  href: Set-CsServerApplication.yml
syntaxes:
- Get-CsServerApplication [[-Identity] <XdsIdentity>] [-LocalStore] [<CommonParameters>]
- Get-CsServerApplication [-Filter <String>] [-LocalStore] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Get-CsServerApplication
  description: |-
    The command shown in Example 1 returns information about all the server applications currently in use in the organization.
    This is done by calling the Get-CsServerApplication cmdlet without any parameters.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Get-CsServerApplication -Identity "service:EdgeServer:atl-edge-001.litwareinc.com"
  description: |-
    In Example 2, information is returned for all the server applications running on the service EdgeServer:atl-edge-001.litwareinc.com.
  summary: ""
- title: '-------------------------- Example 3 --------------------------'
  code: |-
    Get-CsServerApplication -Identity "service:Registrar:atl-cs-001.litwareinc.com/ExumRouting"
  description: |-
    Example 3 returns information for a single server application: the application that has the Identity Registrar:atl-cs-001.litwareinc.com/ExumRouting".
  summary: ""
- title: '-------------------------- Example 4 --------------------------'
  code: |-
    Get-CsServerApplication -Filter "service:*:atl-cs-001.litwareinc.com*"
  description: |-
    Example 4 returns all the server applications configured for use in the pool atl-cs-001.litwareinc.com.
    This is done by using the Filter parameter and the filter value "service:*:atl-cs-001.litwareinc.com*".
    The filter value limits the returned data to applications that have an Identity that begins with the characters "service:" and includes the characters ":atl-cs-001.litwareinc.com".
  summary: ""
- title: '-------------------------- Example 5 --------------------------'
  code: |-
    Get-CsServerApplication | Where-Object {$_.Enabled -eq $False}
  description: |-
    In Example 5, information is returned for all the server applications that are currently disabled.
    To carry out this task, the command first calls the Get-CsServerApplication cmdlet to return a collection of all the server applications configured for use in the organization.
    This collection is then piped to the Where-Object cmdlet, which selects only those applications where the Enabled property is equal to False.
  summary: ""
- title: '-------------------------- Example 6 --------------------------'
  code: |-
    Get-CsServerApplication | Where-Object {$_.Critical -eq $True -and $_.Enabled -eq $False}
  description: |-
    Example 6 is a variation of the command shown in Example 5.
    In Example 6, information is returned for all the server applications that are marked as critical and are currently disabled.
    To do this, the command first calls the Get-CsServerApplication cmdlet without any parameters; that returns a collection of all the server applications configured for use.
    This collection is then piped to the Where-Object cmdlet, which picks out only those applications that meet two criteria: the Critical property must be equal to True; and, the Enabled property must be equal to False.
    The -and operator ensures that only objects that meet both criteria will be returned.
  summary: ""
- title: '-------------------------- Example 7 --------------------------'
  code: |-
    Get-CsServerApplication | Where-Object {$_.Uri -like "*routing*"}
  description: |-
    In Example 7, information is returned for any server application that has the string value "routing" somewhere in its Uri.
    This task is accomplished by first using the Get-CsServerApplication cmdlet to retrieve all the server applications currently in use.
    The resulting collection is then piped to the Where-Object cmdlet, which selects only those applications in which the Uri property includes the string value "routing".
  summary: ""
- title: '-------------------------- Example 8 --------------------------'
  code: |-
    Get-CsServerApplication | Where-Object {$_.ScriptName -ne $Null}
  description: |-
    Example 8 returns information for all the server applications that have been assigned a script.
    To do this, the command first retrieves a collection of all the server applications currently in use; this information is retrieved by calling the Get-CsServerApplication cmdlet without any parameters.
    The complete collection of server applications is then piped to the Where-Object cmdlet, which selects only those applications where the ScriptName property is not equal to a null value.
    If the ScriptName property is not equal to a null value that means that a script has been assigned to that application.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Enables you to use wildcards when returning a server application or set of server applications.
    For example, to return all the server applications that have the string value "IIMFilter" somewhere in their Identity use this syntax:

    `-Filter "*IIMFilter*"`

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Unique identifier for the server application to be retrieved.
    Server application Identities are composed of the service where the application is hosted plus the application name.
    For example, the server application named QoEAgent might have an Identity similar to this: service: Registrar:atl-cs-001.litwareinc.com/QoEAgent.

    To retrieve a collection of all the applications running on a given service, simply leave off the application name:

    `-Identity "Registrar:atl-cs-001.litwareinc.com "`

    If this parameter is omitted, then all the server applications will be returned when you call the Get-CsServerApplication cmdlet.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: LocalStore
  description: |+
    Retrieves the server application data from the local replica of the Central Management store rather than from the Central Management store itself.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Get-CsServerApplication
name: Get-CsServerApplication
description: |-
  Server applications refer to the individual programs that run under Skype for Business Server.
  The Get-CsServerApplication cmdlet provides a way for administrators to return information about any (or all) of the applications running as part of Skype for Business Server.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/get-csserverapplication
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Get-CsServerApplication
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
