### YamlMime:PowershellCmdlet
summary: |-
  Returns information about existing instances of the Skype for Business Server Storage Service.
  The storage service provides a common infrastructure that enables Skype for Business Server components to use Exchange as a back-end data store.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Rtc.Management.WritableConfig.Settings.StorageService.StorageServiceSettings" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-CsStorageServiceConfiguration
  href: New-CsStorageServiceConfiguration.yml
- text: Remove-CsStorageServiceConfiguration
  href: Remove-CsStorageServiceConfiguration.yml
- text: Set-CsStorageServiceConfiguration
  href: Set-CsStorageServiceConfiguration.yml
syntaxes:
- Get-CsStorageServiceConfiguration [-Filter <String>] [-LocalStore] [<CommonParameters>]
- Get-CsStorageServiceConfiguration [[-Identity] <XdsIdentity>] [-LocalStore] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Get-CsStorageServiceConfiguration
  description: |-
    The command shown in Example 1 returns information about all the storage service configuration settings in use in your organization.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Get-CsStorageServiceConfiguration -Identity "site:Redmond"
  description: |-
    In Example 2, information is returned for a single collection of storage service configuration settings: the collection of settings applied to the Redmond site.
  summary: ""
- title: '-------------------------- Example 3 --------------------------'
  code: |-
    Get-CsStorageServiceConfiguration -Filter "service:*"
  description: |-
    Example 3 returns information for all the storage service configuration settings applied at the service scope.
    To do this, the command uses the Filter parameter and the filter value "service:*".
    That filter value limits returned data to collections that have an Identity that begins with the string value "service:".
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Enables you to use wildcards when retrieving one or more collections of storage service configuration settings.
    For example, to return all the settings configured at the site scope, use this syntax:

    `-Filter "site:*"`

    To return all the settings configured at the service scope, use this syntax:

    `-Filter "service:*"`

    Note that you cannot use both the Filter parameter and the Identity parameter in the same command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Unique identifier for the storage service configuration settings to be returned.
    Storage service configuration settings can be applied to the global, site, or service scope (for the Registrar service only).
    To return a complete collection of storage service configuration settings, omit the Identity parameter altogether:

    `Get-CsStorageServiceConfiguration`

    Alternatively, you can use the Identity parameter to retrieve information for a specific collection of storage service configuration settings.
    To return just the global settings, use this syntax:

    `-Identity "global"`

    To return settings configured at the site scope, use syntax similar to this:

    `-Identity "site:Redmond"`

    To return settings at the service level, use syntax similar to this:

    `-Identity "service:Registrr:atl-cs-001.litwareinc.com"`

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: LocalStore
  description: |+
    Retrieves the storage service configuration data from the local replica of the Central Management store rather than from the Central Management store itself.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Get-CsStorageServiceConfiguration
name: Get-CsStorageServiceConfiguration
description: |-
  The Skype for Business Server Storage Service enables Skype for Business Server components (such as archiving) to use Exchange as a back-end data store.
  This helps to reduce operating costs; for example, you do not need to have separate storage solutions for Exchange archiving and for Skype for Business Server archiving.
  The Storage Service also enables Skype for Business Server to leverage the heavy investment that has been made in Exchange archiving and storage, and prevents administrators from having to use multiple tools to retrieve archived data.

  Separate instances of the Skype for Business Server Storage Service can be configured at the global, site, and service scope (for the Registrar service only).
  By default, Skype for Business Server provides you with a single, global collection of Storage Service configuration settings.
  However, administrators have the option of creating custom setting collections by using the New-CsStorageServiceConfiguration cmdlet.
  Information about all of these Storage Service settings can be returned by using the Get-CsStorageServiceConfiguration cmdlet.

  Skype for Business Server Control Panel: The functions carried out by the Get-CsStorageServiceConfiguration cmdlet are not available in the Skype for Business Server Control Panel.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/get-csstorageserviceconfiguration
  applicable: Skype for Business Server 2015, Skype for Business Server 2019
  title: Get-CsStorageServiceConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
