### YamlMime:PowershellCmdlet
summary: |-
  Retrieves the voice configuration object, which contains a full list of all voice test configurations defined for the Skype for Business Server deployment.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    This cmdlet returns an instance of the Microsoft.Rtc.Management.WritableConfig.Policy.Voice.VoiceConfiguration object.
links:
- text: Remove-CsVoiceConfiguration
  href: Remove-CsVoiceConfiguration.yml
- text: Set-CsVoiceConfiguration
  href: Set-CsVoiceConfiguration.yml
- text: Get-CsVoiceTestConfiguration
  href: Get-CsVoiceTestConfiguration.yml
syntaxes:
- Get-CsVoiceConfiguration [[-Identity] <XdsIdentity>] [-LocalStore] [<CommonParameters>]
- Get-CsVoiceConfiguration [-Filter <String>] [-LocalStore] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Get-CsVoiceConfiguration
  description: |-
    This example retrieves the voice configuration.
    To retrieve the voice test configurations, use the Get-CsVoiceTestConfiguration cmdlet.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    There can only be one instance of this object, so this parameter does nothing.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    The scope of the voice configuration to retrieve.
    The only possible value is Global.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: LocalStore
  description: |+
    Retrieves the voice configuration from the local replica of the Central Management store, rather than the Central Management store itself.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Get-CsVoiceConfiguration
name: Get-CsVoiceConfiguration
description: |-
  Voice test configurations are used to test a phone number against a specific voice policy, route, and dial plan.
  This cmdlet is used to retrieve the global instance that holds a list of all voice test configurations defined within the Skype for Business Server 2015 deployment.
  To retrieve individual voice test configurations or to retrieve them as individual objects rather than as a list, use the Get-CsVoiceTestConfiguration cmdlet.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/get-csvoiceconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Get-CsVoiceConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
