### YamlMime:PowershellCmdlet
summary: |-
  Returns the Address Book normalization configuration settings currently in use in the organization.
  Address Book normalization settings are used to convert phone numbers to a format readily understood by Skype for Business Server.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Rtc.Management.WritableConfig.Settings.AddressBook.AddressBookNormalizationSettings" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-CsAddressBookNormalizationConfiguration
  href: New-CsAddressBookNormalizationConfiguration.yml
- text: Remove-CsAddressBookNormalizationConfiguration
  href: Remove-CsAddressBookNormalizationConfiguration.yml
- text: Set-CsAddressBookNormalizationConfiguration
  href: Set-CsAddressBookNormalizationConfiguration.yml
- text: Import-CsCompanyPhoneNormalizationRules
  href: Import-CsCompanyPhoneNormalizationRules.yml
syntaxes:
- Get-CsAddressBookNormalizationConfiguration [-Filter <String>] [-LocalStore] [<CommonParameters>]
- Get-CsAddressBookNormalizationConfiguration [[-Identity] <XdsIdentity>] [-LocalStore] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Get-CsAddressBookNormalizationConfiguration
  description: |-
    The command shown in Example 1 returns a collection of all the Address Book normalization configuration settings currently in use in the organization.
    This is done by calling the Get-CsAddressBookNormalizationConfiguration cmdlet without any additional parameters.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Get-CsAddressBookNormalizationConfiguration -Identity "site:Redmond"
  description: |-
    In Example 2, information is returned for a single collection of normalization rules: the collection with the Identity site:Redmond:
  summary: ""
- title: '-------------------------- Example 3 --------------------------'
  code: |-
    Get-CsAddressBookNormalizationConfiguration -Filter "site:*"
  description: |-
    Example 3 returns information about all the normalization configuration settings applied to the site scope.
    To do this, the command uses the Filter parameter and the parameter value "site:*".
    That syntax limits the returned data to all the collections that have an Identity that begins with the string value "site:".
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Enables you to use wildcard characters in order to return a collection (or multiple collections) of Address Book normalization configuration settings.
    For example, to return a collection of all the settings configured at the site scope, use this syntax: -Filter "site:*"

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Unique identifier for the collection of Address Book normalization configuration settings to be returned.
    To refer to the global settings, use this syntax: -Identity global

    To refer to a collection configured at the site scope, use syntax similar to this: -Identity "site:Redmond"

    Note that you cannot use wildcards when specifying an Identity.
    If you need to use wildcards, use the Filter parameter instead.

    If this parameter is not specified, then the Get-CsAddressBookNormalizationConfiguration cmdlet returns a collection of all the Address Book normalization configuration settings in use in the organization.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: LocalStore
  description: |+
    Retrieves the Address Book normalization configuration data from the local replica of the Central Management store rather than from the Central Management store itself.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Get-CsAddressBookNormalizationConfiguration
name: Get-CsAddressBookNormalizationConfiguration
description: |-
  Normalization rules define the requirements for converting (or translating) numbers from an internal Skype for Business Server format to the standard (E.164) format.
  (Note that an understanding of regular expressions is helpful in order to understood what normalization rules do and how they work.) In Skype for Business Server, the Address Book normalization configuration settings represent collections of normalization created for use by the Address Book server.
  (These collections can be defined at the global scope or at the site scope.) The Get-CsAddressBookNormalizationConfiguration cmdlet provides a way to return information about the Address Book normalization rules currently in use in your organization.

  Although Address Book normalization rules are very similar to voice normalization rules, the two are not interchangeable: you cannot add voice normalization rules to an Address Book collection, nor can you add Address Book normalization rules to a dial plan.
  That means that, in some cases, you might need to create identical rules: one for assignment to Address Book servers, the other for assignment to dial plans.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/get-csaddressbooknormalizationconfiguration
  applicable: Skype for Business Server 2015, Skype for Business Server 2019
  title: Get-CsAddressBookNormalizationConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
