### YamlMime:PowershellCmdlet
summary: |-
  Returns information about the Cloud Call Data Connector configuration settings currently in use in the organization.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Rtc.Management.WritableConfig.Settings.CallDataConnectorConfiguration" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- Get-CsCloudCallDataConnectorConfiguration [[-Identity] <XdsIdentity>] [-LocalStore] [<CommonParameters>]
- Get-CsCloudCallDataConnectorConfiguration [-Filter <String>] [-LocalStore] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> Get-CsCloudCallDataConnectorConfiguration
  description: |-
    Example 1 returns information about all the CloudCallDataConnector configuration settings currently in use in the organization.
  summary: ""
- title: Example 2
  code: |-
    Get-CsCloudCallDataConnectorConfiguration -Identity site:Redmond
  description: |-
    Example 2 uses the Identity parameter to return a single collection of CloudCallDataConnector configuration settings: the settings with the Identity site:Redmond.
  summary: ""
- title: Example 3
  code: |-
    Get-CsCloudCallDataConnectorConfiguration -Filter site:*
  description: |-
    In Example 3, the Filter parameter is employed to return all the CloudCallDataConnector configuration settings that have been configured at the site scope.
    The filter value "site:*" returns all the CloudCallDataConnector configuration settings that have an Identity that begins with the string value "site:".
    By definition, those are settings that have been configured at the site scope.
  summary: ""
- title: Example 4
  code: |-
    Get-CsCloudCallDataConnectorConfiguration | Where-Object {$_.EnableCallDataConnector -eq $True}
  description: |-
    Example 4 returns a collection of all the CloudCallDataConnector configuration settings where the EnableCallDataConnector property is set to $True.
    To do this, the command first uses the Get-CsCdrConfiguration cmdlet to return a collection of all the CloudCallDataConnector configuration settings configured in the organization.
    That collection is then piped to the Where-Object cmdlet, which picks out only those settings where the EnableCallDataConnector value is set to $True.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Enables you to use wildcard characters to return a collection of CloudCallDataConnector configuration settings.
    For example, to return a collection of all the settings configured at the site scope, use this syntax: -Filter site:*.
    To return a collection of all the settings that have the string value "Western" somewhere in their Identity, use this syntax: -Filter Western .

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Indicates the unique identifier for the collection of CloudCallDataConnector configuration settings you want to return.
    To refer to the global settings, use this syntax: -Identity global.
    To refer to a collection configured at the site scope, use syntax similar to this: -Identity site:Redmond.
    Note that you cannot use wildcards when specifying an Identity.
    If you need to use wildcards, use the Filter parameter instead.

    If this parameter is not specified, the Get-CsCloudCallDataConnectorConfiguration cmdlet returns a collection of all the CloudCallDataConnector configuration settings currently in use in the organization.

  defaultValue: None
  position: "1"
  aliases: ""
  applicable:
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: LocalStore
  description: |+
    Retrieves the CloudCallDataConnector configuration data from the local replica of the Central Management store, rather than from the Central Management store itself.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Skype for Business Server 2019
uid: SkypeForBusiness.Get-CsCloudCallDataConnectorConfiguration
name: Get-CsCloudCallDataConnectorConfiguration
description: |-
  Call Data Connector greatly simplifies call monitoring in a hybrid environment because you no longer need to use different sets of on-premises and online tools to monitor all of your users' call quality. Whether your users are homed on premises or online, you can choose to view call quality for your entire organization online.

  With Call Data Connector, the Skype for Business Server pushes call data to the cloud service so that you can leverage the Skype for Business Online Call Analytics (CA) and Call Quality Dashboard (CQD) tools.
metadata:
  external help file: Microsoft.Rtc.Management.dll-Help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/get-cscloudcalldataconnectorconfiguration
  applicable: Skype for Business Server 2019
  title: Get-CsCloudCallDataConnectorConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
