### YamlMime:PowershellCmdlet
summary: |-
  Returns information about all the partner applications configured for use in the organization.
  A partner application is any application that Skype for Business Server can directly exchange security tokens with, without having to exchange those tokens by using a third-party security token server.
  This cmdlet was introduced in Lync Server 2013.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Rtc.Management.WritableConfig.Settings.SSAuth.PartnerApplication#Decorated" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-CsPartnerApplication
  href: New-CsPartnerApplication.yml
- text: Remove-CsPartnerApplication
  href: Remove-CsPartnerApplication.yml
- text: Set-CsPartnerApplication
  href: Set-CsPartnerApplication.yml
syntaxes:
- Get-CsPartnerApplication [-Filter <String>] [-LocalStore] [-Tenant <Guid>] [<CommonParameters>]
- >-
  Get-CsPartnerApplication [[-Identity] <XdsGlobalRelativeIdentity>] [-LocalStore] [-Tenant <Guid>]

   [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Get-CsPartnerApplication
  description: |-
    The command shown in Example 1 returns information about all the partner applications configured for use in the organization
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Get-CsPartnerApplication -Identity "MicrosoftExchange"
  description: |-
    Example 2 returns information for the partner application that has the Identity MicrosoftExchange.
  summary: ""
- title: '-------------------------- Example 3 --------------------------'
  code: |-
    Get-CsPartnerApplication | Where-Object {$_.ApplicationIdentifier -eq "microsoft.exchange"}
  description: |-
    In Example 3, information is returned for all the partner applications that have an application identifier equal to "microsoft.exchange." In order to do this, the command first calls the Get-CsPartnerApplication cmdlet without any parameters; that returns a collection of all the configured partner applications.
    That collection is then piped to the Where-Object cmdlet, which picks out only those partner applications where the ApplicationIdentifier property is equal to "microsoft.exchange."
  summary: ""
- title: '-------------------------- Example 4 --------------------------'
  code: |-
    Get-CsPartnerApplication | Where-Object {$_.Enabled -eq $False}
  description: |-
    In Example 4, information is returned for all the partner applications that are currently disabled.
    To do this, the command first calls the Get-CsPartnerApplication cmdlet in order to return a collection of all the partner applications, both enabled and disabled.
    That collection is then piped to the Where-Object cmdlet, which selects only those applications where the Enabled property is equal to False.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Enables you to use wildcard values to return one or more partner applications.
    For example, to return all the partner applications that have an Identity that includes the string value "Microsoft" use this syntax:

    `-Filter "*Microsoft*"`

    You cannot use both the Filter parameter and the Identity parameter in the same command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsGlobalRelativeIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Unique identifier for the partner application.
    For example:

    `-Identity "MicrosoftExchange"`

    If neither the identity parameter nor the Filter parameter are included in the command then the Get-CsPartnerApplication cmdlet will return information for all your partner applications.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: LocalStore
  description: |+
    Retrieves the partner application data from the local replica of the Central Management store rather than from the Central Management store itself.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Guid" data-throw-if-not-resolved="False" />
  name: Tenant
  description: |+
    Globally unique identifier (GUID) of the Skype for Business Online tenant account where whose partner application settings are to be retrieved.

    For example:

    `-Tenant "38aad667-af54-4397-aaa7-e94c79ec2308"`

    You can return the tenant ID for each of your tenants by running this command:

    `Get-CsTenant | Select-Object DisplayName, TenantID`

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Get-CsPartnerApplication
name: Get-CsPartnerApplication
description: |-
  In Skype for Business Server, server-to-server authentication (for example, the authentication that enables Skype for Business Server and Exchange to share information) is carried out using the OAuth security protocol.
  This type of authentication typically requires three servers: the two servers that need to communicate with one another (Server A and B) and a third-party security token server.
  If Servers A and B need to communicate with one another, the two servers contact the token server (also known as an OAuth server) and obtain mutually-trusted security tokens that the two servers can exchange in order to prove their identities.

  If you are using an on-premises version of Skype for Business Server and you need to communicate with another server product that fully supports the OAuth protocol (for example, Exchange or SharePoint) then you typically do not need to use a token server; that's because these server products are able to issue their own security tokens.
  However, you will need to configure the other server product (e.g., Exchange) as a partner application.
  (You will also need to configure Skype for Business Server as a partner application for the other server product.) In Skype for Business Server, partner applications are managed by using the CsPartnerApplication cmdlets.

  Skype for Business Server Control Panel: The functions carried out by the Get-CsPartnerApplication cmdlet are not available in the Skype for Business Server Control Panel.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/get-cspartnerapplication
  applicable: Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Get-CsPartnerApplication
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
