### YamlMime:PowershellCmdlet
summary: |-
  Retrieves the settings for a trusted application.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Rtc.Management.Xds.DisplayTrustedApplication" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-CsTrustedApplication
  href: New-CsTrustedApplication.yml
- text: Remove-CsTrustedApplication
  href: Remove-CsTrustedApplication.yml
- text: Set-CsTrustedApplication
  href: Set-CsTrustedApplication.yml
syntaxes:
- Get-CsTrustedApplication [[-Identity] <ExternalApplicationIdentity>] [<CommonParameters>]
- Get-CsTrustedApplication [-Filter <String>] [<CommonParameters>]
- Get-CsTrustedApplication [-ApplicationId <String>] [-TrustedApplicationPoolFqdn <String>] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Get-CsTrustedApplication
  description: |-
    This example retrieves information about all trusted applications defined within the Skype for Business Server deployment.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Get-CsTrustedApplication -Identity TrustPool.litwareinc.com/tapp2
  description: |-
    Example 2 retrieves the trusted application with the Identity TrustPool.litwareinc.com/urn:application:tapp2.
    Notice that we were able to omit the urn:application: prefix.
    The Get-CsTrustedApplication cmdlet adds the prefix automatically and retrieves the correct application.
  summary: ""
- title: '-------------------------- Example 3 --------------------------'
  code: |-
    Get-CsTrustedApplication -Filter *trust*
  description: |-
    Example 3 retrieves all trusted applications that have identities matching the wildcard string specified as the Filter value.
    In this case, with a Filter value of *trust*, the command will retrieve all trusted applications with the string "trust" anywhere within the Identity.
    This string can be contained within any part of the Identity, the pool FQDN, or the application ID.
    So this command will retrieve trusted applications with identities such as TrustedPool.litwareinc.com/urn:application:application1, Pool1.litwareinc.com/urn:application:trustedapp, and Pool1.litwareinc.com/urn:application:trust.
  summary: ""
- title: '-------------------------- Example 4 --------------------------'
  code: |-
    Get-CsTrustedApplication -ApplicationId tapp2 -TrustedApplicationPoolFqdn TrustPool.litwareinc.com
  description: |-
    Example 4 will return the same results as Example 2 (where the Identity was specified as the only parameter).
    The only difference between the two examples is that Example 2 retrieves the trusted application based on the Identity, which consists of the trusted pool FQDN followed by the application ID.
    In this example, the application ID and trusted pool FQDN are entered as values to two separate parameters: ApplicationId and TrustedApplicationPoolFqdn.
  summary: ""
- title: '-------------------------- Example 5 --------------------------'
  code: |-
    Get-CsTrustedApplication | Where-Object {$_.TrustedApplicationPoolFqdn -eq "TrustPool.litwareinc.com"}
  description: |-
    Example 5 retrieves all the trusted applications on the pool TrustPool.litwareinc.com.
    The example begins by calling the Get-CsTrustedApplication cmdlet.
    This returns a collection of all trusted applications defined within the Skype for Business Server deployment.
    This collection is then piped to the Where-Object cmdlet, which looks through the collection item-by-item to find those with a TrustedApplicationPoolFqdn property value equal to (-eq) TrustPool.litwareinc.com.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ApplicationId
  description: |+
    The name of the application.
    This can include the application ID prefix, but doesn't need to.
    For example, ApplicationId values of urn:application:tapp1 and tapp1 will both return the same application.
    If you supply a value for ApplicationId, you cannot supply a value for the Identity, but you must supply a value for the TrustedApplicationPoolFqdn parameter.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    A string that includes wildcards that enables you to retrieve trusted applications based on Identity values that match the given wildcard string.
    Identities consist of a trusted application pool FQDN followed by a slash (/) followed by the trusted application ID.
    The Filter value will match any part of the Identity, both the FQDN and the application ID.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="ExternalApplicationIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    The unique identifier of the trusted application you want to retrieve.
    Identity values must be entered in the format \<pool FQDN\>/\<application ID\>, where pool FQDN is the FQDN of the pool on which the application resides, and application ID is the name of the application.
    Note that if you specify an Identity, you cannot specify an ApplicationID or a TrustedApplicationPoolFqdn.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: TrustedApplicationPoolFqdn
  description: |+
    The FQDN of the trusted application pool on which the application will reside.
    If you supply a value for TrustedApplicationPoolFqdn, you cannot supply a value for the Identity, but you must supply a value for the ApplicationID parameter.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Get-CsTrustedApplication
name: Get-CsTrustedApplication
description: |-
  A trusted application is an application developed by a third party that is given trusted status to run as part of Skype for Business Server but that is not a built-in part of the product.
  This cmdlet enables you to retrieve port and Globally Routable User Agent URI (GRUU) settings for one or more trusted applications.

  When you use this cmdlet to retrieve a single trusted application, you must supply a value for the Identity parameter.
  The Identity is the fully qualified domain name (FQDN) of the pool on which the application is homed followed by a slash (/) followed by the application ID.
  For example, TrustPool.litwareinc.com/tapp2, where TrustPool.litwareinc.com is the pool FQDN and tapp2 is the application ID.
  Note that when you retrieve an application by calling this cmdlet, you'll see an ID that looks more like this: TrustPool.litwareinc.com/urn:application:tapp2.
  Notice the prefix urn:application: before the application name (tapp2).
  While this prefix is part of the Identity, it's not required when you specify the value for the Identity parameter.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/get-cstrustedapplication
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Get-CsTrustedApplication
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
