### YamlMime:PowershellCmdlet
summary: |-
  Returns information about the Federal Information Processing Standards (FIPS) configuration settings currently in use in the organization.
  The FIPS standards are a set of United States government security standards required for use in computers maintained by non-military government agencies and by government contractors.
  This cmdlet was introduced in Lync Server 2013.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Rtc.Management.WritableConfig.Settings.FIPSConfiguration.FIPSConfiguration" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-CsFIPSConfiguration
  href: New-CsFIPSConfiguration.yml
- text: Remove-CsFIPSConfiguration
  href: Remove-CsFIPSConfiguration.yml
- text: Set-CsFIPSConfiguration
  href: Set-CsFIPSConfiguration.yml
syntaxes:
- Get-CsFIPSConfiguration [-Filter <String>] [-LocalStore] [-Tenant <Guid>] [<CommonParameters>]
- Get-CsFIPSConfiguration [[-Identity] <XdsIdentity>] [-LocalStore] [-Tenant <Guid>] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Get-CsFIPSConfiguration
  description: |-
    The command shown in Example 1 returns information for all the FIPS configuration settings currently in use in the organization.
    Note that there is only a single, global instance of FIPS configuration settings.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Enables you to use wildcard values when referencing a collection of FIPS configuration settings.
    Because you can only have a single, global instance of these settings there is no reason to use the Filter parameter.
    However, if you prefer you can use the following syntax to reference the global settings:

    `-Filter "g*"`

    That syntax brings back all the FIPS configuration settings that have an Identity that begins with the letter "g".

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Unique Identity of the FIPS configuration settings.
    Because you can only have a single, global instance of these settings, you do not need to specify an Identity when calling the Get-CsFIPSConfiguration cmdlet.
    If you prefer, however, you can use the following syntax to reference the global settings:

    `-Identity global`

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: LocalStore
  description: |+
    Retrieves the FIPS configuration data from the local replica of the Central Management store rather than from the Central Management store itself.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Guid" data-throw-if-not-resolved="False" />
  name: Tenant
  description: |+
    Globally unique identifier (GUID) of the Skype for Business Online tenant account whose FIPS configuration settings are to be retrieved.

    For example:

    `-Tenant "38aad667-af54-4397-aaa7-e94c79ec2308"`

    You can return the tenant ID for each of your tenants by running this command:

    `Get-CsTenant | Select-Object DisplayName, TenantID`

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Get-CsFIPSConfiguration
name: Get-CsFIPSConfiguration
description: |-
  The Federal Information Processing Standards (FIPS) are a series of standards and guidelines used by computers engaged in work for the US government; for example, there are FIPS standards that govern the use of such things as cryptography, encryption, and digital signatures.
  (See https://www.itl.nist.gov/fipspubs/by-num.htm (https://www.itl.nist.gov/fipspubs/by-num.htm) for more information.) Skype for Business Server provides an option that enables the software to use only algorithms that meet the FIPS standards.
  If you need to work with the United States government (or with other entities that follow FIPS) then you can enable FIPS compliance in Skype for Business Server.

  Keep in mind, however, that, for the on-premises version of Skype for Business Server, you have only a single, global collection of FIPS configuration settings: FIPS compliance can only be enabled or disabled for your entire Skype for Business Server implementation.
  You cannot selectively enable or disable FIPS compliance on, say, an individual site or an individual Registrar pool.
  If you do enable FIPS compliance, you could potentially encounter problems when trying to communicate with organizations that do not fully adhere to the FIPS standards.

  By default, FIPS compliance is disabled in Skype for Business Server.

  The functions carried out by the Get-CsFIPSConfiguration cmdlet are not available in the Skype for Business Server Control Panel.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/get-csfipsconfiguration
  applicable: Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Get-CsFIPSConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
