### YamlMime:PowershellCmdlet
summary: |-
  This command is used to get the current URI for setting PSTN calling and voice mail related settings.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- Get-CsUserSettingsPageConfiguration [[-Identity] <XdsIdentity>] [-LocalStore] [<CommonParameters>]
- Get-CsUserSettingsPageConfiguration [-Filter <String>] [-LocalStore] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> Get-CsUserSettingsPageConfiguration
  description: |-
    This example is used to retrieve the Global User Settings Page Configuration.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    The Filter parameter allows you to limit the number of results based on filters you specify.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    The Identity parameter is a unique identifier that designates the scope.

  defaultValue: None
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: LocalStore
  description: |+
    Retrieves the user pool information from the local replica of the Central Management store rather than from the Central Management store itself.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
applicable:
- Skype for Business Server 2019
uid: SkypeForBusiness.Get-CsUserSettingsPageConfiguration
name: Get-CsUserSettingsPageConfiguration
description: |-
  This command is used to get the current URI for setting PSTN calling and voice mail related settings. The Skype for Business Administrator may choose to update these URI based on their configured PSTN calling and Voice mail services using Set-CsUserSettingsPageConfiguration:
  - PstnCallingUri: The URI of the PstnCalling User settings page
  - VoicemailUri: The URI of the Voicemail tab in User Settings Portal
metadata:
  external help file: Microsoft.Rtc.Management.dll-Help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/get-csusersettingspageconfiguration
  applicable: Skype for Business Server 2019
  title: Get-CsUserSettingsPageConfiguration
  schema: 2.0.0
  manager: bulenteg
  author: tomkau
  ms.author: tomkau
  ms.reviewer: rogupta
