### YamlMime:PowershellCmdlet
summary: |-
  Returns information about the User Replicator configuration settings currently employed in your organization.
  The User Replicator periodically retrieves up-to-date user account information from Active Directory and then synchronizes the new information with the current user data stored by Skype for Business Server.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
    The Get-CsUserReplicatorConfiguration cmdlet does not accept pipelined input.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The Get-CsUserReplicatorConfiguration cmdlet returns instances of the Microsoft.Rtc.Management.WritableConfig.Settings.UserReplicator.UserReplicatorConfiguration object.
links:
- text: New-CsUserReplicatorConfiguration
  href: New-CsUserReplicatorConfiguration.yml
- text: Remove-CsUserReplicatorConfiguration
  href: Remove-CsUserReplicatorConfiguration.yml
- text: Set-CsUserReplicatorConfiguration
  href: Set-CsUserReplicatorConfiguration.yml
syntaxes:
- Get-CsUserReplicatorConfiguration [[-Identity] <XdsIdentity>] [-LocalStore] [<CommonParameters>]
- Get-CsUserReplicatorConfiguration [-Filter <String>] [-LocalStore] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Get-CsUserReplicatorConfiguration
  description: |-
    The command shown in Example 1 returns information about all the User Replicator configuration settings currently in use in your organization.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Enables you to use wildcards when specifying the collection (or collections) of User Replicator configuration settings to be returned.
    For example, this command returns all the settings configured at the service scope:

    -Filter "service:*"



  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Unique identifier of the User Replicator configuration settings to be returned.
    To return settings at the service scope, use syntax similar to this:

    -Identity "service:Registrar:atl-cs-001.litwareinc.com"

    Note that service scope settings are available only if you are running Skype for Business Online.
    To return the global settings, use this syntax:

    -Identity global

    If this parameter is not specified then all the User Replicator configurations settings currently in use in your organization will be returned.



  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: LocalStore
  description: |+
    Retrieves the User Replicator configuration data from the local replica of the Central Management store rather than from the Central Management store itself.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Get-CsUserReplicatorConfiguration
name: Get-CsUserReplicatorConfiguration
description: |-
  Although Skype for Business Server maintains its own database of user accounts and user account data, Skype for Business Server still relies on Active Directory as the ultimate source for user information.
  For example, when a new Active Directory user account is created, you must supply basic information about the user account (such as the Active Directory display name).
  When a user is enabled for Skype for Business Server, however, you do not need to specify a new display name for that user.
  That's because Skype for Business Server uses the display name already stored in Active Directory Domain Services.

  Of course, user account information (including the Active Directory display name) is subject to change over time.
  For example, a user who gets married might change her last name and, in turn, need to change her display name as well.
  In order to ensure that the Skype for Business Server database and Active Directory remain in synch Skype for Business Server must periodically check in with Active Directory, retrieve the latest user account updates, and then modify its own user database accordingly.
  This synchronization between Active Directory and Skype for Business Server is carried out by the User Replicator.

  When you install Skype for Business Server a global set of User Replicator configuration settings is created for you.
  By default, these settings are used to manage the User Replicator on an organization-wide basis.
  Management of the User Replicator consists of identifying the domains that Skype for Business Server needs to synch with as well as indicating how often the User Replicator checks Active Directory for user account updates.
  By default, the User Replicator discovers and synchs with all available domains.
  However, by using the AdDomainNamingContextList property you can restrict synchronization to a specific set of domains: the domains that appear in the AdDomainNamingContextList property.

  If you are working with Skype for Business Server you can also use the CsUserReplicatorConfiguration cmdlets to create and manage configuration settings at the service scope.
  However, with the on-premises version of Skype for Business Server you are limited to a single collection of configuration settings assigned to the global scope.

  The Get-CsUserReplicatorConfiguration cmdlet enables administrators to return information about all the User Replicator settings currently employed in their organization.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/get-csuserreplicatorconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Get-CsUserReplicatorConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
