### YamlMime:PowershellCmdlet
summary: |-
  Returns information about the Persistent Chat compliance configuration settings currently in use in the organization.
  Persistent Chat compliance enables administrators to maintain an archive of Persistent Chat items and activities including: new messages; new events (for example, a user entering or existing a chat room); file uploads and downloads; and any searches run against the chat history.
  This cmdlet was introduced in Lync Server 2013.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Rtc.Management.WritableConfig.Settings.PersistentChat.PersistentChatComplianceConfiguration" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-CsPersistentChatComplianceConfiguration
  href: New-CsPersistentChatComplianceConfiguration.yml
- text: Remove-CsPersistentChatComplianceConfiguration
  href: Remove-CsPersistentChatComplianceConfiguration.yml
- text: Set-CsPersistentChatComplianceConfiguration
  href: Set-CsPersistentChatComplianceConfiguration.yml
syntaxes:
- Get-CsPersistentChatComplianceConfiguration [-Filter <String>] [-LocalStore] [<CommonParameters>]
- Get-CsPersistentChatComplianceConfiguration [[-Identity] <XdsIdentity>] [-LocalStore] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Get-CsPersistentChatComplianceConfiguration
  description: |-
    The command shown in Example 1 returns information about all the Persistent Chat compliance configuration settings currently in use in your organization.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Get-CsPersistentChatComplianceConfiguration -Identity "site:Redmond"
  description: |-
    In Example 2, information is returned for the Persistent Chat compliance configuration settings applied to the Redmond site.
  summary: ""
- title: '-------------------------- Example 3 --------------------------'
  code: |-
    Get-CsPersistentChatComplianceConfiguration -Filter "service:*"
  description: |-
    Example 3 returns information about all the Persistent Chat compliance configuration settings applied to the service scope.
    This is done by including the Filter parameter and the filter value "service:*".
  summary: ""
- title: '-------------------------- Example 4 --------------------------'
  code: |-
    Get-CsPersistentChatComplianceConfiguration | Where-Object {$_.OneChatRoomPerOutputFile -eq $True}
  description: |-
    In Example 4, information is returned for all the Persistent Chat compliance configuration settings where the OneChatRoomPerOutputFile property is equal to True.
    To do this, the command first uses the Get-CsPersistentChatComplianceConfiguration to return a collection consisting of all the Persistent Chat compliance configuration settings.
    That collection is then piped to the Where-Object cmdlet, which picks out only those settings where the OneChatRoomPerOutputFile property is equal to True ($True).
  summary: ""
- title: '-------------------------- Example 5 --------------------------'
  code: |-
    Get-CsPersistentChatComplianceConfiguration | Where-Object {$_.CustomConfiguration -ne $Null}
  description: |-
    In Example 5, returned information is limited to Persistent Chat compliance configuration settings where the CustomConfiguration property is set to a null value.
    To carry out this task, the command first uses the Get-CsPersistentChatComplianceConfiguration cmdlet to return a collection of all the Persistent Chat compliance configuration settings currently in use.
    That collection is then piped to the Where-Object cmdlet, which selects only those settings where CustomConfiguration is equal to a null value ($Null)
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Enables you to use wildcards when specifying the collection (or collections) of Persistent Chat compliance settings to be returned.
    For example, this syntax returns all the settings policies configured at the service scope:

    `-Filter "service:*"`

    The Filter and Identity parameters cannot be used in the same command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Unique identifier for the Persistent Chat compliance settings to be returned.
    To return the global collection, use this syntax:

    `-Identity "global"`

    To return a collection of settings configured at the site scope, use syntax similar to this:

    `-Identity "site:Redmond"`

    To return a collection configured at the service scope, use syntax like this:

    `-Identity "service:PersistentChatServer:atl-gc-001.litwareinc.com"`

    Note that you cannot use wildcards with the Identity parameter.

    If neither the Identity parameter nor the Filter parameter are included in a command then the Get-CsPersistentChatComplianceConfiguration cmdlet will return information about all the Persistent Chat compliance settings in use in your organization.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: LocalStore
  description: |+
    Retrieves the Persistent Chat compliance data from the local replica of the Central Management store rather than from the Central Management store itself.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  parameterValueGroup: ""
applicable:
- Lync Server 2013
- Skype for Business Server 2015
uid: SkypeForBusiness.Get-CsPersistentChatComplianceConfiguration
name: Get-CsPersistentChatComplianceConfiguration
description: |-
  The Persistent Chat service provides organizations with messaging and collaboration capabilities similar to those found in Internet discussion forums: users can exchange messages in real-time, yet can also revisit and restart those conversations at any time.
  Conversations can be based around specific topics, and these conversations can be made available to everyone or to only a selected set of users.
  Likewise, individual chat rooms can be configured so that anyone can post a message or configured so that only designated presenters can post messages.

  Many organizations (including organizations involved in health care and organizations involved in the financial industry) are required to maintain archives of all their electronic communications; this includes conversations that might take place using the Persistent Chat service.
  Lync Server allows you to create a separate compliance database that keeps a detailed of archive of everything that happens in your Persistent Chat chat rooms.
  Persistent Chat compliance can be enabled or disabled at the site scope or at the service scope (that is, compliance can be enabled or disabled for a given Persistent Chat pool).
  In addition, Persistent Chat compliance can only be managed using the Windows PowerShell command-line interface; there are no options available in the Skype for Business Server Control Panel for managing Persistent Chat compliance.

  The functions carried out by the Get-CsPersistentChatComplianceConfiguration cmdlet are not available in the Skype for Business Server Control Panel.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/get-cspersistentchatcomplianceconfiguration
  applicable: Lync Server 2013, Skype for Business Server 2015
  title: Get-CsPersistentChatComplianceConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
