### YamlMime:PowershellCmdlet
summary: |-
  Returns information related to managing the upgrade to Teams from Skype for Business. TeamsUpgradeConfiguration should be used in conjunction with TeamsUpgradePolicy. The settings in TeamsUpgradeConfiguration allow administrators to configure whether users subject to upgrade and who are running on Windows clients should automatically download Teams. For Office 365 users, it allows administrators to determine which application end users should use to join Skype for Business meetings.
module: SkypeForBusiness
notes: |-
  These settings are only honored by newer versions of Skype for Business clients.
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Set-CsTeamsUpgradeConfiguration
  href: Set-CsTeamsUpgradeConfiguration.yml
- text: Get-CsTeamsUpgradePolicy
  href: Get-CsTeamsUpgradePolicy.yml
- text: Grant-CsTeamsUpgradePolicy
  href: Grant-CsTeamsUpgradePolicy.yml
- text: Migration and interoperability guidance for organizations using Teams together with Skype for Business
  href: https://learn.microsoft.com/MicrosoftTeams/migration-interop-guidance-for-teams-with-skype
syntaxes:
- >-
  Get-CsTeamsUpgradeConfiguration [-Tenant <Guid>] [[-Identity] <XdsIdentity>] [-LocalStore]

   [<CommonParameters>]
- Get-CsTeamsUpgradeConfiguration [-Tenant <Guid>] [-Filter <String>] [-LocalStore] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> Get-CsTeamsUpgradeConfiguration
  description: |-
    The above cmdlet lists the properties of TeamsUpgradeConfiguration.
  summary: ""
parameters:
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    {{Fill Identity Description}}

  defaultValue: None
  position: "1"
  aliases: ""
  applicable:
  - Skype for Business Online
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: LocalStore
  description: |+
    Do not use

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Guid" data-throw-if-not-resolved="False" />
  name: Tenant
  description: |+
    {{Fill Tenant Description}}

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Skype for Business Online
- Skype for Business Server 2019
uid: SkypeForBusiness.Get-CsTeamsUpgradeConfiguration
name: Get-CsTeamsUpgradeConfiguration
description: |-
  TeamsUpgradeConfiguration is used in conjunction with TeamsUpgradePolicy. The settings in TeamsUpgradeConfiguration allow administrators to configure whether users subject to upgrade and who are running on Windows clients should automatically download the Teams app. It also allows administrators to determine which application Office 365 users should use to join Skype for Business meetings.

  Separate instances of TeamsUpgradeConfiguration exist in Office 365 and Skype for Business Server. 
   - TeamsUpgradeConfiguration in Office 365 applies to any user who does not have an on-premises Skype for Business account.
   - TeamsUpgradeConfiguration in Skype for Business Server can used to manage on-premises users in a hybrid environment. In on-premises, only the DownloadTeams property is available.

  The DownloadTeams property allows admins to control whether the Skype for Business client should automatically download the Teams app in the background. This setting is only honored for users on Windows clients, and only if TeamsUpgradePolicy for the user meets either of these conditions: 
   - NotifySfbUser=true, or 
   - Mode=TeamsOnly
   Otherwise, this setting is ignored. 

  The SfBMeetingJoinUx property allows admins to specify which app is used to join Skype for Business meetings, even after the user has been upgraded to Teams. Allowed values are: SkypeMeetingsApp and NativeLimitedClient.   "NativeLimitedClient"  means the existing Skype for Business rich client will be used, but since the user is upgraded, only meeting functionality is available. Calling and Messaging are done via Teams.  "SkypeMeetingsApp" means use the web-downloadable app. This setting can be useful for organizations that have upgraded to Teams and no longer want to install Skype for Business on their users' computers. This property is only available when configuring TeamsUpgradeConfiguration in Office 365. It is not honored for users homed on-premises in Skype for Business Server.
metadata:
  external help file: Microsoft.Rtc.Management.Hosted.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/get-csteamsupgradeconfiguration
  applicable: Skype for Business Online, Skype for Business Server 2019
  title: Get-CsTeamsUpgradeConfiguration
  schema: 2.0.0
  manager: bulenteg
  author: tomkau
  ms.author: tomkau
  ms.reviewer: rogupta
