### YamlMime:PowershellCmdlet
summary: |-
  Returns information about the configuration settings for computers running the Access Edge service in your organization (also known as Access Edge servers).
  Access Edge servers provide a way for users outside your internal network to communicate with users inside your internal network.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Rtc.Management.WritableConfig.Settings.Edge.DisplayAccessEdgeSettingsDnsSrvRouting" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Rtc.Management.WritableConfig.Settings.Edge.DisplayAccessEdgeSettingsDefaultRoute" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Set-CsAccessEdgeConfiguration
  href: Set-CsAccessEdgeConfiguration.yml
syntaxes:
- Get-CsAccessEdgeConfiguration [[-Identity] <XdsIdentity>] [-LocalStore] [<CommonParameters>]
- Get-CsAccessEdgeConfiguration [-Filter <String>] [-LocalStore] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Get-CsAccessEdgeConfiguration
  description: |-
    Example 1 demonstrates the basic use of the Get-CsAccessEdgeConfiguration cmdlet: calling the cmdlet without any additional parameters returns all the property values for your Access Edge server implementation.
    Note that there is no need to include the Identity or Filter parameters; that's because there is only one set of Access Edge server configuration data.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Get-CsAccessEdgeConfiguration | Select-Object Allow*
  description: |-
    Example 2 returns just three property values for your Access Edge server configuration: AllowAnonymousUsers; AllowFederatedUsers; and AllowOutsideUsers.
    To do this, the command first uses the Get-CsAccessEdgeConfiguration cmdlet to return all the Access Edge server property values.
    This information is then piped to the Select-Object cmdlet, which picks out only those properties that start with the string value "Allow".
    In turn, those are the only property values displayed on the screen.
  summary: ""
- title: '-------------------------- Example 3 --------------------------'
  code: |-
    (Get-CsAccessEdgeConfiguration).EnablePartnerDiscovery
  description: |-
    The command shown in Example 3 returns the value of a single Access Edge server configuration property: EnablePartnerDiscovery.
    To do this, the Get-CsAccessEdgeConfiguration cmdlet is first called in order to return all the Access Edge server configuration property values.
    The call to the Get-CsAccessEdgeConfiguration cmdlet is enclosed in parentheses; this ensures that Windows PowerShell completes this command before doing anything else.
    After all the property values have been returned, standard "dot notation" (the object name followed by a period followed by a property name) is used to display the value of a single property: EnablePartnerDiscovery.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Enables you to use wildcards when specifying the Access Edge configuration settings to be returned.
    Because you can only have a single, global instance of these settings there is little reason to use the Filter parameter.
    However, if you prefer, you can use syntax similar to this to retrieve the global settings: -Identity "g*".

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Unique identifier of the Access Edge configuration settings to be returned.
    Because you can only have a single, global instance of these settings, you do not have to include the Identity when calling the Get-CsAccessEdgeConfiguration cmdlet.
    However, you can use the following syntax to retrieve the global settings: -Identity global.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: LocalStore
  description: |+
    Retrieves the Access Edge configuration data from the local replica of the Central Management store rather than from the Central Management store itself.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Get-CsAccessEdgeConfiguration
name: Get-CsAccessEdgeConfiguration
description: |-
  Access Edge servers (also known as access proxy servers) provide a way for you to extend the capabilities of Skype for Business Server to people who are not logged on to your internal network.
  For example, if you have remote users -- authenticated users who log on to Skype for Business Server over the Internet rather than through the internal network -- you will need to set up an Access Edge server.
  Additionally, Edge Servers are required if you want to establish federation with another organization or if you want to give your users the right to communicate with people who have accounts with a public instant messaging service such as Yahoo!, AOL, or MSN.
  Access Edge servers sit on the perimeter network, and are used to make and validate SIP connections between users inside and outside of your internal network.

  In Skype for Business Server, the Access Edge servers are managed by using a single, global collection of configuration settings.
  The Get-CsAccessEdgeConfiguration cmdlet enables you to return information about these global settings.
  Note that the property values returned by the Get-CsAccessEdgeConfiguration cmdlet will vary depending on the type of routing you have configured for your Edge Servers.
  For details, see the Set-CsAccessEdgeConfiguration Help topic.

  By default, members of the following groups are authorized to run the Get-CsAccessEdgeConfiguration cmdlet locally: RTCUniversalUserAdmins, RTCUniversalServerAdmins.
  To return a list of all the role-based access control (RBAC) roles this cmdlet has been assigned to (including any custom RBAC roles you have created yourself), run the following command from the Windows PowerShell prompt:

  `Get-CsAdminRole | Where-Object {$_.Cmdlets -match "Get-CsAccessEdgeConfiguration"}`
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/get-csaccessedgeconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Get-CsAccessEdgeConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
