### YamlMime:PowershellCmdlet
summary: |-
  **Below Content Applies To:** Lync Server 2010

  Retrieves settings for one or more pools that contain the computers that host trusted applications.

  **Below Content Applies To:** Lync Server 2013, Skype for Business Server 2015

  Retrieves settings for one or more pools that contain the computers that host trusted applications.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Retrieves one or more objects of type Microsoft.Rtc.Management.Xds.DisplayExternalServer.
links:
- text: New-CsTrustedApplicationPool
  href: New-CsTrustedApplicationPool.yml
- text: Remove-CsTrustedApplicationPool
  href: Remove-CsTrustedApplicationPool.yml
- text: Set-CsTrustedApplicationPool
  href: Set-CsTrustedApplicationPool.yml
syntaxes:
- >-
  Get-CsTrustedApplicationPool [[-Identity] <XdsGlobalRelativeIdentity>] [-PoolFqdn <String>]

   [<CommonParameters>]
- Get-CsTrustedApplicationPool [-Filter <String>] [-PoolFqdn <String>] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 ------------------------ (Lync Server 2010)'
  code: |-
    Get-CsTrustedApplicationPool
  description: |-
    Example 1 retrieves all pools within the Lync Server 2010 deployment that have been defined as trusted application pools.
  summary: ""
- title: '-------------------------- EXAMPLE 1 -------------------------- (Lync Server 2013)'
  code: ""
  description: |-
    Example 1 retrieves all pools within the Lync Server deployment that have been defined as trusted application pools.

    Get-CsTrustedApplicationPool
  summary: ""
- title: '-------------------------- EXAMPLE 1 -------------------------- (Skype for Business Server 2015)'
  code: ""
  description: |-
    Example 1 retrieves all pools within the Skype for Business Server 2015 deployment that have been defined as trusted application pools.

    Get-CsTrustedApplicationPool
  summary: ""
- title: '-------------------------- Example 2 ------------------------ (Lync Server 2010)'
  code: |-
    Get-CsTrustedApplicationPool -Identity TrustPool.litwareinc.com
  description: |-
    In this example, we've used the Identity parameter to ensure we retrieve only one trusted application pool, in this case the pool with the FQDN TrustPool.litwareinc.com.
  summary: ""
- title: '-------------------------- EXAMPLE 2 -------------------------- (Lync Server 2013)'
  code: ""
  description: |-
    In this example, we've used the Identity parameter to ensure we retrieve only one trusted application pool, in this case the pool with the FQDN TrustPool.litwareinc.com.

    Get-CsTrustedApplicationPool -Identity TrustPool.litwareinc.com
  summary: ""
- title: '-------------------------- EXAMPLE 2 -------------------------- (Skype for Business Server 2015)'
  code: ""
  description: |-
    In this example, we've used the Identity parameter to ensure we retrieve only one trusted application pool, in this case the pool with the FQDN TrustPool.litwareinc.com.

    Get-CsTrustedApplicationPool -Identity TrustPool.litwareinc.com
  summary: ""
- title: '-------------------------- Example 3 ------------------------ (Lync Server 2010)'
  code: |-
    Get-CsTrustedApplicationPool -Filter *:TrustPool.*
  description: |-
    This example retrieves all trusted application pools that contain the site TrustPool in the pool FQDN.
    The Filter parameter is used with a value of *:TrustPool.*.
    This filter string will search the Identity values of all trusted application pools for those that contain the string ":TrustPool.".
    For example, this command will retrieve the pool with the Identity value TrustedApplicationPool:TrustPool.litwareinc.com.
  summary: ""
- title: '-------------------------- EXAMPLE 3 -------------------------- (Lync Server 2013)'
  code: ""
  description: |-
    This example retrieves all trusted application pools that contain the site TrustPool in the pool FQDN.
    The Filter parameter is used with a value of *:TrustPool.*.
    This filter string will search the Identity values of all trusted application pools for those that contain the string ":TrustPool.".
    For example, this command will retrieve the pool with the Identity value TrustedApplicationPool:TrustPool.litwareinc.com.

    Get-CsTrustedApplicationPool -Filter *:TrustPool.*
  summary: ""
- title: '-------------------------- EXAMPLE 3 -------------------------- (Skype for Business Server 2015)'
  code: ""
  description: |-
    This example retrieves all trusted application pools that contain the site TrustPool in the pool FQDN.
    The Filter parameter is used with a value of *:TrustPool.*.
    This filter string will search the Identity values of all trusted application pools for those that contain the string ":TrustPool.".
    For example, this command will retrieve the pool with the Identity value TrustedApplicationPool:TrustPool.litwareinc.com.

    Get-CsTrustedApplicationPool -Filter *:TrustPool.*
  summary: ""
- title: '-------------------------- Example 4 ------------------------ (Lync Server 2010)'
  code: |-
    Get-CsTrustedApplicationPool | Where-Object {$_.ServiceId -like "Redmond1*"}
  description: |-
    The Filter parameter searches only on Identity, which in the case of trusted application pools is the service ID in the format TrustedApplicationPool:\<FQDN\>.
    This example searches for pools based on service ID in the format \<site\>-ExternalServer-\<id\>; for example, Redmond1-ExternalServer-1.
    This allows us to find trusted pools homed on a specific site.
    The example begins by calling Get-CsTrustedApplicationPool with no parameters, which retrieves a collection of all trusted application pools.
    This collection is then piped to the Where-Object cmdlet, which narrows down the collection to only those pools where the service ID ($_.ServiceId) matches the wildcard string (-like) Redmond1*.
    The result will be a collection of all trusted application pools with FQDNs beginning with the string Redmond1, such as Redmond1-ExternalServer-1, Redmond1-ExternalServer-2, and Redmond1-ExternalServer-3.
  summary: ""
- title: '-------------------------- EXAMPLE 4 -------------------------- (Lync Server 2013)'
  code: ""
  description: |-
    The Filter parameter searches only on Identity, which in the case of trusted application pools is the service ID in the format TrustedApplicationPool:\<FQDN\>.
    This example searches for pools based on service ID in the format \<site\>-ExternalServer-\<id\>; for example, Redmond1-ExternalServer-1.
    This allows us to find trusted pools homed on a specific site.
    The example begins by calling Get-CsTrustedApplicationPool with no parameters, which retrieves a collection of all trusted application pools.
    This collection is then piped to the Where-Object cmdlet, which narrows down the collection to only those pools where the service ID ($_.ServiceId) matches the wildcard string (-like) Redmond1*.
    The result will be a collection of all trusted application pools with FQDNs beginning with the string Redmond1, such as Redmond1-ExternalServer-1, Redmond1-ExternalServer-2, and Redmond1-ExternalServer-3.

    Get-CsTrustedApplicationPool | Where-Object {$_.ServiceId -like "Redmond1*"}
  summary: ""
- title: '-------------------------- EXAMPLE 4 -------------------------- (Skype for Business Server 2015)'
  code: ""
  description: |-
    The Filter parameter searches only on Identity, which in the case of trusted application pools is the service ID in the format TrustedApplicationPool:\<FQDN\>.
    This example searches for pools based on service ID in the format \<site\>-ExternalServer-\<id\>; for example, Redmond1-ExternalServer-1.
    This allows us to find trusted pools homed on a specific site.
    The example begins by calling the Get-CsTrustedApplicationPool cmdlet with no parameters, which retrieves a collection of all trusted application pools.
    This collection is then piped to the Where-Object cmdlet, which narrows down the collection to only those pools where the service ID ($_.ServiceId) matches the wildcard string (-like) Redmond1*.
    The result will be a collection of all trusted application pools with FQDNs beginning with the string Redmond1, such as Redmond1-ExternalServer-1, Redmond1-ExternalServer-2, and Redmond1-ExternalServer-3.

    Get-CsTrustedApplicationPool | Where-Object {$_.ServiceId -like "Redmond1*"}
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    A string containing one or more wildcard characters that is used to search for a pool with an Identity that matches the wildcard string.
    For example, specifying the string *Redmond* would retrieve all trusted application pools with identities containing the string Redmond, such as TrustedApplicationPool:Redmond.litwareinc.com.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsGlobalRelativeIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    The fully qualified domain name (FQDN) or service ID of the pool for which you want to retrieve settings.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: PoolFqdn
  description: |+
    The FQDN of the pool you want to retrieve.
    This behaves the same as the Identity parameter, except that Identity also accepts a service ID.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Get-CsTrustedApplicationPool
name: Get-CsTrustedApplicationPool
description: |-
  **Below Content Applies To:** Lync Server 2010

  It is recommended that computers that are running trusted applications within a Microsoft Lync Server 2010 deployment be added to a separate pool that is only for trusted applications.
  However, you can add trusted application computers to an existing pool that is also used for other purposes.
  This cmdlet retrieves one or more pools that have been defined as trusted application pools.

  Who can run this cmdlet: By default, members of the following groups are authorized to run the Get-CsTrustedApplicationPool cmdlet locally: RTCUniversalUserAdmins, RTCUniversalServerAdmins.
  To return a list of the role-based access control (RBAC) roles this cmdlet has been assigned to (including any custom RBAC roles you have created yourself), run the following command from the Windows PowerShell prompt:

  Get-CsAdminRole | Where-Object {$_.Cmdlets -match "Get-CsTrustedApplicationPool"}

  **Below Content Applies To:** Lync Server 2013

  It is recommended that computers that are running trusted applications within a Lync Server deployment be added to a separate pool that is only for trusted applications.
  However, you can add trusted application computers to an existing pool that is also used for other purposes.
  This cmdlet retrieves one or more pools that have been defined as trusted application pools.

  Who can run this cmdlet: By default, members of the following groups are authorized to run the Get-CsTrustedApplicationPool cmdlet locally: RTCUniversalUserAdmins, RTCUniversalServerAdmins.
  To return a list of the role-based access control (RBAC) roles this cmdlet has been assigned to (including any custom RBAC roles you have created yourself), run the following command from the Windows PowerShell prompt:

  Get-CsAdminRole | Where-Object {$_.Cmdlets -match "Get-CsTrustedApplicationPool"}

  **Below Content Applies To:** Skype for Business Server 2015

  It is recommended that computers that are running trusted applications within a Skype for Business Server 2015 deployment be added to a separate pool that is only for trusted applications.
  However, you can add trusted application computers to an existing pool that is also used for other purposes.
  This cmdlet retrieves one or more pools that have been defined as trusted application pools.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/get-cstrustedapplicationpool
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Get-CsTrustedApplicationPool
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
