### YamlMime:PowershellCmdlet
summary: |-
  Retrieves information about one or more computers that host trusted applications.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Rtc.Management.Xds.DisplayComputer" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-CsTrustedApplicationComputer
  href: New-CsTrustedApplicationComputer.yml
- text: Remove-CsTrustedApplicationComputer
  href: Remove-CsTrustedApplicationComputer.yml
syntaxes:
- >-
  Get-CsTrustedApplicationComputer [[-Identity] <XdsGlobalRelativeIdentity>] [-Pool <String>] [-Local]

   [<CommonParameters>]
- Get-CsTrustedApplicationComputer [-Filter <String>] [-Pool <String>] [-Local] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Get-CsTrustedApplicationComputer
  description: |-
    Example 1 retrieves all computers that have been assigned to any trusted application pool within the Skype for Business Server deployment.
  summary: ""
- title: '-------------------------- Example 2 -------------------------- (Skype for Business Server 2015)'
  code: |-
    Get-CsTrustedApplicationComputer -Identity Trust1.litwareinc.com
  description: |-
    Example 2 retrieves information about the computer with the FQDN Trust1.litwareinc.com.
  summary: ""
- title: '-------------------------- Example 3 --------------------------'
  code: |-
    Get-CsTrustedApplicationComputer -Filter Trust*
  description: |-
    This example uses the Filter parameter to do a wildcard search for all computers that have an FQDN beginning with the string Trust that have been assigned to trusted application pools.
    The Filter parameter searches the Identity property of all trusted application computers.
    The wildcard character (*) at the end of the string means that the Filter should look for identities that begin with the string Trust followed by any other characters.
  summary: ""
- title: '-------------------------- Example 4 --------------------------'
  code: |-
    Get-CsTrustedApplicationComputer -Pool TrustPool.litwareinc.com
  description: |-
    Example 4 retrieves a list of all computers that have been assigned to the trusted application pool TrustPool.litwareinc.com.
  summary: ""
- title: '-------------------------- Example 5 --------------------------'
  code: |-
    Get-CsTrustedApplicationComputer | Where-Object {$_.Pool -like "*.litwareinc.com"}
  description: |-
    In Example 3 we used the Filter parameter to do a wildcard search based on Identity (the FQDN of the computer).
    In this example, we're again doing a wildcard search, but this time on the pool rather than the identity.
    We first call the Get-CsTrustedApplicationComputer cmdlet to retrieve a collection of all the trusted application computers.
    We then pipe that collection to the Where-Object cmdlet.
    The Where-Object cmdlet enables us to narrow down the collection that has been piped to it.
    In this case we want to keep only the trusted application computers that are in any pool on the litwareinc.com domain.
    To do this we check the Pool property of each item in the collection ($_.Pool) and see if it matches (-like) the wildcard string *.litwareinc.com.
    A value will match that string if it begins with any set of characters and ends with the string .litwareinc.com.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    A string that includes wildcards that enables you to retrieve trusted computers based on Identity values that match the given wildcard string.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsGlobalRelativeIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    The fully qualified domain name (FQDN) of the computer you want to retrieve.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Local
  description: |+
    When present, returns information only for the local computer.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Pool
  description: |+
    The FQDN of the trusted application pool for which you want to retrieve computer information.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Get-CsTrustedApplicationComputer
name: Get-CsTrustedApplicationComputer
description: |-
  We recommend that the computers that are running trusted applications within a Skype for Business Server deployment be added to a separate pool that is only for trusted applications.
  However, you can add trusted application computers to an existing pool that is also used for other purposes.
  Use this cmdlet to retrieve the Identity (FQDN) and the pool on which it is located of one of more computers that contain trusted applications.

  You can use this cmdlet to retrieve computers based on the computer FQDN or to retrieve all the computers that are part of a specified pool.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/get-cstrustedapplicationcomputer
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Get-CsTrustedApplicationComputer
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
