### YamlMime:PowershellCmdlet
summary: |-
  Use the Get-CsTelemetryConfiguration cmdlet to return the settings on existing telemetry configurations. 
  Telemetry returns a small set of Skype for Business operational data to Microsoft for quality tracking and product improvement. The data includes sign-in information, meeting joins, and other activity data.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Rtc.Management.WritableConfig.Settings.SignInTelemetry.SignInTelemetryConfiguration" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- Get-CsTelemetryConfiguration [-Filter <String>] [-LocalStore] [<CommonParameters>]
- Get-CsTelemetryConfiguration [[-Identity] <XdsIdentity>] [-LocalStore] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Get-CsTelemetryConfiguration -Identity Site:Redmond
  description: |-
    This example returns the settings for the configuration scoped to the Redmond site.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Enables you to use wildcard characters in order to return one or more collections of telemetry configuration settings.
    For example, to return all the settings that have been configured at the site scope use the following syntax: -Filter "site:*".
    The Filter and the Identity parameters are mutually exclusive.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    A unique identifier that includes the scope of the telemetry configuration.
    Telemetry configurations can be scoped at the Global, Site, or Service level.
    For example, "site:Redmond" (for site).
    The format of the service scope is "Service:\<Identity\>", where identity is derived from the topology.
    You can use the following cmds to identify the relevant services.

    `Get-CsService -WebServer | fl Identity`

    `Get-CsService -PoolFqdn \<pool\> | fl Identity`

    The first command will give you all of the WebServices in the topology, regardless of the pool.
    The second will give you all of the services on the pool, regardless of their role.
    You can combine the two commands to zero in on a single role in a single pool.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: LocalStore
  description: |+
    Retrieves the information from the local replica of the Central Management store, rather than the Central Management store itself.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Get-CsTelemetryConfiguration
name: Get-CsTelemetryConfiguration
description: |-
  For privacy information, see the Skype for Business Privacy Statement (https://go.microsoft.com/fwlink/?LinkID=517480&clcid=0x409).
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/get-cstelemetryconfiguration
  applicable: Skype for Business Server 2015, Skype for Business Server 2019
  title: Get-CsTelemetryConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
