### YamlMime:PowershellCmdlet
summary: |-
  Returns information about all the Web Services configuration settings in use in your organization.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
    The Get-CsWebServiceConfiguration cmdlet does not accept pipelined input.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The Get-CsWebServiceConfiguration cmdlet returns instances of the Microsoft.Rtc.Management.WritableConfig.Web.WebServiceSettings object.
links:
- text: New-CsWebServiceConfiguration
  href: New-CsWebServiceConfiguration.yml
- text: Remove-CsWebServiceConfiguration
  href: Remove-CsWebServiceConfiguration.yml
- text: Set-CsWebServiceConfiguration
  href: Set-CsWebServiceConfiguration.yml
syntaxes:
- Get-CsWebServiceConfiguration [[-Identity] <XdsIdentity>] [-LocalStore] [<CommonParameters>]
- Get-CsWebServiceConfiguration [-Filter <String>] [-LocalStore] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 ------------------------'
  code: |-
    Get-CsWebServiceConfiguration
  description: |-
    Example 1 returns information about all the Web Services configuration settings currently in use in the organization.
  summary: ""
- title: '-------------------------- Example 2 ------------------------'
  code: |-
    Get-CsWebServiceConfiguration -Identity site:Redmond
  description: |-
    The command shown in Example 2 returns information about the Web Services configuration settings that have the Identity site:Redmond.
  summary: ""
- title: '-------------------------- Example 3 ------------------------'
  code: |-
    Get-CsWebServiceConfiguration -Filter "site:*"
  description: |-
    Example 3 returns all the Web Services configuration settings that have been assigned at the site scope.
    To do this, the Filter parameter is included when calling the Get-CsWebServiceConfiguration cmdlet; the filter value "site:*" ensures that only those settings that have an Identity that begins with the string value "site:" are returned.
  summary: ""
- title: '-------------------------- Example 4 ------------------------'
  code: |-
    Get-CsWebServiceConfiguration | Where-Object {$_.UsePinAuth -eq $False}
  description: |-
    In Example 4, the command returns all the Web Services configuration settings that do not allow personal identification number (PIN) authentication.
    This is done by first calling the Get-CsWebServiceConfiguration cmdlet to return all the Web Services configuration settings currently in use.
    This collection is then piped to the Where-Object cmdlet, which picks out only those settings where the UsePinAuth property is equal to False.
  summary: ""
- title: '-------------------------- Example 5 ------------------------'
  code: |-
    Get-CsWebServiceConfiguration | Where-Object {$_.MaxGroupSizeToExpand -gt 100}
  description: |-
    Example 5 returns all the Web Services configuration settings where the maximum group expansion size is greater than 100.
    To do this, the command first uses the Get-CsWebServiceConfiguration cmdlet to return all the Web Services configuration settings currently in use.
    This information is then piped to the Where-Object cmdlet, which selects only those settings where the MaxGroupSizeToExpand property is greater than 100.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Enables you to use wildcards when specifying the Web Services configuration settings collection (or collections) to be returned.
    For example, this syntax returns all the settings configured at the site scope:

    -Filter "site:*"

    You cannot use both the Filter and the Identity parameters in the same command.



  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Unique identifier for the Web Services configuration settings to be returned.
    To return the global settings, use this syntax:

    -Identity global

    To return settings configured at the site scope, use syntax similar to this:

    -Identity "site:Redmond"

    Service-scope settings can be returned using syntax like this:

    -Identity "service:WebServer:atl-cs-001.litwareinc.com"

    You cannot use both the Filter and the Identity parameters in the same command.
    If you do not specify either parameter, the Get-CsWebServiceConfiguration cmdlet will return all the Web Services settings collections currently in use in your organization.



  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: LocalStore
  description: |+
    Retrieves the Web Services configuration data from the local replica of the Central Management store rather than from the Central Management store itself.



  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Get-CsWebServiceConfiguration
name: Get-CsWebServiceConfiguration
description: |-
  Many Skype for Business Server components are web-based: these components either use web services or webpages to carry out their tasks.
  For example, users employ a web service when searching for new contacts in the Address Book or when using group expansion to view the individual members of a distribution group.
  Likewise, components ranging from dial-in conferencing to Skype for Business Server Control Panel use webpages as the interface between Skype for Business Server and users.

  The CsWebServiceConfiguration cmdlets enable administrators to manage Web Services configuration settings throughout the organization; this includes managing group expansion, certificate settings, and allowed authentication methods.
  Because you can configure different settings at the global, site, and service scope (albeit for the only the Web Services service), you can customize Web Services capabilities for different users and different locations.

  The Get-CsWebServiceConfiguration cmdlet enables you to return detailed information about the Web Services configuration settings currently in use in your organization.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/get-cswebserviceconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Get-CsWebServiceConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
