### YamlMime:PowershellCmdlet
summary: |-
  Returns information about the Registrar configuration settings currently in use in your organization.
  Registrars are used to authenticate logon requests and to maintain information about user status and availability.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Rtc.Management.WritableConfig.Settings.Registrar.RegistrarSettings" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-CsRegistrarConfiguration
  href: New-CsRegistrarConfiguration.yml
- text: Remove-CsRegistrarConfiguration
  href: Remove-CsRegistrarConfiguration.yml
- text: Set-CsRegistrarConfiguration
  href: Set-CsRegistrarConfiguration.yml
syntaxes:
- Get-CsRegistrarConfiguration [[-Identity] <XdsIdentity>] [-LocalStore] [<CommonParameters>]
- Get-CsRegistrarConfiguration [-Filter <String>] [-LocalStore] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Get-CsRegistrarConfiguration
  description: |-
    The command shown in Example 1 returns a collection of all the Registrar configuration settings currently in use in the organization.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Get-CsRegistrarConfiguration -Identity site:Redmond
  description: |-
    Example 2 returns a single collection of Registrar configuration settings: the settings configured for the Redmond site (-Identity site:Redmond).
  summary: ""
- title: '-------------------------- Example 3 --------------------------'
  code: |-
    Get-CsRegistrarConfiguration -Filter "service:*"
  description: |-
    In Example 3, information is returned for all the Registrar configuration settings assigned at the service scope.
    To do this, the command uses the Filter parameter and the filter value "service:*"; that filter value ensures that only settings that have an Identity that begins with the string value "service:" will be returned.
  summary: ""
- title: '-------------------------- Example 4 --------------------------'
  code: |-
    Get-CsRegistrarConfiguration | Where-Object {$_.EnableDHCPServer -eq $True}
  description: |-
    Example 4 returns information about the Registrar configuration settings that enable the use of DHCP servers in order to register clients.
    To carry out this task, the command first calls the Get-CsRegistrarConfiguration cmdlet without any parameters; that returns a collection of all the Registrar configuration settings currently in use.
    This collection is then piped to the Where-Object cmdlet, which selects only those settings where the EnableDHCPServer property is equal to True.
  summary: ""
- title: '-------------------------- Example 5 --------------------------'
  code: |-
    Get-CsRegistrarConfiguration | Where-Object {$_.MaxEndpointsPerUser -gt 8}
  description: |-
    In Example 5, information is returned for all the Registrar configuration settings that allow more than eight endpoints per user.
    To accomplish this, the command first uses the Get-CsRegistrarConfiguration cmdlet to return a collection of all the Registrar configuration settings used in the organization.
    This collection is then piped to the Where-Object cmdlet, which picks out those settings where the MaxEndpointsPerUser property is greater than 8.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Enables you to use wildcards in order to return one or more collections of Registrar configuration settings.
    For example, to return all the settings configured at the site scope, use this syntax:

    `-Filter "site:*"`

    To return all the settings configured at the service scope, use this syntax:

    `-Filter "service:*"`

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Unique identifier for the Registrar configuration settings to be returned.
    To return the global settings, use this syntax:

    `-Identity global`

    To return settings configured at the site scope, use syntax similar to this:

    `-Identity site:Redmond`

    To return settings at the service level, use syntax like this:

    `-Identity service:Registrar:atl-cs-001.litwareinc.com`

    If this parameter is omitted then the Get-CsRegistrarConfiguration cmdlet returns all of the Registrar configuration settings currently in use in your organization.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: LocalStore
  description: |+
    Retrieves the Registrar configuration settings data from the local replica of the Central Management store rather than from the Central Management store itself.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Get-CsRegistrarConfiguration
name: Get-CsRegistrarConfiguration
description: |-
  The Registrar is perhaps the most important component in Skype for Business Server; after all, without a Registrar, users would not be able to log on to the system, and Skype for Business Server would not be able to keep track of users and their current status.
  When a user logs on to Skype for Business Server, the endpoint the user is logging on from sends a REGISTER request to the Registrar; in turn, the server responds by challenging the client device for authentication credentials.
  If the client passes the challenge (that is, if the client presents a valid set of credentials), then the user is authenticated and endpoint information such as IP address, port, and user name is logged in the registration database.
  When a user logs off, this information is then removed from the database.
  In between log on and log off, the Registrar keeps status information up-to-date and helps to route messages to and from the user.

  Registrar configuration settings are used to help manage endpoints and endpoint subscriptions; these settings can be applied at the global, site, or service scope.
  (Service scoped-settings can only be used with the Registrar service.) The Get-CsRegistrarConfiguration cmdlet is used to return information about all the Registrar configurations collections currently in use in your organization.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/get-csregistrarconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Get-CsRegistrarConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
