### YamlMime:PowershellCmdlet
summary: |-
  Retrieves information about one or more trusted application endpoints.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href="String" data-throw-if-not-resolved="False" />
  description: |-
    Accepts a pipelined string value representing the Identity of a user account.
outputs:
- name: <xref href="Microsoft.Rtc.Management.ADConnect.Schema.OCSADApplicationContact" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-CsTrustedApplicationEndpoint
  href: New-CsTrustedApplicationEndpoint.yml
- text: Remove-CsTrustedApplicationEndpoint
  href: Remove-CsTrustedApplicationEndpoint.yml
- text: Set-CsTrustedApplicationEndpoint
  href: Set-CsTrustedApplicationEndpoint.yml
syntaxes:
- >-
  Get-CsTrustedApplicationEndpoint [[-Identity] <UserIdParameter>] [-Filter <String>] [-ApplicationId <String>]

   [-Credential <PSCredential>] [-DomainController <Fqdn>] [-OU <OUIdParameter>]

   [-ResultSize <Microsoft.Rtc.Management.ADConnect.Core.Unlimited`1[System.UInt32]>]

   [-TrustedApplicationPoolFqdn <String>] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Get-CsTrustedApplicationEndpoint
  description: |-
    This example retrieves information about all trusted application endpoints defined within the Skype for Business Server deployment.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Get-CsTrustedApplicationEndpoint -Identity "sip:endpoint1@litwareinc.com"
  description: |-
    Example 2 retrieves information about the application endpoint contact with the SIP address endpoint1@litwareinc.com.
    Note that the sip: prefix is required when using a SIP address as the Identity.
  summary: ""
- title: '-------------------------- Example 3 --------------------------'
  code: |-
    Get-CsTrustedApplicationEndpoint -Filter {DisplayName -like "*endpoint*"}
  description: |-
    Example 3 retrieves all trusted application endpoints that have the string "endpoint" anywhere within their display name.
    To do this, the command uses the Filter parameter.
    The value of the parameter filters to find endpoint objects that have a display name (DisplayName) that contains (-like) the string endpoint (*endpoint* - the wildcard characters indicate that any characters can come before or after the string endpoint, meaning endpoint can be anywhere within the display name).
  summary: ""
- title: '-------------------------- Example 4 --------------------------'
  code: |-
    Get-CsTrustedApplicationEndpoint -ApplicationId tapp2 | Select-Object SipAddress, DisplayName, OwnerUrn
  description: |-
    Example 4 will return all trusted application endpoints associated with the application tapp2.
    This is accomplished by passing the ID tapp2 to the ApplicationId parameter.
    Notice that we didn't supply a pool FQDN; this means that if an application with the ID tapp2 exists on more than one pool, endpoints for all those applications will be retrieved.
    The next part of this command pipes the returned object or objects to the Select-Object cmdlet, which displays only the SipAddress, DisplayName, and OwnerUrn properties of those objects.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ApplicationId
  description: |+
    The application ID of the trusted application for the endpoint you want to retrieve.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PSCredential" data-throw-if-not-resolved="False" />
  name: Credential
  description: |+
    Alternate credentials to be used to retrieve the endpoint.
    You can retrieve a PSCredential object by calling the Get-Credential cmdlet.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Fqdn" data-throw-if-not-resolved="False" />
  name: DomainController
  description: |+
    Allows you to specify a domain controller.
    If no domain controller is specified, the first available will be used.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Enables you to limit the returned data by filtering on specific attributes for Skype for Business Server.
    For example, you can limit returned data to contacts whose display names or SIP addresses match a certain wildcard pattern.

    The Filter parameter uses the same Windows PowerShell filtering syntax that is used by the Where-Object cmdlet.
    For example, a filter that returns only contacts that have been enabled for Enterprise Voice would look like this: {EnterpriseVoiceEnabled -eq $True}, with EnterpriseVoiceEnabled representing the Active Directory attribute, -eq representing the comparison operator (equal to), and $True (a built-in Windows PowerShell variable) representing the filter value.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UserIdParameter" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    The Identity (distinguished name), SIP address, or display name of the application endpoint to be retrieved.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="OUIdParameter" data-throw-if-not-resolved="False" />
  name: OU
  description: |+
    The OU in which the endpoint resides.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Microsoft.Rtc.Management.ADConnect.Core.Unlimited`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.UInt32" data-throw-if-not-resolved="False" /><span>]</span>
  name: ResultSize
  description: |+
    The maximum number of endpoint records to retrieve.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: TrustedApplicationPoolFqdn
  description: |+
    The fully qualified domain name (FQDN) of the trusted application pool associated with the application for the endpoint you want to retrieve.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Get-CsTrustedApplicationEndpoint
name: Get-CsTrustedApplicationEndpoint
description: |-
  A trusted application endpoint is an Active Directory contact object that enables routing of calls to a trusted application.
  This cmdlet retrieves one or more existing endpoint contact objects in Active Directory Domain Services.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/get-cstrustedapplicationendpoint
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Get-CsTrustedApplicationEndpoint
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
