### YamlMime:PowershellCmdlet
summary: |-
  Returns information about the diagnostic configuration settings currently in use in your organization.
  Diagnostic configuration settings are used to determine whether traffic to or from a given domain or Uniform Resource Identifier (URI) is recorded in your Skype for Business Server log files.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Rtc.Management.WritableConfig.Settings.Diagnostics.DiagnosticFilterSettings" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-CsDiagnosticConfiguration
  href: New-CsDiagnosticConfiguration.yml
- text: Remove-CsDiagnosticConfiguration
  href: Remove-CsDiagnosticConfiguration.yml
- text: Set-CsDiagnosticConfiguration
  href: Set-CsDiagnosticConfiguration.yml
syntaxes:
- Get-CsDiagnosticConfiguration [[-Identity] <XdsIdentity>] [-LocalStore] [<CommonParameters>]
- Get-CsDiagnosticConfiguration [-Filter <String>] [-LocalStore] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Get-CsDiagnosticConfiguration
  description: |-
    In Example 1, information is returned for all of the diagnostic configuration settings currently in use in the organization.
    This is done by calling the Get-CsDiagnosticConfiguration cmdlet without any parameters.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Get-CsDiagnosticConfiguration -Identity site:Redmond
  description: |-
    Example 2 returns information for the diagnostic configuration settings applied to the Redmond site (-Identity site:Redmond).
  summary: ""
- title: '-------------------------- Example 3 --------------------------'
  code: |-
    Get-CsDiagnosticConfiguration -Identity site:Redmond | Select-Object -ExpandProperty Filter
  description: |-
    The command shown in Example 3 displays the information about the individual filters contained within the diagnostic configuration settings for the Redmond site.
    To do this, the command first uses the Get-CsDiagnosticConfiguration cmdlet to return the settings for the Redmond site.
    This information is then piped to the Select-Object cmdlet, which uses the ExpandProperty parameter to "expand" the value of the Filter property.
    Expanding the Filter property enables you to access the properties and property values for the individual filters maintained in the diagnostic configuration settings.
  summary: ""
- title: '-------------------------- Example 4 --------------------------'
  code: |-
    Get-CsDiagnosticConfiguration -Identity global | Select-Object -ExpandProperty Filter | Where-Object {$_.Uri -contains "sip:diagnostics@litwareinc.com"}
  description: |-
    The command shown in Example 4 returns a subset of the filters found in the global diagnostic configuration settings; in particular, it returns filters where the Uri property includes the SIP address sip:diagnostics@litwareinc.com.
    To do this, the command first uses the Get-CsDiagnosticConfiguration cmdlet to return all the filter information for the global instance of the diagnostic configuration settings.
    This information is then piped to the Select-Object cmdlet, which expands the Filter property.
    The individual filter objects are then piped to the Select-Object cmdlet, which extracts only those filters where the Uri property includes the SIP address sip:diagnostics@litwareinc.com.
  summary: ""
- title: '-------------------------- Example 5 --------------------------'
  code: |-
    Get-CsDiagnosticConfiguration -Identity global | Select-Object -ExpandProperty Filter | Where-Object {$_.Uri -notcontains "sip:diagnostics@litwareinc.com"}
  description: |-
    Example 5 is a variation of the command shown in Example 4; in Example 5, however, filters are returned only if the Uri property does not include the SIP address sip:diagnostics@litwareinc.com.
    To carry out this task, the command calls the Get-CsDiagnosticConfiguration cmdlet to return all the diagnostic configuration information for the global instance of the configuration settings.
    This information is then piped to the Select-Object cmdlet, which expands the Filter property.
    Those filter objects are then piped to the Select-Object cmdlet, which selects only those filters where the Uri property does not include the SIP address sip:diagnostics@litwareinc.com.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Enables you to use wildcard characters when specifying the settings collection (or collections) to be returned.
    For example, this syntax returns all the settings configured at the site scope: -Filter "site:*".

    Note that you cannot use both the Filter and the Identity parameters in the same command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Unique identifier for the diagnostic configuration settings to be returned.
    To return settings configured at the site scope, use syntax similar to this: -Identity "site:Redmond".
    To return the global settings, use this syntax: -Identity global.

    If this parameter is not specified, then all of the diagnostics configuration settings currently in use will be returned.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: LocalStore
  description: |+
    Retrieves the diagnostic configuration data from the local replica of the Central Management store rather than from the Central Management store itself.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Get-CsDiagnosticConfiguration
name: Get-CsDiagnosticConfiguration
description: |-
  If you enable logging for Skype for Business Server, then, by default, traffic traveling to or from any domain or URI is included in those log files.
  This ensures that as much information as possible is recorded in the log files.

  However, this can occasionally result in too much information.
  For example, if you are experiencing connectivity problems with a particular domain, you might want to limit logging to traffic between your network and that domain; that makes it easier for you to identify the relevant records and, in turn, might make it easier for you to diagnose and correct the problem.

  Diagnostic configuration settings make it possible for you to specify the domains or URIs that will be recorded in the log files.
  Skype for Business Server 2015 enables you to create diagnostic configuration settings at the site scope.
  In turn, this enables you to apply different settings to the Redmond site while than you do on your other sites.

  The Get-CsDiagnosticConfiguration cmdlet enables you to return information about the diagnostic configuration settings currently in use in your organization.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/get-csdiagnosticconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Get-CsDiagnosticConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
