### YamlMime:PowershellCmdlet
summary: |-
  Returns information about the XMPP gateway configuration settings in use in the organization.
  The extensible Messaging and Presence Protocol (XMPP) is an open-standard communications protocol for exchanging messages using XML.
  XMPP gateways enable Skype for Business Server users to exchange instant message and presence information with users belonging to IM and presence providers that employ XMPP.
  This cmdlet was introduced in Lync Server 2013.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
    The Get-CsXmppGatewayConfiguration cmdlet does not accept pipelined input.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The Get-CsXmppGatewayConfiguration cmdlet returns instances of the Microsoft.Rtc.Management.WritableConfig.Settings.XmppFederation.XmppGatewaySettings object.
links:
- text: Set-CsXmppGatewayConfiguration
  href: Set-CsXmppGatewayConfiguration.yml
syntaxes:
- Get-CsXmppGatewayConfiguration [-Filter <String>] [-LocalStore] [<CommonParameters>]
- Get-CsXmppGatewayConfiguration [[-Identity] <XdsIdentity>] [-LocalStore] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Get-CsXmppGatewayConfiguration
  description: |-
    In Example 1, information is returned for the XMPP gateway settings currently in use in the organization.
    Because Skype for Business Server 2015 only allows for a single, global collection of gateway settings you do not need to include the Identity parameter in order to get back information for the global settings.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Enables you to use wildcard values when referencing a collection of XMPP gateway configuration settings.
    Because you can only have a single, global instance of these settings there is no reason to use the Filter parameter.
    However, if you prefer you can use the following syntax to reference the global settings:

    -Filter "g*"

    That syntax brings back all the XMPP gateway configuration settings that have an Identity that begins with the letter "g".

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Unique identifier for the XMPP gateway configuration settings.
    Because you can only have a single, global instance of these settings, you do not need to specify an Identity when calling the Get-CsXmppGatewayConfiguration cmdlet.
    If you prefer, however, you can use the following syntax to reference the global settings:

    -Identity global



  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: LocalStore
  description: |+
    Retrieves the XMPP gateway data from the local replica of the Central Management store rather than from the Central Management store itself.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  parameterValueGroup: ""
applicable:
- Lync Server 2013
- Skype for Business Server 2015
uid: SkypeForBusiness.Get-CsXmppGatewayConfiguration
name: Get-CsXmppGatewayConfiguration
description: |-
  The Extensible Messaging and Presence Protocol (XMPP) is a standard communications protocol (based on XML) used for sending messages across the Internet.
  XMPP was originally named Jabber, and is supported by a number of Internet messaging and communication applications, including Google Talk and Facebook Chat.

  The XMPP gateway that enables Skype for Business to communicate with users on an XMPP network was originally released as an add-on to Microsoft Lync Server 2010; in Skype for Business Server, this functionality is built into the software.
  This means that your users can communicate with XMPP users provided that you:

  Configure the XMPP gateway settings.

  Configure the other XMPP network (for example, Google Talk) as an allowed XMPP partner.

  Note that Skype for Business Server provides only a single, global set of XMPP configuration settings: you cannot selectively enable or disable XMPP for a given site or a given Registrar pool.
  In fact you cannot enable or disable XMPP at all: XMPP is always enabled.
  If you do not want users communicating with XMPP networks then you should remove all the allowed XMPP partners.
  Users can only communicate with an XMPP network if that network has been configured as an allowed partner.

  Skype for Business Server Control Panel: The functions carried out by the Get-CsXmppGatewayConfiguration cmdlet are not available in the Skype for Business Server Control Panel.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/get-csxmppgatewayconfiguration
  applicable: Lync Server 2013, Skype for Business Server 2015
  title: Get-CsXmppGatewayConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
