### YamlMime:PowershellCmdlet
summary: |-
  Use the Get-CsVideoInteropServerConfiguration cmdlet to return information about Video Interop Server (VIS) configuration settings.
  VIS configuration settings are scoped to appropriate VIS instances, and will govern the behavior of those instances.
  The Video Interop Server (VIS) enables you to incorporate 3rd party video teleconferencing systems (VTCs) into your Skype for Business infrastructure.
  VIS is a Skype for Business service that runs on a standalone pool and cannot be co-located on an FE pool.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
    The Get-CsVideoInteropServerConfiguration cmdlet does not accept pipelined input.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The Get-CsVideoInteropServerConfiguration cmdlet returns instances of the Microsoft.Rtc.Management.WritableConfig.Settings.VideoInteropServer.VideoInteropServerConfiguration object.
links:
- text: New-CsVideoInteropServerConfiguration
  href: New-CsVideoInteropServerConfiguration.yml
- text: Remove-CsVideoInteropServerConfiguration
  href: Remove-CsVideoInteropServerConfiguration.yml
- text: Set-CsVideoInteropServerConfiguration
  href: Set-CsVideoInteropServerConfiguration.yml
syntaxes:
- Get-CsVideoInteropServerConfiguration [-Filter <String>] [-LocalStore] [<CommonParameters>]
- Get-CsVideoInteropServerConfiguration [[-Identity] <XdsIdentity>] [-LocalStore] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Get-CsVideoInteropServerConfiguration
  description: |-
    This example returns information about all the VIS configuration settings in the organization.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Get-CsVideoInteropServerConfiguration -Identity "site:Redmond"
  description: |-
    This example returns information for the collection of VIS configurations that are scoped to the Redmond site.
  summary: ""
- title: '-------------------------- Example 3 --------------------------'
  code: |-
    Get-CsVideoInteropServerConfiguration -Filter "site:*"
  description: |-
    This example returns all the VIS collections configured at the site scope by including the Filter value "site:*".
  summary: ""
- title: '-------------------------- Example 4 --------------------------'
  code: |-
    Get-CsVideoInteropServerConfiguration | Where-Object {$_.EnableEnhancedVideoExperience -eq $True}
  description: |-
    This example returns information about all the VIS configurations where the enhanced video experience has been enabled.
    First, all the VIS configurations are returned by using Get-CsVideoInteropServerConfiguration to return a collection of all the available settings.
    That collection is then piped to the Where-Object cmdlet, which picks out only those settings where the EnableEnhancedVideoExperience value is equal to True ($True).
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Enables you to use wildcard characters in order to return one or more collections of VIS configuration settings.
    For example, to return all the settings that have been configured at the site scope use the following syntax:

    -Filter "site:*"

    The Filter and the Identity parameters are mutually exclusive.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Unique identity assigned to the VIS configuration when it was created.
    VIS settings can be configured at the global, site, or service scope (for the VideoInteropServer service only).
    To refer to the global instance, use this syntax:

    -Identity "global"

    Use this syntax to refer to a collection at the site scope:

    -Identity "site:Redmond"

    Wildcard characters such as the asterisk (*) cannot be used with the Identity parameter.
    To do a wildcard search for policies, use the Filter parameter instead.

    If neither the Identity nor the Filter parameter is specified, then the Get-CsVideoInteropServerConfiguration cmdlet returns all the VIS configurations in your organization.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: LocalStore
  description: |+
    Retrieves the VIS configuration from the local replica of the Central Management store rather than from the Central Management store itself.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Get-CsVideoInteropServerConfiguration
name: Get-CsVideoInteropServerConfiguration
description: |-
  The Video Interop Server (VIS) enables you to incorporate 3rd party video teleconferencing systems (VTCs) into your Skype for Business infrastructure.
  VIS is a Skype for Business service that runs on a standalone pool and cannot be co-located on an FE pool.

  To enable the Video Interop Server (VIS) you must use Topology Builder to define at least one VIS instance.
  Each VIS instance will typically be associated with one or more Video Gateways.
  Video Gateways route traffic between internal and external video devices such as an internal Skype for Business endpoint receiving video from an external PBX supporting 3rd party video teleconferencing systems (VTCs).
  The Video Gateway and a VIS use a Session Initiation Protocol (SIP) trunk to connect video calls between external VTCs and internal endpoints.

  You can manage the Video Interop Server (VIS) by using VIS configuration settings and the CsVideoInteropServerConfiguration cmdlets.
  These settings are used to enable or disable the enhanced video experience (in which a single video stream is converted to multiple streams in order to accommodate the needs of devices that use different frame rates or video resolutions).

  By default, Skype for Business Server ships with a single, global collection of Video Interop Server configuration settings.
  You can use the New-CsVideoInteropServerConfiguration cmdlet to create additional settings at the site or the service scope (for the VIS service only.)

  To return a list of all the Role-Based Access Control (RBAC) roles a cmdlet has been assigned to (including any custom RBAC roles you have created), run the following command from the Windows PowerShell prompt.

  `Get-CsAdminRole | Where-Object {$_.Cmdlets -Match "\<DesiredCmdletName\>"}`
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/get-csvideointeropserverconfiguration
  applicable: Skype for Business Server 2015, Skype for Business Server 2019
  title: Get-CsVideoInteropServerConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
