### YamlMime:PowershellCmdlet
summary: |-
  Returns the conversation history configuration settings for the organization.
  These settings manage conversation histories for mobile device users.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Rtc.Management.WritableConfig.Settings.ConversationHistory.ConversationHistorySettings" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Remove-CsConversationHistoryConfiguration
  href: Remove-CsConversationHistoryConfiguration.yml
- text: Set-CsConversationHistoryConfiguration
  href: Set-CsConversationHistoryConfiguration.yml
syntaxes:
- Get-CsConversationHistoryConfiguration [-Filter <String>] [-LocalStore] [<CommonParameters>]
- Get-CsConversationHistoryConfiguration [[-Identity] <XdsIdentity>] [-LocalStore] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Get-CsConversationHistoryConfiguration
  description: |-
    The command shown in Example 1 returns the conversation history configuration settings for the organization.
    Note that you will always get back just one collection of settings; that's because Skype for Business Server 2015 limits you to a single, global collection of conversation history settings.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Enables you to use wildcard values when referencing a collection of conversation history configuration settings.
    Because you can only have a single, global instance of these settings there is no reason to use the Filter parameter.
    However, if you prefer you can use the following syntax to reference the global settings:

    `-Filter "g*"`

    That syntax brings back all the conversation history configuration settings that have an Identity that begins with the letter "g".

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Unique Identity of the conversation history configuration settings.
    Because you can only have a single, global instance of these settings, you do not need to specify an Identity when calling the Get-CsConversationHistoryConfiguration cmdlet.
    If you prefer, however, you can use the following syntax to reference the global settings:

    `-Identity "global"`

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: LocalStore
  description: |+
    Retrieves the conversation history configuration data from the local replica of the Central Management store rather than from the Central Management store itself.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Get-CsConversationHistoryConfiguration
name: Get-CsConversationHistoryConfiguration
description: |-
  Prior to the release of Skype for Business Server, conversation histories were stored in the Conversation History folder in users's mailbox, written by the rich client.
  This made it difficult to access the conversation history from mobile devices because the Conversation History folder is typically not replicated to mobile devices.
  With Skype for Business Server, conversation histories and missed IM notifications can be stored on the server in user mailboxes, which makes them easily accessible from mobile devices.
  Administrators can manage the server-side processing of these conversation histories by using the conversation history configuration settings.
  Just keep in mind that a single, global, collection of these settings is used to manage conversation histories throughout your deployment.
  There is no option for creating additional conversation history settings at the site, service, or per-user scope.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/get-csconversationhistoryconfiguration
  applicable: Skype for Business Server 2015, Skype for Business Server 2019
  title: Get-CsConversationHistoryConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
