### YamlMime:PowershellCmdlet
summary: |-
  Use the Get-CsAuthConfig cmdlet to retrieve the authentication configuration for your organization.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- Get-CsAuthConfig [[-Pool] <String>] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> {{ Add example code here }}
  description: |-
    {{ Add example description here }}
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Pool
  description: |+
    {{Fill Pool Description}}

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  applicable:
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Skype for Business Server 2019
uid: SkypeForBusiness.Get-CsAuthConfig
name: Get-CsAuthConfig
description: |-
  Use the Get-CsAuthConfig cmdlet to retrieve the authentication configuration for your organization.

  This cmdlet gets authentication configuration from two server roles: Registrar and WebServices.

  It is meant to only be run at the global level.

  If you do run it at the pool level and only one of the roles are present on the pool, the cmdlet will return the setting that corresponds to the role that exists on the pool and the global settings for the role that doesn't exist on the pool.

  If neither role is present on the pool, it will return an error.

  If both roles are present for the pool, but policies are not defined at the pool level, the cmdlet will return an error.
metadata:
  external help file: Microsoft.Rtc.Management.dll-Help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/get-csauthconfig
  applicable: Skype for Business Server 2019
  title: Get-CsAuthConfig
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
