### YamlMime:PowershellCmdlet
summary: |-
  Returns information about the health monitoring configuration settings currently in use in your organization.
  These settings enable administrators to run quality assurance tests without having to supply user names and passwords for the required test accounts.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Rtc.Management.WritableConfig.Settings.HealthMonitoring.HealthMonitoringSettings" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-CsHealthMonitoringConfiguration
  href: New-CsHealthMonitoringConfiguration.yml
- text: Remove-CsHealthMonitoringConfiguration
  href: Remove-CsHealthMonitoringConfiguration.yml
- text: Set-CsHealthMonitoringConfiguration
  href: Set-CsHealthMonitoringConfiguration.yml
syntaxes:
- >-
  Get-CsHealthMonitoringConfiguration [[-Identity] <XdsGlobalRelativeIdentity>] [-LocalStore]

   [<CommonParameters>]
- Get-CsHealthMonitoringConfiguration [-Filter <String>] [-LocalStore] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Get-CsHealthMonitoringConfiguration
  description: |-
    Example 1 returns all the health monitoring configuration settings currently in use in your organization.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Get-CsHealthMonitoringConfiguration -Identity atl-cs-001.litwareinc.com
  description: |-
    The command shown in Example 2 returns a single collection of health monitoring configuration settings: the settings that have the Identity atl-cs-001.litwareinc.com.
  summary: ""
- title: '-------------------------- Example 3 --------------------------'
  code: |-
    Get-CsHealthMonitoringConfiguration -Filter *.litwareinc.com
  description: |-
    Example 3 returns all the health monitoring configuration settings that have been created for the domain litwareinc.com.
    To do this, the Get-CsHealthMonitoringConfiguration cmdlet is called along with the Filter parameter; the filter value "*.litwareinc.com" ensures that only those settings that have an Identity that ends with the string value ".litwareinc.com" will be returned.
  summary: ""
- title: '-------------------------- Example 4 --------------------------'
  code: |-
    Get-CsHealthMonitoringConfiguration | Where-Object {$_.FirstTestUserSipUri -eq "sip:kenmyer@litwareinc.com" -or $_.SecondTestUserSipUri -eq " sip:kenmyer@litwareinc.com"}
  description: |-
    The command shown in Example 4 returns all the health monitoring configuration settings that include the user with the SIP address sip:kenmyer@litwareinc.com as one of the test users.
    To carry out this task, the command first calls the Get-CsHealthMonitoringConfiguration cmdlet without any additional parameters; this returns a collection of all the health monitoring configuration settings currently in use in the organization.
    This collection is then piped to the Where-Object cmdlet, which picks out only those settings where the FirstTestUserSipUri property is equal to "sip:kenmyer@litwareinc.com" or where the SecondTestUserSipUri property is equal to "sip:kenmyer@litwareinc.com".
    As a result, any collection of settings where Ken Myer's SIP address is used for either the first or the second test user will be returned.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Enables you to use wildcard characters when specifying the health monitoring configuration settings to be retrieved.
    For example, this syntax returns all the settings configured for the litwareinc.com domain: -Filter "*.litwareinc.com".

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsGlobalRelativeIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Fully qualified domain name (FQDN) of the pool where the health monitoring configuration settings have been assigned.
    For example: -Identity atl-cs-001.litwareinc.com.

    If this parameter is not included, then the Get-CsHealthMonitoringConfiguration cmdlet will return information about all the health monitoring configuration settings currently in use.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: LocalStore
  description: |+
    Retrieves the health monitoring configuration data from the local replica of the Central Management store rather than from the Central Management store itself.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Get-CsHealthMonitoringConfiguration
name: Get-CsHealthMonitoringConfiguration
description: |-
  Synthetic transactions are used in Skype for Business Server to verify that users are able to successfully complete common tasks such as logging on to the system, exchanging instant messages, or making calls to a phone located on the public switched telephone network (PSTN).
  These tests can be conducted "manually" by an administrator, or they can be automatically run by an application such as Microsoft System Center Operations Manager (formerly Microsoft Operations Manager).

  Synthetic transactions can be conducted in two different ways.
  Many administrators will use the CsHealthMonitoringConfiguration cmdlets to set up test accounts for each of their Registrar or Director pools.
  These test accounts are a pair of user accounts that have been preconfigured for use with synthetic transactions.
  (Typically these are test accounts and not accounts that belong to actual users.) When test accounts have been configured for a pool, administrators can run a synthetic transaction against that pool without having to specify the identities of (and supply the credentials for) the user accounts involved in the test.
  Instead, the synthetic transaction will automatically use the preconfigured test accounts when performing its checks.

  Alternatively, administrators can run a synthetic transaction using actual user accounts.
  For example, if two users are unable to exchange instant messages, an administrator can run a synthetic transaction using the two user accounts in question (as opposed to a pair of test accounts).
  If you decide to conduct a synthetic transaction using actual user accounts you will have to supply the credentials for each user.

  The Get-CsHealthMonitoringConfiguration cmdlet provides a way for you to retrieve information about the health monitoring configuration settings currently in use in your organization.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/get-cshealthmonitoringconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Get-CsHealthMonitoringConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
