### YamlMime:PowershellCmdlet
summary: |-
  Returns information about the Call Park service.
  Call parking is a service that allows a user to "park" an incoming phone call.
  Parking a call transfers it to a number in a specified range, or orbit, and then immediately places the call on hold.
  Anyone (not just the person who originally answered the call) can resume the conversation from any telephone in the system by entering the correct number.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Rtc.Management.WritableConfig.Settings.CallParkServiceSettings.CallParkServiceSettings" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-CsCpsConfiguration
  href: New-CsCpsConfiguration.yml
- text: Remove-CsCpsConfiguration
  href: Remove-CsCpsConfiguration.yml
- text: Set-CsCpsConfiguration
  href: Set-CsCpsConfiguration.yml
- text: Set-CsCallParkServiceMusicOnHoldFile
  href: Set-CsCallParkServiceMusicOnHoldFile.yml
syntaxes:
- Get-CsCpsConfiguration [[-Identity] <XdsIdentity>] [-LocalStore] [<CommonParameters>]
- Get-CsCpsConfiguration [-Filter <String>] [-LocalStore] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Get-CsCpsConfiguration
  description: |-
    Example 1 retrieves a collection of all the Call Park service configurations that have been defined for use in your organization.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Get-CsCpsConfiguration -Identity site:Redmond1
  description: |-
    Example 2 retrieves only the Call Park service configurations with the Identity site:Redmond1.
  summary: ""
- title: '-------------------------- Example 3 --------------------------'
  code: |-
    Get-CsCpsConfiguration -Filter site:*
  description: |-
    In Example 3, the Filter parameter is used to return all the Call Park service configurations that have been configured at the site scope.
    The wildcard string site:* tells the Get-CsCpsConfiguration cmdlet to return only those settings where the Identity begins with the string value site:.
  summary: ""
- title: '-------------------------- Example 4 --------------------------'
  code: |-
    Get-CsCpsConfiguration -Filter *:re*
  description: |-
    As in Example 3, in this example we use the Filter parameter to retrieve a subset of all the defined Call Park service configurations.
    In this case, we filter on the string *:re*, which will return Call Park configurations for all sites with names beginning with the letters re, such as Redmond1, Redmond2, and RemoteComputer.
  summary: ""
- title: '-------------------------- Example 5 --------------------------'
  code: |-
    Get-CsCpsConfiguration | Where-Object {$_.EnableMusicOnHold -eq $False}
  description: |-
    Example 5 returns all the Call Park service settings that do not play music when a caller is placed on hold.
    To do this, the command first uses the Get-CsCpsConfiguration cmdlet to retrieve all the Call Park service settings configured for use in the organization.
    That collection is then piped to the Where-Object cmdlet, which, in turn, applies a filter that limits the returned data to those items where the EnableMusicOnHold property is equal to (-eq) False.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Allows you to do a wildcard search to retrieve only those configurations with Identity values matching the wildcard string.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    The unique identifier of the Call Park service configuration you want to retrieve.
    This identifier will be either Global or site:\<sitename\>, where \<sitename\> is the name of the site to which the configuration applies.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: LocalStore
  description: |+
    Retrieves the Call Park service information from the local replica of the Central Management store, rather than the Central Management store itself.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Get-CsCpsConfiguration
name: Get-CsCpsConfiguration
description: |-
  This cmdlet is used to retrieve one or more Call Park service configurations.
  A Call Park service configuration specifies what happens to a call once it's parked.
  For example, if a parked call isn't answered after a period of time it can be automatically forwarded to someone else, such as an administrator, or to a Response Group.
  Calls can also be configured to ring after a certain period of time to ensure the call isn't forgotten.
  In addition, Call Park service can be configured to play music on hold to the caller while the call is parked.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/get-cscpsconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Get-CsCpsConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
