### YamlMime:PowershellCmdlet
summary: |-
  Use the Get-CsVideoInteropServerSyntheticTransactionConfiguration cmdlet to retrieve Video Interop Server (VIS) synthetic transaction configurations.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Returns an object array, or single instance (if used with the Identity parameter) of the VideoInteropServerSyntheticTransactionConfiguration object.
links:
- text: Set-CsVideoInteropServerSyntheticTransactionConfiguration
  href: Set-CsVideoInteropServerSyntheticTransactionConfiguration.yml
- text: New-CsVideoInteropServerSyntheticTransactionConfiguration
  href: New-CsVideoInteropServerSyntheticTransactionConfiguration.yml
- text: Remove-CsVideoInteropServerSyntheticTransactionConfiguration
  href: Remove-CsVideoInteropServerSyntheticTransactionConfiguration.yml
- text: Test-CsP2PVideoInteropServerSipTrunkAV
  href: Test-CsP2PVideoInteropServerSipTrunkAV.yml
syntaxes:
- Get-CsVideoInteropServerSyntheticTransactionConfiguration [-Filter <String>] [-LocalStore] [<CommonParameters>]
- >-
  Get-CsVideoInteropServerSyntheticTransactionConfiguration [[-Identity] <XdsIdentity>] [-LocalStore]

   [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Get-CsVideoInteropServerSyntheticTransactionConfiguration -Identity "site:Redmond"
  description: |-
    This example returns the Video Interop Server synthetic transaction configuration for the Redmond site.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Enables you to use wildcard characters in order to return one or more collections of VIS configuration settings.
    For example, to return all the settings that have been configured at the site scope use the following syntax:

    -Filter "site:*"

    The Filter and the Identity parameters are mutually exclusive.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    The Video Interop Server (VIS) synthetic transaction configuration to be retrieved.

    Wildcard characters such as the asterisk (*) cannot be used with the Identity parameter.
    To do a wildcard search for policies, use the Filter parameter instead.

    If neither the Identity nor the Filter parameter is specified, then the Get-CsVideoInteropServerConfiguration cmdlet returns all the VIS synthetic transaction configurations in your organization.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: LocalStore
  description: |+
    Retrieves the VIS configuration data from the local replica of the Central Management store rather than from the Central Management store itself.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Get-CsVideoInteropServerSyntheticTransactionConfiguration
name: Get-CsVideoInteropServerSyntheticTransactionConfiguration
description: |-
  To return a list of all the Role-Based Access Control (RBAC) roles a cmdlet has been assigned to (including any custom RBAC roles you have created), run the following command from the Windows PowerShell prompt.

  `Get-CsAdminRole | Where-Object {$_.Cmdlets -Match "\<DesiredCmdletName\>"}`
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/get-csvideointeropserversynthetictransactionconfiguration
  applicable: Skype for Business Server 2015, Skype for Business Server 2019
  title: Get-CsVideoInteropServerSyntheticTransactionConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
