### YamlMime:PowershellCmdlet
summary: |-
  Imports Response Group configuration data that was previously exported using the Export-CsRgsConfiguration cmdlet.
  The ability to export and import Response Group configuration data is particularly useful disaster recovery scenarios.
  This cmdlet was introduced in Lync Server 2013.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
    The Import-CsRgsConfiguration cmdlet does not accept pipelined input.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
links:
- text: Export-CsRgsConfiguration
  href: Export-CsRgsConfiguration.yml
syntaxes:
- >-
  Import-CsRgsConfiguration -Destination <RgsIdentity> -FileName <String> [-Force] [-OverwriteOwner]

   [-ReplaceExistingRgsSettings] [-ResolveNameConflicts] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Import-CsRgsConfiguration -FileName "C:\Export\RgsExport.zip" -Destination "ApplicationServer:atl-cs-001.litwareinc.com"
  description: |-
    The command shown in Example 1 imports a previously exported collection of Response Group application settings, and then applies those settings to the Response Group installation hosted by the Application Server on atl-cs-001.litwareinc.com.
  summary: ""
parameters:
- type: <xref href="RgsIdentity" data-throw-if-not-resolved="False" />
  name: Destination
  isRequired: true
  description: |+
    Identity of the Response Group instance where the configuration settings are being imported.
    For example:

    `-Destination "ApplicationServer:atl-rgs-001.litwareinc.com"`



  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: FileName
  isRequired: true
  description: |+
    Path to the .ZIP file created by the Export-CsRgsConfiguration cmdlet.
    For example:

    `-FileName "C:\Exports\RgsConfig.zip"`



  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error message that might occur when running the command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: OverwriteOwner
  description: |+
    When present the current owner of the Response Group objects will be overwritten with the service identity of the new Response Group pool.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: ReplaceExistingRgsSettings
  description: |+
    When specified, all the existing service settings for the destination pool are replaced with the imported settings.
    If not specified, then service settings will remain as-is and only Response Group object (such as workflows and agent groups) will be imported.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: ResolveNameConflicts
  description: |+
    When present, duplicate names will be resolved by appending a unique identifying number.
    For example, if there are two workflows named Help Desk Workflow one of the two will be renamed Help Desk Workflow (2).

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Import-CsRgsConfiguration
name: Import-CsRgsConfiguration
description: |-
  The Export-CsRgsConfiguration cmdlet and the Import-CsRgsConfiguration cmdlet enable you to export data about your current implementation of the Response Group application (including such things as workflows, queues, agent groups, holiday sets and business hours, as well as audio files and service configuration settings) and then later import (or re-import) that information.
  This can be extremely useful in a disaster recovery scenario (for example, in a case where the server hosting the Response Group application has failed) or if you simply need to transfer the Response Group application to a different pool.

  Note that the Export-CsRgsConfiguration cmdlet and the Import-CsRgsConfiguration cmdlet are designed to work only with Lync Server 2013 and Skype for Business Server.
  If you want to migrate Response Group data from Microsoft Lync Server 2010 to Skype for Business Server, you should use the Move-CsRgsConfiguration cmdlet instead.

  Skype for Business Server Control Panel: The functions carried out by the Import-CsRgsConfiguration cmdlet are not available in the Skype for Business Server Control Panel.
metadata:
  external help file: Microsoft.Rtc.Rgs.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/import-csrgsconfiguration
  applicable: Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Import-CsRgsConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
