### YamlMime:PowershellCmdlet
summary: |-
  Moves an endpoint to a different Registrar pool.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    String.
    Accepts a pipelined string value representing the Identity of an application endpoint.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    When used with the PassThru parameter, returns an object of type Microsoft.Rtc.Management.ADConnect.Schema.OCSADApplicationContact.
links:
- text: Get-CsApplicationEndpoint
  href: Get-CsApplicationEndpoint.yml
syntaxes:
- >-
  Move-CsApplicationEndpoint [-Identity] <UserIdParameter> [-TargetApplicationPool] <Fqdn>

   [-DomainController <Fqdn>] [-Force] [-PassThru] [-WhatIf] [-Confirm] [-IgnoreBackendStoreException]

   [<CommonParameters>]
examples:
- title: '-------------------------- EXAMPLE 1 --------------------------'
  code: |-
    Move-CsApplicationEndpoint -Identity sip:endpoint1@litwareinc.com -TargetApplicationPool TrustPoolA.litwareinc.com
  description: |-
    This example moves the application endpoint contact object with the SIP address endpoint1@litwareinc.com to the trusted Registrar pool TrustPoolA.litwareinc.com.
    Use this command to upgrade a UCMA 2.0 application to a Skype for Business Server application after coexistence.
  summary: ""
- title: '-------------------------- EXAMPLE 2 --------------------------'
  code: |-
    Move-CsApplicationEndpoint -Identity sip:endpoint2@litwareinc.com -TargetApplicationPool TrustPoolA.litwareinc.com -Force
  description: |-
    This example moves the application endpoint contact object with the SIP address endpoint2@litwareinc.com to the trusted Registrar pool TrustPoolA.litwareinc.com.
    This example differs from Example 1 in that this command includes the Force parameter.
    Use this command for an in-place migration of a UCMA 2.0 application or for direct deployment of a UCMA 2.0 application against a pure Skype for Business Server deployment.
    This will update an existing object in Active Directory with the necessary attributes so that routing can occur through the Skype for Business Server Registrar.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Fqdn" data-throw-if-not-resolved="False" />
  name: DomainController
  description: |+
    Allows you to specify a domain controller.
    If no domain controller is specified, the first available will be used.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    This flag is required if you are moving a Microsoft Unified Communications Managed API (UCMA) 2.0 contact object to the same pool but on a Skype for Business Server deployment.
    This will force routing to occur through the Skype for Business Server Registrar.



  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UserIdParameter" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    The SIP address or distinguished name (DN) of the endpoint contact you want to move.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: IgnoreBackendStoreException
  description: |+
    When present, instructs the computer to ignore any errors that might occur with the backend database and attempt to move the application endpoint despite those errors.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PassThru
  description: |+
    Specifying this parameter will return the application endpoint object after the object has been moved.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Fqdn" data-throw-if-not-resolved="False" />
  name: TargetApplicationPool
  isRequired: true
  description: |+
    The fully qualified domain name (FQDN) of the pool to which the endpoint is moving.
    The target pool must have a Registrar service dependency.

  defaultValue: None
  position: "2"
  aliases: Target
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Move-CsApplicationEndpoint
name: Move-CsApplicationEndpoint
description: |-
  This cmdlet moves an existing endpoint contact object in Active Directory Domain Services to a Skype for Business Server application pool.
  The application associated with the given endpoint must exist on the target pool.
  To determine which application is associated with the endpoint, run the Get-CsTrustedApplicationEndpoint cmdlet.

  This cmdlet is also used to upgrade the Active Directory contact object properties when an application is retargeted against Skype for Business Server.
  Note that the source and target application pool will be the same in that case.
  Also, if an application originally designed to work against Skype for Business Server is directly deployed against Skype for Business Server, then this cmdlet must be used with the Force flag to upgrade the Active Directory contact object properties.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/move-csapplicationendpoint
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Move-CsApplicationEndpoint
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
