### YamlMime:PowershellCmdlet
summary: |-
  Enables you to migrate Response Group configuration settings from legacy version pool to newer version pool. For example, from Microsoft Office Communications Server 2007 R2 or Microsoft Lync Server 2010/2013 to Skype for Business Server 2015.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
    Move-CsRgsConfiguration does not accept pipelined input.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Move-CsRgsConfiguration moves instances of the Microsoft.Rtc.Management.WritableSettings.ServiceSettings from one service to another.
links:
- text: Get-CsRgsConfiguration
  href: Get-CsRgsConfiguration.yml
- text: Move-CsRgsConfiguration
  href: Move-CsRgsConfiguration.yml
syntaxes:
- >-
  Move-CsRgsConfiguration [-Source] <String> [-Destination] <String> [-Force] [-ResolveNameConflicts]

   [<CommonParameters>]
examples:
- title: '-------------------------- EXAMPLE 1 --------------------------'
  code: |-
    Move-CsRgsConfiguration -Source atl-ocsrgs-001.litwareinc.com -Destination redmond-lyncrgs-001.litwareinc.com
  description: |-
    The command shown in Example 1 migrates the Response Group application from atl-ocsrgs-001.litwareinc.com to redmond-lyncrgs-001.litwareinc.com.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Destination
  isRequired: true
  description: |+
    FQDN of the computer where the newer server Response Group application is to be hosted (the "copy to" location).

  defaultValue: None
  position: "3"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error message that might occur when running the command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: ResolveNameConflicts
  description: |+
    When present, duplicate names will be resolved by appending a unique identifying number. For example, if there are two workflows named Help Desk Workflow one of the two will be renamed Help Desk Workflow (2).

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Source
  isRequired: true
  description: |+
    FQDN of the pool where the legacy Response Group application is currently hosted (the "copy from" location).

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Move-CsRgsConfiguration
name: Move-CsRgsConfiguration
description: |-
  The Response Group application provides a way for you to automatically route phone calls to entities such as a help desk or customer support line.
  When someone calls a designated phone number, that call can be automatically routed to the appropriate set of Response Group agents.
  Alternatively, the call might be routed to an interactive voice response (IVR) queue.
  In that queue, the caller would be asked a series of questions (for example, "Are you calling about an existing order?") and then, based on the answers to those questions, be given the asked-for information or be routed to a Response Group agent.

  If you are currently running the Response Group application on legacy server, the Move-CsRgsConfiguration cmdlet provides a way for you to migrate this service to newer version server.
  To migrate the service, you need to call the Move-CsRgsConfiguration cmdlet and specify: 1) the fully qualified domain name (FQDN) for the existing version of the Response Group application (the Source); and, 2) the FQDN for the new Skype for Business Server version of the service (the Destination).
  Move-CsRgsConfiguration will then move all the configuration settings, audio files, and contact objects from the existing version (for example, Office Communications Server 2007 R2 or Lync Server 2010) to newer version.
  After the service has been migrated, all calls to a Response Group phone number will be handled by the newer server.
  Calls will no longer be handled by the previous version of the service.

  >[!Note]
  > If you are running this service on Office Communications Server 2007 R2 or Lync Server 2010, before you can run Move-CsRgsConfiguration, you must first install the Windows Management Instrumentation (WMI) Backward Compatibility interfaces package; this application is installed by running OCSWMIBC.msi. The file OCSWMIBC.msi can be found on the installation DVD in the Setup folder.

  >[!Note]
  > If Office Communications Server 2007 is running Microsoft SQL Server 2005 then, before you attempt to migrate the Response Group application, you must install the Microsoft SQL Server 2005 Native Client on the computer where you will be running the Move-CsRgsConfiguration cmdlet.
  If the Native Client is not installed you will receive the error message "Cannot access WMI settings" when you call Move-CsRgsConfiguration.

  >[!Note]
  > The Move-CsRgsConfiguration cmdlet is only for migrating from legacy version to newer version; you cannot use this cmdlet to migrate between the same version (for example, one instance of Skype for Business Server 2015 to a new instance of Skype for Business Server 2015).
  That type of migration can only be done by using the new Import-CsRgsConfiguration and Export-CsRgsConfiguration cmdlets.
metadata:
  external help file: Microsoft.Rtc.Rgs.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/move-csrgsconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Move-CsRgsConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
