### YamlMime:PowershellCmdlet
summary: |-
  Creates a new collection of reporting configuration settings at the service scope.
  Reporting configuration settings are used to specify the URL used to access Skype for Business Server 2015 Monitoring Reports.
  This cmdlet was introduced in Lync Server 2013.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
    The New-CsReportingConfiguration cmdlet does not accept pipelined data.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The New-CsReportingConfiguration cmdlet creates new instances of the Microsoft.Rtc.Management.WritableConfig.Settings.Reporting.ReportingConfiguration object.
links:
- text: Get-CsReportingConfiguration
  href: Get-CsReportingConfiguration.yml
- text: Remove-CsReportingConfiguration
  href: Remove-CsReportingConfiguration.yml
- text: Set-CsReportingConfiguration
  href: Set-CsReportingConfiguration.yml
syntaxes:
- >-
  New-CsReportingConfiguration [-Identity] <XdsIdentity> [-Confirm] [-Force] [-InMemory] [-ReportingUrl <String>]

   [-WhatIf] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    New-CsReportingConfiguration -Identity "service:MonitoringDatabase:atl-sql-001.litwareinc.com" -ReportingUrl "https://atl-sql-001.litwareinc.com/lync_reports"
  description: |-
    The command shown in Example 1 creates a new collection of reporting configuration settings assigned to the monitoring database with the identity service:MonitoringDatabase:atl-sql-001.litwareinc.com.
    In this example, the value of the ReportingUrl property is set to `https://atl-sql-001.litwareinc.com/lync_reports`.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error message that might occur when running the command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Service Identity of the monitoring database to be associated with the new reporting configuration settings.
    For example:

    `-Identity "Service:MonitoringDatabase:atl-sql-001.litwareinc.com"`

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: InMemory
  description: |+
    Creates an object reference without actually committing the object as a permanent change.
    If you assign the output of this cmdlet called with this parameter to a variable, you can make changes to the properties of the object reference and then commit those changes by calling this cmdlet's matching Set- cmdlet.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ReportingUrl
  description: |+
    URL for the Skype for Business Server Monitoring Reports.



  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.New-CsReportingConfiguration
name: New-CsReportingConfiguration
description: |-
  Reporting configuration settings are used to specify the home page for the Skype for Business Server Monitoring Reports; if you are not using Monitoring Reports then there is no reason for you to modify the reporting configuration settings.

  If you do not know the URL for the Monitoring Reports home page you can determine that URL by doing the following:

  Open the SQL Server Reporting Services Configuration Manager for the SQL Server instance that contains your monitoring database.

  In the Configuration Manager, click Report Manager URL and then click the URL for your Monitoring Reports.
  If you see two URLs, click the one that uses the https protocol.

  In SQL Server Reporting Services, click LyncServerReports.

  On the LyncServerReports page, click Reports Home Page.
  That will take you to the home page for the Monitoring Reports.
  You can then copy the URL and use that URL in conjunction with the CsReportingConfiguration cmdlets.

  Skype for Business Server Control Panel: The functions carried out by the New-CsReportingConfiguration cmdlet are not available in the Skype for Business Server Control Panel.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/new-csreportingconfiguration
  applicable: Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: New-CsReportingConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
