### YamlMime:PowershellCmdlet
summary: |-
  Creates settings that, when enabled, provide phone numbers that Skype for Business Server routes to over public switched telephone network (PSTN) if IP connectivity from Skype for Business Server in the branch site to the Exchange Server located in the data center is not available.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Creates an object of type Microsoft.Rtc.Management.WritableConfig.Settings.ExumRouting.VoicemailReroutingConfiguration.
links:
- text: Remove-CsVoicemailReroutingConfiguration
  href: Remove-CsVoicemailReroutingConfiguration.yml
- text: Set-CsVoicemailReroutingConfiguration
  href: Set-CsVoicemailReroutingConfiguration.yml
- text: Get-CsVoicemailReroutingConfiguration
  href: Get-CsVoicemailReroutingConfiguration.yml
syntaxes:
- >-
  New-CsVoicemailReroutingConfiguration [-Identity] <XdsIdentity> [-AutoAttendantNumber <String>]

   [-Enabled <Boolean>] [-SubscriberAccessNumber <String>] [-Force] [-InMemory] [-WhatIf] [-Confirm]

   [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    New-CsVoicemailReroutingConfiguration -Identity site:Redmond1 -Enabled $True -AutoAttendantNumber "+14255551212"
  description: |-
    This example creates new voice mail rerouting settings that apply to the site Redmond1.
    The Enabled parameter is set to True to turn on this configuration and a phone number (+14255551212) is supplied to specify the Auto-Attendant to which calls will be rerouted.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    New-CsVoicemailReroutingConfiguration -Identity site:Redmond1 -SubscriberAccessNumber "+14255551213"
  description: |-
    This example creates new voice mail rerouting settings that apply to the site Redmond1.
    A phone number (+14255551213) is supplied to specify the Subscriber Access number to which calls will be rerouted.
    Notice that the Enabled parameter has not been set.
    Enabled is set to False by default, so Subscriber Access calls will not be rerouted to this number until the Enabled property is set to True.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AutoAttendantNumber
  description: |+
    Phone number of the Auto-Attendant to which the voice mail deposit attempts should be re-routed.

    The number supplied to this parameter must be a LineUri of an existing contact object.

    Value must be a number beginning with a digit 1 through 9, optionally preceded by a plus (+), followed by any number of digits.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: Enabled
  description: |+
    Indicates whether attempts to access voice mail should be re-routed through PSTN when IP connectivity is down.

    Default: False

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses any confirmation prompts that would otherwise be displayed before making changes.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    This parameter contains a unique identifier specifying the scope at which this configuration is applied.
    New voice mail rerouting configurations can be created only at the site level, so the Identity would be in the format Site:\<site name\>, where \<site name\> is the name of the site to which the settings are applied.
    A global voice mail rerouting configuration exists by default and cannot be re-created by calling the `New-CsVoicemailReroutingConfiguration` cmdlet.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: InMemory
  description: |+
    Creates an object reference without actually committing the object as a permanent change.
    If you assign the output of this cmdlet called with this parameter to a variable, you can make changes to the properties of the object reference and then commit those changes by calling this cmdlet's matching Set-\<cmdlet\>.


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SubscriberAccessNumber
  description: |+
    Subscriber Access number to which the voice mail retrieval attempts should be re-routed.

    The number supplied to this parameter must be a LineUri of an existing contact object.

    Value must be a number beginning with a digit 1 through 9, optionally preceded by a plus (+), followed by any number of digits.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.New-CsVoicemailReroutingConfiguration
name: New-CsVoicemailReroutingConfiguration
description: |-
  This cmdlet allows you to create settings that are applied at either the global or site level that determine where Auto-Attendant and Subscriber Access calls are rerouted to over PSTN when IP connectivity is lost.

  Auto-Attendant and Subscriber Access are features of Exchange.
  The Auto-Attendant feature provides voice recognition and touch-tone control (dual-tone multifrequency, or DTMF) for outside callers to navigate a company's phone system to reach the department or employee that they want or, in Message Taking Mode, to accept messages for users.
  (Voice rerouting for Message Taking Mode is recommended.) Subscriber Access allows internal users to access their Microsoft Outlook mailbox from a phone.
  The numbers provided by these settings allow callers to leave voice mail messages for Enterprise Voice users (the AutoAttendantNumber setting) and for those users to retrieve voice mail even if the IP connectivity from the Skype for Business Server deployment at a remote site to Exchange in the data center is unavailable (the SubscriberAccessNumber setting).

  Note that these settings are not available unless the Enabled property has been set to True.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/new-csvoicemailreroutingconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: New-CsVoicemailReroutingConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
