### YamlMime:PowershellCmdlet
summary: |-
  Creates a new collection of Address Book normalization configuration settings.
  Address Book normalization settings are used to convert phone numbers to a format readily understood by Skype for Business Server.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
    The New-CsAddressBookNormalizationConfiguration cmdlet does not accept pipelined input.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The New-CsAddressBookNormalizationConfiguration cmdlet creates new instances of the Microsoft.Rtc.Management.WritableConfig.Settings.AddressBook.AddressBookNormalizationSettings object cmdlet.
links:
- text: Get-CsAddressBookNormalizationConfiguration
  href: Get-CsAddressBookNormalizationConfiguration.yml
- text: Remove-CsAddressBookNormalizationConfiguration
  href: Remove-CsAddressBookNormalizationConfiguration.yml
- text: Set-CsAddressBookNormalizationConfiguration
  href: Set-CsAddressBookNormalizationConfiguration.yml
- text: Import-CsCompanyPhoneNormalizationRules
  href: Import-CsCompanyPhoneNormalizationRules.yml
syntaxes:
- >-
  New-CsAddressBookNormalizationConfiguration [-Identity] <XdsIdentity>

   [-AddressBookNormalizationRules <PSListModifier>] [-Confirm] [-Force] [-InMemory] [-WhatIf]

   [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    New-CsAddressBookNormalizationConfiguration -Identity "site:Redmond"
  description: |-
    The command shown in Exercise 1 creates a new set of Address Book normalization configuration settings assigned to the Redmond site.
    Note that this collection will not contain any Address Book normalization rules.
    Those rules are most-easily created using the New-CsAddressBookNormalizationRule cmdlet after the new settings collection is in place.
  summary: ""
parameters:
- type: <xref href="PSListModifier" data-throw-if-not-resolved="False" />
  name: AddressBookNormalizationRules
  description: |+
    One or more normalization rules to be assigned to the collection.
    Although these rules can be created directly using the New-CsAddressBookNormalizationConfiguration cmdlet, it is recommended that you create the normalization rules using the New-CsAddressBookNormalizationRule cmdlet instead.
    That cmdlet creates the rule and assigns it to the specified collection using a single command, and using much simpler syntax.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error message that might occur when running the command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Unique identifier for the new collection of Address Book normalization rules.
    Because new rule collections can only be created at the site scope, the Identity will always be similar to this: `-Identity "site:Redmond"`

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: InMemory
  description: |+
    Creates an object reference without actually committing the object as a permanent change.
    If you assign the output of this cmdlet called with this parameter to a variable, you can make changes to the properties of the object reference and then commit those changes by calling this cmdlet's matching Set-\<cmdlet\>.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.New-CsAddressBookNormalizationConfiguration
name: New-CsAddressBookNormalizationConfiguration
description: |-
  Normalization rules define the requirements for converting (or translating) numbers from an internal Skype for Business Server format to a standard (E.164) format.
  (Note that an understanding of regular expressions is helpful in order to understand what normalization rules do and how they do it.) In Skype for Business Server, the Address Book normalization configuration settings represent collections of normalization rules that carry out these conversions and translations for Address Book servers.
  (These settings can be defined at the global scope or at the site scope.) The New-CsAddressBookNormalizationConfiguration cmdlet provides a way create new collections scoped to a specified site.

  In general, you will typically find it easier to add rules to a new collection by using the New-CsAddressBookNormalizationRule cmdlet; that cmdlet enables you to add a rule by using one simple command.
  However, you cannot add a rule to a collection until you have first used the New-CsAddressBookNormalizationConfiguration cmdlet to create that collection.

  Although Address Book normalization rules are very similar to voice normalization rules, the two are not interchangeable: you cannot add voice normalization rules to an Address Book collection, nor can you add Address Book normalization rules to a dial plan.
  That means that, in some cases, you might need to create identical rules: one for assignment to Address Book servers, the other for assignment to dial plans.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/new-csaddressbooknormalizationconfiguration
  applicable: Skype for Business Server 2015, Skype for Business Server 2019
  title: New-CsAddressBookNormalizationConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
