### YamlMime:PowershellCmdlet
summary: |-
  Creates a new collection of media settings.
  These settings can be used to specify such things as the supported level of encryption and the maximum allowed video resolution.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Creates an object of type Microsoft.Rtc.Management.WritableConfig.Settings.Media.MediaSettings.
links:
- text: Remove-CsMediaConfiguration
  href: Remove-CsMediaConfiguration.yml
- text: Set-CsMediaConfiguration
  href: Set-CsMediaConfiguration.yml
- text: Get-CsMediaConfiguration
  href: Get-CsMediaConfiguration.yml
syntaxes:
- >-
  New-CsMediaConfiguration [-Identity] <XdsIdentity> [-EnableQoS <Boolean>] [-EnableSiren <Boolean>]

   [-EncryptionLevel <EncryptionLevel>] [-MaxVideoRateAllowed <MaxVideoRateAllowed>] [-Force] [-InMemory]

   [-WhatIf] [-Confirm] [-EnableAdaptiveBandWidthEstimation <Boolean>] [-EnableG722StereoCodec <Boolean>]

   [-EnableH264Codec <Boolean>] [-EnableInCallQoS <Boolean>] [-EnableRtpRtcpMultiplexing <Boolean>]

   [-InCallQoSIntervalSeconds <UInt16>] [-EnableVideoBasedSharing <Boolean>] [<CommonParameters>]
examples:
- title: '-------------------------- EXAMPLE 1 --------------------------'
  code: |-
    New-CsMediaConfiguration -Identity site:Redmond1 -EncryptionLevel RequireEncryption
  description: |-
    Example 1 uses the New-CsMediaConfiguration cmdlet to create a new media configuration with the Identity site:Redmond1.
    This new configuration requires both parties involved in a multimedia conversation to use encryption.
    That requirement is put in place by adding the EncryptionLevel parameter and setting the parameter value to RequireEncryption.
  summary: ""
- title: '-------------------------- EXAMPLE 2 --------------------------'
  code: |-
    New-CsMediaConfiguration -Identity MediationServer:pool0.litwareinc.com -EnableSiren $True
  description: |-
    This example uses the New-CsMediaConfiguration cmdlet to create a new media configuration with the Identity MediationServer:pool0.litwareinc.com.
    This new configuration will have an EnableSiren value of True, which means that Siren is enabled for calls involving this Mediation Server.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableAdaptiveBandWidthEstimation
  description: |+
    When set to True (the default value) Microsoft Lync Server will select the bandwidth rate at which to play a video stream.
    This selection will be based on such factors as the network congestion and the client's quality of the client's current network connection.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableG722StereoCodec
  description: |+
    When set to True (the default value) allows the use of the G.722 wideband speech codec.
    G.722 is a standard voice codec commonly used with Voice over IP applications; with a sampling rate of 16 KHz G.722 provides higher voice quality and clarity than many other commonly-used speech codecs.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableH264Codec
  description: |+
    When set to True (the default value) allows the use of the H.264/MPEG-4 AVC video codec.
    H.264 is a standard codec commonly used for recording, compressing, and distributing high-definition video.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableInCallQoS
  description: |+
    Enables or disables the ability of Skype for Business clients to send the raw data that's required to generate InCallQuality messages.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableQoS
  description: |+
    QoS monitors the quality of voice signals over a network. When set to True, enables call Quality of Service (QoS) settings.

  defaultValue: "False"
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableRtpRtcpMultiplexing
  description: |+
    Enables or disables the use of RTP/RTCP Multiplexing, if enabled, when negotiating, only one candidate will be used for both RTP and RTCP.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableSiren
  description: |+
    By default, the Mediation Server does not negotiate Siren as a possible codec for calls between itself and clients.
    If this setting is True, Siren will be included as a possible codec for use between the Mediation Server and other clients.

    Default: False



  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableVideoBasedSharing
  description: |+
    Enables the use of Video Based Sharing, for more information, see [Video based Screen Sharing for Skype for Business Server](https://learn.microsoft.com/skypeforbusiness/manage/video-based-screen-sharing) 

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="EncryptionLevel" data-throw-if-not-resolved="False" />
  name: EncryptionLevel
  description: |+
    The level of encryption between unified communications devices.

    Valid values:

    SupportEncryption - secure real-time transport protocol (SRTP) will be used if it can be negotiated.

    RequireEncryption - SRTP must be negotiated.

    DoNotSupportEncryption - SRTP must not be used.

    Default: RequireEncryption



  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses any confirmation prompts that would otherwise be displayed before making changes.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    A unique identifier specifying the scope at which this configuration is applied (site or service).
    A configuration at the site scope would be entered as site:\<site name\>, such as site:Redmond.
    A service would be entered as \<server role\>:\<fqdn\>, such as MediationServer:pool0.litwareinc.com.
    A media configuration at the global scope will always exist and cannot be removed, so a new global configuration cannot be created.

    Media configurations created at the service scope can be created for only the A/V Conferencing service, Mediation Server, and Application Server.



  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt16" data-throw-if-not-resolved="False" />
  name: InCallQoSIntervalSeconds
  description: |+
    Specifies the interval between call QoS actions.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: InMemory
  description: |+
    Creates an object reference without actually committing the object as a permanent change.
    If you assign the output of this cmdlet called with this parameter to a variable, you can make changes to the properties of the object reference and then commit those changes by calling this cmdlet's matching Set-\<cmdlet\>.



  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="MaxVideoRateAllowed" data-throw-if-not-resolved="False" />
  name: MaxVideoRateAllowed
  description: |+
    The maximum rate at which video signals will be transferred at the client endpoints.

    Valid values: Hd720p15M, VGA600K, CIF250K

    Hd720p15M - High definition, with a resolution of 1280 x 720 and aspect ratio 16:9.

    VGA600K - VGA, with a resolution of 640 x 480, 25 fps with the aspect ratio 4:3.

    CIF250K - Common Intermediate Format (CIF) video format, 15 fps with a resolution of 352 x 288.

    Note that these values are not case sensitive; values will be converted to appropriate casing when the configuration is created.

    Default: VGA600K

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.New-CsMediaConfiguration
name: New-CsMediaConfiguration
description: |-
  This cmdlet creates a new collection of settings that define the behavior of specific media actions.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/new-csmediaconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: New-CsMediaConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
