### YamlMime:PowershellCmdlet
summary: |-
  Creates a test scenario you can use to test phone numbers against specified routes and rules.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    This cmdlet creates an object of type Microsoft.Rtc.Management.WritableConfig.Policy.Voice.TestConfiguration
links:
- text: Remove-CsVoiceTestConfiguration
  href: Remove-CsVoiceTestConfiguration.yml
- text: Set-CsVoiceTestConfiguration
  href: Set-CsVoiceTestConfiguration.yml
- text: Get-CsVoiceTestConfiguration
  href: Get-CsVoiceTestConfiguration.yml
- text: Test-CsVoiceTestConfiguration
  href: Test-CsVoiceTestConfiguration.yml
- text: Get-CsVoiceRoute
  href: Get-CsVoiceRoute.yml
- text: Get-CsPstnUsage
  href: Get-CsPstnUsage.yml
- text: Get-CsDialPlan
  href: Get-CsDialPlan.yml
- text: Get-CsVoicePolicy
  href: Get-CsVoicePolicy.yml
syntaxes:
- >-
  New-CsVoiceTestConfiguration [-Identity] <XdsGlobalRelativeIdentity> [-DialedNumber <String>]

   [-ExpectedRoute <String>] [-ExpectedTranslatedNumber <String>] [-ExpectedUsage <String>]

   [-TargetVoicePolicy <String>] [-Force] [-InMemory] [-WhatIf] [-Confirm] [-TargetDialplan <String>]

   [<CommonParameters>]
- >-
  New-CsVoiceTestConfiguration -Name <String> [-DialedNumber <String>] [-ExpectedRoute <String>]

   [-ExpectedTranslatedNumber <String>] [-ExpectedUsage <String>] [-TargetVoicePolicy <String>] [-Force]

   [-InMemory] [-WhatIf] [-Confirm] [-TargetDialplan <String>] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    New-CsVoiceTestConfiguration -Identity TestConfig1
  description: |-
    This example creates a new voice test configuration with default values that has the Identity TestConfig1.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    New-CsVoiceTestConfiguration TestConfig1 -TargetDialplan site:Redmond1
  description: |-
    This example creates a new voice test configuration named TestConfig1 and sets the TargetDialplan parameter to site:Redmond1.
    This will result in the tests for expected number, usage and route to be run against the settings for the dial plan for the site Redmond1.

    In this example we declared TestConfig1 without specifying the Identity parameter.
    Identity is a positional parameter, so the first value in the command following the cmdlet name is recognized by the cmdlet as the Identity.
  summary: ""
- title: '-------------------------- Example 3 --------------------------'
  code: |-
    New-CsVoiceTestConfiguration -Identity TestConfig1 -DialedNumber 5551212 -ExpectedTranslatedNumber +5551212
  description: |-
    This example creates a new voice test configuration named TestConfig1.
    This configuration will use the default values to test the DialedNumber 5551212 against an expected output (ExpectedTranslatedNumber) of +5551212.
    This expectation is based on the normalization rules associated with the dial plan that will be used when a test is run against this object.
    That test must be run using the `Test-CsVoiceTestConfiguration` cmdlet.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DialedNumber
  description: |+
    The phone number you want to use to test the policies, usages, etc.

    Must be 512 characters or fewer.

    Default: 1234

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ExpectedRoute
  description: |+
    The name of the voice route expected to be used during the configuration test.
    If a different route is used, based on the target dial plan and voice policy, the test will fail.
    You can retrieve available voice routes by calling the `Get-CsVoiceRoute` cmdlet.

    Must be 256 characters or fewer.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ExpectedTranslatedNumber
  description: |+
    The phone number in the format you expect to see it after translation.
    This is the value of the DialedNumber parameter after normalization.
    If you run the `Test-CsVoiceTestConfiguration` cmdlet and the DialedNumber does not result in the value in ExpectedTranslatedNumber, the test will report as Fail.

    Must be 512 characters or fewer.

    Default: +1234


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ExpectedUsage
  description: |+
    The name of the PSTN usage expected to be used during the configuration test.
    If a different PSTN usage is used, based on the target dial plan and voice policy, the test will fail.
    You can retrieve available usages by calling the `Get-CsPstnUsage` cmdlet.

    Must be 256 characters or fewer.


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses any confirmation prompts that would otherwise be displayed before making changes.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsGlobalRelativeIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    A string uniquely identifying this test scenario.

    This string can be up to 32 characters in length and may contain any alphanumeric characters plus the backslash (\\), period (.) or underscore (_).

    The value of this parameter does not include scope because this object can be created only at the global scope.
    Therefore only a unique name is required.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: InMemory
  description: |+
    Creates an object reference without actually committing the object as a permanent change.
    If you assign the output of this cmdlet called with this parameter to a variable, you can make changes to the properties of the object reference and then commit those changes by calling this cmdlet's matching Set-\<cmdlet\>.


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    This parameter contains the same value as the Identity.
    If the Identity parameter is specified, you cannot include the Name parameter in your command.
    Likewise, if the Name parameter is specified, you cannot specify an Identity.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: TargetDialplan
  description: |+
    The Identity of the dial plan to be used for this test.
    Dial plans can be retrieved by called the `Get-CsDialPlan` cmdlet.

    Must be 40 characters or fewer.

    Default: Global


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: TargetVoicePolicy
  description: |+
    The Identity of the voice policy against which to run this test.
    Voice policies can be retrieved by calling the `Get-CsVoicePolicy` cmdlet.

    Must be 40 characters or fewer.

    Default: Global


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.New-CsVoiceTestConfiguration
name: New-CsVoiceTestConfiguration
description: |-
  Before implementing voice routes and voice policies, it's a good idea to test them out on various phone numbers to ensure the results are what you're expecting.
  You can do this testing by creating test scenarios with this cmdlet.

  The `New-CsVoiceTestConfiguration` cmdlet defines the voice route, usage, dial plan and voice policy against which to test a specified phone number.
  All of this information can be defined and retrieved using other cmdlets; see the parameter descriptions for this topic for more information.

  The configurations created with this cmdlet are tested using the `Test-CsVoiceTestConfiguration` cmdlet.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/new-csvoicetestconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: New-CsVoiceTestConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
