### YamlMime:PowershellCmdlet
summary: |-
  Creates a new collection of centralized logging configuration settings.
  Centralized logging provides a way for administrators to simultaneously enable or disable Skype for Business Server tracing on multiple computers.
  This cmdlet was introduced in Lync Server 2013.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
    The New-CsClsConfiguration cmdlet does not accept pipelined input.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The New-CsClsConfiguration cmdlet creates new instances of the icrosoft.Rtc.Management.WritableConfig.Settings.CentralizedLogging.CentralizedLoggingConfiguration object.
links:
- text: Get-CsClsConfiguration
  href: Get-CsClsConfiguration.yml
- text: Remove-CsClsConfiguration
  href: Remove-CsClsConfiguration.yml
- text: Set-CsClsConfiguration
  href: Set-CsClsConfiguration.yml
syntaxes:
- >-
  New-CsClsConfiguration [-Identity] <XdsIdentity> [-CacheFileLocalFolders <String>]

   [-CacheFileLocalMaxDiskUsage <UInt32>] [-CacheFileLocalRetentionPeriod <UInt32>]

   [-CacheFileNetworkFolder <String>] [-ComponentThrottleLimit <UInt32>] [-ComponentThrottleSample <UInt32>]

   [-Confirm] [-EtlFileFolder <String>] [-EtlFileRolloverMinutes <UInt32>] [-EtlFileRolloverSizeMB <UInt32>]

   [-Force] [-InMemory] [-MinimumClsAgentServiceVersion <UInt32>] [-Regions <PSListModifier>]

   [-Scenarios <PSListModifier>] [-SearchTerms <PSListModifier>] [-SecurityGroups <PSListModifier>]

   [-TmfFileSearchPath <String>] [-WhatIf] [-NetworkUsagePacketSize <UInt32>] [-NetworkUsageThreshold <UInt32>]

   [-Version <String>] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    New-CsClsConfiguration -Identity "site:Redmond" -EtlFileRolloverSizeMB 40 -EtlFileRolloverMinutes 120
  description: |-
    The command shown in Example 1 creates a new collection of centralized logging configuration settings for the Redmond site.
    In this new collection, the ETL file rollover size is set to 40 megabytes, and the ETL file rollover time is set to 2 hours (120 minutes).
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: CacheFileLocalFolders
  description: |+
    One or more full paths to the local folders where the cache files will be stored.
    The default value is %TEMP%\Tracing.
    If more than one path is specified, then separate them with semi-colons.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: CacheFileLocalMaxDiskUsage
  description: |+
    Maximum amount of disk space (percentage) that can be used for the cache files.
    The default value is 80.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: CacheFileLocalRetentionPeriod
  description: |+
    Maximum number of days that cache files are retained locally.
    The default value is 14.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: CacheFileNetworkFolder
  description: |+
    Full UNC path to the network cache folder.
    There is no default value.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: ComponentThrottleLimit
  description: |+
    Maximum rate at which a component is allowed to generate trace records before its tracing is throttled.
    The default value is 5000 trace calls per second.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: ComponentThrottleSample
  description: |+
    Maximum number of times the ComponentThrottleLimit can be exceeded within a one minute interval.
    The default value is 3.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: EtlFileFolder
  description: |+
    Full path to the folder where the event log trace files will be stored.
    The default value is %TEMP%\Tracing.
    Note that %TEMP% is evaluated in the contents of the CLS Service so it actual expands to %WINDIR%\ServiceProfiles\NetworkService\AppData\Local

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: EtlFileRolloverMinutes
  description: |+
    Maximum amount of time (in minutes) that can elapse before a new event log trace file is created.
    (This new file will be created even if the existing trace file has not reached the specified rollover size.) The default value is 60.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: EtlFileRolloverSizeMB
  description: |+
    Maximum size (in megabytes) that at event trace log file can reach before a new file is created.
    The default value is 20.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error message that might occur when running the command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Unique identifier for the centralized logging configuration settings to be created.
    Because these settings can only be created at the site scope, use syntax similar to this, with the prefix "site:" followed by the name of the site:

    `-Identity "site:Redmond"`

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: InMemory
  description: |+
    Creates an object reference without actually committing the object as a permanent change.
    If you assign the output of this cmdlet called with this parameter to a variable, you can make changes to the properties of the object reference and then commit those changes by calling this cmdlet's matching Set- cmdlet.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: MinimumClsAgentServiceVersion
  description: |+
    Specifies the minimum version of the centralized logging service agent to be used when logging data; any computers with an agent version lower than the minimum value will be excluded from the logging operations.
    The default value is 6, representing Skype for Business Server.
    This parameter is intended for use with Skype for Business Online.



  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: NetworkUsagePacketSize
  description: |+
    Packet size (in kilobytes) for transmitting agent search results and copying cache files over the network.
    The default value is 64 KB.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: NetworkUsageThreshold
  description: |+
    Bandwidth usage threshold (in MB per second) for transmitting agent search results and copying cache files over the network.
    The default value is 10.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PSListModifier" data-throw-if-not-resolved="False" />
  name: Regions
  description: |+
    Collection of regions defined for the centralized logging configuration settings.
    Regions are defined using the New-CsClsRegion cmdlet.

    This parameter is intended for use with Skype for Business Online.



  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PSListModifier" data-throw-if-not-resolved="False" />
  name: Scenarios
  description: |+
    Collection of components/situations that can be traced using centralized logging.
    Scenarios are managed using the CsClsScenario cmdlets.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PSListModifier" data-throw-if-not-resolved="False" />
  name: SearchTerms
  description: |+
    Collection of terms that help determine the personally identifiable information available to technical support personnel who search the centralized logging files.
    Search terms are managed using the CsClsSearchTerm cmdlets.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PSListModifier" data-throw-if-not-resolved="False" />
  name: SecurityGroups
  description: |+
    Security groups who are allowed to access the log files.

    This parameter is intended for use with Skype for Business Online.



  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: TmfFileSearchPath
  description: |+
    Search path for TMF (trace message format) files.
    TMF files convert binary trace messages to a human-readable format.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Version
  description: |+
    This parameter is reserved for internal Microsoft use.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.New-CsClsConfiguration
name: New-CsClsConfiguration
description: |-
  The centralized logging service (which replaces the OCSLogger and OCSTracer tools used in Microsoft Lync Server 2010) provides a way for administrators to manage logging and tracing for all computers and pools running Skype for Business Server.
  Centralized logging enables administrators to stop, start, and configure logging for one or more pools and computers by using a single command; for example, you can use one command to enable Address Book service logging on all your Address Book servers.
  This differs from the OCSLogger and OCSTracer tools, which had to be individually managed (including individually stopped and started) on each server.
  In addition, the centralized logging service also provides a way for administrators to search trace logs from the command, using the Windows PowerShell command-line interface and the Search-CsClsLogging cmdlet.

  Centralized logging is built around a series of predefined scenarios that offer a more finely-targeted approach to logging than offered in previous versions of Skype for Business Server.
  These scenarios predetermine the server components and logging for you; as a result, an administrator enabling the RGS scenario can be confident that he or she will only log information relevant to the Response Group service and not to, say, the audio conferencing provider service.

  It is also possible to define custom scenarios by using the New-CsClsScenario cmdlet.

  Centralized logging is managed by using collections of centralized logging service configuration settings.
  When you install Skype for Business Server, you install a global set of these configuration settings; in addition, administrators can add custom settings collections at the site scope.
  This is done by using the New-CsClsConfiguration cmdlet.

  Skype for Business Server Control Panel: The functions carried out by the New-CsCClsConfiguration cmdlet are not available in the Skype for Business Server Control Panel.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/new-csclsconfiguration
  applicable: Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: New-CsClsConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
