### YamlMime:PowershellCmdlet
summary: |-
  Assigns a new collection of watcher node configuration settings to a pool.
  Watcher nodes are computers that periodically use Microsoft System Center Operations Manager and Skype for Business Server synthetic transactions to verify that Skype for Business Server components are working as expected.
  This cmdlet was introduced in Lync Server 2013.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
    The `New-CsWatcherNodeConfiguration` cmdlet does not accept pipelined input.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The `New-CsWatcherNodeConfiguration` cmdlet creates new instances of the Microsoft.Rtc.Management.WritableConfig.Settings.WatcherNode.TargetPool#Decorated object.
syntaxes:
- >-
  New-CsWatcherNodeConfiguration [-Identity] <XdsGlobalRelativeIdentity> -PortNumber <UInt16> [-Confirm]

   [-Enabled <Boolean>] [-ExtendedTests <PSListModifier>] [-Force] [-InMemory] [-Tests <PSListModifier>]

   [-TestUsers <PSListModifier>] [-UseInternalWebUrls <Boolean>] [-WhatIf]

   [-XmppTestReceiverMailAddress <String>] [-UseAutoDiscovery <Boolean>] [<CommonParameters>]
- >-
  New-CsWatcherNodeConfiguration -PortNumber <UInt16> -TargetFqdn <String> [-Confirm] [-Enabled <Boolean>]

   [-ExtendedTests <PSListModifier>] [-Force] [-InMemory] [-Tests <PSListModifier>] [-TestUsers <PSListModifier>]

   [-UseInternalWebUrls <Boolean>] [-WhatIf] [-XmppTestReceiverMailAddress <String>]

   [-UseAutoDiscovery <Boolean>] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Set-CsTestUserCredential -SipAddress "sip:kenmyer@litwareinc.com" -UserName "litwareinc\kenmyer" -Password "07Apples"

    Set-CsTestUserCredential -SipAddress "sip:pilar@litwareinc.com" -UserName "litwareinc\pilar" -Password "07Apples"

    $x = New-CsExtendedTest -TestUsers "sip:kenmyer@litwareinc.com", "sip:pilar@litwareinc.com" -Name "PSTN Test" -TestType "PSTN"

    New-CsWatcherNodeConfiguration -TargetFqdn "atl-cs-001.litwareinc.com" -PortNumber 5061 -TestUsers "sip:kenmyer@litwareinc.com","sip:pilar@litwareinc.com"} -ExtendedTests @{Add=$x}
  description: |-
    The commands shown in Example 1 create a new collection of watcher node configuration settings for the pool `atl-cs-001.litwareinc.com`.
    To do this, the first two commands in the example create a pair watcher node test users (sip:kenmyer@litwareinc.com and sip:pilar@litwareinc.com).
    After the test users have been created, the third command in the example creates a new extended PSTN test using the two newly-created users.
    This new test (which, at this point in time, exists only in memory) is stored in a variable named $x.

    Finally, the fourth command in the example creates the watcher node configuration settings for atl-cs-001.litwareinc.com.
    These new settings use port 5061; the two new test users and the extended test stored in the variable $x.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: Enabled
  description: |+
    Enables or disables the watcher node.
    The default value is True ($True).

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PSListModifier" data-throw-if-not-resolved="False" />
  name: ExtendedTests
  description: |+
    PSTN or Audio Conferencing Provider tests that can be assigned to a watcher node configuration.
    These tests must be created using the `New-CsExtendedTest` cmdlet and stored in a variable (for example, $x).
    The test can then be assigned to a watcher node by using syntax similar to this:

    `-ExtendedTests @{Add=$x}`

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error message that might occur when running the command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsGlobalRelativeIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Fully qualified domain name of the pool being associated with the watcher node configuration settings.
    You can use either the Identity parameter or the TargetFqdn parameter to specify the pool; however, you cannot use both these parameters in the same command.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: InMemory
  description: |+
    Creates an object reference without actually committing the object as a permanent change.
    If you assign the output of this cmdlet called with this parameter to a variable, you can make changes to the properties of the object reference and then commit those changes by calling this cmdlet's matching Set- cmdlet.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt16" data-throw-if-not-resolved="False" />
  name: PortNumber
  isRequired: true
  description: |+
    SIP port used by the Registrar service.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: TargetFqdn
  isRequired: true
  description: |+
    Fully qualified domain name of the pool being associated with the watcher node configuration settings.
    You can use either the TargetFqdn parameter or the Identity parameter to specify the pool; however, you cannot use both these parameters in the same command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PSListModifier" data-throw-if-not-resolved="False" />
  name: Tests
  description: |+
    Synthetic transactions to be run by the watcher node.
    Allowed values are:

    Registration

    IM

    GroupIM

    P2PAV

    AvConference

    Presence

    ABS

    ABWQ

    MCXP2PIM

    ExumConnectivity

    JoinLauncher

    PersistentChatMessage

    DataConference

    XmppIM

    UnifiedContactStore

    AVEdgeConnectivity

    To configure tests at the time you create a new watcher node, use the following syntax, separating the individual tests by using commas:

    `-Tests "ABS","ABWQ","IM","GroupIM","XmppIM"`


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PSListModifier" data-throw-if-not-resolved="False" />
  name: TestUsers
  description: |+
    SIP addresses of the test users to be assigned to the watcher node; these user accounts must have previously been configured by using the `Set-CsTestUserCredential` cmdlet.
    To add test users, use syntax similar to this, separating user addresses by using commas:

    `-TestUsers "sip:kenmyer@litwareinc.com","sip:pilar@litwareinc.com"`

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: UseAutoDiscovery
  description: |+
    When set to True ($True), Skype for Business Online watcher nodes will use the Autodiscover service to locate the target pool.
    When set to False (the default value) watcher nodes will use SRV records to locate the pool.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: UseInternalWebUrls
  description: |+
    When set to True ($True), instructs the watcher node to use the internal Web URLs rather than the external Web URLs.
    This provides a way to way to verify URL validity for users located behind the organization's firewall.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: XmppTestReceiverMailAddress
  description: |+
    XMPP email address to be used when testing the XMPP gateway.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.New-CsWatcherNodeConfiguration
name: New-CsWatcherNodeConfiguration
description: |-
  If you are using Microsoft System Center Operations Manager to monitor Skype for Business Server then you have the option of setting up "watcher nodes": computers that periodically and automatically, run synthetic transactions in order to verify that Skype for Business Server is working as expected.
  Watcher nodes are assigned to pools, and are managed using the CsWatcherNodeConfiguration cmdlets.
  Note that you do not need to install watcher nodes if you are using System Center Operations Manager.
  You can still monitor your system without using watcher nodes; the only difference is that any synthetic transactions you want to run will need to be invoked manually rather than automatically invoked by Operations Manager.

  Skype for Business Server Control Panel: The functions carried out by the `New-CsWatcherNodeConfiguration` cmdlet are not available in the Skype for Business Server Control Panel.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/new-cswatchernodeconfiguration
  applicable: Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: New-CsWatcherNodeConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
