### YamlMime:PowershellCmdlet
summary: |-
  This cmdlet returns an object containing the default settings for a routing configuration object.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Can create an in-memory object of type Microsoft.Rtc.Management.WritableConfig.Policy.Voice.PstnRoutingSettings.
links:
- text: Remove-CsRoutingConfiguration
  href: Remove-CsRoutingConfiguration.yml
- text: Set-CsRoutingConfiguration
  href: Set-CsRoutingConfiguration.yml
- text: Get-CsRoutingConfiguration
  href: Get-CsRoutingConfiguration.yml
- text: New-CsVoiceRoute
  href: New-CsVoiceRoute.yml
- text: Get-CsVoiceRoute
  href: Get-CsVoiceRoute.yml
syntaxes:
- >-
  New-CsRoutingConfiguration [-Identity] <XdsIdentity> [-Route <PSListModifier>] [-Force] [-InMemory] [-WhatIf]

   [-Confirm] [-CallViaWorkCallerId <String>] [-EnableLocationBasedRouting <Boolean>] [<CommonParameters>]
examples:
- title: '-------------------------- EXAMPLE 1 --------------------------'
  code: |-
    $x = New-CsRoutingConfiguration -Identity global -InMemory
  description: |-
    This command creates an object containing the default routing configuration values and assigns that object to the variable $x.
    Any other use of this cmdlet will return an error.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: CallViaWorkCallerId
  description: |+
    The number the system will display for the callback portion of an external call.
    External calls first connect the user making the call by calling a specified number (typically the user's desk phone), once connected to the user, the system dials the outside number.
    The CallViaWorkCallerId parameter specifies the number that will be displayed during the first leg, or callback segment, of the call via work external call.
    For more information, see New-CsCallViaWorkPolicy.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableLocationBasedRouting
  description: |+
    When set to True, voice routing will be managed by taking into account the location of both the user placing the call and the user receiving the call.
    The default value is False.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses any confirmation prompts that would otherwise be displayed before making changes.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    The scope of the routing configuration.
    This value must be Global.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: InMemory
  description: |+
    Creates an object reference without actually committing the object as a permanent change.
    If you assign the output of this cmdlet called with this parameter to a variable, you can make changes to the properties of the object reference and then commit those changes by calling this cmdlet's matching Set-\<cmdlet\>.



  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PSListModifier" data-throw-if-not-resolved="False" />
  name: Route
  description: |+
    A list of all voice routes (Microsoft.Rtc.Management.WritableConfig.Policy.Voice.Route objects) defined for the Skype for Business Server deployment.

    You can create voice route objects by using the New-CsVoiceRoute cmdlet.
    That is the recommended way of adding voice routes to this list.



  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.New-CsRoutingConfiguration
name: New-CsRoutingConfiguration
description: |-
  A routing configuration is a container for all voice routes defined within a Skype for Business Server deployment.
  To create a new voice route, use the New-CsVoiceRoute cmdlet.

  A routing configuration can be defined only at the global level.
  In addition, you cannot have individually named routing configurations; there is only one voice route list for the entire Skype for Business Server deployment.
  In the Skype for Business Server implementation of Windows PowerShell, if you try to create an object that already exists by calling a cmdlet beginning with the New verb, you'll receive an error message.
  Every implementation of Skype for Business Server includes a default routing configuration object with a Global Identity.
  What this means is that the only voice route list that could be created already exists.
  So a call to the New-CsRoutingConfiguration cmdlet will always return an error message and will not create a new routing configuration.

  The only exception to this is if you specify the InMemory parameter in the call to this cmdlet.
  This command will create an object only in memory that contains a default list of voice routes.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/new-csroutingconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: New-CsRoutingConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
