### YamlMime:PowershellCmdlet
summary: |-
  Creates a new collection of User Replicator configuration settings.
  The User Replicator periodically retrieves up-to-date user account information from Active Directory and then synchronizes the new information with the current user data stored by Skype for Business Server.
  This cmdlet is designed for use with Skype for Business Online and will not work with the on-premises version of Skype for Business Server.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
    The `New-CsUserReplicatorConfiguration` cmdlet does not accept pipelined input.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The `New-CsUserReplicatorConfiguration` cmdlet creates new instances of the Microsoft.Rtc.Management.WritableConfig.Settings.UserReplicator.UserReplicatorConfiguration object.
links:
- text: Get-CsUserReplicatorConfiguration
  href: Get-CsUserReplicatorConfiguration.yml
- text: Remove-CsUserReplicatorConfiguration
  href: Remove-CsUserReplicatorConfiguration.yml
- text: Set-CsUserReplicatorConfiguration
  href: Set-CsUserReplicatorConfiguration.yml
syntaxes:
- >-
  New-CsUserReplicatorConfiguration [-Identity] <XdsIdentity> [-ADDomainNamingContextList <PSListModifier>]

   [-ReplicationCycleInterval <TimeSpan>] [-Force] [-InMemory] [-WhatIf] [-Confirm]

   [-SkipFirstSyncAllowedDowntime <TimeSpan>] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 ------------------------'
  code: |-
    New-CsUserReplicatorConfiguration -Identity "service:Registrar:atl-cs-001.litwareinc.com"
  description: |-
    The command shown in Example 1 creates a new collection of User Replicator configuration settings for the service Registrar:atl-cs-001.litwareinc.com.
    Because no additional parameters are specified, the new collection will use the default user replicator values.
  summary: ""
- title: '-------------------------- Example 2 ------------------------'
  code: |-
    New-CsUserReplicatorConfiguration -Identity "service:Registrar:atl-cs-001.litwareinc.com" -ADDomainNamingContextList @{Add="dc=fabrikam,dc=com","dc=contoso.com"}
  description: |-
    Example 2 also creates a new collection of user replicator configuration settings for the service Registrar:atl-cs-001.litwareinc.com.
    In this case, however, the ADDomainNamingContextList is added, along with the distinguished names of the two domains to synchronize with: fabrikam.com and contoso.com.
    This new collection of user replicator configuration settings will only configure with those two domains, even if other domains are available.
  summary: ""
parameters:
- type: <xref href="PSListModifier" data-throw-if-not-resolved="False" />
  name: ADDomainNamingContextList
  description: |+
    Distinguished names of the Active Directory domains that the User Replicator must synchronize with.
    For example, to add a domain to the list use syntax similar to this:

    `-ADDomainNamingContextList @{Add="dc=fabrikam,dc=com"}`

    You can add more than one domain name when calling the `New-CsUserReplicatorConfiguration` cmdlet.
    To do this, simply separate the domain names by using a comma:

    `-ADDomainNamingContextList @{Add="dc=fabrikam,dc=com","dc=contoso,dc=com"}`

    If you set this property to a null value the user replicator will discover and synchronize with all available domains.
    If this property is not null then the replicator will only synchronize with the domains specified in the ADDomainNamingContextList.


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error message that might arise when running the command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Unique identifier of the User Replicator configuration settings to be created.
    Settings can only be created at the service scope and only for the Registrar service.
    That means that new settings must have an Identity similar to this:

    `-Identity "service:Registrar:atl-cs-001.litwareinc.com"`

    Note that this applies only to Skype for Business Online.


  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: InMemory
  description: |+
    Creates an object reference without actually committing the object as a permanent change.
    If you assign the output of this cmdlet called with this parameter to a variable, you can make changes to the properties of the object reference and then commit those changes by calling this cmdlet's matching Set-\<cmdlet\>.


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="TimeSpan" data-throw-if-not-resolved="False" />
  name: ReplicationCycleInterval
  description: |+
    Represents the amount of time that the User Replicator waits before checking for user account updates in Active Directory.
    The replication cycle interval can be any time value between 1 second and 23 hours, 59 minutes and 59 seconds; the default value is 1 minute.
    The interval must be expressed using the format hours:minutes:seconds.
    For example, this syntax sets to time interval to one hour and 15 minutes:

    `-ReplicationCycleInterval 01:15:00`


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="TimeSpan" data-throw-if-not-resolved="False" />
  name: SkipFirstSyncAllowedDowntime
  description: |+
    Indicates how long Skype for Business Server should wait for user data to synchronize before marking the service as started.
    The default value is 2 hours (02:00:00), meaning that, after 2 hours, the status of the replication service will changed from Pending to Started.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.New-CsUserReplicatorConfiguration
name: New-CsUserReplicatorConfiguration
description: |-
  Although Skype for Business Server maintains its own database of user accounts and user account data, Skype for Business Server still relies on Active Directory as the ultimate source for user information.
  For example, when a new Active Directory user account is created, you must supply basic information about the user account (such as the Active Directory display name).
  When a user is enabled for Skype for Business Server, however, you do not need to specify a new display name.
  That's because Skype for Business Server uses the display name already stored in Active Directory.

  User account information, including the Active Directory display name, is subject to change over time.
  For example, a user who gets married might change her last name and, in turn, need to change her display name as well.
  In order to ensure that the Skype for Business Server database and Active Directory remain in synch, Skype for Business Server must periodically check in with Active Directory, retrieve the latest user account updates, and then modify the Skype for Business Server user database accordingly.
  This synchronization between Active Directory and Skype for Business Server is carried out by the User Replicator.

  When you install Skype for Business Server a global set of User Replicator configuration settings is created for you.
  By default, these settings are used to manage the User Replicator on an organization-wide basis.
  Management of the User Replicator consists of identifying the domains that Skype for Business Server needs to synch with as well as indicating how often the User Replicator checks Active Directory for user account updates.
  You can also create additional collections at the service scope, but only if you are working with Skype for Business Online.

  New User Replicator configurations settings are created using the `New-CsUserReplicatorConfiguration` cmdlet.
  Note that these settings can only be created at the service scope and only for Skype for Business Online.
  You cannot create new User Replicator settings for the on-premises version of Skype for Business Server.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/new-csuserreplicatorconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: New-CsUserReplicatorConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
