### YamlMime:PowershellCmdlet
summary: |-
  Adds a computer that hosts trusted applications to an existing pool.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Creates an object of type Microsoft.Rtc.Management.Xds.DisplayComputer.
links:
- text: Remove-CsTrustedApplicationComputer
  href: Remove-CsTrustedApplicationComputer.yml
- text: Get-CsTrustedApplicationComputer
  href: Get-CsTrustedApplicationComputer.yml
- text: New-CsTrustedApplicationPool
  href: New-CsTrustedApplicationPool.yml
- text: Get-CsTrustedApplicationPool
  href: Get-CsTrustedApplicationPool.yml
syntaxes:
- >-
  New-CsTrustedApplicationComputer [-Identity] <XdsGlobalRelativeIdentity> -Pool <String> [-Force] [-WhatIf]

   [-Confirm] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 ------------------------'
  code: |-
    New-CsTrustedApplicationComputer -Identity Trust1.litwareinc.com -Pool TrustPool.litwareinc.com
  description: |-
    This example adds a new computer with the FQDN Trust1.litwareinc.com to the pool TrustPool.litwareinc.com.
    We use the Identity parameter to specify the FQDN of the new computer and the Pool parameter to specify the FQDN of the pool.
    The pool must exist and must be a trusted application pool.
    (Note: To create a trusted application pool, call the `New-CsTrustedApplicationPool` cmdlet.)
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses any confirmation prompts that would otherwise be displayed before making changes.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsGlobalRelativeIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    The FQDN of the computer that hosts the trusted application.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Pool
  isRequired: true
  description: |+
    The FQDN of the pool hosting the trusted application computer.
    You can find available pools by running the `Get-CsTrustedApplicationPool` cmdlet.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.New-CsTrustedApplicationComputer
name: New-CsTrustedApplicationComputer
description: |-
  We recommend that the computers that are running trusted applications within a Skype for Business Server deployment be added to a separate pool that is only for trusted applications.
  However, you can add trusted application computers to an existing pool that is also used for other purposes.
  By default, when you create a pool, a computer with the same fully qualified domain name (FQDN) as the pool is also created.
  Use this cmdlet to create a new computer and add it to a pool.

  The trusted application pool must already exist in order for this cmdlet to succeed.
  In addition, you can't add an additional trusted application computer to a pool that contains service roles other than the ExternalServer role.
  For example, if the pool also supports Registrar or CentralMgmt roles, the pool can contain only one trusted application computer.
  In addition, if you did not specify a computer FQDN for the default computer when you created the pool (by calling the `New-CsTrustedApplicationPool`) cmdlet, the computer will have the same FQDN as the pool and you cannot add another computer.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/new-cstrustedapplicationcomputer
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: New-CsTrustedApplicationComputer
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
