### YamlMime:PowershellCmdlet
summary: |-
  Creates a Skype for Business application endpoint to the Skype for Business Server users if Hybrid connectivity has been deployed in the environment.

  This cmdlet was introduced in the July 2017 cumulative update for the Lync Server 2013 and May 2017 cumulative update for Skype Business Server 2015.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-CsHybridApplicationEndpoint
  href: https://learn.microsoft.com/powershell/module/skype/get-cshybridapplicationendpoint?view=skype-ps
- text: Set-CsHybridApplicationEndpoint
  href: https://learn.microsoft.com/powershell/module/skype/set-cshybridapplicationendpoint?view=skype-ps
- text: Remove-CsHybridApplicationEndpoint
  href: https://learn.microsoft.com/powershell/module/skype/remove-cshybridapplicationendpoint?view=skype-ps
syntaxes:
- >-
  New-CsHybridApplicationEndpoint -OU <OUIdParameter> -DisplayName <String> -SipAddress <String>

   -ApplicationId <Guid> [-LineUri <String>] [-PassThru] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    PS C:\> New-CsHybridApplicationEndpoint -ApplicationId 41ec7d50-ba91-1208-73ee-136b88859725 -DisplayName NewBot1 -SipAddress sip:newbot1@litwareinc.com -OU "ou=Redmond,dc=litwareinc,dc=com"
  description: |-
    This example creates a hybrid application endpoint named NewBot1 in Skype for Business Server. This application was created using the Skype for Business Bot Framework which allows you to build and connect intelligent bots to interact with your Skype for Business users using text, cards, or speech.
  summary: ""
parameters:
- type: <xref href="Guid" data-throw-if-not-resolved="False" />
  name: ApplicationId
  isRequired: true
  description: |+
    The ApplicationId or Client Id for which the endpoint is being created.

    There are predefined values if you are creating an on-premises resource account for Skype for Business hybrid deployments:
    * Auto Attendant: ce933385-9390-45d1-9512-c8d228074e07
    * Call Queue: 11cd3e2e-fccb-42ad-ad00-878b93575e07

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DisplayName
  isRequired: true
  description: |+
    Friendly name for the application endpoint is being created.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: LineUri
  description: |+
    Valid phone number for the application endpoint is being created. (Not currently supported through BOT framework)

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="OUIdParameter" data-throw-if-not-resolved="False" />
  name: OU
  isRequired: true
  description: |+
    Active Directory Organizational Unit (OU) for the disabled user to be created. Wait for the newly created user object to be directory synced to the Microsoft Entra ID or start a new directory sync cycle by running the [Start-ADSyncSyncCycle](https://learn.microsoft.com/azure/active-directory/connect/active-directory-aadconnectsync-feature-scheduler#start-the-scheduler) on the domain controller machine.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PassThru
  description: |+
    Returns an object representing the item with which you are working. By default, this cmdlet does not generate any output.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SipAddress
  isRequired: true
  description: |+
    The SipUri for the Endpoint. SIP Uri must be lowercase.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs. The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.New-CsHybridApplicationEndpoint
name: New-CsHybridApplicationEndpoint
description: |-
  Skype for Business application endpoint can be connected to the Skype for Business Server users if Hybrid connectivity has been deployed in the environment.

  Hybrid connectivity between Skype for Business Server and Skype for Business Online means users of a domain, such as contoso.com, are split between using Skype for Business Server on premises and Skype for Business Online. Some of the domain users are homed on premises, and some users are homed online. Application endpoint will be configured as online users reachable by the on-premises users.

  `New-CsHybridApplicationEndpoint` must be run in Skype for Business Server. It will be copied to Skype for Business Online via dir sync.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/new-cshybridapplicationendpoint
  applicable: Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: New-CsHybridApplicationEndpoint
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
