### YamlMime:PowershellCmdlet
summary: |-
  Creates a new collection of health monitoring configuration settings for use in your organization.
  These settings enable administrators to run quality assurance tests without having to supply the user names and passwords for the required test accounts.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
    The New-CsHealthMonitoringConfiguration cmdlet does not accept pipelined input.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The New-CsHealthMonitoringConfiguration cmdlet creates new instances of the Microsoft.Rtc.Management.WritableConfig.Settings.HealthMonitoring.HealthMonitoringSettings object.
links:
- text: Get-CsHealthMonitoringConfiguration
  href: Get-CsHealthMonitoringConfiguration.yml
- text: Remove-CsHealthMonitoringConfiguration
  href: Remove-CsHealthMonitoringConfiguration.yml
- text: Set-CsHealthMonitoringConfiguration
  href: Set-CsHealthMonitoringConfiguration.yml
syntaxes:
- >-
  New-CsHealthMonitoringConfiguration [-Identity] <XdsGlobalRelativeIdentity> [-FirstTestSamAccountName <String>]

   -FirstTestUserSipUri <String> [-SecondTestSamAccountName <String>] -SecondTestUserSipUri <String> [-Force]

   [-InMemory] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  New-CsHealthMonitoringConfiguration -TargetFqdn <String> [-FirstTestSamAccountName <String>]

   -FirstTestUserSipUri <String> [-SecondTestSamAccountName <String>] -SecondTestUserSipUri <String> [-Force]

   [-InMemory] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: '-------------------------- EXAMPLE 1 --------------------------'
  code: |-
    New-CsHealthMonitoringConfiguration -Identity atl-cs-001.litwareinc.com -FirstTestUserSipUri "sip:kenmyer@litwareinc.com" -SecondTestUserSipUri "sip:pilar@litwareinc.com"
  description: |-
    The command shown in Example 1 creates a new collection of health monitoring configuration settings for the pool atl-cs-001.litwareinc.com.
    These new settings will use sip:kenmyer@litwareinc.com and sip:pilar@litwareinc.com as the preconfigured test accounts.
  summary: ""
- title: '-------------------------- EXAMPLE 2 --------------------------'
  code: |-
    $x = Get-CsService -Registrar | Select-Object PoolFqdn

    foreach ($i in $x)

    {New-CsHealthMonitoringConfiguration -Identity $i.PoolFqdn -FirstTestUserSipUri "sip:kenmyer@litwareinc.com" -SecondTestUserSipUri "sip:pilar@litwareinc.com"}
  description: |-
    Example 2 creates a new collection of health monitoring configuration settings for all the Registrar pools in the organization.
    To do that, the first command in the example uses the Get-Service cmdlet and the Registrar parameter to return a collection of all the Registrar pools.
    This collection is then piped to the Select-Object cmdlet, which picks out only the PoolFqdn property.
    (This property returns the FQDN of a Registrar pool.) These FQDNs are stored in a variable named $x.

    In the second command, a foreach loop is created to loop through each Registrar pool FQDN.
    For each FQDN, the New-CsHealthMonitoringConfiguration cmdlet is called to create a new collection of configuration settings, with the FQDN stored in $x used as the Identity for the new collection.
    Each collection is also assigned the same two test accounts: sip:kenmyer@litwareinc.com and sip:pilar@litwareinc.com.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: FirstTestSamAccountName
  description: |+
    SamAccountName of the first test user.
    The FirstTestSamAccountName must be entered by using the format domain\username; for example:

    `-FirstTestSamAccountName litwareinc\kenmyer`

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: FirstTestUserSipUri
  isRequired: true
  description: |+
    SIP address of the first test user to be configured for use by this collection of health monitoring settings.
    Note that the SIP address must include the sip: prefix.
    For example: `-FirstTestUserSipUri "sip:kenmyer@litwareinc.com".`

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error message that might occur when running the command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsGlobalRelativeIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    FQDN of the pool where the health monitoring configuration settings are to be assigned (for example: `-Identity atl-cs-001.litwareinc.com`).
    Your command will fail if the specified pool already hosts a collection of health monitoring configuration settings.

    The Identity is equivalent to the TargetFqdn parameter.
    When creating a new collection of settings, you can use either parameter.
    If you leave out both parameters, the New-CsHealthMonitoringConfiguration cmdlet will prompt you to enter the Identity.



  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: InMemory
  description: |+
    Creates an object reference without actually committing the object as a permanent change.
    If you assign the output of this cmdlet called with this parameter to a variable, you can make changes to the properties of the object reference and then commit those changes by calling this cmdlet's matching Set-\<cmdlet\>.



  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SecondTestSamAccountName
  description: |+
    SamAccountName of the second test user.
    The SecondTestSamAccountName must be entered by using the format domain\username; for example:

    `-SecondTestSamAccountName litwareinc\pilar`

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SecondTestUserSipUri
  isRequired: true
  description: |+
    SIP address of the second test user to be configured for use by this collection of health monitoring settings.
    Note that the SIP address must include the sip: prefix.
    For example: `-SecondTestUserSipUri "sip:pilar@litwareinc.com".`

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: TargetFqdn
  isRequired: true
  description: |+
    FQDN of the pool where the health monitoring configuration settings are to be assigned (for example: `-TargetFqdn atl-cs-001.litwareinc.com`).
    Your command will fail if the specified pool already hosts a collection of health monitoring configuration settings.

    The TargetFqdn is equivalent to the Identity parameter.
    When creating a new collection of settings, you can use either parameter.
    If you leave out both parameters, the New-CsHealthMonitoringConfiguration cmdlet will prompt you to enter the Identity.



  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.New-CsHealthMonitoringConfiguration
name: New-CsHealthMonitoringConfiguration
description: |-
  Synthetic transactions are used in Skype for Business Server to verify that users are able to successfully complete common tasks such as logging on to the system, exchanging instant messages, or making calls to a phone located on the public switched telephone network (PSTN).
  These tests can be conducted "manually" by an administrator, or they can be automatically run by an application such as Microsoft System Center Operations Manager (formerly Microsoft Operations Manager).

  Synthetic transactions can be conducted in two different ways.
  Many administrators will use the CsHealthMonitoringConfiguration cmdlets to set up test accounts for each of their Registrar pools.
  These test accounts are a pair of user accounts that have been preconfigured for use with synthetic transactions.
  (Typically these are test accounts and not accounts that belong to actual users.) When these test accounts are configured for a pool, administrators can run a synthetic transaction against that pool without having to specify the identities of (and supply the credentials for) the user accounts involved in the test.
  Instead, the synthetic transaction will automatically use the preconfigured test accounts when performing its checks.

  Alternatively, administrators can run a synthetic transaction using actual user accounts.
  For example, if two users are unable to exchange instant messages, an administrator can run a synthetic transaction using the two user accounts in question (as opposed to a pair of test accounts).
  If you decide to conduct a synthetic transaction using actual user accounts you will have to supply the credentials for each user.

  The New-CsHealthMonitoringConfiguration cmdlet provides a way for you to create a new health monitoring configuration settings for a Registrar or Director pool.
  When creating a new collection of health monitoring configuration settings, you must specify the fully qualified domain name (FQDN) of the pool, as well as the SIP addresses of the two accounts that will serve as the pool test accounts.
  (However, you do not need to provide the passwords for those test accounts.) Note that each pool can host, at most, a single collection of health monitoring configuration settings.
  If you try to create a new collection for the pool atl-cs-001.litwareinc.com and this pool has already been assigned a Registrar, then your command will fail.

  When you run the New-CsHealthMonitoringConfiguration cmdlet you might receive a warning if you have pools that have not been assigned test users; this might include Director pools as well as Office Communications Server pools.
  These warnings can be ignored.
  If you prefer, you can assign test users homed on other pools to your Director pools; that would enable you to run the Test-CsRegistration cmdlet against the Director.
  However, test users cannot be assigned to Office Communications Server pools.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/new-cshealthmonitoringconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: New-CsHealthMonitoringConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
