### YamlMime:PowershellCmdlet
summary: |-
  Creates a new collection of Persistent Chat configuration settings at the site or service scope.
  Persistent Chat configuration settings are used to manage the Persistent Chat service.
  For example, these settings allow you to specify the maximum number of users who can participate in a chat room.
  This cmdlet was introduced in Lync Server 2013.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
    The New-CsPersistentChatConfiguration cmdlet does not accept pipelined input.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The New-CsPersistentChatConfiguration cmdlet creates new instances of the Microsoft.Rtc.Management.WritableConfig.Settings.PersistentChat.PersistentChatConfiguration object.
links:
- text: Get-CsPersistentChatConfiguration
  href: Get-CsPersistentChatConfiguration.yml
- text: Remove-CsPersistentChatConfiguration
  href: Remove-CsPersistentChatConfiguration.yml
- text: Set-CsPersistentChatConfiguration
  href: Set-CsPersistentChatConfiguration.yml
syntaxes:
- >-
  New-CsPersistentChatConfiguration [-Identity] <XdsIdentity> [-Confirm] [-DefaultChatHistory <Int16>] [-Force]

   [-InMemory] [-MaxFileSizeKB <UInt32>] [-ParticipantUpdateLimit <UInt32>] [-RoomManagementUrl <String>]

   [-WhatIf] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    New-CsPersistentChatConfiguration -Identity "site:Redmond" -ParticipantUpdateLimit 100
  description: |-
    The command shown in Example 1 creates a new set of Persistent Chat configuration settings applied to the Redmond site.
    In this example, the ParticipantUpdateLimit property is set to 100.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  parameterValueGroup: ""
- type: <xref href="Int16" data-throw-if-not-resolved="False" />
  name: DefaultChatHistory
  description: |+
    Default number of chat messages instantly available in a chat room.
    Note that this value represents only the number of messages immediately available; it does not place a limit on the total amount of messages that can be retrieved.

    DefaultChatHistory can be set to any value between 1 and 500, inclusive.
    The default value is 30.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error message that might occur when running the command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Unique identifier for the new Persistent Chat configuration settings being created.
    New configuration settings can be created at either the site or the service scope (for the Persistent Chat Server service, only).
    To create new settings at the site scope, use syntax similar to this:

    `-Identity "site:Redmond"`

    To create new settings at the service scope, use syntax like this:

    `-Identity "service:PersistentChatServer:atl-gc-001.litwarein.com"`

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: InMemory
  description: |+
    Creates an object reference without actually committing the object as a permanent change.
    If you assign the output of this cmdlet called with this parameter to a variable, you can make changes to the properties of the object reference and then commit those changes by calling this cmdlet's matching Set- cmdlet.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: MaxFileSizeKB
  description: |+
    Maximum size of a file (in kilobytes) that can be uploaded or downloaded by the web service.
    The default value is 20000 KB.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: ParticipantUpdateLimit
  description: |+
    Maximum number of users who can participate in a chat room before the active participant list updates are disabled.
    The default value is 75.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: RoomManagementUrl
  description: |+
    URL for the Web page that administrators can use to manage individual chat rooms.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  parameterValueGroup: ""
applicable:
- Lync Server 2013
- Skype for Business Server 2015
uid: SkypeForBusiness.New-CsPersistentChatConfiguration
name: New-CsPersistentChatConfiguration
description: |-
  The Persistent Chat service (which replaces the Group Chat service used in Microsoft Lync Server 2010) provides organizations with messaging and collaboration capabilities similar to those found in Internet discussion forums: users can exchange messages in real-time, yet can also revisit and restart those conversations at any time.
  Conversations can be based around specific topics, and these conversations can be made available to everyone or to only a selected set of users.
  Likewise, individual chat rooms can be configured so that anyone can post a message or configured so that only designated presenters can post messages.

  The Persistent Chat service is managed, in part, by Persistent Chat configuration settings, which dictate such things as the number of previously-posted chat messages immediately available when you log on to a chat room (the chat history) or the maximum size of a file that can be uploaded to (or downloaded from) the service.
  These settings can be configured at the global or the site scope, or at the service scope (that is, you can have a custom collection of settings assigned to an individual Persistent Chat pool).

  Skype for Business Server Control Panel: To create a new collection of Persistent Chat configuration settings using the Skype for Business Server Control Panel, click Persistent Chat, click Persistent Chat Configuration, click New, and then click either Site configuration or Pool configuration.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/new-cspersistentchatconfiguration
  applicable: Lync Server 2013, Skype for Business Server 2015
  title: New-CsPersistentChatConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
