### YamlMime:PowershellCmdlet
summary: |-
  Use the `New-CsTelemetryConfiguration` cmdlet to create new configurations for telemetry.
  UNRESOLVED_TOKEN_VAL(PS_TelemetryDataStatement)
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
syntaxes:
- >-
  New-CsTelemetryConfiguration [-Identity] <XdsIdentity> [-Confirm] [-EnableClientTelemetry <Boolean>] [-Force]

   [-InMemory] [-WhatIf] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    New-CsTelemetryConfiguration -Identity Site:Redmond -EnableClientTelemetry $True
  description: |-
    This example creates a new telemetry configuration with telemetry enabled and scoped for the Redmond site.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableClientTelemetry
  description: |+
    When set to true, client telemetry will be enabled.
    The default is false.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error messages and completes the cmdlet operation.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    A unique identifier that includes the scope of the telemetry configuration.
    Telemetry configurations can be scoped at the Global, Site, or Service level.
    For example, "site:Redmond" (for site).
    The format of the service scope is "Service:\<Identity\>", where identity is derived from the topology.
    You can use the following commands to identify the relevant services.

    `Get-CsService -WebServer | fl Identity`

    `Get-CsService -PoolFqdn \<pool\> | fl Identity`

    The first command will give you all of the WebServices in the topology, regardless of the pool.
    The second will give you all of the services on the pool, regardless of their role.
    You can combine the two commands to zero in on a single role in a single pool.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: InMemory
  description: |+
    Creates an object reference without actually committing the object as a permanent change.
    If you assign the output of this cmdlet called with this parameter to a variable, you can make changes to the properties of the object reference and then commit those changes by calling this cmdlet's matching Set-\<cmdlet\>.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.New-CsTelemetryConfiguration
name: New-CsTelemetryConfiguration
description: |-
  For privacy information, see the Skype for Business Privacy Statement (https://go.microsoft.com/fwlink/?LinkID=517480&clcid=0x409).
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/new-cstelemetryconfiguration
  applicable: Skype for Business Server 2015, Skype for Business Server 2019
  title: New-CsTelemetryConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
