### YamlMime:PowershellCmdlet
summary: |-
  Creates a new endpoint contact for a trusted application.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Creates an object of type Microsoft.Rtc.Management.ADConnect.Schema.OCSADApplicationContact.
links:
- text: Remove-CsTrustedApplicationEndpoint
  href: Remove-CsTrustedApplicationEndpoint.yml
- text: Set-CsTrustedApplicationEndpoint
  href: Set-CsTrustedApplicationEndpoint.yml
- text: Get-CsTrustedApplicationEndpoint
  href: Get-CsTrustedApplicationEndpoint.yml
syntaxes:
- >-
  New-CsTrustedApplicationEndpoint -ApplicationId <String> -TrustedApplicationPoolFqdn <Fqdn>

   [-SipAddress <String>] [-DisplayName <String>] [-DisplayNumber <String>] [-LineURI <String>]

   [-PrimaryLanguage <String>]

   [-SecondaryLanguages <Microsoft.Rtc.Management.ADConnect.Core.MultiValuedProperty`1[System.String]>]

   [-Tenant <Guid>] [-PassThru] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 ------------------------'
  code: |-
    New-CsTrustedApplicationEndpoint -ApplicationId tapp1 -TrustedApplicationPoolFqdn TrustPool.litwareinc.com
  description: |-
    This example creates a trusted application endpoint for the application with the Application ID tapp1 homed on the pool TrustPool.litwareinc.com.
    ApplicationID and TrustedApplicationPoolFqdn are the only parameters that are required to create a trusted application endpoint.
    However, keep in mind that assigning values to only these two parameters will auto-generate a SIP address for the contact.
    In order to ensure the SIP address is unique, the auto-generated address will include a globally unique identifier (GUID) and will look something like this: sip:RtcApplication-fbf9e2d1-c6aa-45a3-a045-b92d4ef961b2@litwareinc.com.
    If you'd like a more readable SIP address, see Example 2.
  summary: ""
- title: '-------------------------- Example 2 ------------------------'
  code: |-
    New-CsTrustedApplicationEndpoint -ApplicationId tapp1 -TrustedApplicationPoolFqdn TrustPool.litwareinc.com -SipAddress sip:endpoint1@litwareinc.com
  description: |-
    Example 2 is identical to Example 1 in that it creates a trusted application endpoint for the application with the Application ID tapp1 on the TrustPool.litwareinc.com pool.
    Unlike Example 1, we include one more parameter in our endpoint creation: SipAddress.
    Rather than allowing the system to generate a SIP address, we've specified an address of endpoint1@litwareinc.com.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ApplicationId
  isRequired: true
  description: |+
    The application ID of the trusted application for which the endpoint contact is being created.
    An application with this ID must already exist.
    Note that you may include only the name part of the application ID, you don't need to (but you can) include the prefix information.
    For example, if the application ID is urn:application:TrustedApp1 you only need to pass the string TrustedApp1 to this parameter.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DisplayName
  description: |+
    The display name of the endpoint contact object.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DisplayNumber
  description: |+
    The telephone number of the contact as it will appear in the Address Book.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: LineURI
  description: |+
    The phone number of the contact.
    Must be in the format TEL:\<number\>, for example TEL:+14255551212.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PassThru
  description: |+
    Returns the results of this command.
    Running this cmdlet will display the newly created object; including this parameter will simply repeat that output, making the use of this parameter redundant.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: PrimaryLanguage
  description: |+
    The primary language used for the trusted application.
    The language must be configured using a valid language code, such as en-US (U.S.
    English), fr-FR (French), etc.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Microsoft.Rtc.Management.ADConnect.Core.MultiValuedProperty`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.String" data-throw-if-not-resolved="False" /><span>]</span>
  name: SecondaryLanguages
  description: |+
    A collection of languages that can also be used for trusted applications.
    Values must be configured as a comma-separated values list of language codes.
    For example, the following syntax sets French Canadian and French as secondary languages: `-SecondaryLanguages "fr-CA","fr-FR"`.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SipAddress
  description: |+
    A SIP address for the new contact object.
    If you do not include a value for this parameter a SIP address will be auto-generated in the format sip:RtcApplication-\<GUID\>.\<domain\>, for example sip:RtcApplication-fbf9e2d1-c6aa-45a3-a045-b92d4ef961b2@litwareinc.com.
    The domain will be the default SIP domain.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Guid" data-throw-if-not-resolved="False" />
  name: Tenant
  description: |+
    Globally unique identifier (GUID) of the Skype for Business Online tenant account for which the new trusted application pool endpoint is being created.
    For example:

    `-Tenant "38aad667-af54-4397-aaa7-e94c79ec2308"`

    You can return the tenant ID for each of your tenants by running this command:

    `Get-CsTenant | Select-Object DisplayName, TenantID`


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Fqdn" data-throw-if-not-resolved="False" />
  name: TrustedApplicationPoolFqdn
  isRequired: true
  description: |+
    The fully qualified domain name (FQDN) of the trusted application pool associated with the application.
    The application must already be associated with this pool for the endpoint to be created.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.New-CsTrustedApplicationEndpoint
name: New-CsTrustedApplicationEndpoint
description: |-
  A trusted application endpoint is an Active Directory contact object that enables routing of calls to a trusted application.
  This cmdlet creates a new endpoint contact object in Active Directory Domain Services for a specified application.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/new-cstrustedapplicationendpoint
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: New-CsTrustedApplicationEndpoint
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
