### YamlMime:PowershellCmdlet
summary: |-
  Creates a new bandwidth policy service configuration.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Creates an object of type Microsoft.Rtc.Management.WritableConfig.Settings.BandwidthPolicyServiceConfiguration.BandwidthPolicyServiceConfiguration.
links:
- text: Remove-CsBandwidthPolicyServiceConfiguration
  href: Remove-CsBandwidthPolicyServiceConfiguration.yml
- text: Set-CsBandwidthPolicyServiceConfiguration
  href: Set-CsBandwidthPolicyServiceConfiguration.yml
- text: Get-CsBandwidthPolicyServiceConfiguration
  href: Get-CsBandwidthPolicyServiceConfiguration.yml
syntaxes:
- >-
  New-CsBandwidthPolicyServiceConfiguration [-Identity] <XdsIdentity> [-EnableLogging <Boolean>]

   [-LogCleanUpInterval <TimeSpan>] [-MaxLogFileSizeMb <UInt32>] [-MaxTokenLifetime <TimeSpan>] [-Force]

   [-InMemory] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: '-------------------------- EXAMPLE 1 --------------------------'
  code: |-
    New-CsBandwidthPolicyServiceConfiguration -Identity site:Redmond
  description: |-
    This example creates a new bandwidth policy service configuration at the site Redmond (`-Identity site:Redmond`).
    No other parameters are specified, so the defaults are used for all configuration values.
  summary: ""
- title: '-------------------------- EXAMPLE 2 --------------------------'
  code: |-
    New-CsBandwidthPolicyServiceConfiguration -Identity site:Dublin -EnableLogging $True -LogCleanupInterval 30.00:00:00
  description: |-
    In this example we again create a new bandwidth policy service configuration, this time for the Dublin site (`-Identity site:Dublin`).
    For this site, rather than accepting the default values, we want to enable logging and set the number of days that pass before logs are cleaned up to 30 days.
    We do this by passing a value of True ($True) to the EnableLogging parameter, and then passing a value of 30.00:00:00 to the parameter LogCleanupInterval.
    The LogCleanupInterval value is a TimeSpan object, which is in the format dd.hh:mm:ss, where d is days, h is hours, m is minutes, and s is seconds.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableLogging
  description: |+
    Set this parameter to True to generate CAC failure and link status logs related to the bandwidth policy service.

    Default: False

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses any confirmation prompts that would otherwise be displayed before making changes.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    A unique identifier that contains the scope and name of the configuration.
    This configuration can be created only at the site scope, so the Identity will be in the following format: site:\<site name\>, where \<site name\> is the name of the site to which the configuration applies.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: InMemory
  description: |+
    Creates an object reference without actually committing the object as a permanent change.
    If you assign the output of this cmdlet called with this parameter to a variable, you can make changes to the properties of the object reference and then commit those changes by calling this cmdlet's matching Set-\<cmdlet\>.



  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="TimeSpan" data-throw-if-not-resolved="False" />
  name: LogCleanUpInterval
  description: |+
    The period of time after which CAC failure and link status logs will be removed.

    This value must be within the range 1 day through 60 days.
    The value must be entered in the format dd.hh:mm:ss, where d is days, h is hours, m is minutes, and s is seconds.

    Default: 10 days (10.00:00:00)

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: MaxLogFileSizeMb
  description: |+
    The maximum size the log file is allowed to reach.
    The value for this parameter must be a positive number; it specifies the file size in megabytes.

    Default: 3 (MB)

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="TimeSpan" data-throw-if-not-resolved="False" />
  name: MaxTokenLifetime
  description: |+
    The maximum amount of time the token issued by the Bandwidth Policy Authentication service will exist.

    This value must be in the range 1 hour through 24 hours.
    The value must be entered in the format dd.hh:mm:ss, where d is days, h is hours, m is minutes, and s is seconds.

    Default: 8 hours (08:00:00)

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.New-CsBandwidthPolicyServiceConfiguration
name: New-CsBandwidthPolicyServiceConfiguration
description: |-
  Call admission control (CAC) is a way of determining whether to allow real-time communications sessions, such as voice or video calls, to be established based on bandwidth constraints.
  Within the Skype for Business Server implementation of CAC, regions, sites, and subnets are defined within a network along with the relationships and links between those entities in order to place bandwidth constraints between them.
  Bandwidth Policy service is the component that performs CAC functionality in the Skype for Business Server deployment, enabling the decision as to whether sufficient bandwidth exists for a call to be established.
  This cmdlet configures a new bandwidth policy service at the site level.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/new-csbandwidthpolicyserviceconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: New-CsBandwidthPolicyServiceConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
