### YamlMime:PowershellCmdlet
summary: |-
  Removes a trusted application endpoint.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.Rtc.Management.ADConnect.Schema.OCSADApplicationContact object.
    Accepts pipelined input of trusted application endpoint objects.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    This cmdlet does not return a value.
    It removes an object of type Microsoft.Rtc.Management.ADConnect.Schema.OCSADApplicationContact.
links:
- text: New-CsTrustedApplicationEndpoint
  href: New-CsTrustedApplicationEndpoint.yml
- text: Set-CsTrustedApplicationEndpoint
  href: Set-CsTrustedApplicationEndpoint.yml
- text: Get-CsTrustedApplicationEndpoint
  href: Get-CsTrustedApplicationEndpoint.yml
syntaxes:
- Remove-CsTrustedApplicationEndpoint [-Identity] <UserIdParameter> [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 ------------------------'
  code: |-
    Remove-CsTrustedApplicationEndpoint -Identity "Endpoint 1"
  description: |-
    This example removes the endpoint contact with the Identity (in this case the display name) Endpoint 1.
    Because identities must be unique, this command will remove, at most, one endpoint.
  summary: ""
- title: '-------------------------- Example 2 ------------------------'
  code: |-
    Get-CsTrustedApplicationEndpoint -ApplicationId tapp2 | Remove-CsTrustedApplicationEndpoint
  description: |-
    This example removes all trusted application endpoints associated with the application tapp2.
    This is accomplished by first calling the `Get-CsTrustedApplicationEndpoint` cmdlet and passing the ID tapp2 to the ApplicationId parameter.
    This will return a collection of endpoints that are associated with the tapp2 trusted application.
    This collection is then piped to the `Remove-CsTrustedApplicationEndpoint` cmdlet, which removes each endpoint in the collection.
    Keep in mind that this call to the `Get-CsTrustedApplicationEndpoint` cmdlet could retrieve endpoints with the application ID tapp2 from multiple pools, which would result in this command removing trusted application endpoints from multiple pools.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UserIdParameter" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    The Identity (the distinguished name of the contact), SIP address, or display name of the application endpoint to be removed.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Remove-CsTrustedApplicationEndpoint
name: Remove-CsTrustedApplicationEndpoint
description: |-
  A trusted application endpoint is an Active Directory contact object that enables routing of calls to a trusted application.
  This cmdlet removes an existing endpoint contact object from Active Directory Domain Services.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/remove-cstrustedapplicationendpoint
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Remove-CsTrustedApplicationEndpoint
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
