### YamlMime:PowershellCmdlet
summary: |-
  Removes the specified hybrid application endpoint.

  This cmdlet was introduced in the July 2017 cumulative update for the Lync Server 2013 and May 2017 cumulative update for Skype Business Server 2015.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href="Microsoft.Rtc.Management.AD.UserIdParameter" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-CsHybridApplicationEndpoint
  href: https://learn.microsoft.com/powershell/module/skype/new-cshybridapplicationendpoint?view=skype-ps
- text: Get-CsHybridApplicationEndpoint
  href: https://learn.microsoft.com/powershell/module/skype/get-cshybridapplicationendpoint?view=skype-ps
- text: Set-CsHybridApplicationEndpoint
  href: https://learn.microsoft.com/powershell/module/skype/set-cshybridapplicationendpoint?view=skype-ps
syntaxes:
- Remove-CsHybridApplicationEndpoint [-Identity] <UserIdParameter> [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    PS C:\> Remove-CsHybridApplicationEndpoint -Identity "CN={4f6c99fe-7999-4088-ac4d-e88e0b3d3820},OU=Redmond,DC=litwareinc,DC=com"
  description: |-
    This example removes the specified hybrid application endpoint including the Active Directory user object.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UserIdParameter" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    The ApplicationId for the endpoint that is being deleted.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs. The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Remove-CsHybridApplicationEndpoint
name: Remove-CsHybridApplicationEndpoint
description: |-
  This cmdlet removes an existing hybrid application endpoint user object in Active Directory Domain Services. A hybrid application endpoint is an Active Directory user object that enables a trusted application endpoint like bots in hybrid environments.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/remove-cshybridapplicationendpoint
  applicable: Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Remove-CsHybridApplicationEndpoint
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
