### YamlMime:PowershellCmdlet
summary: |-
  Removes the specified collection of media configuration settings.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.Rtc.Management.WritableConfig.Settings.Media.MediaSettings object.
    Accepts pipelined input of media configuration objects.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Removes an object of type Microsoft.Rtc.Management.WritableConfig.Settings.Media.MediaSettings.
links:
- text: New-CsMediaConfiguration
  href: New-CsMediaConfiguration.yml
- text: Set-CsMediaConfiguration
  href: Set-CsMediaConfiguration.yml
- text: Get-CsMediaConfiguration
  href: Get-CsMediaConfiguration.yml
syntaxes:
- Remove-CsMediaConfiguration [-Identity] <XdsIdentity> [-Force] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Remove-CsMediaConfiguration -Identity site:Redmond1
  description: |-
    In Example 1, the `Remove-CsMediaConfiguration` cmdlet is used to delete the media configuration collection with the Identity site:Redmond1.
    When media settings are removed from the site scope, that site will automatically begin to use the global media settings.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Get-CsMediaConfiguration | Where-Object {$_.EncryptionLevel -eq "RequireEncryption"} | Remove-CsMediaConfiguration
  description: |-
    In Example 2, three cmdlets--the `Get-CsMediaConfiguration` cmdlet, the `Where-Object` cmdlet and the `Remove-CsMediaConfiguration` cmdlet--are used to remove all the media configuration collections where encryption is required of all parties involved in the conversation.
    To do this, the `Get-CsMediaConfiguration` cmdlet is first used to return all the media configuration collections in the organization.
    That information is then piped to the `Where-Object` cmdlet, which applies a filter that restricts the pipeline data to those collections where the EncryptionLevel property is equal to (-eq) RequireEncryption.
    Finally, that filtered set of data is passed to the `Remove-CsMediaConfiguration` cmdlet, which deletes each item in the set.
  summary: ""
- title: '-------------------------- Example 3 --------------------------'
  code: |-
    Get-CsMediaConfiguration -Filter service:* | Remove-CsMediaConfiguration
  description: |-
    In this example all media configurations defined at the service scope (meaning the configuration applies to a specific service) are removed.
    This is accomplished by first calling the `Get-CsMediaConfiguration` cmdlet using the Filter service:*.
    This filter retrieves all media configuration collections with an Identity starting with service, which means all collections at the service scope.
    That set of collections is then piped the `Remove-CsMediaConfiguration` cmdlet, which removes them all.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses any confirmation prompts that would otherwise be displayed before making changes.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    The unique identifier of the media configuration settings you want to remove.
    This identifier specifies the scope at which this configuration is applied (global, site, or service).

  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Remove-CsMediaConfiguration
name: Remove-CsMediaConfiguration
description: |-
  This cmdlet removes a collection of media settings.
  These settings relate to audio and video calls between client endpoints.

  This cmdlet can also be used to remove the global media settings.
  In that case, however, the settings will not actually be removed; instead, they will simply be reset to their default values.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/remove-csmediaconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Remove-CsMediaConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
