### YamlMime:PowershellCmdlet
summary: |-
  Removes an existing collection of health monitoring configuration settings.
  These settings enable administrators to run quality assurance tests without having to supply the user names and passwords for the required test accounts.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.Rtc.Management.WritableConfig.Settings.HealthMonitoring.HealthMonitoringSettings object.
    The `Remove-CsHealthMonitoringConfiguration` cmdlet accepts pipelined instances of the health monitoring configuration object.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
    Instead, the `Remove-CsHealthMonitoringConfiguration` cmdlet deletes existing instances of the Microsoft.Rtc.Management.WritableConfig.Settings.HealthMonitoring.HealthMonitoringSettings object.
links:
- text: Get-CsHealthMonitoringConfiguration
  href: Get-CsHealthMonitoringConfiguration.yml
- text: New-CsHealthMonitoringConfiguration
  href: New-CsHealthMonitoringConfiguration.yml
- text: Set-CsHealthMonitoringConfiguration
  href: Set-CsHealthMonitoringConfiguration.yml
syntaxes:
- >-
  Remove-CsHealthMonitoringConfiguration [-Identity] <XdsGlobalRelativeIdentity> [-Force] [-WhatIf] [-Confirm]

   [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 ------------------------'
  code: |-
    Remove-CsHealthMonitoringConfiguration -Identity atl-cs-001.litwareinc.com
  description: |-
    The command shown in Example 1 deletes the collection of health monitoring configuration settings with the Identity atl-cs-001.litwareinc.com.
    Because identities must be unique, this command will delete, at most, a single collection of settings.
  summary: ""
- title: '-------------------------- Example 2 ------------------------'
  code: |-
    Get-CsHealthMonitoringConfiguration | Remove-CsHealthMonitoringConfiguration
  description: |-
    Example 2 deletes all the health monitoring configuration settings currently in use.
    To do this, the command first calls the `Get-CsHealthMonitoringConfiguration` cmdlet without any parameters; this returns a collection of all the health monitoring configuration settings in the organization.
    This collection is then piped to the `Remove-CsHealthMonitoringConfiguration` cmdlet, which deletes each item in the collection.
  summary: ""
- title: '-------------------------- Example 3 ------------------------'
  code: |-
    Get-CsHealthMonitoringConfiguration -Filter *.litwareinc.com | Remove-CsHealthMonitoringConfiguration
  description: |-
    Example 3 deletes all the health monitoring configuration settings that have been created for the domain litwareinc.com.
    To do this, the `Get-CsHealthMonitoringConfiguration` cmdlet is called along with the Filter parameter; the filter value "*.litwareinc.com" ensures that only those settings that have an Identity that ends with the string value ".litwareinc.com" will be returned.
    The filtered collection is then piped to the `Remove-CsHealthMonitoringConfiguration` cmdlet, which deletes each item in the collection.
  summary: ""
- title: '-------------------------- Example 4 ------------------------'
  code: |-
    (Get-CsHealthMonitoringConfiguration | Where-Object {$_.FirstTestUserSipUri -eq "sip:kenmyer@litwareinc.com" -or $_.SecondTestUserSipUri -eq " sip:kenmyer@litwareinc.com"}) | Remove-CsHealthMonitoringConfiguration
  description: |-
    The command shown in Example 4 deletes all the health monitoring configuration settings that include the user with the SIP address sip:kenmyer@litwareinc.com as one of the test users.
    To perform this task, the command starts off by calling the `Get-CsHealthMonitoringConfiguration` cmdlet without any parameters; this returns a collection of all the health monitoring configuration settings currently in use in the organization.
    This collection is then piped to the `Where-Object` cmdlet, which picks out only those settings where the FirstTestUserSipUri property is equal to "sip:kenmyer@litwareinc.com" or where the SecondTestUserSipUri property is equal to "sip:kenmyer@litwareinc.com".
    In turn, those settings are piped to and removed by, the `Remove-CsHealthMonitoringConfiguration` cmdlet.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error message that might occur when running the command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsGlobalRelativeIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Fully qualified domain name (FQDN) of the pool hosting the health monitoring configuration settings that are to be deleted.
    For example: -Identity atl-cs-001.litwareinc.com.

  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Remove-CsHealthMonitoringConfiguration
name: Remove-CsHealthMonitoringConfiguration
description: |-
  Synthetic transactions are used in Skype for Business Server to verify that users are able to successfully complete common tasks such as logging on to the system, exchanging instant messages, or making calls to a phone located on the public switched telephone network (PSTN).
  These tests can be conducted manually by an administrator, or they can be automatically run by an application such as Microsoft System Center Operations Manager (formerly Microsoft Operations Manager).

  Synthetic transactions can be conducted in two different ways.
  Many administrators will use the CsHealthMonitoringConfiguration cmdlets to set up test accounts for each of their Registrar pools.
  These test accounts are a pair of user accounts that have been preconfigured for use with synthetic transactions.
  (Typically these are test accounts and not accounts that belong to actual users.) When these test accounts are configured for a pool, administrators can run a synthetic transaction against that pool without having to specify the identities of (and supply the credentials for) the user accounts involved in the test.
  Instead, the synthetic transaction will automatically use the preconfigured test accounts when performing its checks.

  Alternatively, administrators can run a synthetic transaction using actual user accounts.
  For example, if two users are unable to exchange instant messages, an administrator can run a synthetic transaction using the two user accounts in question (as opposed to a pair of test accounts).
  If you decide to conduct a synthetic transaction using actual user accounts you will have to supply the credentials for each user.

  The `Remove-CsHealthMonitoringConfiguration` cmdlet provides a way for you to remove any of the health monitoring configuration settings that have been configured for use in your organization.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/remove-cshealthmonitoringconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Remove-CsHealthMonitoringConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
