### YamlMime:PowershellCmdlet
summary: |-
  Removes one or more collections of Web Services configuration settings.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.Rtc.Management.WritableConfig.Settings.Web.WebServiceSettings object.
    The `Remove-CsWebServiceConfiguration` cmdlet accepts pipelined input of the Web Services settings object.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
    Instead, the `Remove-CsWebServiceConfiguration` cmdlet deletes existing instances of the Microsoft.Rtc.Management.WritableConfig.Settings.Web.WebServiceSettings object.
links:
- text: Get-CsWebServiceConfiguration
  href: Get-CsWebServiceConfiguration.yml
- text: New-CsWebServiceConfiguration
  href: New-CsWebServiceConfiguration.yml
- text: Set-CsWebServiceConfiguration
  href: Set-CsWebServiceConfiguration.yml
syntaxes:
- Remove-CsWebServiceConfiguration [-Identity] <XdsIdentity> [-Force] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 ------------------------'
  code: |-
    Remove-CsWebServiceConfiguration -Identity site:Redmond
  description: |-
    Example 1 removes the Web Services configuration settings for the Redmond site.
  summary: ""
- title: '-------------------------- Example 2 ------------------------'
  code: |-
    Get-CsWebServiceConfiguration -Filter "site:*" | Remove-CsWebServiceConfiguration
  description: |-
    In Example 2, all the Web Services settings configured at the site scope are removed.
    To carry out this task, the command first calls the `Get-CsWebServiceConfiguration` cmdlet and the Filter parameter; the filter value "site:*" ensures that only those settings that have an Identity that begins with the characters "site:" are returned.
    This filtered collection is then piped to the `Remove-CsWebServiceConfiguration` cmdlet, which deletes each item in the collection.
  summary: ""
- title: '-------------------------- Example 3 ------------------------'
  code: |-
    Get-CsWebServiceConfiguration | Where-Object {$_.EnableGroupExpansion -eq $False} | Remove-CsWebServiceConfiguration
  description: |-
    The command shown in Example 3 deletes all the Web Services configuration settings where group expansion has been disabled.
    To do this, the command first calls the `Get-CsWebServiceConfiguration` cmdlet without any parameters in order to return a collection of all the Web Services configuration settings used in the organization.
    This collection is then piped to the `Where-Object` cmdlet, which selects only those settings where the EnableGroupExpansion property is equal to False.
    The filtered collection is then piped to the `Remove-CsWebServiceConfiguration` cmdlet, which deletes each item in the collection.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error message that might occur when running the command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Unique identifier for the Web Services configuration settings to be removed.
    To remove settings configured at the site scope, use syntax similar to this:

    `-Identity "site:Redmond"`

    To remove settings configured at the service scope, use syntax similar to this:

    `-Identity "service:WebServer:atl-cs-001.litwareinc.com"`

    The `Remove-CsWebServiceConfiguration` cmdlet can also be run against the global collection.
    In that case, however, the global collection will not be removed; instead, all the properties in that collection will be reset to their default values.
    To reset the global collection, use this syntax:

    `-Identity global`


  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Remove-CsWebServiceConfiguration
name: Remove-CsWebServiceConfiguration
description: |-
  Many Skype for Business Server components are web-based: these components either use web services or webpages to carry out their tasks.
  For example, users employ a web service when searching for new contacts in the Address Book or when using group expansion to view the individual members of a distribution group.
  Likewise, components ranging from dial-in conferencing to Skype for Business Server Control Panel use webpages as the interface between Skype for Business Server and users.

  The CsWebServiceConfiguration cmdlets enable administrators to manage Web Services configuration settings throughout the organization.
  This includes managing group expansion, certificate settings and allowed authentication methods.
  Because you can configure different settings at the global, site and service scope (for the Web Services service only), you can customize Web Services capabilities for different users and different locations.

  If you create custom Web Services configuration settings at the site or service scope these settings can later be removed by using the `Remove-CsWebServiceConfiguration` cmdlet.
  Note that you can also run the `Remove-CsWebServiceConfiguration` cmdlet against the global collection of Web Services settings.
  In that case, however, the global collection will not be removed; that's because Skype for Business Server does not allow you to remove global settings.
  Instead, all the properties in the global collection will revert to their default values.
  For example, suppose you have changed the MaxGroupSizeToExpand value to 500.
  Because the default value for this property is 100, "removing" the global collection will reset the value of the MaxGroupSizeToExpand property to 100.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/remove-cswebserviceconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Remove-CsWebServiceConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
