### YamlMime:PowershellCmdlet
summary: |-
  Removes an existing Call Park service configuration.
  Call parking is a service that allows a user to "park" an incoming phone call.
  Parking a call transfers it to a number in a specified range, or orbit and then immediately places the call on hold.
  Anyone (not just the person who originally answered the call) can resume the conversation from any telephone simply by entering the correct number.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.Rtc.Management.WritableConfig.Settings.CallParkServiceSettings.CallParkServiceSettings object.
    Accepts pipelined input of Call Park service configuration objects.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Removes an object of type Microsoft.Rtc.Management.WritableConfig.Settings.CallParkServiceSettings.CallParkServiceSettings.
links:
- text: New-CsCpsConfiguration
  href: New-CsCpsConfiguration.yml
- text: Set-CsCpsConfiguration
  href: Set-CsCpsConfiguration.yml
- text: Get-CsCpsConfiguration
  href: Get-CsCpsConfiguration.yml
- text: Set-CsCallParkServiceMusicOnHoldFile
  href: Set-CsCallParkServiceMusicOnHoldFile.yml
syntaxes:
- Remove-CsCpsConfiguration [-Identity] <XdsIdentity> [-Force] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Remove-CsCpsConfiguration -Identity site:Redmond1
  description: |-
    Example 1 uses the `Remove-CsCpsConfiguration` cmdlet to delete the Call Park service configuration with the Identity site:Redmond1.
    Because identities are unique, this command will result in only one configuration being deleted.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Get-CsCpsConfiguration -Filter site:* | Remove-CsCpsConfiguration
  description: |-
    In Example 2, all the Call Park service configurations that have been defined at the site scope are deleted.
    To carry out this task, the command first uses the `Get-CsCpsConfiguration` cmdlet and the Filter parameter to return all the Call Park service configurations that have been defined at the site scope; the wildcard site:* ensures that only settings that have an Identity that begins with the string value site: will be returned.
    This filtered collection is then piped to the `Remove-CsCpsConfiguration` cmdlet, which proceeds to delete each item in the collection.
    Note that any time you remove Call Park service settings from a site, the site will automatically begin to use the Call Park service settings configured at the global scope.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses any confirmation prompts that would otherwise be displayed before making changes.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    The unique identifier of the Call Park service configuration you want to remove.
    This identifier will be either Global or site:\<sitename\>, where \<sitename\> is the name of the site to which the configuration applies.

  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Remove-CsCpsConfiguration
name: Remove-CsCpsConfiguration
description: |-
  This cmdlet is used to remove a Call Park service configuration.
  A Call Park service configuration specifies what happens to a call after it has been parked.
  For example, if a parked call isn't answered after a period of time it can be automatically forwarded to someone else, such as an administrator, or to a Response Group.
  Calls can be configured to ring after a certain period of time to ensure the call isn't forgotten.
  In addition, Call Park service can be configured to play music on hold to the caller while the call is parked.

  This cmdlet can be used to remove any Call Park configurations, including the Global configuration.
  In the case of the Global configuration, however, the configuration will not actually be removed; instead, it will simply be reset to the default values.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/remove-cscpsconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Remove-CsCpsConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
