### YamlMime:PowershellCmdlet
summary: |-
  Removes the Active Directory service control point for the Central Management store.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
    The `Remove-CsConfigurationStoreLocation` cmdlet does not accept pipelined input.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The `Remove-CsConfigurationStoreLocation` cmdlet does not return any objects or values.
links:
- text: Get-CsConfigurationStoreLocation
  href: Get-CsConfigurationStoreLocation.yml
- text: Set-CsConfigurationStoreLocation
  href: Set-CsConfigurationStoreLocation.yml
syntaxes:
- >-
  Remove-CsConfigurationStoreLocation [-GlobalSettingsDomainController <Fqdn>] [-Force] [-Report <String>]

   [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 ------------------------'
  code: |-
    Remove-CsConfigurationStoreLocation
  description: |-
    The command shown in Example 1 removes the Active Directory service control point for the Central Management store.
    To restore this SCP (or to create a new SCP), you must run the `Set-CsConfigurationStoreLocation` cmdlet.
  summary: ""
- title: '-------------------------- Example 2 ------------------------'
  code: |-
    Remove-CsConfigurationStoreLocation -Report C:\Logs\Store_Location.html
  description: |-
    Example 2 also removes the Active Directory service control point for the Central Management store.
    In addition to deleting the SCP, this command records information about the success (or failure) of the operation to the log file C:\Logs\Store_Location.html.
    To create this log file, the command uses the Report parameter followed by the path to the log file where information should be recorded.
    If this file already exists, the contents will be overwritten when the command runs.
    If the file does not exist, it will be created when the command runs.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error message that might occur when running the command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Fqdn" data-throw-if-not-resolved="False" />
  name: GlobalSettingsDomainController
  description: |+
    Fully qualified domain name (FQDN) of a domain controller where global settings are stored.
    If global settings are stored in the Active Directory System container, then this parameter must point to the root domain controller.
    If global settings are stored in the Configuration container, then any domain controller can be used and this parameter can be omitted.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Report
  description: "Enables you to specify a file path for the log file created when the cmdlet runs.\r\nFor example: `-Report \"C:\\Logs\\ConfigurationStore.html\"`\r\n\r\n "
  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Remove-CsConfigurationStoreLocation
name: Remove-CsConfigurationStoreLocation
description: |-
  Active Directory Domain Services uses service control points (SCP) to help computers locate services.
  For example, when you install Skype for Business Server, an SCP is created that provides location information for the Central Management store used to maintain Skype for Business Server data.
  Computers that need access to the database connect to Active Directory and use the information contained in the SCP to help them locate the correct computer and the correct instance of SQL Server.

  As noted, when you install Skype for Business Server, an SCP for the Central Management store is automatically created for you.
  Typically, you do not want to delete that SCP; if you do, computers will not be able to locate the database.
  However, there might be times (perhaps when troubleshooting a problem) when you will need to delete the SCP.
  To do that, use the `Remove-CsConfigurationStoreLocation` cmdlet.
  After the SCP has been deleted, you can recreate it (or create a new service control point) by using the `Set-CsConfigurationStoreLocation` cmdlet.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/remove-csconfigurationstorelocation
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Remove-CsConfigurationStoreLocation
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
