### YamlMime:PowershellCmdlet
summary: |-
  Removes the specified collection of archiving settings.
  Archiving settings are used to enable or disable the automatic saving of instant messaging (IM) sessions and to optionally block any instant message that cannot be archived.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.Rtc.Management.WritableConfig.Settings.Archiving.ArchivingSettings object.
    The `Remove-CsArchivingConfiguration` cmdlet accepts pipelined input of archiving configuration objects.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The `Remove-CsArchivingConfiguration` cmdlet does not return a value or object.
    Instead, the cmdlet removes instances of the Microsoft.Rtc.Management.WritableConfig.Settings.Archiving.ArchivingSettings object.
links:
- text: Get-CsArchivingConfiguration
  href: Get-CsArchivingConfiguration.yml
- text: New-CsArchivingConfiguration
  href: New-CsArchivingConfiguration.yml
- text: Set-CsArchivingConfiguration
  href: Set-CsArchivingConfiguration.yml
- text: Set-CsArchivingServer
  href: Set-CsArchivingServer.yml
syntaxes:
- Remove-CsArchivingConfiguration [-Identity] <XdsIdentity> [-Force] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Remove-CsArchivingConfiguration -Identity site:Redmond
  description: |-
    Example 1 uses the `Remove-CsArchivingConfiguration` cmdlet to delete the archiving configuration settings with the identity site:Redmond.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Get-CsArchivingConfiguration -Filter "site:*" | Remove-CsArchivingConfiguration
  description: |-
    The command shown in Example 2 removes all of the archiving configuration settings that have been configured at the site scope.
    To do this, the command first uses the `Get-CsArchivingConfiguration` cmdlet and the Filter parameter to return a collection of all of the settings configured at the site scope.
    This is done by using the filter value "site:*", which limits the returned data to settings that have an Identity that begins with the characters "site:".
    The filtered collection is then piped to the `Remove-CsArchivingConfiguration` cmdlet, which deletes each item in that collection.
  summary: ""
- title: '-------------------------- Example 3 --------------------------'
  code: |-
    Get-CsArchivingConfiguration | Where-Object {$_.EnableArchiving -eq "None"} | Remove-CsArchivingConfiguration
  description: |-
    Example 3 deletes all the archiving configuration settings where the EnableArchiving property has been set to "None".
    To carry out this task, the `Get-CsArchivingConfiguration` cmdlet is called without any parameters in order to return a collection of all the archiving settings configured for use in the organization.
    This collection is then piped to the `Where-Object` cmdlet, which picks out only those settings where the EnableArchiving property is equal to "None".
    The filtered collection is then piped to the `Remove-CsArchivingConfiguration` cmdlet, which deletes each item in the collection.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error message that might occur when running the command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Unique identifier for the collection of archiving configuration settings to be removed.
    To remove the global collection, use the following syntax: `-Identity global`.
    (Note that you cannot actually remove the global settings; instead, you can only reset the properties to their default values.) To remove a site collection, use syntax similar to this: `-Identity site:Redmond`.
    To remove settings configured for an individual Registrar pool syntax like this:

    `-Identity "service:Registrar:atl-cs-001.litwareinc.com"`

    Note that pool-level settings are available only in Skype for Business Server.

    You cannot use wildcards when specifying a policy Identity.


  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Remove-CsArchivingConfiguration
name: Remove-CsArchivingConfiguration
description: |-
  Many organizations find it useful to keep a transcript of all the IM sessions and conferences their users participate in.
  For other organizations, it's mandatory to keep such transcripts; for example, many organizations in the financial world are required by law to keep copies of all their electronic communications.

  Skype for Business Server gives you flexibility when it comes to archiving IM and web conferencing sessions.
  If you have deployed Archiving Server, you can use the various CsArchivingConfiguration cmdlets to enable and disable IM session archiving and to manage your archiving database.
  You can also suspend IM should archiving fail; this helps to ensure that you keep a record of all your electronic communications.

  When you install Skype for Business Server, a collection of global archiving settings will be created for you; by default, these settings will apply to your entire organization.
  Alternatively, you can use the `New-CsArchivingConfiguration` cmdlet to create custom configuration settings on a site-by-site basis.
  Any site-specific settings created using the `New-CsArchivingConfiguration` cmdlet can later be removed by using the `Remove-CsArchivingConfiguration` cmdlet.
  When you remove the settings for a site, the affected site will then be governed by the global settings.

  Note that you can also run the `Remove-CsArchivingConfiguration` cmdlet against the global archiving settings.
  In that case, however, the settings will not be removed; that's because you cannot delete the global settings.
  Instead, all the global properties will be reset to their default values.
  For example, suppose you have enabled IM session archiving at the global scope; sometime later, you run this command:

  `Remove-CsArchivingConfiguration -Identity global`

  Running that command will reset the property values for the global settings; that means that EnableArchiving will revert to its default value of None.
  In turn, that will disable archiving at the global scope.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/remove-csarchivingconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Remove-CsArchivingConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
