### YamlMime:PowershellCmdlet
summary: |-
  Removes one or more collections of dial-in conferencing configuration settings.
  These settings determine how Skype for Business Server responds when users join or leave a dial-in conference.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.Rtc.Management.WritableConfig.Settings.DialInConferencingSettings.DialInConferencingConfiguration object.
    The `Remove-CSDialInConferencingConfiguration` cmdlet accepts pipelined instances of the dial-in conferencing configuration object.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
    Instead, the `Remove-CSDialInConferencingConfiguration` cmdlet deletes instances of the Microsoft.Rtc.Management.WritableConfig.Settings.DialInConferencingSettings.DialInConferencingConfiguration object.
links:
- text: Get-CsDialInConferencingConfiguration
  href: Get-CsDialInConferencingConfiguration.yml
- text: New-CsDialInConferencingConfiguration
  href: New-CsDialInConferencingConfiguration.yml
- text: Set-CsDialInConferencingConfiguration
  href: Set-CsDialInConferencingConfiguration.yml
syntaxes:
- >-
  Remove-CsDialInConferencingConfiguration [-Identity] <XdsIdentity> [-Force] [-WhatIf] [-Confirm]

   [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 ------------------------'
  code: |-
    Remove-CSDialInConferencingConfiguration -Identity "site:Redmond"
  description: |-
    In Example 1, the dial-in conferencing configuration settings for the Redmond site are deleted.
  summary: ""
- title: '-------------------------- Example 2 ------------------------'
  code: |-
    Get-CSDialInConferencingConfiguration -Filter "site:*" | Remove-CSDialInConferencingConfiguration
  description: |-
    In Example 2, all the dial-in conferencing settings that have been configured at the site scope are deleted.
    To do this, the command first uses the `Get-CSDialInConferencingConfiguration` cmdlet and the Filter parameter to return a collection of all the dial-in conferencing settings that have been configured at the site scope.
    (The filter value "site:*" ensures that only settings that have an Identity that begins with the string value "site:" are returned.) This filtered collection is then piped to the `Remove-CSDialInConferencingConfiguration` cmdlet, which removes each item in the collection.
  summary: ""
- title: '-------------------------- Example 3 ------------------------'
  code: |-
    Get-CSDialInConferencingConfiguration | Where-Object {$_.EnableNameRecording -eq $False} | Remove-CSDialInConferencingConfiguration
  description: |-
    In Example 3, all the dial-in conferencing configuration settings that do not use name recording are deleted.
    To carry out this task, the command first calls the `Get-CSDialInConferencingConfiguration` cmdlet without any parameters in order to return a collection of all the dial-in conferencing configuration settings currently in use in the organization.
    This collection is then piped to the `Where-Object` cmdlet, which picks out only those settings where the EnableNameRecording property is equal to False.
    In turn, this filtered collection is piped to the `Remove-CSDialInConferencingConfiguration` cmdlet, which deletes each item in the collection.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error message that might occur when running the command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Indicates the Identity of the dial-in conferencing configuration settings to be removed.
    To refer to the global settings, use this syntax: `-Identity global`.
    To refer to site settings, use syntax similar to this: `-Identity site:Redmond`.
    Note that you cannot use wildcards when specifying an Identity.

  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Remove-CsDialInConferencingConfiguration
name: Remove-CsDialInConferencingConfiguration
description: |-
  When users join (or leave) a dial-in conference, Skype for Business Server can respond in different ways.
  For example, participants might be asked to record their name before they can enter the conference itself.
  Likewise, administrators can decide whether they want to have Skype for Business Server announce that dial-in participants have either left or joined a conference.

  These conference "join behaviors" are managed using dial-in conferencing configuration settings; these settings can be configured at the global scope or at the site scope.
  (Settings configured at the site scope take precedence over settings configured at the global scope.) When you install Skype for Business Server, a global collection of dial-in conferencing configuration settings will be created for you.
  If you want to have different settings for a site (or set of sites), you can create those collections by using the `New-CSDialInConferencingConfiguration` cmdlet.

  The `Remove-CSDialInConferencingConfiguration` cmdlet deletes any dial-in conferencing settings that have been configured at the site scope.
  When these site-specific settings are deleted, users in the affected sites will have their dial-in conferencing behaviors governed by the global settings.

  You can also run the `Remove-CSDialInConferencingConfiguration` cmdlet against the global dial-in conferencing settings.
  If you do that, the global settings will not be removed; that's because the global settings cannot be removed.
  Instead, all the properties within that collection of settings will be reset to their default values.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/remove-csdialinconferencingconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Remove-CsDialInConferencingConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
