### YamlMime:PowershellCmdlet
summary: |-
  Removes one or more of the diagnostic configuration settings collections currently in use in your organization.
  Diagnostic configuration settings are used to determine whether traffic to or from a given domain or Uniform Resource Identifier (URI) is recorded in your Skype for Business Server log files.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.Rtc.Management.WritableConfig.Settings.Diagnostics.DiagnosticFilterSettings object.
    The `Remove-CsDiagnosticConfiguration` cmdlet accepts pipelined instances of the diagnostic filter settings object.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
    Instead, the `Remove-CsDiagnosticConfiguration` cmdlet deletes existing instances of the Microsoft.Rtc.Management.WritableConfig.Settings.Diagnostics.DiagnosticFilterSettings object.
links:
- text: Get-CsDiagnosticConfiguration
  href: Get-CsDiagnosticConfiguration.yml
- text: New-CsDiagnosticConfiguration
  href: New-CsDiagnosticConfiguration.yml
- text: Set-CsDiagnosticConfiguration
  href: Set-CsDiagnosticConfiguration.yml
syntaxes:
- Remove-CsDiagnosticConfiguration [-Identity] <XdsIdentity> [-Force] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 ------------------------'
  code: |-
    Remove-CsDiagnosticConfiguration -Identity site:Redmond
  description: |-
    Example 1 deletes the diagnostic configuration settings that have the Identity site:Redmond.
  summary: ""
- title: '-------------------------- Example 2 ------------------------'
  code: |-
    Get-CsDiagnosticConfiguration -Filter site:* | Remove-CsDiagnosticConfiguration
  description: |-
    The command shown in Example 2 deletes all the diagnostic configuration settings that have been configured at the site scope.
    To do this, the command calls the `Get-CsDiagnosticConfiguration` cmdlet along with the Filter parameter; the filter value "site:*" limits the returned data to settings where the Identity begins with the characters "site:".
    The filtered collection is then piped to the `Remove-CsDiagnosticConfiguration` cmdlet, which removes each item in that collection.
  summary: ""
- title: '-------------------------- Example 3 ------------------------'
  code: |-
    Get-CsDiagnosticConfiguration | Remove-CsDiagnosticConfiguration
  description: |-
    In Example 3, the command deletes all the diagnostic configuration settings currently in use in the organization.
    To perform this task, the `Get-CsDiagnosticConfiguration` cmdlet is first called without any parameters in order to return a collection of all the diagnostic configuration settings currently in use in the organization.
    These items are then piped to the `Remove-CsDiagnosticConfiguration` cmdlet, which removes each item in the collection.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error message that might occur when running the command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Unique identifier for the diagnostic configuration settings to be removed.
    To remove settings configured at the site scope, use syntax similar to this: `-Identity "site:Redmond"`.

    The `Remove-CsDiagnosticConfiguration` cmdlet can also be run against the global configuration settings; in that case, use this syntax: `-Identity global`.
    However, the global settings will not actually be removed; instead, the properties found in the global settings will be reset to their default values.


  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Remove-CsDiagnosticConfiguration
name: Remove-CsDiagnosticConfiguration
description: |-
  If you enable logging for Skype for Business Server, then, by default, traffic traveling to or from any domain or URI is included in those log files.
  This ensures that as much information as possible is recorded in the log files.

  However, this can occasionally result in too much information.
  For example, if you are experiencing connectivity problems with a particular domain, you might want to limit logging to traffic between your network and that domain; that makes it easier for you to identify the relevant records and, in turn, might make it easier for you to diagnose and correct the problem.

  Diagnostic configuration settings make it possible for you to specify the domains or URIs that will be recorded in the log files; if a diagnostic filter is enabled then only traffic to or from the specified domains will be logged.
  Skype for Business Server enables you to create diagnostic configuration settings and apply diagnostic filters, at the site scope.
  In turn, this enables you to apply filtering to, say, the Redmond site while leaving filtering disabled on your other sites.

  You can use the `Remove-CsDiagnosticConfiguration` cmdlet to remove any of the diagnostic configuration settings you have created at the site scope.
  The `Remove-CsDiagnosticConfiguration` cmdlet can also be run against the global diagnostic configuration settings.
  In that case, however, the collection will not be deleted; that's because Skype for Business Server does not allow you to delete global collections.
  Instead, removing a global collection causes the properties in that collection to be reset to their default values.
  That means that all the filters added to that collection will be removed.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/remove-csdiagnosticconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Remove-CsDiagnosticConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
