### YamlMime:PowershellCmdlet
summary: |-
  Use the `Remove-CsVideoInteropServerSyntheticTransactionConfiguration` cmdlet to remove an existing Video Interop (VIS) server synthetic transaction configuration.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Accepts pipelined instances of the VideoInteropServerSyntheticTransactionConfiguration object.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None
links:
- text: Get-CsVideoInteropServerSyntheticTransactionConfiguration
  href: Get-CsVideoInteropServerSyntheticTransactionConfiguration.yml
- text: Set-CsVideoInteropServerSyntheticTransactionConfiguration
  href: Set-CsVideoInteropServerSyntheticTransactionConfiguration.yml
- text: New-CsVideoInteropServerSyntheticTransactionConfiguration
  href: New-CsVideoInteropServerSyntheticTransactionConfiguration.yml
- text: Test-CsP2PVideoInteropServerSipTrunkAV
  href: Test-CsP2PVideoInteropServerSipTrunkAV.yml
syntaxes:
- >-
  Remove-CsVideoInteropServerSyntheticTransactionConfiguration [-Identity] <XdsIdentity> [-Confirm] [-Force]

   [-WhatIf] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Remove-CsVideoInteropServerSyntheticTransactionConfiguration -Identity "site:Redmond"
  description: |-
    This example removes the Video Interop Server synthetic transaction configuration for the Redmond site.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error messages and completes the cmdlet operation.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Identity of the VIS configuration to be removed.
    VIS settings can be configured at the global, site, or service scope (for the VideoInteropServer service only).
    To refer to the global instance, use this syntax:

    `-Identity "Global"`

    Use this syntax to refer to a collection at the site scope:

    `-Identity "site:Redmond"`

  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Remove-CsVideoInteropServerSyntheticTransactionConfiguration
name: Remove-CsVideoInteropServerSyntheticTransactionConfiguration
description: |-
  To return a list of all the Role-Based Access Control (RBAC) roles a cmdlet has been assigned to (including any custom RBAC roles you have created), run the following command from the Windows PowerShell prompt.

  `Get-CsAdminRole | Where-Object {$_.Cmdlets -Match "\<DesiredCmdletName\>"}`
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/remove-csvideointeropserversynthetictransactionconfiguration
  applicable: Skype for Business Server 2015, Skype for Business Server 2019
  title: Remove-CsVideoInteropServerSyntheticTransactionConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
