### YamlMime:PowershellCmdlet
summary: |-
  Removes one or more of the simple URL configuration collections currently in use in your organization.
  Simple URLs make it easier for users to join meetings and conferences, as well as making it easier for Administrators to log on to the Skype for Business Server Control Panel.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.Rtc.Management.WritableConfig.Settings.SimpleUrl.SimpleUrlConfiguration object.
    The `Remove-CsSimpleUrlConfiguration` cmdlet accepts pipelined instances of the simple URL configuration object.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
links:
- text: Get-CsSimpleUrlConfiguration
  href: Get-CsSimpleUrlConfiguration.yml
- text: New-CsSimpleUrlConfiguration
  href: New-CsSimpleUrlConfiguration.yml
- text: Set-CsSimpleUrlConfiguration
  href: Set-CsSimpleUrlConfiguration.yml
syntaxes:
- >-
  Remove-CsSimpleUrlConfiguration [-Identity] <XdsIdentity> [-Force] [-WhatIf] [-Confirm] [-Tenant <Guid>]

   [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 ------------------------'
  code: |-
    Remove-CsSimpleUrlConfiguration -Identity "site:Redmond"
  description: |-
    The command shown in Example 1 deletes the simple URL configuration collection applied to the Redmond site.
    This command deletes all the simple URLs assigned to the specified site.
  summary: ""
- title: '-------------------------- Example 2 ------------------------'
  code: |-
    Get-CsSimpleUrlConfiguration -Filter "site:*" | Remove-CsSimpleUrlConfiguration
  description: |-
    In Example 2, all the simple URL configuration collections applied at the site scope are deleted.
    To do this, the command first uses the `Get-CsSimpleUrlConfiguration` cmdlet and the Filter parameter to return all the simple URL collections configured at the site scope; the filter value "site:*" limits the returned data to those collections that have an Identity that begins with the string value "site:".
    The filtered collection is then piped to the `Remove-CsSimpleUrlConfiguration` cmdlet, which deletes each item in that collection.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error message that might occur when running the command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Unique identifier for the collection of simple URLs to be removed.
    To remove a collection from the site scope, use syntax similar to this:

    `-Identity "site:Redmond"`

    Note that you cannot use wildcards when specifying an Identity.

    You can also run this cmdlet against the global collection by using this syntax:

    `-Identity global`

    In that case, however, the global collection will not be deleted.
    Instead, all the Simple URLs within that collection will be deleted.


  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Guid" data-throw-if-not-resolved="False" />
  name: Tenant
  description: |+
    Globally unique identifier (GUID) of the Skype for Business Online tenant account for the Simple URL configuration settings being deleted.
    For example:

    `-Tenant "38aad667-af54-4397-aaa7-e94c79ec2308"`

    You can return the tenant ID for each of your tenants by running this command:

    `Get-CsTenant | Select-Object DisplayName, TenantID`


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Remove-CsSimpleUrlConfiguration
name: Remove-CsSimpleUrlConfiguration
description: |-
  In Microsoft Office Communications Server 2007 R2, meetings had URLs similar to this:

  `https://imdf.litwareinc.com/Join?uri=sip%3Akenmyer%40litwareinc.com%3Bgruu%3Bopaque%3Dapp%3Aconf%3Afocus%3Aid%3A125f95a0b0184dcea706f1a0191202a8&key=EcznhLh5K5t`

  However, such URLs are not especially intuitive, and not easy to convey to someone else.
  The simple URLs introduced in Lync Server 2010 help overcome those problems by providing users with URLs that look more like this:

  `https://meet.litwareinc.com/kenmyer/071200`

  Simple URLs are an improvement over the URLs used in Office Communications Server.
  However, simple URLs are not automatically created for you; instead, you must configure the URLs yourself.
  In addition, you must also do such things as create Domain Name System (DNS) records for each URL; configure reverse proxy rules for external access; add the simple URLs to the your Front End Server certificates; and so on.

  Skype for Business Server enables you to create three different simple URLs:

  Meet - Used for meetings.
  You must have at least one Meet URL for each of your SIP domains.

  Admin - Used to point administrators to the Skype for Business Server Control Panel.

  Dialin - Used for the dial-in conferencing webpage.

  Simple URLs are stored in simple URL configuration collections.
  When you install Skype for Business Server, a global collection is created for you; you can also create custom collections at the site scope.
  This gives you the ability to use different simple URLs at each of your sites.

  Simple URL configuration collections are created by using the `New-CsSimpleUrlConfiguration` cmdlet; you can then use additional cmdlets (such as the `New-CsSimpleUrlEntry` cmdlet and the `Set-CsSimpleUrlConfiguration` cmdlet) to populate these collections with simple URLs.
  If you later decide to delete one or more of the site-scoped collections, you can do so by using the `Remove-CsSimpleUrlConfiguration` cmdlet.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/remove-cssimpleurlconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Remove-CsSimpleUrlConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
