### YamlMime:PowershellCmdlet
summary: |-
  Removes the specified instant message file transfer filter configuration.
  (Instant message file transfer filter settings are used to block a user's ability to transfer certain types of files within an instant message.) This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.Rtc.Management.WritableConfig.Settings.ImFilter.FileTransferFilterConfiguration object.
    Accepts pipelined input of file transfer filter configuration objects.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    This cmdlet does not return a value or object.
    Instead, it removes instances of the Microsoft.Rtc.Management.WritableConfig.Settings.ImFilter.FileTransferFilterConfiguration object.
links:
- text: New-CsFileTransferFilterConfiguration
  href: New-CsFileTransferFilterConfiguration.yml
- text: Set-CsFileTransferFilterConfiguration
  href: Set-CsFileTransferFilterConfiguration.yml
- text: Get-CsFileTransferFilterConfiguration
  href: Get-CsFileTransferFilterConfiguration.yml
syntaxes:
- >-
  Remove-CsFileTransferFilterConfiguration [-Identity] <XdsIdentity> [-Force] [-WhatIf] [-Confirm]

   [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Remove-CsFileTransferFilterConfiguration -Identity site:Redmond
  description: |-
    In Example 1, the `Remove-CsFileTransferFilterConfiguration` cmdlet is used to remove the file transfer filter configuration that has the Identity site:Redmond.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Get-CsFileTransferFilterConfiguration -Filter site:* | Remove-CsFileTransferFilterConfiguration
  description: |-
    In Example 2, all the file transfer filter configurations at the site scope are removed.
    To carry out this task, the command first uses the `Get-CsFileTransferFilterConfiguration` cmdlet and the Filter parameter to return all the configurations at the site scope.
    The filter value "site:*" tells the `Get-CsFileTransferFilterConfiguration` cmdlet to return only those configurations that have an Identity that begins with the string value "site:".
    The filtered collection of configurations is then piped to the `Remove-CsFileTransferFilterConfiguration` cmdlet, which deletes each item in the collection.
  summary: ""
- title: '-------------------------- Example 3 --------------------------'
  code: |-
    Get-CsFileTransferFilterConfiguration | Where-Object {$_.Enabled -eq $False} | Remove-CsFileTransferFilterConfiguration
  description: |-
    Example 3 shows you how you can remove all the file transfer filter configurations that are currently disabled.
    To do this, the command first uses the `Get-CsFileTransferFilterConfiguration` cmdlet to return a collection of all the file transfer filter configurations currently in use in the organization.
    That information is then piped to the `Where-Object` cmdlet, which selects only those file transfer filter configurations where the Enabled property is equal to (-eq) False ($False).
    That filtered collection is then piped to the `Remove-CsFileTransferFilterConfiguration` cmdlet, which proceeds to remove each item in the filtered collection.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses any confirmation prompts that would otherwise be displayed before making changes.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Unique identifier for the file transfer configuration to be removed.
    To refer to the global configuration, use this syntax: `-Identity global`.
    To refer to a configuration at the site scope, use syntax similar to this: `-Identity site:Redmond`.
    Note that you cannot use wildcard values when specifying an Identity.

  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Remove-CsFileTransferFilterConfiguration
name: Remove-CsFileTransferFilterConfiguration
description: |-
  When sending instant messages, users can attach and send files to the other participants in the conversation.
  Skype for Business Server can be configured so that files with certain extensions--typically extensions of file types that could potentially prove harmful--are not allowed to be sent using a Skype for Business Server client.

  The `Remove-CsFileTransferFilterConfiguration` cmdlet enables you to delete a file transfer filter configuration.
  For configurations at the site scope, the `Remove-CsFileTransferFilterConfiguration` cmdlet will remove the configuration; in turn, the users on the site will automatically inherit the global file transfer filter configuration.
  The `Remove-CsFileTransferFilterConfiguration` cmdlet can also be run against the global configuration.
  In that case, however, the global configuration will not be removed; instead, all the property values in that configuration will be reset to their default values.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/remove-csfiletransferfilterconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Remove-CsFileTransferFilterConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
