### YamlMime:PowershellCmdlet
summary: |-
  Use the `Remove-CsVideoInteropServerConfiguration` cmdlet to remove an existing collection of Video Interop Server (VIS) configuration settings.
  Video Interop Server configuration settings are scoped to appropriate Video Interop Server (VIS) instances and will govern the behavior of those instances.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The `Remove-CsVideoInteropServerConfiguration` cmdlet accepts pipelined input of the Microsoft.Rtc.Management.WritableConfig.Settings.VideoInteropServer.VideoInteropServerConfiguration object.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
    The `Remove-CsVideoInteropServerConfiguration` cmdlet deletes instances of the Microsoft.Rtc.Management.WritableConfig.Settings.VideoInteropServer.VideoInteropServerConfiguration object.
links:
- text: Get-CsVideoInteropServerConfiguration
  href: Get-CsVideoInteropServerConfiguration.yml
- text: New-CsVideoInteropServerConfiguration
  href: New-CsVideoInteropServerConfiguration.yml
- text: Set-CsVideoInteropServerConfiguration
  href: Set-CsVideoInteropServerConfiguration.yml
syntaxes:
- >-
  Remove-CsVideoInteropServerConfiguration [-Identity] <XdsIdentity> [-Confirm] [-Force] [-WhatIf]

   [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Remove-CsVideoInteropServerConfiguration -Identity "site:Redmond"
  description: |-
    This example deletes the VIS configuration settings assigned to the Redmond site.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Get-CsVideoInteropServerConfiguration -Filter "site:*" | Remove-CsVideoInteropServerConfiguration
  description: |-
    This example deletes all the VIS settings that have been assigned to the site scope are deleted.
    The command calls the `Get-CsVideoInteropServerConfiguration` and filters the configuration by using the Filter parameter value "site:*".
    Those configuration objects are then piped to and deleted by, the `Remove-CsVideoInteropServerConfiguration` cmdlet.
  summary: ""
- title: '-------------------------- Example 3 --------------------------'
  code: |-
    Get-CsVideoInteropServerConfiguration | Where-Object {$_.EnableEnhancedVideoExperience -eq $True} | Remove-CsVideoInteropServerConfiguration
  description: |-
    This example deletes all the VIS settings where the enhanced video experience has been enabled.
    The command first calls `Get-CsVideoInteropServerConfiguration` to return a collection of all the VIS settings in use in the organization.
    Those configuration objects then piped to the `Where-Object` cmdlet, which filters for VIS configuration objects in which EnableEnhancedVideoExperience property has been set to True ($True).
    Those configuration objects are then piped to and deleted by the `Remove-CsVideoInteropServerConfiguration`.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error messages and completes the cmdlet operation.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Unique identity assigned to the video interop service configuration settings when they were created.
    Video interop settings can be assigned at the global, site, or service scope (for the VideoInteropServer service only).
    For example, to remove settings configured at the site scope use the following syntax:

    `-Identity "site:Redmond"`

    Wildcard characters such as the asterisk (*) cannot be used with the Identity parameter.
    The `Remove-CsVideoInteropServerConfiguration` cmdlet can be run against the global settings collection.
    However, the global collection will not be deleted.
    Instead, all the properties within the collection will be reset to their default values.

  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Remove-CsVideoInteropServerConfiguration
name: Remove-CsVideoInteropServerConfiguration
description: |-
  The Video Interop Server (VIS) enables you to incorporate 3rd party video teleconferencing systems (VTCs) into your Skype for Business infrastructure.
  VIS is a Skype for Business service that runs on a standalone pool and cannot be co-located on an FE pool.

  To enable the Video Interop Server (VIS) you must use Topology Builder to define at least one VIS instance.
  Each VIS instance will typically be associated with one or more Video Gateways.
  Video Gateways route traffic between internal and external video devices such as an internal Skype for Business endpoint receiving video from an external PBX supporting 3rd party video teleconferencing systems (VTCs).
  The Video Gateway and a VIS use a Session Initiation Protocol (SIP) trunk to connect video calls between external VTCs and internal endpoints.

  You can manage the Video Interop Server (VIS) by using VIS configuration settings and the CsVideoInteropServerConfiguration cmdlets.
  These settings are used to enable or disable the enhanced video experience (in which a single video stream is converted to multiple streams in order to accommodate the needs of devices that use different frame rates or video resolutions).

  By default, Skype for Business Server ships with a single, global collection of Video Interop Server configuration settings.
  You can use the `New-CsVideoInteropServerConfiguration` cmdlet to create additional settings at the site or the service scope (for the VIS service only.) These custom settings can later be removed by using the `Remove-CsVideoInteropServerConfiguration` cmdlet.
  This cmdlet can also be run against the global collection of VIS settings.
  The global collection will not be removed, but all the properties in the global collection will be reset to their default values.
  Skype for Business Server does not allow you to delete the global settings.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/remove-csvideointeropserverconfiguration
  applicable: Skype for Business Server 2015, Skype for Business Server 2019
  title: Remove-CsVideoInteropServerConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
