### YamlMime:PowershellCmdlet
summary: |-
  Resets all the network configuration settings for a Skype for Business Server deployment to the default values.
  This deletes an entire call admission control (CAC) deployment and related E9-1-1 configuration.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.Rtc.Management.WritableConfig.Settings.NetworkConfiguration.NetworkConfigurationSettings object.
    Accepts pipelined input of a network configuration object.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    This cmdlet does not return an object.
    It removes an object of type Microsoft.Rtc.Management.WritableConfig.Settings.NetworkConfiguration.NetworkConfigurationSettings object.
links:
- text: Set-CsNetworkConfiguration
  href: Set-CsNetworkConfiguration.yml
- text: Get-CsNetworkConfiguration
  href: Get-CsNetworkConfiguration.yml
- text: Get-CsNetworkSite
  href: Get-CsNetworkSite.yml
- text: Get-CsNetworkRegionLink
  href: Get-CsNetworkRegionLink.yml
- text: Get-CsNetworkInterSitePolicy
  href: Get-CsNetworkInterSitePolicy.yml
- text: Get-CsNetworkInterRegionRoute
  href: Get-CsNetworkInterRegionRoute.yml
- text: Get-CsNetworkRegion
  href: Get-CsNetworkRegion.yml
- text: Get-CsNetworkSubnet
  href: Get-CsNetworkSubnet.yml
- text: Get-CsNetworkBandwidthPolicyProfile
  href: Get-CsNetworkBandwidthPolicyProfile.yml
syntaxes:
- Remove-CsNetworkConfiguration [-Identity] <XdsIdentity> [-Force] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Remove-CsNetworkConfiguration -Identity Global -Confirm
  description: |-
    This example removes all CAC, location, E9-1-1 network and media bypass settings.
    The Confirm parameter is used so you'll be prompted to verify you really want to do this before everything is deleted.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.
    It is recommended that you always use this parameter with this cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses any confirmation prompts that would otherwise be displayed before making changes.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    This will always be Global.

  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Remove-CsNetworkConfiguration
name: Remove-CsNetworkConfiguration
description: |-
  WARNING: Running this cmdlet will delete an entire network configuration, including CAC, E9-1-1 regions and sites, and media bypass.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/remove-csnetworkconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Remove-CsNetworkConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
