### YamlMime:PowershellCmdlet
summary: |-
  Removes existing instances of the Skype for Business Server Storage Service.
  The storage service provides a common infrastructure that enables Skype for Business Server components to use Skype for Business Server as a back-end data store.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The `Remove-CsStorageServiceConfiguration` cmdlet accepts pipelined instances of the Microsoft.Rtc.Management.WritableConfig.Settings.StorageService.StorageServiceSettings object.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
    The `Remove-CsStorageServiceConfiguration` cmdlet does not return any objects or data.
links:
- text: Get-CsStorageServiceConfiguration
  href: Get-CsStorageServiceConfiguration.yml
- text: New-CsStorageServiceConfiguration
  href: New-CsStorageServiceConfiguration.yml
- text: Set-CsStorageServiceConfiguration
  href: Set-CsStorageServiceConfiguration.yml
syntaxes:
- >-
  Remove-CsStorageServiceConfiguration [-Identity] <XdsIdentity> [-Confirm] [-Force] [-WhatIf]

   [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Remove-CsStorageServiceConfiguration -Identity "site:Redmond"
  description: |-
    The command shown in Example 1 deletes the storage service configuration settings applied to the Redmond site.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Get-CsStorageServiceConfiguration -Filter "site:*" | Remove-CsStorageServiceConfiguration
  description: |-
    In Example 2, all the storage service settings applied to the site scope are deleted.
    To carry out this task, the command first uses the `Get-CsStorageServiceConfiguration` cmdlet and the Filter parameter to return all the settings configured at the site scope.
    That collection is then piped to the `Remove-CsStorageServiceConfiguration` cmdlet, which deletes each item in the collection.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error message that might occur when running the command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Unique identifier for the collection of storage service configuration settings to be removed.
    To remove a collection applied to the site scope, use syntax similar to this:

    `-Identity "site:Redmond"`

    To remove a collection applied to the service scope, use syntax like this:

    `-Identity "service:Registrar:atl-cs-001.litwareinc.com"`

    Note that you can also run the `Remove-CsStorageServiceConfiguration` cmdlet against the global collection of settings.
    In that case, however, the global settings will not actually be removed.
    Instead, the properties within that collection will all be reset to their default values.

  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Remove-CsStorageServiceConfiguration
name: Remove-CsStorageServiceConfiguration
description: |-
  The Skype for Business Server Storage Service enables Skype for Business Server components (such as archiving) to use Exchange as a back-end data store.
  This helps to reduce operating costs: for example, you do not need to have separate storage solutions for Exchange archiving and for Skype for Business Server archiving.
  The Storage Service also enables Skype for Business Server to leverage the heavy investment that has been made in Exchange archiving and storage and prevents administrators from having to use multiple tools to retrieve archived data.

  Separate instances of the Skype for Business Server Storage Service can be configured at the global, site and service scope (for the Registrar service only).
  By default, Skype for Business Server provides you with a single, global collection of Storage Service configuration settings.
  However, administrators have the option of creating custom settings by using the `New-CsStorageServiceConfiguration` cmdlet.
  Those custom settings can later be deleted by using the `Remove-CsStorageServiceConfiguration` cmdlet.

  The `Remove-CsStorageServiceConfiguration` cmdlet can also be run against the global settings collection.
  In that case, however, the global collection will not be deleted.
  Instead, any properties within the global collection will be reset to their default values.

  Skype for Business Server Control Panel: The functions carried out by the `Remove-CsStorageServiceConfiguration` cmdlet are not available in the Skype for Business Server Control Panel.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/remove-csstorageserviceconfiguration
  applicable: Skype for Business Server 2015, Skype for Business Server 2019
  title: Remove-CsStorageServiceConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
