### YamlMime:PowershellCmdlet
summary: |-
  Removes the specified collection of Address Book configuration settings.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.Rtc.Management.WritableConfig.Settings.AddressBook.AddressBookSettings object.
    The `Remove-CsAddressBookConfiguration` cmdlet accepts pipelined input of Address Book configuration objects.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The `Remove-CsAddressBookConfiguration` cmdlet does not return a value or object.
    Instead, the cmdlet removes instances of the Microsoft.Rtc.Management.WritableConfig.Settings.AddressBook.AddressBookSettings object.
links:
- text: Get-CsAddressBookConfiguration
  href: Get-CsAddressBookConfiguration.yml
- text: New-CsAddressBookConfiguration
  href: New-CsAddressBookConfiguration.yml
- text: Set-CsAddressBookConfiguration
  href: Set-CsAddressBookConfiguration.yml
syntaxes:
- Remove-CsAddressBookConfiguration [-Identity] <XdsIdentity> [-Force] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Remove-CsAddressBookConfiguration -Identity site:Redmond
  description: |-
    In this example, the `Remove-CsAddressBookConfiguration` cmdlet is used to delete the Address Book configuration settings with the identity site:Redmond.
    Using the Identity parameter ensures that only the specified Address Book settings will be removed.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Get-CsAddressBookConfiguration -Filter site:* | Remove-CsAddressBookConfiguration
  description: |-
    In Example 2, all the Address Book setting collections configured at the site scope are removed.
    To do this, the `Get-CsAddressBookConfiguration` cmdlet is used to retrieve a collection of all the Address Book settings that have been configured at the site scope; this is done by using the Filter parameter and the filter value "site:*".
    The retrieved collection is then piped to the `Remove-CsAddressBookConfiguration` cmdlet, which removes all the items in that collection.
  summary: ""
- title: '-------------------------- Example 3 --------------------------'
  code: |-
    Get-CsAddressBookConfiguration | Where-Object {$_.KeepDuration -lt 30.} | Remove-CsAddressBookConfiguration
  description: |-
    Example 3 removes all the Address Book settings in which change files are kept for less than 30 days.
    To carry out this task, the `Get-CsAddressBookConfiguration` cmdlet is used to return a collection of all the Address Book settings currently in use in the organization.
    This collection is then piped to the `Where-Object` cmdlet, which selects only those settings where the KeepDuration property is less than 30 days.
    (Note the syntax: 30., with a period following the number of days.) Finally, the filtered collection is piped to the `Remove-CsAddressBookConfiguration` cmdlet, which deletes each item in that collection.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error message that might occur when running the command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Unique identifier for the collection of Address Book configuration settings to be removed.
    To remove the global collection, use the following syntax: `-Identity global`.
    (When you "remove" the global settings you simply reset all the properties to their default values.) To remove a site collection, use syntax similar to this: `-Identity site:Redmond`.
    Note that you cannot use wildcards when specifying a policy Identity.

  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Remove-CsAddressBookConfiguration
name: Remove-CsAddressBookConfiguration
description: |-
  Address Book servers are intermediaries between AD DS and Skype for Business Server.
  The Address Book server ensures that the user information stored in Skype for Business Server is in synch with the user information stored in AD DS.
  This is done by periodically synching Address Book files with information stored in the User database.

  In addition, Address Book servers periodically generate index files that are downloaded to computers running Skype for Business Server.
  When a user searches for contacts, he or she either search through these index files or search the Address Book index files stored in the Central Management store.

  Address Book servers are governed using Address Book configuration settings; these settings determine such things as how often Address Book files are synchronized with the user database and how often these Address Book index files are generated.
  When you install Skype for Business Server, a set of global Address Book settings is created for you.
  You can also create custom configuration settings that can be applied to individual sites.
  These settings, if they exist, apply to any Address Book servers operating in the site and take precedence over the global settings.

  The `New-CsAddressBookConfiguration` cmdlet enables you to create site-level Address Book configuration settings.
  To later remove Address Book settings configured at the site scope, use the `Remove-CsAddressBookConfiguration` cmdlet.
  Note that you can also run the `Remove-CsAddressBookConfiguration` cmdlet against the global settings; however, the global settings cannot actually be removed.
  Instead, running the `Remove-CsAddressBookConfiguration` cmdlet against the global settings will reset all of the global properties to their default values.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/remove-csaddressbookconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Remove-CsAddressBookConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
