### YamlMime:PowershellCmdlet
summary: |-
  Removes a trusted application computer.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.Rtc.Management.Xds.DisplayComputer object.
    Accepts pipelined input of trusted application computer objects.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    This cmdlet does not return a value.
    It removes an object of type Microsoft.Rtc.Management.Xds.DisplayComputer.
links:
- text: New-CsTrustedApplicationComputer
  href: New-CsTrustedApplicationComputer.yml
- text: Get-CsTrustedApplicationComputer
  href: Get-CsTrustedApplicationComputer.yml
- text: Remove-CsTrustedApplicationPool
  href: Remove-CsTrustedApplicationPool.yml
- text: Get-CsTrustedApplicationPool
  href: Get-CsTrustedApplicationPool.yml
syntaxes:
- >-
  Remove-CsTrustedApplicationComputer [-Identity] <XdsGlobalRelativeIdentity> [-Force] [-WhatIf] [-Confirm]

   [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 ------------------------'
  code: |-
    Remove-CsTrustedApplicationComputer -Identity Trust1.litwareinc.com
  description: |-
    This example removes the computer with the FQDN Trust1.litwareinc.com.
  summary: ""
- title: '-------------------------- Example 2 ------------------------'
  code: |-
    Get-CsTrustedApplicationComputer -Filter Trust* | Remove-CsTrustedApplicationComputer
  description: |-
    This example removes all trusted computers that have FQDNs beginning with the string Trust.
    The example begins by calling the `Get-CsTrustedApplicationComputer` cmdlet, passing the Filter parameter the value Trust*.
    This will retrieve all trusted application computers with an FQDN beginning with Trust and ending with any set of characters.
    That collection of computers is then piped to the `Remove-CsTrustedApplicationComputer` cmdlet, which removes each item (each computer) in the collection.
    Keep in mind that this won't remove the computers from a pool if removing those computers would result in an empty pool.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses any confirmation prompts that would otherwise be displayed before making changes.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsGlobalRelativeIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    The fully qualified domain name (FQDN) of the computer to remove.

  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Remove-CsTrustedApplicationComputer
name: Remove-CsTrustedApplicationComputer
description: |-
  It is recommended that the computers that are running trusted applications within a Skype for Business Server deployment be added to a separate pool that is only for trusted applications.
  However, you can add trusted application computers to an existing pool that is also used for other purposes.
  Use this cmdlet to remove a trusted application computer.

  When you use this cmdlet to remove a trusted application computer, it will be removed not only from the list of trusted application computers but from the list of computers available on Skype for Business Server.
  In other words, if you call the `Get-CsTrustedApplicationComputer` cmdlet or the `Get-CsComputer` cmdlet the computer will no longer be listed.
  You cannot remove a trusted application computer if it's the only computer on the pool.
  If you want to remove the only computer on a pool you must remove the entire pool (which can be done by calling the `Remove-CsTrustedApplicationPool` cmdlet).
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/remove-cstrustedapplicationcomputer
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Remove-CsTrustedApplicationComputer
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
