### YamlMime:PowershellCmdlet
summary: |-
  Removes a collection of QoE (Quality of Experience) settings.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.Rtc.Management.WritableConfig.Settings.QoE.QoESettings object.
    Accepts pipelined input of QoE configuration objects.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    This cmdlet does not return a value or object.
    Instead, it removes instances of the Microsoft.Rtc.Management.WritableConfig.Settings.QoE.QoESettings object.
links:
- text: New-CsQoEConfiguration
  href: New-CsQoEConfiguration.yml
- text: Set-CsQoEConfiguration
  href: Set-CsQoEConfiguration.yml
- text: Get-CsQoEConfiguration
  href: Get-CsQoEConfiguration.yml
syntaxes:
- Remove-CsQoEConfiguration [-Identity] <XdsIdentity> [-Force] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Remove-CsQoEConfiguration -Identity site:Redmond
  description: |-
    Example 1 uses the `Remove-CsQoEConfiguration` cmdlet to remove the QoE settings assigned to the site Redmond.
    Using the Identity parameter ensures that only the settings assigned to the specified site will be removed.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Get-CsQoEConfiguration -Filter site:* | Remove-CsQoEConfiguration
  description: |-
    The command shown in Example 2 removes all the QoE settings that have been assigned at the site scope.
    To do this, the command first uses the `Get-CsQoEConfiguration` cmdlet and the Filter parameter to retrieve the appropriate QoE settings; the wildcard string "site:*" ensures that only those settings that have an identity beginning with the string value site: are returned.
    The filtered collection is then passed to the `Remove-CsQoEConfiguration` cmdlet, which deletes all the items in the collection.
  summary: ""
- title: '-------------------------- Example 3 --------------------------'
  code: |-
    Get-CsQoEConfiguration | Where-Object {$_.KeepQoEDataForDays -lt 30} | Remove-CsQoEConfiguration
  description: |-
    In Example 3, any QoE settings where the KeepQoEDataForDays property is less than 30 are deleted.
    To carry out this task, the command calls the `Get-CsQoEConfiguration` cmdlet without any parameters in order to return a collection of all the QoE settings currently in use in the organization.
    This collection is then piped to the `Where-Object` cmdlet, which picks out only those settings where the KeepQoEDataForDays property is less than (-lt) 30 days.
    In turn, the filtered collection is piped to the `Remove-CsQoEConfiguration` cmdlet, which deletes each item in that collection.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses any confirmation prompts that would otherwise be displayed before making changes.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    The unique identifier of the settings you want to remove.
    Possible values are global and site:\<site name\>, where \<site name\> is the name of the site in your Skype for Business Server deployment with the settings to be removed.


  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Remove-CsQoEConfiguration
name: Remove-CsQoEConfiguration
description: |-
  QoE metrics track the quality of audio and video calls made in your organization, including such things as the number of network packets lost, background noise and the amount of "jitter" (differences in packet delay).
  These metrics are stored in a database apart from other data (such as call detail records), which allows you to enable and disable QoE independent of other data recording.
  Use this cmdlet to remove settings that configure QoE at the site level.
  Calling this cmdlet on the global QoE configuration will reset all properties to the defaults.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/remove-csqoeconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Remove-CsQoEConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
