### YamlMime:PowershellCmdlet
summary: |-
  Deletes one or more collections of Address Book normalization configuration settings.
  Address Book normalization settings are used to convert phone numbers to a format readily understood by Skype for Business Server.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The `Remove-CsAddressBookNormalizationConfiguration` cmdlet accepts pipelined instances of the Microsoft.Rtc.Management.WritableConfig.Settings.AddressBook.AddressBookNormalizationSettings object.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
    Instead, the `Remove-CsAddressBookNormalizationConfiguration` cmdlet deletes existing instances of the Microsoft.Rtc.Management.WritableConfig.Settings.AddressBook.AddressBookNormalizationSettings object.
links:
- text: Get-CsAddressBookNormalizationConfiguration
  href: Get-CsAddressBookNormalizationConfiguration.yml
- text: New-CsAddressBookNormalizationConfiguration
  href: New-CsAddressBookNormalizationConfiguration.yml
- text: Set-CsAddressBookNormalizationConfiguration
  href: Set-CsAddressBookNormalizationConfiguration.yml
- text: Import-CsCompanyPhoneNormalizationRules
  href: Import-CsCompanyPhoneNormalizationRules.yml
syntaxes:
- >-
  Remove-CsAddressBookNormalizationConfiguration [-Identity] <XdsIdentity> [-Confirm] [-Force] [-WhatIf]

   [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Remove-CsAddressBookNormalizationConfiguration -Identity "site:Redmond"
  description: |-
    The command shown in Example 1 deletes the Address Book normalization configuration settings currently applied to the Redmond site.
    After this collection has been deleted, Address Book servers in the Redmond site will use the global configuration settings to handle phone number normalization.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Get-CsAddressBookNormalizationConfiguration -Filter "site:*" | Remove-CsAddressBookNormalizationConfiguration
  description: |-
    In Example 2, all the Address Book normalization configuration settings applied to the site scope are deleted.
    To do this, the command first uses the `Get-CsAddressBookNormalizationConfiguration` cmdlet and the Filter parameter to return a collection of all the configuration settings applied to the site scope.
    This collection is then piped to the `Remove-CsAddressBookNormalizationConfiguration` cmdlet, which removes each item in the collection.
    When this command completes, the deployment will be limited to the global collection of Address Book normalization settings.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error message that might occur when running the command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Unique identifier for the collection of Address Book configuration settings to be removed.
    For example: `-Identity "site:Redmond"`

    Note that you cannot use wildcards when specifying the collection to be removed.

  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Remove-CsAddressBookNormalizationConfiguration
name: Remove-CsAddressBookNormalizationConfiguration
description: |-
  Normalization rules define the requirements for converting (or translating) numbers from an internal Skype for Business Server format to a standard (E.164) format.
  (Note that an understanding of regular expressions is helpful in order to understand what normalization rules do and how they do it.) In Skype for Business Server, the Address Book normalization configuration settings represent collections of normalization rules that carry out these conversions and translations for Address Book servers.
  (These settings can be defined at the global scope or at the site scope.) The `Remove-CsAddressBookNormalizationConfiguration` cmdlet provides a way delete normalization rule configuration settings that have been configured at the site scope.
  This cmdlet can also be run against the global collection of settings.
  In that case, however, the global settings will not be removed; that's because the global collection cannot be deleted.
  However, all the properties in the global collection will be reset to their default values.
  That means that any custom rules you have created for the global collection will be deleted.

  Although Address Book normalization rules are very similar to voice normalization rules, the two are not interchangeable: you cannot add voice normalization rules to an Address Book collection, nor can you add Address Book normalization rules to a dial plan.
  That means, in some cases, you might need to create identical rules: one for assignment to Address Book servers, the other for assignment to dial plans.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/remove-csaddressbooknormalizationconfiguration
  applicable: Skype for Business Server 2015, Skype for Business Server 2019
  title: Remove-CsAddressBookNormalizationConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
