### YamlMime:PowershellCmdlet
summary: |-
  Use the `Remove-CsVideoTrunkConfiguration` to remove one or more Video Trunk configurations.
  Video Trunk configuration settings are scoped to Video Gateway instances and govern the behavior of the Session Initiation Protocol (SIP) trunk between each Video Gateway instance and the paired Video Interop Server instance that together define the Video Trunk.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The` Remove-CsVideoTrunkConfiguration` cmdlet accepts pipelined input of the Microsoft.Rtc.Management.WritableConfig.Settings.VideoTrunkConfiguration object.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
    The `Remove-CsVideoTrunkConfiguration` cmdlet removes specified Microsoft.Rtc.Management.WritableConfig.Settings.VideoTrunkConfiguration objects.
links:
- text: Get-CsVideoTrunkConfiguration
  href: Get-CsVideoTrunkConfiguration.yml
- text: New-CsVideoTrunkConfiguration
  href: New-CsVideoTrunkConfiguration.yml
- text: Set-CsVideoTrunkConfiguration
  href: Set-CsVideoTrunkConfiguration.yml
syntaxes:
- Remove-CsVideoTrunkConfiguration [-Identity] <XdsIdentity> [-Confirm] [-Force] [-WhatIf] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Remove-CsVideoTrunkConfiguration -Identity "site:Seattle"
  description: |-
    This example removes the Video Trunk configuration settings scoped to the Seattle site.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Get-CsVideoTrunkConfiguration -Filter "site:*" | Remove-CsVideoTrunkConfiguration
  description: |-
    This example removes all the configuration settings that have been scoped at the site level.
    The command first calls the `Get-CsVideoTrunkConfiguration` cmdlet along with the Filter parameter that limits the returns to configurations scoped at the site level.
    Those configuration objects are then piped to, and removed by, the `Remove-CsVideoTrunkConfiguration` cmdlet.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error messages and completes the cmdlet operation.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    The Identity parameter specifies the Video Trunk configuration to remove.
    Video Trunk configuration settings can be configured at the global, site, or service scope (for the VideoGateway service only).
    To refer to the global instance, use this syntax: `-Identity "global"` To refer to a collection at the site scope: `-Identity "site:Redmond"`

    Wildcard characters such as the asterisk (*) cannot be used with the Identity parameter.

    The `Remove-CsVideoTrunkConfiguration` cmdlet can be run against the single global collection of settings.
    However, that single global collection will not be deleted.
    Instead, all the properties within the collection will be reset to their default values.

  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Remove-CsVideoTrunkConfiguration
name: Remove-CsVideoTrunkConfiguration
description: |-
  The Video Interop Server (VIS) in Skype for Business Server incorporates 3rd party video teleconferencing systems (VTCs) into your Skype for Business Server 2015 infrastructure.
  The VIS is a service that runs on a standalone pool and cannot be co-located on an FE pool.

  To enable the Video Interop Server, you must use Topology Builder to define at least one VIS instance.
  Each VIS instance will typically be associated with one or more Video Gateways.
  Video Gateways route traffic between internal and third party video devices such as an internal Skype endpoint receiving video from an third party PBX supporting 3rd party video teleconferencing systems (VTCs).
  The Video Gateway and a Video Interop Server (VIS) use a Session Initiation Protocol (SIP) trunk to connect video calls between third party VTCs and internal endpoints.

  Video Trunks settings can be managed by using the CsVideoTrunkConfiguration cmdlets.
  These settings are used to manage the following Video Trunk characteristics.

  RTCP for active calls

  RTCP for calls on hold

  Secure Real-time Transport Protocol (SRTP) use when Transport Layer Security (TLS) is used for the SIP signaling

  Session timers usage on the Video Interop Server (VIS) for dialogs associated with a Video Trunk

  By default, Skype for Business Server ships with a single, global collection of Video Trunk configuration settings.
  However, administrators can use the `New-CsVideoTrunkConfiguration` cmdlet to create additional settings at the site or the service scope (for the Video Gateway service only).
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/remove-csvideotrunkconfiguration
  applicable: Skype for Business Server 2015, Skype for Business Server 2019
  title: Remove-CsVideoTrunkConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
