### YamlMime:PowershellCmdlet
summary: |-
  Removes an existing server application.
  Server applications are applications that are hosted by Skype for Business Server.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.Rtc.Management.WritableConfig.Settings.ServerApplication.Application object.
    The `Remove-CsServerApplication` cmdlet accepts pipelined instances of the server application object.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The `Remove-CsServerApplication` cmdlet deletes existing instances of the Microsoft.Rtc.Management.WritableConfig.Settings.ServerApplication.Application object.
links:
- text: Get-CsServerApplication
  href: Get-CsServerApplication.yml
- text: New-CsServerApplication
  href: New-CsServerApplication.yml
- text: Set-CsServerApplication
  href: Set-CsServerApplication.yml
syntaxes:
- Remove-CsServerApplication [-Identity] <XdsIdentity> [-Force] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 ------------------------'
  code: |-
    Remove-CsServerApplication -Identity "service:EdgeServer:atl-edge-001.litwareinc.com/EdgeMonitor"
  description: |-
    In Example 1, the server application that has the Identity service: EdgeServer:atl-edge-001.litwareinc.com/EdgeMonitor is removed.
    Because Identities must be unique, this command will never delete more than a single application.
  summary: ""
- title: '-------------------------- Example 2 ------------------------'
  code: |-
    Get-CsServerApplication | Where-Object {$_.Critical -eq $False} | Remove-CsServerApplication
  description: |-
    In Example 2, all the non-critical server applications are removed.
    To carry out this task, the command first calls the `Get-CsServerApplication` cmdlet in order to return a collection of all the server applications currently in use in the organization.
    This collection is then piped to the `Where-Object` cmdlet, which picks all the applications where the Critical property is equal to False.
    This filtered collection is then piped to the `Remove-CsServerApplication` cmdlet, which deletes each item in the collection.
  summary: ""
- title: '-------------------------- Example 3 ------------------------'
  code: |-
    Get-CsServerApplication -Filter "service:EdgeServer:atl-cs-001.litwareinc.com/*" | Remove-CsServerApplication
  description: |-
    Example 3 deletes all the server applications that have been configured for use by the service EdgeServer:atl-cs-001.litwareinc.com.
    To do this, the `Get-CsServerApplication` cmdlet is used along with the Filter parameter; the filter value "service:EdgeServer:atl-cs-001.litwareinc.com/*" returns all the applications that have an Identity that begins with the characters "service:EdgeServer:atl-cs-001.litwareinc.com/".
    In turn, that collection is piped to the `Remove-CsServerApplication` cmdlet, which deletes each application from the EdgeServer:atl-cs-001.litwareinc.com.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error message that might occur when running the command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Unique identifier for the server application to be removed.
    Server application Identities are composed of the service where the application is hosted plus the application name.
    For example, the server application named QoEAgent might have an Identity similar to this: service:Registrar:atl-cs-001.litwareinc.com/QoEAgent.

  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Remove-CsServerApplication
name: Remove-CsServerApplication
description: |-
  Server applications refer to the individual programs that run under Skype for Business Server.
  The `Remove-CsServerApplication` cmdlet provides a way for administrators to remove any application running as part of Skype for Business Server.
  Note that deleting a server application is not the same thing as uninstalling that application.
  When you run the `Remove-CsServerApplication` cmdlet, the application no longer runs under Skype for Business Server.
  However, the software itself is not uninstalled and the application can be re-enabled by running the `New-CsServerApplication` cmdlet.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/remove-csserverapplication
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Remove-CsServerApplication
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
