### YamlMime:PowershellCmdlet
summary: |-
  Removes an existing bandwidth policy service configuration.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.Rtc.Management.WritableConfig.Settings.BandwidthPolicyServiceConfiguration.BandwidthPolicyServiceConfiguration object.
    Accepts pipelined input of bandwidth policy service configuration objects.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    This cmdlet does not return a value.
    It removes an object of type Microsoft.Rtc.Management.WritableConfig.Settings.BandwidthPolicyServiceConfiguration.BandwidthPolicyServiceConfiguration.
links:
- text: New-CsBandwidthPolicyServiceConfiguration
  href: New-CsBandwidthPolicyServiceConfiguration.yml
- text: Set-CsBandwidthPolicyServiceConfiguration
  href: Set-CsBandwidthPolicyServiceConfiguration.yml
- text: Get-CsBandwidthPolicyServiceConfiguration
  href: Get-CsBandwidthPolicyServiceConfiguration.yml
syntaxes:
- >-
  Remove-CsBandwidthPolicyServiceConfiguration [-Identity] <XdsIdentity> [-Force] [-WhatIf] [-Confirm]

   [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Remove-CsBandwidthPolicyServiceConfiguration -Identity site:Redmond
  description: |-
    This example removes the bandwidth policy service configuration defined for the Redmond site (-Identity site:Redmond).
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Get-CsBandwidthPolicyServiceConfiguration | Where-Object {$_.EnableLogging -eq $False} | Remove-CsBandwidthPolicyServiceConfiguration
  description: |-
    Example 2 removes all bandwidth policy service configurations where logging is disabled.
    To accomplish this, the example begins with a call to the `Get-CsBandwidthPolicyServiceConfiguration` cmdlet.
    This will return a collection of all bandwidth policy service configurations in the Skype for Business Server deployment.
    This collection is then piped to the `Where-Object` cmdlet, which narrows the collection down to only those configurations where the EnableLogging property is equal to (-eq) False ($False).
    This leaves a collection of configurations that have logging disabled.
    This collection is then piped to the `Remove-CsBandwidthPolicyServiceConfiguration` cmdlet, which removes every item in the collection.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses any confirmation prompts that would otherwise be displayed before making changes.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    The unique identifier of the configuration you want to remove.
    This identifier will consist of the scope (for the global configuration) or the scope and name (for a site-level configuration, such as site:Redmond).

  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Remove-CsBandwidthPolicyServiceConfiguration
name: Remove-CsBandwidthPolicyServiceConfiguration
description: |-
  Call admission control (CAC) is a way of determining whether to allow real-time communications sessions, such as voice or video calls, to be established based on bandwidth constraints.
  Within the Skype for Business Server implementation of CAC, regions, sites and subnets are defined within a network along with the relationships and links between those entities in order to place bandwidth constraints between them.
  Bandwidth Policy service is the component that performs CAC functionality in the Skype for Business Server deployment, enabling the decision as to whether sufficient bandwidth exists for a call to be established.
  This cmdlet removes a bandwidth policy service configuration defined at the site level.
  You can also use the cmdlet to "remove" the global bandwidth policy service; however, the global service will not actually be removed, it will simply be reset to its default values.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/remove-csbandwidthpolicyserviceconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Remove-CsBandwidthPolicyServiceConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
