### YamlMime:PowershellCmdlet
summary: |-
  Removes one or more collections of Federal Information Processing Standards (FIPS) configuration settings.
  The FIPS standards are a set of United States government security standards required for use in computers maintained by non-military government agencies and by government contractors.
  This cmdlet was introduced in Lync Server 2013.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The `Remove-CsFIPSConfiguration` cmdlet accepts pipelined instances of the Microsoft.Rtc.Management.WritableConfig.Settings.FIPSConfiguration.FIPSConfiguration object
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
    Instead, the `Remove-CsFIPSConfiguration` cmdlet deletes existing instances of the Microsoft.Rtc.Management.WritableConfig.Settings.FIPSConfiguration.FIPSConfiguration object.
links:
- text: Get-CsFIPSConfiguration
  href: Get-CsFIPSConfiguration.yml
- text: New-CsFIPSConfiguration
  href: New-CsFIPSConfiguration.yml
- text: Set-CsFIPSConfiguration
  href: Set-CsFIPSConfiguration.yml
syntaxes:
- >-
  Remove-CsFIPSConfiguration [-Identity] <XdsIdentity> [-Confirm] [-Force] [-Tenant <Guid>] [-WhatIf]

   [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Remove-CsFIPSConfiguration -Identity "Global"
  description: |-
    Example 1 resets the properties in the global collection of FIPS configuration settings to their default values.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error message that might occur when running the command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Unique Identity of the FIPS configuration settings to be removed.
    Because Skype for Business Server only supports a single, global collection of FIPS settings, the only collection that can be deleted is the global collection:

    `-Identity global`

    Note that, in this case, the global collection will not actually be removed from the system; Skype for Business Server does not support the deletion of the global settings.
    Instead, the lone property in that collection - RequireFIPSCompliantMedia - will be reset to its default value of False.


  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Guid" data-throw-if-not-resolved="False" />
  name: Tenant
  description: |+
    Globally unique identifier (GUID) of the Skype for Business Server tenant account for the FIPS configuration settings being deleted.
    For example:

    `-Tenant "38aad667-af54-4397-aaa7-e94c79ec2308"`

    You can return the tenant ID for each of your tenants by running this command:

    `Get-CsTenant | Select-Object DisplayName, TenantID`


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Remove-CsFIPSConfiguration
name: Remove-CsFIPSConfiguration
description: |-
  The Federal Information Processing Standards (FIPS) are a series of standards and guidelines used by computers engaged in work for the United States government; for example, there are FIPS standards that govern the use of such things as cryptography, encryption, and digital signatures.
  (See https://www.itl.nist.gov/fipspubs/by-num.htm (https://www.itl.nist.gov/fipspubs/by-num.htm) for more information.) Skype for Business Server provides an option that enables the software to use only algorithms that meet the FIPS standards.
  If you need to work with the United States government (or with other entities that follow FIPS) then you can enable FIPS compliance in Skype for Business Server.

  Keep in mind, however, that, for the on-premises version of Skype for Business Server, you have only a single, global collection of FIPS configuration settings: FIPS compliance can only be enabled or disabled for your entire Skype for Business Server implementation.
  You cannot selectively enable or disable FIPS compliance on, say, an individual site or an individual Registrar pool.
  If you do enable FIPS compliance, you could potentially encounter problems when trying to communicate with organizations that do not fully adhere to the FIPS standards.

  By default, FIPS compliance is disabled in Skype for Business Server.

  Skype for Business Server Control Panel: The functions carried out by the `Remove-CsFIPSConfiguration` cmdlet are not available in Skype for Business Server Control Panel.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/remove-csfipsconfiguration
  applicable: Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Remove-CsFIPSConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
