### YamlMime:PowershellCmdlet
summary: |-
  `Set-CsMeetingConfiguration` enables you to modify the meeting configuration settings currently in use in your organization.
  Meeting configuration settings help dictate the type of meetings (also called conferences) that users can create, and also control how (or even if) anonymous users and dial-in conferencing users can join these meetings.
  Note that these settings only affect scheduled meetings; they do not affect ad-hoc meetings created by clicking the Meet Now option in Skype for Business.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.Rtc.Management.WritableConfig.Settings.UserServices.MeetingConfiguration object.
    The `Set-CsMeetingConfiguration` cmdlet accepts pipelined instances of the meeting configuration object.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The `Set-CsMeetingConfiguration` cmdlet does not return any objects or values.
    Instead, the cmdlet modifies existing instances of the Microsoft.Rtc.Management.WritableConfig.Settings.UserServices.MeetingConfiguration object.
links:
- text: Get-CsMeetingConfiguration
  href: Get-CsMeetingConfiguration.yml
- text: New-CsMeetingConfiguration
  href: New-CsMeetingConfiguration.yml
- text: Remove-CsMeetingConfiguration
  href: Remove-CsMeetingConfiguration.yml
- text: Update-CsTenantMeetingUrl
  href: Update-CsTenantMeetingUrl.yml
syntaxes:
- >-
  Set-CsMeetingConfiguration [-Tenant <Guid>] [-PstnCallersBypassLobby <Boolean>]

   [-EnableAssignedConferenceType <Boolean>] [-DesignateAsPresenter <DesignateAsPresenter>]

   [-AssignedConferenceTypeByDefault <Boolean>] [-AdmitAnonymousUsersByDefault <Boolean>]

   [-RequireRoomSystemsAuthorization <Boolean>] [-LogoURL <String>] [-LegalURL <String>] [-HelpURL <String>]

   [-CustomFooterText <String>] [-AllowConferenceRecording <Boolean>] [-AllowCloudRecordingService <Boolean>]

   [-EnableMeetingReport <Boolean>] [-UserUriFormatForStUser <String>] [[-Identity] <XdsIdentity>] [-Force]

   [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Set-CsMeetingConfiguration [-Tenant <Guid>] [-PstnCallersBypassLobby <Boolean>]

   [-EnableAssignedConferenceType <Boolean>] [-DesignateAsPresenter <DesignateAsPresenter>]

   [-AssignedConferenceTypeByDefault <Boolean>] [-AdmitAnonymousUsersByDefault <Boolean>]

   [-RequireRoomSystemsAuthorization <Boolean>] [-LogoURL <String>] [-LegalURL <String>] [-HelpURL <String>]

   [-CustomFooterText <String>] [-AllowConferenceRecording <Boolean>] [-AllowCloudRecordingService <Boolean>]

   [-EnableMeetingReport <Boolean>] [-UserUriFormatForStUser <String>] [-Instance <PSObject>] [-Force] [-WhatIf]

   [-Confirm] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 ------------------------'
  code: |-
    Set-CsMeetingConfiguration -Identity site:Redmond -DesignateAsPresenter Everyone
  description: |-
    The command shown in Example 1 modifies the meeting configuration settings assigned to the Redmond site (-Identity site:Redmond).
    In this case, the value of the DesignateAsPresenter property is set to Everyone.
  summary: ""
- title: '-------------------------- Example 2 ------------------------'
  code: |-
    Get-CsMeetingConfiguration | Set-CsMeetingConfiguration -DesignateAsPresenter Everyone
  description: |-
    The command shown in Example 2 is a variation of the command shown in Example 1.
    In this case, however, the value of the DesignateAsPresenter property is modified for all the meeting configuration settings in use in the organization.
    To do this, the `Get-CsMeetingConfiguration` cmdlet is called without any parameters in order to return a collection of all the meeting configuration settings currently in use.
    This collection is then piped to the `Set-CsMeetingConfiguration` cmdlet, which modifies the DesignateAsPresenter property for each item in the collection.
  summary: ""
- title: '-------------------------- Example 3 ------------------------'
  code: |-
    Get-CsMeetingConfiguration | Where-Object {$_.AdmitAnonymousUsersByDefault -eq $False} | Set-CsMeetingConfiguration -PstnCallersBypassLobby $True
  description: |-
    In Example 3, all the meeting configuration settings that do not allow the default admission of anonymous users are modified.
    To perform this task, the command first calls the `Get-CsMeetingConfiguration` cmdlet to return a collection of all the meeting configuration settings currently in use.
    This collection is then piped to the `Where-Object` cmdlet, which picks out only those settings where the AdmitAnonymousUsersByDefault property is equal to False.
    In turn, this filtered collection is piped to the `Set-CsMeetingConfiguration` cmdlet, which takes each item in the collection and sets the PstnCallersBypassLobby property to True.
  summary: ""
parameters:
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AdmitAnonymousUsersByDefault
  description: |+
    Determines whether meetings will, by default, allow attendance by anonymous users (that is, unauthenticated users). Set this value to True if you would like new meetings to allow for attendance by anonymous users by default. Set this value to False if you would prefer that, by default, new meetings do not allow for attendance by anonymous users. The default value is True.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Online
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AllowCloudRecordingService
  description: |+
    PARAMVALUE: $true | $false

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AllowConferenceRecording
  description: |+
    Determines whether or not users are allowed to record conference proceedings.
    The default value is True.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AssignedConferenceTypeByDefault
  description: |+
    Determines whether new meetings will be configured, by default, as public meetings.
    Set this value to True to use public meetings by default; set this value to False to use private meetings by default.
    The default value is True.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Online
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Online
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: CustomFooterText
  description: |+
    Text to be used on custom meeting invitations. Multiple lines are supported using the Enter key.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Online
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="DesignateAsPresenter" data-throw-if-not-resolved="False" />
  name: DesignateAsPresenter
  description: |+
    Indicates which users (besides the meeting organizer) are automatically designated as presenters when they join a meeting.
    Valid choices are: None; Company and Everyone.
    By default, DesignateAsPresenter is set to Company, meaning everyone in your organization will have presenter rights the moment they join a meeting.
    Note: When DesignateAsPresenter is set to Everyone, only dynamic meetings will comply with this setting. Static meetings do not allow Everyone to join as a Presenter. 

  defaultValue: Company
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Online
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableAssignedConferenceType
  description: |+
    This parameter is not available in Skype for Business Online.

    Indicates whether users are allowed to schedule public meetings.
    With a public meeting, the conference ID and the meeting link remain consistent each time the meeting is held.
    With a private meeting, the conference ID and meeting link change from meeting to meeting.
    The default value is True.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableMeetingReport
  description: |+
    PARAMVALUE: $true | $false

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error message that might occur when running the command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Online
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: HelpURL
  description: |+
    URL to a website where users can obtain assistance on joining the meeting.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Online
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Indicates the unique identifier for the collection of meeting configuration settings you want to modify.
    To refer to the global settings, use this syntax: -Identity global.
    To refer to a collection configured at the site scope, use syntax similar to this: -Identity "site:Redmond".
    Settings configured at the service scope can be referenced using syntax like this: -Identity "service:UserServer:atl-cs-001.litwareinc.com".

    If this parameter is not specified, then the `Set-CsMeetingConfiguration` cmdlet will modify the global settings.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Online
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PSObject" data-throw-if-not-resolved="False" />
  name: Instance
  description: |+
    Allows you to pass a reference to an object to the cmdlet rather than set individual parameter values.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Online
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: LegalURL
  description: |+
    URL to a website containing legal information and meeting disclaimers.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Online
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: LogoURL
  description: |+
    URL for the image to be used on custom meeting invitations.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Online
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: PstnCallersBypassLobby
  description: |+
    Indicates whether users dialing in over a public switched telephone network (PSTN) phone line should automatically be admitted to a meeting.
    If set to True ($True), PSTN callers will automatically be admitted to the meeting.
    If set to False ($False), then PSTN callers will initially be routed to the conference lobby.
    At that point, they will have to wait, on hold, until a conference presenter grants them access to the meeting.
    The default value is True.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Online
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: RequireRoomSystemsAuthorization
  description: |+
    When set to True ($True) all users must be authenticated before they can join a meeting using the Skype for Business Room System.
    The default value is False ($False).

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Online
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Guid" data-throw-if-not-resolved="False" />
  name: Tenant
  description: |+
    Globally unique identifier (GUID) of the Office 365 tenant account whose meeting configuration settings are being modified.

    For example:

    -Tenant "38aad667-af54-4397-aaa7-e94c79ec2308"

    You can return the tenant ID for each of your tenants by running this command:

    Get-CsTenant | Select-Object DisplayName, TenantID

    If you are using a remote session of Windows PowerShell and are connected only to Skype for Business Online you do not have to include the Tenant parameter.
    Instead, the tenant ID will automatically be filled in for you based on your connection information.
    The Tenant parameter is primarily for use in a hybrid deployment.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Online
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: UserUriFormatForStUser
  description: |+
    PARAMVALUE: String

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Online
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Online
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Set-CsMeetingConfiguration
name: Set-CsMeetingConfiguration
description: |-
  Meetings (also called conferences) are an integral part of Skype for Business Server.
  The CsMeetingConfiguration cmdlets enable administrators to control the type of meetings that users can create and to determine how meetings deal with anonymous users and dial-in conferencing users.
  For example, you can configure meetings so that anyone dialing in over the public switched telephone network (PSTN) is automatically admitted to the meeting.
  Alternatively, you can configure meetings so that dial-in users are not automatically admitted the meeting, but are instead routed to the meeting lobby.
  These dial-in users remain on hold in the lobby until a presenter admits them to the meeting.

  As noted previously, these settings only affect scheduled meetings; they do not affect ad-hoc meetings created by clicking Meet Now in Microsoft Lync.
  When you create a meeting by clicking Meet Now, participant access is automatically open to all everyone and anonymous users can join the meeting without having to wait in the lobby.
  This will occur regardless of how you have configured your meeting settings using the CsMeetingConfiguration cmdlets.

  The `Set-CsMeetingConfiguration` cmdlet enables you to modify any of the meeting configuration settings currently in use in your organization.
metadata:
  external help file: Microsoft.Rtc.Management.Hosted.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/set-csmeetingconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Online, Skype for Business Server 2015, Skype for Business Server 2019
  title: Set-CsMeetingConfiguration
  schema: 2.0.0
  manager: bulenteg
  author: tomkau
  ms.author: tomkau
  ms.reviewer: rogupta
