### YamlMime:PowershellCmdlet
summary: |-
  Modifies an existing bandwidth policy service configuration.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.Rtc.Management.WritableConfig.Settings.BandwidthPolicyServiceConfiguration.BandwidthPolicyServiceConfiguration object.
    Accepts pipelined input of bandwidth policy service configuration objects.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    This cmdlet does not return a value.
    It modifies an object of type Microsoft.Rtc.Management.WritableConfig.Settings.BandwidthPolicyServiceConfiguration.BandwidthPolicyServiceConfiguration.
links:
- text: New-CsBandwidthPolicyServiceConfiguration
  href: New-CsBandwidthPolicyServiceConfiguration.yml
- text: Remove-CsBandwidthPolicyServiceConfiguration
  href: Remove-CsBandwidthPolicyServiceConfiguration.yml
- text: Get-CsBandwidthPolicyServiceConfiguration
  href: Get-CsBandwidthPolicyServiceConfiguration.yml
syntaxes:
- >-
  Set-CsBandwidthPolicyServiceConfiguration [[-Identity] <XdsIdentity>] [-EnableLogging <Boolean>]

   [-LogCleanUpInterval <TimeSpan>] [-MaxLogFileSizeMb <UInt32>] [-MaxTokenLifetime <TimeSpan>] [-Force]

   [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Set-CsBandwidthPolicyServiceConfiguration [-Instance <PSObject>] [-EnableLogging <Boolean>]

   [-LogCleanUpInterval <TimeSpan>] [-MaxLogFileSizeMb <UInt32>] [-MaxTokenLifetime <TimeSpan>] [-Force]

   [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Set-CsBandwidthPolicyServiceConfiguration -Identity site:Redmond -EnableLogging $true -MaxTokenLifetime 3:00:00 -LogCleanUpInterval 5.00:00:00
  description: |-
    This example modifies the bandwidth policy service configuration for the site Redmond (-Identity site:Redmond).
    The configuration is modified to enable logging, change the maximum lifetime of a token to three hours and the number of days before log cleanup to five days.
    This is all accomplished in this one command.
    To enable logging, the EnableLogging parameter is set to True ($true).
    Next the MaxTokenLifetime parameter receives a value of 3:00:00, which represents three hours.
    Finally, the LogCleanUpInterval parameter receives a value of 5.00:00:00, which signifies five days.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableLogging
  description: |+
    Set this parameter to True to generate CAC failure and link status logs related to the bandwidth policy service.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses any confirmation prompts that would otherwise be displayed before making changes.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    The unique identifier of the configuration you want to change.
    This identifier will consist of the scope (for the global configuration) or the scope and name (for a site-level configuration, such as site:Redmond).

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PSObject" data-throw-if-not-resolved="False" />
  name: Instance
  description: |+
    A reference to a bandwidth policy service configuration object.
    This object must be of type BandwidthPolicyServiceConfiguration, which can be retrieved by calling the `Get-CsBandwidthPolicyServiceConfiguration` cmdlet.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="TimeSpan" data-throw-if-not-resolved="False" />
  name: LogCleanUpInterval
  description: |+
    The period of time after which CAC failure and link status logs will be removed.

    This value must be within the range 1 day through 60 days.
    The value must be entered in the format dd.hh:mm:ss, where d is days, h is hours, m is minutes, and s is seconds.
    For example, 20 days would be 20.00:00:00.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: MaxLogFileSizeMb
  description: |+
    The maximum size the log file is allowed to reach.
    The value for this parameter must be a positive number and specifies the file size in megabytes.
    For example, to allow the log file to reach a maximum size of 10 megabytes, enter the value 10.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="TimeSpan" data-throw-if-not-resolved="False" />
  name: MaxTokenLifetime
  description: |+
    The maximum amount of time the token issued by the Bandwidth Policy Authentication service will exist.

    This value must be in the range 1 hour through 24 hours.
    The value must be entered in the format dd.hh:mm:ss, where d is days, h is hours, m is minutes, and s is seconds.
    For example, the value for 12 hours would be 12:00:00.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Set-CsBandwidthPolicyServiceConfiguration
name: Set-CsBandwidthPolicyServiceConfiguration
description: |-
  Call admission control (CAC) is a way of determining whether to allow real-time communications sessions, such as voice or video calls, to be established based on bandwidth constraints.
  Within the Skype for Business Server implementation of CAC, regions, sites and subnets are defined within a network along with the relationships and links between those entities in order to place bandwidth constraints between them.
  Bandwidth Policy service is the component that performs CAC functionality in the Skype for Business Server deployment, enabling the decision as to whether sufficient bandwidth exists for a call to be established.
  This cmdlet modifies an existing bandwidth policy service configuration.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/set-csbandwidthpolicyserviceconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Set-CsBandwidthPolicyServiceConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
