### YamlMime:PowershellCmdlet
summary: |-
  Modifies an existing collection of media settings.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.Rtc.Management.WritableConfig.Settings.Media.MediaSettings object.
    Accepts pipelined input of media configuration objects.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The `Set-CsMediaConfiguration` cmdlet does not return a value or object.
    Instead, the cmdlet configures instances of the Microsoft.Rtc.Management.WritableConfig.Settings.Media.MediaSettings object.
links:
- text: New-CsMediaConfiguration
  href: New-CsMediaConfiguration.yml
- text: Remove-CsMediaConfiguration
  href: Remove-CsMediaConfiguration.yml
- text: Get-CsMediaConfiguration
  href: Get-CsMediaConfiguration.yml
syntaxes:
- >-
  Set-CsMediaConfiguration [[-Identity] <XdsIdentity>] [-EnableQoS <Boolean>] [-EnableSiren <Boolean>]

   [-EncryptionLevel <EncryptionLevel>] [-MaxVideoRateAllowed <MaxVideoRateAllowed>] [-Force] [-WhatIf]

   [-Confirm] [-EnableAdaptiveBandWidthEstimation <Boolean>] [-EnableG722StereoCodec <Boolean>]

   [-EnableH264Codec <Boolean>] [-EnableInCallQoS <Boolean>] [-EnableRtpRtcpMultiplexing <Boolean>]

   [-InCallQoSIntervalSeconds <UInt16>] [-EnableVideoBasedSharing <Boolean>] [-EnableDtls <Boolean>] [-EnableSilkForAudioVideoConferences <Boolean>] -[EnableServerFecForVideoInterop] [-WaitIceCompletedToAddDialOutUser] [-EnableRtx <Boolean>] [-EnableAVBundling <Boolean>] [-EnableReceiveAgc <Boolean>] 

   [<CommonParameters>]
- >-
  Set-CsMediaConfiguration [-Instance <PSObject>] [-EnableQoS <Boolean>] [-EnableSiren <Boolean>]

   [-EncryptionLevel <EncryptionLevel>] [-MaxVideoRateAllowed <MaxVideoRateAllowed>] [-Force] [-WhatIf]

   [-Confirm] [-EnableAdaptiveBandWidthEstimation <Boolean>] [-EnableG722StereoCodec <Boolean>]

   [-EnableH264Codec <Boolean>] [-EnableInCallQoS <Boolean>] [-EnableRtpRtcpMultiplexing <Boolean>]

   [-InCallQoSIntervalSeconds <UInt16>] [-EnableVideoBasedSharing <Boolean>] [-EnableDtls <Boolean>] [-EnableSilkForAudioVideoConferences <Boolean>] -[EnableServerFecForVideoInterop] [-WaitIceCompletedToAddDialOutUser] [-EnableRtx <Boolean>] [-EnableAVBundling <Boolean>] [-EnableReceiveAgc <Boolean>] 

   [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    Set-CsMediaConfiguration -Identity site:Redmond1 -MaxVideoRateAllowed hd720p15m
  description: |-
    Example 1 modifies the media configuration collection with the Identity site:Redmond1; in particular, the command sets the value of the MaxVideoRateAllowed property to Hd720p15M.
    Note that the value passed to the MaxVideoRateAllowed parameter must be one of the values specified in the parameter description.
    Also note that the values are not case sensitive; the value entered here as hd720p15m will be automatically converted to the appropriate casing (in this instance, to Hd720p15M).
  summary: ""
- title: Example 2
  code: |-
    Set-CsMediaConfiguration site:Redmond1 -EncryptionLevel donotsupportencryption
  description: |-
    This example modifies the media configuration collection with the Identity site:Redmond1 to have an EncryptionLevel value of DoNotSupportEncryption.
    Note that this value is not case sensitive; the value was entered as donotsupportencryption, but that value will be accepted as a valid value and will be automatically changed to mixed case (DoNotSupportEncryption).
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableAdaptiveBandWidthEstimation
  description: |+
    When set to True (the default value) Microsoft Lync Server will select the bandwidth rate at which to play a video stream.
    This selection will be based on such factors as the network congestion and the client's quality of the client's current network connection. This parameter was removed starting Lync Server Cumulative Update 3.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableAVBundling
  description: |+
    This parameter is reserved for internal Microsoft use.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableDtls
  description: |+
    Enables the use of Datagram Transport Layer Security (DTLS) for ICE

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableG722StereoCodec
  description: |+
    When set to True (the default value) allows the use of the G.722 wideband speech codec.
    G.722 is a standard voice codec commonly used with Voice over IP applications; with a sampling rate of 16 KHz G.722 provides higher voice quality and clarity than many other commonly-used speech codecs.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableH264Codec
  description: |+
    When set to True (the default value) allows the use of the H.264/MPEG-4 AVC video codec.
    H.264 is a standard codec commonly used for recording, compressing and distributing high-definition video.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableInCallQoS
  description: |+
    Enables or disables the ability of Skype for Business clients to send the raw data that's required to generate InCallQuality messages.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableQoS
  description: |+
    QoS monitors the quality of voice signals over a network. When set to True, enables call Quality of Service (QoS) settings.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableReceiveAgc
  description: |+
    This parameter is reserved for internal Microsoft use.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableRtpRtcpMultiplexing
  description: |+
    Enables or disables the use of RTP/RTCP Multiplexing, if enabled, when negotiating, only one candidate will be used for both RTP and RTCP.

  defaultValue: "True"
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableRtx
  description: |+
    This parameter is reserved for internal Microsoft use.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableServerFecForVideoInterop
  description: |+
    Enables the use of server Forward Error Correction for video interoperability

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableSilkForAudioVideoConferences
  description: |+
    Enables the use of SILK codec for A/V conferences

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableSiren
  description: |+
    By default, the Mediation Server does not negotiate Siren as a possible codec for calls between itself and other clients.
    If this setting is True, Siren will be included as a possible codec for use between the Mediation Server and other clients.


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableVideoBasedSharing
  description: |+
    Enables the use of Video Based Sharing, for more information, see [Video based Screen Sharing for Skype for Business Server](https://learn.microsoft.com/skypeforbusiness/manage/video-based-screen-sharing) 

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="EncryptionLevel" data-throw-if-not-resolved="False" />
  name: EncryptionLevel
  description: |+
    The level of encryption between unified communications devices.

    Valid values:

    SupportEncryption - secure real-time transport protocol (SRTP) will be used if it can be negotiated.

    RequireEncryption - SRTP must be negotiated.

    DoNotSupportEncryption - SRTP must not be used.

    This value is not case sensitive.
    (For details, see the Examples in this topic.)

    Default: RequireEncryption


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses any confirmation prompts that would otherwise be displayed before making changes.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    The unique identifier of the media configuration settings you want to change.
    This identifier specifies the scope at which this configuration is applied (global, site, or service).

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt16" data-throw-if-not-resolved="False" />
  name: InCallQoSIntervalSeconds
  description: |+
    Specifies the interval between call QoS actions.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PSObject" data-throw-if-not-resolved="False" />
  name: Instance
  description: |+
    An instance of the Microsoft.Rtc.Management.WritableConfig.Settings.Media.MediaSettings object.
    You can retrieve this object by calling the `Get-CsMediaConfiguration` cmdlet with a specific Identity.
    You can then assign new values to the properties of that object and then save those changes by passing the object to the `Set-CsMediaConfiguration` cmdlet.


  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="MaxVideoRateAllowed" data-throw-if-not-resolved="False" />
  name: MaxVideoRateAllowed
  description: |+
    The maximum rate at which video signals will be transferred at the client endpoints.

    Valid values: Hd720p15M, VGA600K, CIF250K

    Hd720p15M - High definition, with a resolution of 1280 x 720 and aspect ratio 16:9.

    VGA600K - VGA, with a resolution of 640 x 480, 25 fps with the aspect ratio 4:3.

    CIF250K - Common Intermediate Format (CIF) video format, 15 fps with a resolution of 352 x 288.

    Note that these values are not case sensitive; values will be converted to appropriate casing when the configuration is created.
    (For details, see the Examples in this topic.)

    Default: VGA600K

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: WaitIceCompletedToAddDialOutUser
  description: |+
    Waits until ICE negotiation is complete to dial out other people

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Set-CsMediaConfiguration
name: Set-CsMediaConfiguration
description: |-
  This cmdlet modifies a collection of settings that define media configuration.
  These actions relate to audio and video calls between client endpoints.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/set-csmediaconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Set-CsMediaConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
