### YamlMime:PowershellCmdlet
summary: |-
  Modifies the XMPP gateway configuration settings in use in the organization.
  The extensible Messaging and Presence Protocol (XMPP) is an open-standard communications protocol for exchanging messages using XML.
  XMPP gateways enable Skype for Business Server users to exchange instant message and presence information with users from IM and presence providers that employ XMPP.
  This cmdlet was introduced in Lync Server 2013.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The `Set-CsXmppGatewayConfiguration` cmdlet accepts pipelined instances of the Microsoft.Rtc.Management.WritableConfig.Settings.XmppFederation.XmppGatewaySettings object.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
    Instead, the `Set-CsXmppGatewayConfiguration` cmdlet modifies existing instances of the Microsoft.Rtc.Management.WritableConfig.Settings.XmppFederation.XmppGatewaySettings object.
links:
- text: Get-CsXmppGatewayConfiguration
  href: Get-CsXmppGatewayConfiguration.yml
syntaxes:
- >-
  Set-CsXmppGatewayConfiguration [[-Identity] <XdsIdentity>] [-Confirm] [-ConnectionLimit <UInt32>]

   [-DialbackPassphrase <String>] [-EnableLoggingAllMessageBodies <Boolean>] [-Force]

   [-KeepAliveInterval <UInt32>] [-PartnerConnectionLimit <UInt32>] [-StreamEstablishmentTimeout <UInt32>]

   [-StreamInactivityTimeout <UInt32>] [-SubscriptionRefreshInterval <UInt32>] [-WhatIf] [<CommonParameters>]
- >-
  Set-CsXmppGatewayConfiguration [-Confirm] [-ConnectionLimit <UInt32>] [-DialbackPassphrase <String>]

   [-EnableLoggingAllMessageBodies <Boolean>] [-Force] [-Instance <PSObject>] [-KeepAliveInterval <UInt32>]

   [-PartnerConnectionLimit <UInt32>] [-StreamEstablishmentTimeout <UInt32>] [-StreamInactivityTimeout <UInt32>]

   [-SubscriptionRefreshInterval <UInt32>] [-WhatIf] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Set-CsXmppGatewayConfiguration -Identity "global" -ConnectionLimit 1200
  description: |-
    Example 1 modifies the ConnectionLimit property for the global collection of XMPP gateway settings.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: ConnectionLimit
  description: |+
    Total number of simultaneous connections allowed for all XMPP partners.
    The default value is 1000.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DialbackPassphrase
  description: |+
    Password used when connecting to an XMPP partner over a TCP dialback connection.
    With TCP dialback, the partner contacts the XMPP gateway and then hangs up.
    The XMPP gateway calls the partner back, and the communication session can then begin.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableLoggingAllMessageBodies
  description: |+
    When set to True, Skype for Business Server will log the actual content of all instant messages.
    For privacy reasons, message content is typically deleted and only information about the communicating endpoints is included in the log files.

    The default value is False.


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error message that might occur when running the command

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Unique identifier for the XMPP gateway configuration settings to be modified.
    Because you can only have a single, global instance of these settings, you do not need to specify an Identity when calling the `Set-CsXmppGatewayConfiguration` cmdlet.
    If you prefer, however, you can use the following syntax to reference the global settings:

    `-Identity global`


  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  parameterValueGroup: ""
- type: <xref href="PSObject" data-throw-if-not-resolved="False" />
  name: Instance
  description: |+
    Allows you to pass a reference to an object to the cmdlet rather than set individual parameter values.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: KeepAliveInterval
  description: |+
    Maximum amount of time (in seconds) that can elapse before the partner must send a "keep alive" message.
    (A keep alive message simply verifies that the connection is still active.) If the time interval expires before a keep alive message is received, the connection will be closed.
    The default value is 300 seconds.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: PartnerConnectionLimit
  description: |+
    Total number of simultaneous connections allowed for a single XMPP partner.
    The default value is 20.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: StreamEstablishmentTimeout
  description: |+
    Maximum amount of time (in seconds) allotted for the XMPP partner to establish an XMPP stream.
    If this timeout period is surpassed the connection will automatically be terminated.
    The default value is 60 seconds.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: StreamInactivityTimeout
  description: |+
    Maximum amount of time (in seconds) that an XMPP stream can be inactive before the connection is automatically terminated.
    The default value is 600 seconds (10 minutes).

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: SubscriptionRefreshInterval
  description: |+
    Maximum amount of time (in seconds) that can elapse before the partner must refresh its presence subscription.
    The default value is 28800 seconds (8 hours).

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  parameterValueGroup: ""
applicable:
- Lync Server 2013
- Skype for Business Server 2015
uid: SkypeForBusiness.Set-CsXmppGatewayConfiguration
name: Set-CsXmppGatewayConfiguration
description: |-
  The Extensible Messaging and Presence Protocol (XMPP) is a standard communications protocol (based on XML) used for sending messages across the Internet.
  XMPP was originally named Jabber, and is supported by a number of Internet messaging and communication applications, including Google Talk and Facebook Chat.

  The XMPP gateway that enables Skype for Business to communicate with users on an XMPP network was originally released as an add-on to Microsoft Lync Server 2010; in Skype for Business Server, this functionality is built into the software.
  This means that your users can communicate with XMPP users provided that you:

  Configure the XMPP gateway settings.

  Configure the other XMPP network (for example, Google Talk) as an allowed XMPP partner.

  Note that Skype for Business Server provides only a single, global set of XMPP configuration settings: you cannot selectively enable or disable XMPP for a given site or a given Registrar pool.
  In fact you cannot enable or disable XMPP at all: XMPP is always enabled.
  If you do not want users communicating with XMPP networks then you should remove all the allowed XMPP partners.
  Users can only communicate with an XMPP network if that network has been configured as an allowed partner.

  Skype for Business Server Control Panel: The functions carried out by the `Set-CsXmppGatewayConfiguration` cmdlet are not available in the Skype for Business Server Control Panel
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/set-csxmppgatewayconfiguration
  applicable: Lync Server 2013, Skype for Business Server 2015
  title: Set-CsXmppGatewayConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
