### YamlMime:PowershellCmdlet
summary: |-
  Enables you to modify configuration properties of one or more servers running the Application service.
  These servers (also known as Application Servers) host software programs, such as the Call Park application, that were developed using the Microsoft Unified Communications Managed API (UCMA) set.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
    The `Set-CsApplicationServer` cmdlet does not accept pipelined input.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The `Set-CsApplicationServer` cmdlet does not return any values or objects.
    Instead, the cmdlet modifies existing instances of the Microsoft.Rtc.Management.Xds.DisplayApplicationServer object.
links:
- text: Get-CsServerApplication
  href: Get-CsServerApplication.yml
syntaxes:
- >-
  Set-CsApplicationServer [[-Identity] <XdsGlobalRelativeIdentity>] [-ApplicationDatabase <String>]

   [-AppSharingPortCount <UInt16>] [-AppSharingPortStart <UInt16>] [-AtsSipPort <UInt16>]

   [-AudioPortCount <UInt16>] [-AudioPortStart <UInt16>] [-CaaSipPort <UInt16>] [-CasSipPort <UInt16>]

   [-CpsSipPort <UInt16>] [-PdpSipPort <UInt16>] [-PdpTurnPort <UInt16>] [-RgsSipPort <UInt16>]

   [-RgsWcfMtlsPort <UInt16>] [-VideoPortCount <UInt16>] [-VideoPortStart <UInt16>] [-Force] [-WhatIf] [-Confirm]

   [-Registrar <String>] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 ------------------------'
  code: |-
    Set-CsApplicationServer -Identity "ApplicationServer:atl-cs-001.litwareinc.com" -CasSipPort 5074
  description: |-
    The command shown in Example 1 configures the SIP port for the Conferencing Announcement application on the Application Server ApplicationServer:atl-cs-001.litwareinc.com to 5074.
  summary: ""
- title: '-------------------------- Example 2 ------------------------'
  code: |-
    Set-CsApplicationServer -Identity "ApplicationServer:atl-cs-001.litwareinc.com" -AudioPortStart 49500 -AudioPortCount 5500
  description: |-
    Example 2 configures audio ports for the Application Server ApplicationServer:atl-cs-001.litwareinc.com.
    In this example, the starting audio port is set to 49500 and a total of 5500 ports are set aside for audio traffic.
  summary: ""
- title: '-------------------------- Example 3 ------------------------'
  code: |-
    Get-CsService -ApplicationServer | ForEach-Object {Set-CsApplicationServer -Identity $_.Identity -CasSipPort 5074}
  description: |-
    In Example 3, the SIP port for the Conferencing Announcement application is set to 5074 for all of the Application Servers in the organization.
    To do this, the command first uses the `Get-CsService` cmdlet to return a collection of all the Application Servers currently in use.
    This collection is then piped to the `ForEach-Object` cmdlet, which takes each server in the collection and uses the `Set-CsApplicationServer` cmdlet to set the Conferencing Announcement application SIP port to 5074.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ApplicationDatabase
  description: |+
    Service location of the Application database.
    For example: `-ApplicationDatabase "ApplicationDatabase:atl-cs-001.litwareinc.com"`.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt16" data-throw-if-not-resolved="False" />
  name: AppSharingPortCount
  description: |+
    Total number of ports allocated for application sharing.
    The actual ports to be opened will start with the value configured for AppSharingPortStart and continue through the number of ports specified for AppSharingPortCount.
    For example, if the AppSharingPortStart is set to 60000 and the AppSharingPortCount is set to 100 then ports 60000 through 60099 will be used for application sharing.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt16" data-throw-if-not-resolved="False" />
  name: AppSharingPortStart
  description: |+
    First port in the range of ports allocated for application sharing.
    For example: `-AppSharingPortStart 60000`.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt16" data-throw-if-not-resolved="False" />
  name: AtsSipPort
  description: |+
    Port used for the Audio Test service.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt16" data-throw-if-not-resolved="False" />
  name: AudioPortCount
  description: |+
    Total number of ports allocated for sending and receiving audio traffic.
    The actual ports to be opened will start with the value configured for AudioPortStart and continue through the number of ports specified for AudioPortCount.
    For example, if the AudioPortStart is set to 60000 and the AudioPortCount is set to 100, then ports 60000 through 60099 will be used for audio traffic.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt16" data-throw-if-not-resolved="False" />
  name: AudioPortStart
  description: |+
    First port in the range of ports allocated for sending and receiving audio traffic.
    For example: `-AudioPortStart 60000`.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt16" data-throw-if-not-resolved="False" />
  name: CaaSipPort
  description: |+
    SIP port used by the Conferencing Attendant application, used when connecting users to a dial-in conference.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt16" data-throw-if-not-resolved="False" />
  name: CasSipPort
  description: |+
    SIP port used by the Conferencing Announcement application, used to play announcements (for example, "Ken Myer is now exiting") during a conference.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt16" data-throw-if-not-resolved="False" />
  name: CpsSipPort
  description: |+
    SIP port used by the Call Park service.
    The Call Park service enables you to place a call on hold from one telephone, then have that call retrieved from a different phone.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error message that might occur when running the command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsGlobalRelativeIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Service location of the Application Server to be modified.
    For example: `-Identity "ApplicationServer:atl-cs-001.litwareinc.com"`.

    Note that you can leave off the prefix "ApplicationServer:" when specifying an Application server.
    For example: `-Identity "atl-cs-001.litwareinc.com"`.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt16" data-throw-if-not-resolved="False" />
  name: PdpSipPort
  description: |+
    SIP port used by the Policy Decision Point Server.
    The Policy Decision Point Server is used for bandwidth management.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt16" data-throw-if-not-resolved="False" />
  name: PdpTurnPort
  description: |+
    Turn traffic port used by the Policy Decision Point Server.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Registrar
  description: |+
    Fully qualified domain name of the Registrar associated with the Policy Decision Point Server.


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt16" data-throw-if-not-resolved="False" />
  name: RgsSipPort
  description: |+
    SIP port used by the Response Group application.
    The Response Group application provides a way to direct incoming phone calls to a specific group of people, such as an organization's support team.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt16" data-throw-if-not-resolved="False" />
  name: RgsWcfMtlsPort
  description: |+
    Port used for Windows Communication Foundation (WCF) mutual TLS (MTLS) traffic used by the Response Group application.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt16" data-throw-if-not-resolved="False" />
  name: VideoPortCount
  description: |+
    Total number of ports allocated for sending and receiving video traffic.
    The actual ports to be opened will start with the value configured for VideoPortStart and continue through the number of ports specified for VideoPortCount.
    For example, if the VideoPortStart is set to 60000 and the VideoPortCount is set to 100, then ports 60000 through 60099 will be used for video traffic.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt16" data-throw-if-not-resolved="False" />
  name: VideoPortStart
  description: |+
    First port in the range of ports allocated for sending and receiving video traffic.
    For example `-VideoPortStart 60000`.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Set-CsApplicationServer
name: Set-CsApplicationServer
description: |-
  The Application service hosts a number of Skype for Business Server programs that are not part of the core server components; these programs include the Response Group application, the Conferencing Attendant application and the Conferencing Announcement application.
  The Application service takes these programs and fully integrates them into the Skype for Business Server environment.

  The `Set-CsApplicationServer` cmdlet enables administrators to modify the configuration settings for any (or all) of the Application Servers deployed in their organization.
  For example, you can modify the ports used for audio, video, or application sharing traffic, or assign new values to ports used by individual applications such as the Conferencing Attendant application or the Conferencing Announcement application.
  Note that any time you change ports you will then need to restart the corresponding service.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/set-csapplicationserver
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Set-CsApplicationServer
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
