### YamlMime:PowershellCmdlet
summary: |-
  Modifies settings that determine how Skype for Business Server responds when users join or leave a dial-in conference.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.Rtc.Management.WritableConfig.Settings.DialInConferencingSettings.DialInConferencingConfiguration object.
    The `Set-CSDialInConferencingConfiguration` cmdlet accepts pipelined instances of the dial-in conferencing configuration object.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The `Set-CsDialInConferencingConfiguration` cmdlet does not return any objects or values.
    Instead, the cmdlet modifies existing instances of the Microsoft.Rtc.Management.WritableConfig.Settings.DialInConferencingSettings.DialInConferencingConfiguration object.
links:
- text: Get-CsDialInConferencingConfiguration
  href: Get-CsDialInConferencingConfiguration.yml
- text: New-CsDialInConferencingConfiguration
  href: New-CsDialInConferencingConfiguration.yml
- text: Remove-CsDialInConferencingConfiguration
  href: Remove-CsDialInConferencingConfiguration.yml
syntaxes:
- >-
  Set-CsDialInConferencingConfiguration [[-Identity] <XdsIdentity>] [-EnableNameRecording <Boolean>] [-Force]

   [-WhatIf] [-Confirm] [-EntryExitAnnouncementsEnabledByDefault <Boolean>]

   [-EntryExitAnnouncementsType <EntryExitAnnouncementsType>] [-AllowAnonymousPstnActivation <Boolean>]

   [-PinAuthType <String>] [<CommonParameters>]
- >-
  Set-CsDialInConferencingConfiguration [-Instance <PSObject>] [-EnableNameRecording <Boolean>] [-Force]

   [-WhatIf] [-Confirm] [-EntryExitAnnouncementsEnabledByDefault <Boolean>]

   [-EntryExitAnnouncementsType <EntryExitAnnouncementsType>] [-AllowAnonymousPstnActivation <Boolean>]

   [-PinAuthType <String>] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 ------------------------'
  code: |-
    Set-CsDialInConferencingConfiguration -Identity site:Redmond -EntryExitAnnouncementsType "ToneOnly"
  description: |-
    The command shown in Example 1 modifies the EntryExitAnnoucements property for the dial-in configuration settings for the Redmond site.
    In this case, the EntryExitAnnouncementsType property is set to ToneOnly.
  summary: ""
- title: '-------------------------- Example 2 ------------------------'
  code: |-
    Get-CsDialInConferencingConfiguration | Set-CsDialInConferencingConfiguration -EnableNameRecording $True
  description: |-
    Example 2 modifies all the dial-in conferencing configurations settings in use in the organization.
    To do this, the command first uses the `Get-CsDialInConferencingConfiguration` cmdlet to return a collection of all dial-in conferencing settings.
    That collection is then piped to the `Set-CsDialInConferencingConfiguration` cmdlet, which sets the EnableNameRecording property for each item in the collection to True ($True).
  summary: ""
- title: '-------------------------- Example 3 ------------------------'
  code: |-
    Get-CsDialInConferencingConfiguration -Filter "site:*" | Set-CsDialInConferencingConfiguration -EnableNameRecording $True -EntryExitAnnouncementsType "UseNames"
  description: |-
    Example 3 modifies all the dial-in conferencing settings that have been configured at the site scope.
    To carry out this task, the command first uses the `Get-CsDialInConferencingConfiguration` cmdlet and the Filter parameter to return a collection of all the settings configured at the site scope; the filter value "site:*" restricts returned data to settings that have an Identity beginning with the string value "site:".
    That filtered collection is then piped to the `Set-CsDialInConferencingConfiguration` cmdlet, which modifies the EnableNameRecording property and the EntryExitAnnouncementsType property for each item in the collection.
    When the command finishes running, all the dial-in conferencing settings configured at the site scope will have their EnableNameRecording property set to True and their EntryExitAnnoucements property set to "UseNames".
  summary: ""
parameters:
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AllowAnonymousPstnActivation
  description: |+
    Specifies whether unauthenticated callers can start a meeting if they are the first person to join.
    An unauthenticated caller is defined as a participant who joins a meeting over the phone and doesn't provide a PIN when joining the meeting.
    $True to allow anonymous activation, otherwise $False.
    The default is $False.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableNameRecording
  description: |+
    Determines whether or not users are asked to record their name before entering the conference.
    Set to True to enable name recording; set to False to bypass name recording.
    The default value is True.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EntryExitAnnouncementsEnabledByDefault
  description: |+
    If set to True announcements will be played each time a participant enters or exits a conference.
    If set to False (the default value), entry and exit announcements will not be played.


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="EntryExitAnnouncementsType" data-throw-if-not-resolved="False" />
  name: EntryExitAnnouncementsType
  description: |+
    Indicates the action taken by the system any time a participant enters or leaves a conference.
    (Announcements are made only if the EntryExitAnnouncementsEnabledByDefault is set to True.) Valid values are:

    UseNames.
    The person's name is announced any time her or she enters or leaves a conference (for example, "Ken Myer is exiting the conference").

    ToneOnly.
    A tone is played any time a participant enters or leaves a conference.

    The default value is UseNames.


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error message that might occur when running the command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Indicates the Identity of the dial-in conferencing configuration settings to be modified.
    To refer to the global settings, use this syntax: `-Identity global`.
    To refer to site settings, use syntax similar to this: `-Identity site:Redmond`.
    Note that you cannot use wildcards when specifying an Identity.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PSObject" data-throw-if-not-resolved="False" />
  name: Instance
  description: |+
    Allows you to pass a reference to an object to the cmdlet rather than set individual parameter values.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: PinAuthType
  description: |+
    Specifies which users are allowed to use PIN authentication.
    Allowed values are:

    Everyone

    OrganizerOnly

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Set-CsDialInConferencingConfiguration
name: Set-CsDialInConferencingConfiguration
description: |-
  When users join (or leave) a dial-in conference Skype for Business Server can respond in different ways.
  For example, participants might be asked to record their name before they can enter the conference itself.
  Likewise, administrators can decide whether they want to have Skype for Business Server announce that dial-in participants have either left or joined a conference.

  These conference "join behaviors" are managed using dial-in conferencing configuration settings; these settings can be configured at the global scope or at the site scope.
  When you first install Skype for Business Server, the only dial-in conferencing configuration settings you will have are the ones at the global scope; however, you can create new settings at the site scope by using the `New-CsDialInConferencingConfiguration` cmdlet.
  In addition, you can modify any of these configuration settings (at either the global or site scopes) by using the `Set-CsDialInConferencingConfiguration` cmdlet.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/set-csdialinconferencingconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Set-CsDialInConferencingConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
