### YamlMime:PowershellCmdlet
summary: |-
  Modifies the property values of an existing server application.
  Server applications are applications that are hosted by Skype for Business Server.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.Rtc.Management.WritableConfig.Settings.ServerApplication.Application object.
    The `Set-CsServerApplication` cmdlet accepts pipelined instances of the server application object.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The `Set-CsServerApplication` cmdlet does not return a value or object.
    Instead, the cmdlet configures instances of the Microsoft.Rtc.Management.WritableConfig.Settings.ServerApplication.application object.
links:
- text: Get-CsServerApplication
  href: Get-CsServerApplication.yml
- text: New-CsServerApplication
  href: New-CsServerApplication.yml
- text: Remove-CsServerApplication
  href: Remove-CsServerApplication.yml
syntaxes:
- >-
  Set-CsServerApplication [[-Identity] <XdsIdentity>] [-Critical <Boolean>] [-Enabled <Boolean>]

   [-Priority <Int32>] [-ScriptName <String>] [-Uri <String>] [-Force] [-Confirm] [-WhatIf] [-Script <String>]

   [<CommonParameters>]
- >-
  Set-CsServerApplication [-Instance <PSObject>] [-Critical <Boolean>] [-Enabled <Boolean>] [-Priority <Int32>]

   [-ScriptName <String>] [-Uri <String>] [-Force] [-Confirm] [-WhatIf] [-Script <String>] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 ------------------------'
  code: |-
    Set-CsServerApplication -Identity "Registrar:atl-cs-001.litwareinc.com/ExumRouting" -Enabled $True
  description: |-
    The command shown in Example 1 enables the server application that has the Identity Registrar:atl-cs-001.litwareinc.com/ExumRouting.
    Because Identities must be unique, this command will only enable a single server application.
  summary: ""
- title: '-------------------------- Example 2 ------------------------'
  code: |-
    Get-CsServerApplication | Where-Object {$_.Enabled -eq $False} | Set-CsServerApplication -Enabled $True
  description: |-
    Example 2 enables all the server applications that are currently disabled.
    To do this, the command first calls the `Get-CsServerApplication` cmdlet in order to return a collection of all the server applications currently in use in the organization.
    This collection is then piped to the `Where-Object` cmdlet, which picks out only those applications where the Enabled property is equal to False.
    In turn, the filtered collection is piped to the `Set-CsServerApplication` cmdlet, which takes each item in the collection and sets the Enabled property to True.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: Critical
  description: |+
    If set to True (the default value), then Skype for Business Server will not start unless the application in question can be started.
    If False, then Skype for Business Server will start regardless of whether or not the application can be started.


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: Enabled
  description: |+
    Set this value to True to enable the application.
    Set the value to False to disable the application.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error message that might occur when running the command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Unique identifier for the server application to be modified.
    Server application Identities are composed of the service where the application is hosted plus the application name.
    For example, the server application named QoEAgent might have an Identity similar to this: Registrar:atl-cs-001.litwareinc.com/QoEAgent.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PSObject" data-throw-if-not-resolved="False" />
  name: Instance
  description: |+
    Allows you to pass a reference to an object to the cmdlet rather than set individual parameter values.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: Priority
  description: |+
    Indicates the order of execution for server applications.
    The application with priority 0 is started first; the application with priority 1 is started second and so on.
    Note that each service that hosts a server application has its own unique set of priorities.
    For example, the Registrar service might host three applications with corresponding priorities 0, 1 and 2.
    Similarly, the Edge Server service might have four applications; these applications will have the priorities 0, 1, 2 and 3.

    If you do not specify a priority then the application will automatically be added to the bottom of the priority list.
    If you add or remove an application, the priorities of the other applications will be adjusted accordingly.
    For example, if you delete an application that has a priority of 0, then the application that previously had the priority 1 will automatically have its priority set to 0.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Script
  description: |+
    Enables you to associate the server application with a script.
    To add a script to a server application, use syntax similar to this:

    `-Script "Update.ps1"`

    To remove a script, simply set the Script property to a null value:

    `-Script $Null`

    Each server application can only be associated with one script.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ScriptName
  description: |+
    Path to the Microsoft SIP Processing Language (MSPL) script used by the application.
    MSPL is a scripting language used for filtering and routing SIP messages.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Uri
  description: |+
    Unique Uniform Resource Identifier (URI) for the application.
    For example, the QoEAgent application has the URI `http://www.microsoft.com/LCS/QoEAgent`.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Set-CsServerApplication
name: Set-CsServerApplication
description: |-
  Server applications refer to the individual programs that run under the Skype for Business Server.
  The `Set-CsServerApplication` cmdlet provides a way for administrators to modify the property values of any application running as part of Skype for Business Server.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/set-csserverapplication
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Set-CsServerApplication
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
