### YamlMime:PowershellCmdlet
summary: |-
  Sets the Active Directory service control point for the Central Management store.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
    The `Set-CsConfigurationStoreLocation` cmdlet does not accept pipelined input.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The `Set-CsConfigurationStoreLocation` cmdlet does not return any objects or values.
links:
- text: Get-CsConfigurationStoreLocation
  href: Get-CsConfigurationStoreLocation.yml
- text: Remove-CsConfigurationStoreLocation
  href: Remove-CsConfigurationStoreLocation.yml
syntaxes:
- >-
  Set-CsConfigurationStoreLocation -SqlServerFqdn <Fqdn> [-GlobalSettingsDomainController <Fqdn>]

   [-SqlInstanceName <String>] [-SkipLookup] [-Force] [-Report <String>] [-WhatIf] [-Confirm]

   [-MirrorSqlInstanceName <String>] [-MirrorSqlServerFqdn <Fqdn>] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 ------------------------'
  code: |-
    Set-CsConfigurationStoreLocation -SqlServerFqdn atl-sql-001.litwareinc.com -SqlInstanceName Rtc
  description: |-
    The command shown in Example 1 sets the Active Directory service control point for the Skype for Business Server Central Management store.
    In this example, the SCP points to the computer atl-sql-001.litwareinc.com and to the SQL Server instance Rtc.
  summary: ""
- title: '-------------------------- Example 2 ------------------------'
  code: |-
    Set-CsConfigurationStoreLocation -SqlServerFqdn atl-sql-001.litwareinc.com -SqlInstanceName Rtc -Report C:\Logs\Store_Location.html
  description: |-
    The command shown in Example 2 is a variation of the command shown in Example 1.
    This command also sets the Active Directory SCP for the Skype for Business Server Central Management store.
    In addition, information regarding the success (or failure) of this operation is logged to the file C:\Logs\Store_Location.html.
    This log is generated by including the Report parameter followed by the full path to the log file.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error message that might occur when running the command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Fqdn" data-throw-if-not-resolved="False" />
  name: GlobalSettingsDomainController
  description: |+
    FQDN of a domain controller where global settings are stored.
    If global settings are stored in the Active Directory System container, then this parameter must point to the root domain controller.
    If global settings are stored in the Configuration container, then any domain controller can be used and this parameter can be omitted.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: MirrorSqlInstanceName
  description: |+
    Name of the SQL Server instance containing the Skype for Business Server mirror database tables and data.
    For example: `-SqlInstanceName "rtc"`.


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Fqdn" data-throw-if-not-resolved="False" />
  name: MirrorSqlServerFqdn
  description: |+
    Fully qualified domain name (FQDN) of the computer where the Central Management store mirror database has been installed.
    For example: `-SqlServer atl-mirror-001.litwareinc.com`.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Report
  description: |+
    Enables you to specify a file path for the log file created when the cmdlet runs.
    For example: `-Report "C:\Logs\ConfigurationStore.html"`

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: SkipLookup
  description: |+
    If this parameter is included then the `Set-CsConfigurationStoreLocation` cmdlet will not verify that the specified computer and the specified instance of SQL Server are available.
    Instead, it will simply change the service control point.

    If this parameter is not included then both the specified computer and the specified instance of SQL Server must be available before the SCP will be changed.


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SqlInstanceName
  description: |+
    Name of the SQL Server instance containing the Skype for Business Server tables and data.
    For example: `-SqlInstanceName "rtc"`.


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Fqdn" data-throw-if-not-resolved="False" />
  name: SqlServerFqdn
  isRequired: true
  description: |+
    Fully qualified domain name (FQDN) of the computer where the Central Management store has been installed.
    For example: `-SqlServer atl-sql-001.litwareinc.com`.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Set-CsConfigurationStoreLocation
name: Set-CsConfigurationStoreLocation
description: |-
  Active Directory Domain Services uses service control points (SCP) to help computers locate services.
  For example, when you install Skype for Business Server, a service control point is created that provides location information for the Central Management store used to maintain Skype for Business Server data.
  Computers that need access to the database connect to Active Directory and use the information contained in the SCP to help them locate the correct computer and the correct instance of SQL Server.

  As noted, when you install Skype for Business Server an SCP that for the Central Management store is automatically created for you.
  If you need to move that database to another computer or if you need to move that database to a different instance of SQL Server, then you will need to update the corresponding service control point.
  That's a task that can be carried out by using the `Set-CsConfigurationStoreLocation` cmdlet.
  When you run it, the `Set-CsConfigurationStoreLocation` cmdlet searches Active Directory for the computer specified by the SqlServer parameter.
  The cmdlet then sets the store location to the FQDN of that computer.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/set-csconfigurationstorelocation
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Set-CsConfigurationStoreLocation
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
