### YamlMime:PowershellCmdlet
summary: |-
  Use the `Set-CsVideoInteropServerSyntheticTransactionConfiguration` cmdlet to modify an existing Video Interop Server (VIS) synthetic transaction configuration.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Accepts pipelined instances of the VideoInteropServerSyntheticTransactionConfiguration object.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
links:
- text: Get-CsVideoInteropServerSyntheticTransactionConfiguration
  href: Get-CsVideoInteropServerSyntheticTransactionConfiguration.yml
- text: New-CsVideoInteropServerSyntheticTransactionConfiguration
  href: New-CsVideoInteropServerSyntheticTransactionConfiguration.yml
- text: Remove-CsVideoInteropServerSyntheticTransactionConfiguration
  href: Remove-CsVideoInteropServerSyntheticTransactionConfiguration.yml
- text: Test-CsP2PVideoInteropServerSipTrunkAV
  href: Test-CsP2PVideoInteropServerSipTrunkAV.yml
syntaxes:
- >-
  Set-CsVideoInteropServerSyntheticTransactionConfiguration [[-Identity] <XdsIdentity>] [-Confirm] [-Force]

   [-WatcherNodeFqdns <PSListModifier>] [-WhatIf] [<CommonParameters>]
- >-
  Set-CsVideoInteropServerSyntheticTransactionConfiguration [-Confirm] [-Force] [-Instance <PSObject>]

   [-WatcherNodeFqdns <PSListModifier>] [-WhatIf] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Set-CsVideoInteropServerSyntheticTransactionConfiguration -Identity Global -WatcherNodeFqdns "watchernode.contoso.com"
  description: |-
    This example sets the Global configuration to trust connections from the WatcherNode "watchernode.contoso.com".
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error messages and completes the cmdlet operation.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Unique identity assigned to the VIS configuration when it was created.
    VIS settings can be configured at the global, site, or service scope (for the VideoInteropServer service only).
    To refer to the global instance, use this syntax:

    `-Identity "Global"`

    Use this syntax to refer to a collection at the site scope:

    `-Identity "site:Redmond"`

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PSObject" data-throw-if-not-resolved="False" />
  name: Instance
  description: |+
    Allows you to pass a reference to an object to the cmdlet rather than set individual parameter values.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PSListModifier" data-throw-if-not-resolved="False" />
  name: WatcherNodeFqdns
  description: |+
    Specifies the URL of the watcher node relevant to the synthetic transaction.
    For example: `-WatcherNodeFqdns "atl-cs-001.Contoso.com"`.
    Watcher nodes are computers that periodically use Microsoft System Center Operations Manager and Skype for Business Server synthetic transactions to verify that Skype for Business Server components are working as expected.
    For more information, see `New-CsWatcherNodeConfiguration`.

    To enter multiple values and overwrite any existing entries, use the following syntax: \<value1\>,\<value2\>....
    If the values contain spaces or otherwise require quotation marks, you need to use the following syntax: "\<value1\>","\<value2\>"....

    To add or remove one or more values without affecting any existing entries, use the following syntax: @{Add="\<value1\>","\<value2\>"...; Remove="\<value1\>","\<value2\>"...}.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Set-CsVideoInteropServerSyntheticTransactionConfiguration
name: Set-CsVideoInteropServerSyntheticTransactionConfiguration
description: |-
  To return a list of all the Role-Based Access Control (RBAC) roles a cmdlet has been assigned to (including any custom RBAC roles you have created), run the following command from the Windows PowerShell prompt.

  `Get-CsAdminRole | Where-Object {$_.Cmdlets -Match "\<DesiredCmdletName\>"}`
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/set-csvideointeropserversynthetictransactionconfiguration
  applicable: Skype for Business Server 2015, Skype for Business Server 2019
  title: Set-CsVideoInteropServerSyntheticTransactionConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
