### YamlMime:PowershellCmdlet
summary: |-
  Modifies an existing collection of Persistent Chat configuration settings.
  Persistent Chat configuration settings are used to manage the Persistent Chat service.
  For example, these settings allow you to specify the maximum number of users who can participate in a chat room.
  This cmdlet was introduced in Lync Server 2013.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The `Set-CsPersistentChatConfiguration` cmdlet accepts pipelined instances of the Microsoft.Rtc.Management.WritableConfig.Settings.PersistentChat.PersistentChatConfiguration object.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
    Instead, the `Set-CsPersistentChatConfiguration` cmdlet modifies existing instances of the Microsoft.Rtc.Management.WritableConfig.Settings.PersistentChat.PersistentChatConfiguration object.
links:
- text: Get-CsPersistentChatConfiguration
  href: Get-CsPersistentChatConfiguration.yml
- text: New-CsPersistentChatConfiguration
  href: New-CsPersistentChatConfiguration.yml
- text: Remove-CsPersistentChatConfiguration
  href: Remove-CsPersistentChatConfiguration.yml
syntaxes:
- >-
  Set-CsPersistentChatConfiguration [[-Identity] <XdsIdentity>] [-Confirm] [-DefaultChatHistory <Int16>] [-Force]

   [-MaxFileSizeKB <UInt32>] [-ParticipantUpdateLimit <UInt32>] [-RoomManagementUrl <String>] [-WhatIf]

   [<CommonParameters>]
- >-
  Set-CsPersistentChatConfiguration [-Confirm] [-DefaultChatHistory <Int16>] [-Force] [-Instance <PSObject>]

   [-MaxFileSizeKB <UInt32>] [-ParticipantUpdateLimit <UInt32>] [-RoomManagementUrl <String>] [-WhatIf]

   [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Set-CsPersistentChatConfiguration -Identity "global" -DefaultChatHistory 100
  description: |-
    The command shown in Example 1 sets the DefaultChatHistory property of the global Persistent Chat configuration settings to 100.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Get-CsPersistentChatConfiguration | Set-CsPersistentChatConfiguration -DefaultChatHistory 100
  description: |-
    In Example 2, the DefaultChatHistory property is set to 100 for all the Persistent Chat configuration settings.
    To carry out this task, the command first uses the `Get-CsPersistentChatConfiguration` cmdlet to return a collection of all the Persistent Chat configuration settings in the organization.
    This collection is then piped to the `Set-CsPersistentChatConfiguration` cmdlet, which modifies the DefaultChatHistory property for all the items in the collection.
  summary: ""
- title: '-------------------------- Example 3 --------------------------'
  code: |-
    Get-CsPersistentChatConfiguration -Filter "site:*" | Set-CsPersistentChatConfiguration -DefaultChatHistory 100
  description: |-
    Example 3 shows how you can modify the DefaultChatHistory property for all the Persistent Chat configuration settings applied to the site scope.
    To do this, the command first calls the `Get-CsPersistentChatConfiguration` cmdlet along with the Filter parameter; the parameter value "site:*" limits the returned data to setting collections configured at the site scope.
    These settings are then piped to the `Set-CsPersistentChatConfiguration` cmdlet, which changes the DefaultChatHistory property for each settings collection to 100.
  summary: ""
- title: '-------------------------- Example 4 --------------------------'
  code: |-
    Get-CsPersistentChatConfiguration | Where-Object {$_.DefaultChatHistory -gt 100} | Set-CsPersistentChatConfiguration -DefaultChatHistory 100
  description: |-
    In Example 4, the DefaultChatHistory property is modified for any collection of Persistent Chat configuration settings where the default chat history is currently greater than 100.
    To carry out this task, the command first uses the `Get-CsPersistentChatConfiguration` cmdlet to return a collection of all the Persistent Chat configuration settings in use in the organization.
    This collection is then piped to the `Where-Object` cmdlet, which picks out only those settings where the DefaultChatHistory property is greater than (-gt) 100.
    In turn, that filtered collection is piped to the `Set-CsPersistentChatConfiguration` cmdlet, which takes each item in the filtered collection and sets the value of the DefaultChatHistory property to 100.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  parameterValueGroup: ""
- type: <xref href="Int16" data-throw-if-not-resolved="False" />
  name: DefaultChatHistory
  description: |+
    Default number of chat messages instantly available in a chat room.
    Note that this value represents only the number of messages immediately available; it does not place a limit on the total amount of messages that can be retrieved.

    DefaultChatHistory can be set to any value between 1 and 500, inclusive.
    The default value is 30.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error message that might occur when running the command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Unique identifier for the Persistent Chat configuration settings to be modified.
    To modify a collection of settings configured at the site scope, use syntax similar to this:

    `-Identity "site:Redmond"`

    To modify a collection configured at the service scope, use syntax like this:

    `-Identity "service:PersistentChatServer:atl-gc-001.litwareinc.com"`

    To modify the global collection, use this syntax:

    `-Identity "global"`

    If you do not include the Identity parameter the `Set-CsPersistentChatConfiguration` cmdlet will automatically modify the global settings.


  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  parameterValueGroup: ""
- type: <xref href="PSObject" data-throw-if-not-resolved="False" />
  name: Instance
  description: |+
    Allows you to pass a reference to an object to the cmdlet rather than set individual parameter values.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: MaxFileSizeKB
  description: |+
    Maximum size of a file (in kilobytes) that can be uploaded or downloaded by the web service.
    The default value is 20000 KB.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: ParticipantUpdateLimit
  description: |+
    Maximum number of users who can participate in a chat room before the active participant list updates are disabled.
    The default value is 75.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: RoomManagementUrl
  description: |+
    URL for the Web page administrators can use to manage individual chat rooms.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  parameterValueGroup: ""
applicable:
- Lync Server 2013
- Skype for Business Server 2015
uid: SkypeForBusiness.Set-CsPersistentChatConfiguration
name: Set-CsPersistentChatConfiguration
description: |-
  The Persistent Chat service (which replaces the Group Chat service used in Microsoft Lync Server 2010) provides organizations with messaging and collaboration capabilities similar to those found in Internet discussion forums: users can exchange messages in real-time, yet can also revisit and restart those conversations at any time.
  Conversations can be based around specific topics, and these conversations can be made available to everyone or to only a selected set of users.
  Likewise, individual chat rooms can be configured so that anyone can post a message or configured so that only designated presenters can post messages.

  The Persistent Chat service is managed, in part, by Persistent Chat configuration settings, which dictate such things as the number of previously-posted chat messages immediately available when you log on to a chat room (the chat history) or the maximum size of a file that can be uploaded to (or downloaded from) the service.
  These settings can be configured at the global or the site scope, or at the service scope (that is, you can have a custom collection of settings assigned to an individual Persistent Chat pool).

  Skype for Business Server Control Panel: To modify an existing collection of Persistent Chat configuration settings using the Skype for Business Server Control Panel, click Persistent Chat, click Persistent Chat Configuration, then double-click the collection to be modified.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/set-cspersistentchatconfiguration
  applicable: Lync Server 2013, Skype for Business Server 2015
  title: Set-CsPersistentChatConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
