### YamlMime:PowershellCmdlet
summary: |-
  Use the `Set-CsVideoTrunkConfiguration` to modify one or more Video Trunk configurations containing settings applicable to a video SIP trunk between the Video Interoperability Server (VIS) and a Video Gateway.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The `Set-CsVideoTrunkConfiguration` cmdlet accepts pipelined instances of the Microsoft.Rtc.Management.WritableConfig.Settings.VideoTrunkConfiguration object.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
    The `Set-CsVideoTrunkConfiguration` cmdlet modifies existing instances of the Microsoft.Rtc.Management.WritableConfig.Settings.VideoTrunkConfiguration object.
links:
- text: Get-CsVideoTrunkConfiguration
  href: Get-CsVideoTrunkConfiguration.yml
- text: New-CsVideoTrunkConfiguration
  href: New-CsVideoTrunkConfiguration.yml
- text: Remove-CsVideoTrunkConfiguration
  href: Remove-CsVideoTrunkConfiguration.yml
syntaxes:
- >-
  Set-CsVideoTrunkConfiguration [[-Identity] <XdsIdentity>] [-Confirm]

   [-EnableMediaEncryptionForSipOverTls <Boolean>] [-EnableSessionTimer <Boolean>] [-Force]

   [-ForwardErrorCorrectionType <String>] [-GatewaySendsRtcpForActiveCalls <Boolean>]

   [-GatewaySendsRtcpForCallsOnHold <Boolean>] [-WhatIf] [<CommonParameters>]
- >-
  Set-CsVideoTrunkConfiguration [-Confirm] [-EnableMediaEncryptionForSipOverTls <Boolean>]

   [-EnableSessionTimer <Boolean>] [-Force] [-ForwardErrorCorrectionType <String>]

   [-GatewaySendsRtcpForActiveCalls <Boolean>] [-GatewaySendsRtcpForCallsOnHold <Boolean>] [-Instance <PSObject>]

   [-WhatIf] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Set-CsVideoTrunkConfiguration -Identity "site:Seattle" -EnableSessionTimer $False
  description: |-
    This example disables session timers for the collection of Video Trunk configuration settings assigned to the Seattle site.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Get-CsVideoTrunkConfiguration | Set-CsVideoTrunkConfiguration -EnableSessionTimer $False
  description: |-
    In this example the session timers are disabled for all the Video Trunk configuration settings in use in the organization.
    The command first uses the `Get-CsVideoTrunkConfiguration` cmdlet to return a collection of all the available Video Trunk configuration settings.
    That collection is then piped to the `Set-CsVideoTrunkConfiguration` cmdlet, which disables the session timer for each item in the collection.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableMediaEncryptionForSipOverTls
  description: |+
    When set to True ($True) it is expected that the Video Gateway or third party video teleconferencing system (VTC) uses TLS to protect SIP signaling and uses SRTP to protect the media traffic.
    The default value is True ($True).

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableSessionTimer
  description: |+
    Specifies whether the session timer is enabled.
    Session timers are used to determine whether a particular session is still active.
    The default is false ($False).

    Note that even if this parameter is set to False, session timers can be applicable if the remote connection has session timer enabled.
    In such a case, the Video Interop Server will reply to session timer probes from the remote entity.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error messages and completes the cmdlet operation.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ForwardErrorCorrectionType
  description: |+
    Specifies the type of Forward Error Correction (FEC) to be used between the Video Interop Server (VIS) and a Video Gateway.
    The valid settings are:

    None: Turns off FEC between the VIS and the Video Gateway.

    Cisco: Enables FEC compatible with Cisco Video Gateways, such as Cisco Unified Communications Manager (CUCM).

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: GatewaySendsRtcpForActiveCalls
  description: |+
    When set to True ($True) it is expected that the Video Gateway or third party video teleconferencing system (VTC) sends RTCP for calls that are enabled for media sending from the Video Gateway or VTC.
    The default value is True ($True).

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: GatewaySendsRtcpForCallsOnHold
  description: |+
    When set to True ($True) it is expected that the Video Gateway or third party video teleconferencing system (VTC) sends RTCP for calls that are disabled for media sending from the Video Gateway or VTC.
    The default value is False ($False).

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    The Identity parameter specifies the unique identifier for the video trunk configuration to be modified.

    For example, this syntax creates a new collection of settings assigned to the Redmond site: `-Identity "site:Redmond"`.
    And this syntax creates a new collection assigned to the Video Gateway "video-pbx-001.litwareinc.com": `-Identity "service:VideoGateway:video-pbx-001.litwareinc.com"`

    If this parameter is not specified, the `Set-CsVideoTrunkConfiguration` cmdlet will automatically modify the global settings.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PSObject" data-throw-if-not-resolved="False" />
  name: Instance
  description: |+
    Allows you to pass a reference to an object to the cmdlet rather than set individual parameter values.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Set-CsVideoTrunkConfiguration
name: Set-CsVideoTrunkConfiguration
description: |-
  The Video Interop Server in Skype for Business Server enables you to incorporate 3rd party video teleconferencing systems (VTCs) into your Skype for Business Server 2015 infrastructure.
  The Video Interop Server is a Skype service that runs on a standalone pool and cannot be co-located on an FE pool.

  To enable the Video Interop Server, you must use Topology Builder to define at least one VIS instance.
  Each VIS instance will typically be associated with one or more Video Gateways.
  Video Gateways route traffic between internal and third party video devices such as an internal Skype endpoint receiving video from an third party PBX supporting 3rd party video teleconferencing systems (VTCs).
  The Video Gateway and a Video Interop Server (VIS) use a Session Initiation Protocol (SIP) trunk to connect video calls between third party VTCs and internal endpoints.

  Video Trunks settings can be managed by using the CsVideoTrunkConfiguration cmdlets.
  These settings are used to manage the following Video Trunk characteristics.

  RTCP for active calls

  RTCP for calls on hold

  Secure Real-time Transport Protocol (SRTP) use when Transport Layer Security (TLS) is used for the SIP signaling

  Session timers usage on the Video Interop Server (VIS) for dialogs associated with a Video Trunk

  By default, Skype for Business Server ships with a single, global collection of Video Trunk configuration settings.
  However, administrators can use the `New-CsVideoTrunkConfiguration` cmdlet to create additional settings at the site or the service scope (for the Video Gateway service only).
  Both the single global collection of settings and any custom settings that you create can be modified by using the `Set-CsVideoTrunkConfiguration` cmdlet.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/set-csvideotrunkconfiguration
  applicable: Skype for Business Server 2015, Skype for Business Server 2019
  title: Set-CsVideoTrunkConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
