### YamlMime:PowershellCmdlet
summary: |-
  Use the `Set-CsTelemetryConfiguration` cmdlet to change the settings on existing telemetry configurations.
  UNRESOLVED_TOKEN_VAL(PS_TelemetryDataStatement)
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    This cmdlet takes pipeline input of the `Get-CsTelemetryConfiguration` cmdlet.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None
syntaxes:
- >-
  Set-CsTelemetryConfiguration [[-Identity] <XdsIdentity>] [-Confirm] [-EnableClientTelemetry <Boolean>] [-Force]

   [-WhatIf] [<CommonParameters>]
- >-
  Set-CsTelemetryConfiguration [-Confirm] [-EnableClientTelemetry <Boolean>] [-Force] [-Instance <PSObject>]

   [-WhatIf] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Set-CsTelemetryConfiguration -Identity site:Redmond -EnableClientTelemetry $True
  description: |-
    This example enables client telemetry on the configuration scoped to the Redmond site.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableClientTelemetry
  description: |+
    When set to true, client telemetry will be enabled.
    The default is false.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error messages and completes the cmdlet operation.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    A unique identifier that includes the scope of the telemetry configuration.
    Telemetry configurations can be scoped at the Global, Site, or Service level.
    For example, "site:Redmond" (for site).
    The format of the service scope is "Service:\<Identity\>", where identity is derived from the topology.
    You can use the following commands to identify the relevant services.

    `Get-CsService -WebServer | fl Identity`

    `Get-CsService -PoolFqdn \<pool\> | fl Identity`

    The first command will give you all of the WebServices in the topology, regardless of the pool.
    The second will give you all of the services on the pool, regardless of their role.
    You can combine the two commands to zero in on a single role in a single pool.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PSObject" data-throw-if-not-resolved="False" />
  name: Instance
  description: |+
    Allows you to pass a reference to an object to the cmdlet rather than set individual parameter values.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Set-CsTelemetryConfiguration
name: Set-CsTelemetryConfiguration
description: |-
  For privacy information, see the Skype for Business Privacy Statement (https://go.microsoft.com/fwlink/?LinkID=517480&clcid=0x409).
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/set-cstelemetryconfiguration
  applicable: Skype for Business Server 2015, Skype for Business Server 2019
  title: Set-CsTelemetryConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
