### YamlMime:PowershellCmdlet
summary: |-
  Modifies existing instances of the Skype for Business Server Storage Service.
  The storage service provides a common infrastructure that enables Skype for Business Server components to use Exchange as a back-end data store.
  Note that, at this point in time, there are no property values that can be modified by using this cmdlet.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The `Set-CsStorageServiceConfiguration` cmdlet accepts pipelined instances of the Microsoft.Rtc.Management.WritableConfig.Settings.StorageService.StorageServiceSettings object.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
    The `Set-CsStorageServiceConfiguration` cmdlet does not return any data or objects.
links:
- text: Get-CsStorageServiceConfiguration
  href: Get-CsStorageServiceConfiguration.yml
- text: New-CsStorageServiceConfiguration
  href: New-CsStorageServiceConfiguration.yml
- text: Remove-CsStorageServiceConfiguration
  href: Remove-CsStorageServiceConfiguration.yml
syntaxes:
- >-
  Set-CsStorageServiceConfiguration [[-Identity] <XdsIdentity>] [-Confirm]

   [-EnableAsyncAdaptorTaskAbort <Boolean>] [-EnableAutoImportFlushedData <Boolean>]

   [-EnableFabricReplicationSetReduction <Boolean>] [-FabricInvalidStateTimeoutDuration <UInt64>] [-Force]

   [-WhatIf] [<CommonParameters>]
- >-
  Set-CsStorageServiceConfiguration [-Confirm] [-EnableAsyncAdaptorTaskAbort <Boolean>]

   [-EnableAutoImportFlushedData <Boolean>] [-EnableFabricReplicationSetReduction <Boolean>]

   [-FabricInvalidStateTimeoutDuration <UInt64>] [-Force] [-Instance <PSObject>] [-WhatIf] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 ------------------------'
  description: ""
  summary: |-
    At this point in time there are no property values that can be modified by using the Set-CsStorageServiceConfiguration cmdlet.
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableAsyncAdaptorTaskAbort
  description: |+
    PARAMVALUE: $true | $false

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableAutoImportFlushedData
  description: |+
    PARAMVALUE: $true | $false

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableFabricReplicationSetReduction
  description: |+
    PARAMVALUE: $true | $false

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt64" data-throw-if-not-resolved="False" />
  name: FabricInvalidStateTimeoutDuration
  description: |+
    PARAMVALUE: UInt64

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any nonfatal error message that might occur when running the command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Unique identifier for the storage service configuration settings to be modified.
    Storage service configuration settings can be applied to the global, site, or service scope (for the Registrar service only).

    To modify the global settings, use this syntax:

    `-Identity "global"`

    To modify settings configured at the site scope, use syntax similar to this:

    `-Identity "site:Redmond"`

    To modify settings at the service level, use syntax similar to this:

    `-Identity "service:Registar:atl-cs-001.litwareinc.com"`

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PSObject" data-throw-if-not-resolved="False" />
  name: Instance
  description: |+
    Allows you to pass a reference to an object to the cmdlet rather than set individual parameter values.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Set-CsStorageServiceConfiguration
name: Set-CsStorageServiceConfiguration
description: |-
  The Skype for Business Server Storage Service enables Skype for Business Server components, such as archiving, to use Exchange as a back-end data store.
  This helps to reduce operating costs: for example, you do not need to have separate storage solutions for Exchange archiving and for Skype for Business Server archiving.
  The Storage Service also enables Skype for Business Server to leverage the heavy investment that has been made in Exchange archiving and storage and prevents administrators from having to use multiple tools to retrieve archived data.

  Separate instances of the Skype for Business Server Storage Service can be configured at the global, site and service scope (for the Registrar service only).
  By default, Skype for Business Server provides you with a single, global collection of Storage Service configuration settings.
  Administrators have the option of creating custom settings by using the `New-CsStorageServiceConfiguration` cmdlet.
  At this point in time, however, these Storage service instances do not include any settings that can managed by using the `Set-CsStorageServiceConfiguration` cmdlet.

  Skype for Business Server Control Panel: The functions carried out by the `Set-CsStorageServiceConfiguration` cmdlet are not available in the Skype for Business Server Control Panel.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/set-csstorageserviceconfiguration
  applicable: Skype for Business Server 2015, Skype for Business Server 2019
  title: Set-CsStorageServiceConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
