### YamlMime:PowershellCmdlet
summary: |-
  Modifies an existing collection of QoE (Quality of Experience) settings.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.Rtc.Management.WritableConfig.Settings.QoE.QoESettings object.
    Accepts pipelined input of QoE configuration objects.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The `Set-CsQoEConfiguration` cmdlet does not return a value or object.
    Instead, the cmdlet configures instances of the Microsoft.Rtc.Management.WritableConfig.Settings.QoE.QoESettings object.
links:
- text: New-CsQoEConfiguration
  href: New-CsQoEConfiguration.yml
- text: Remove-CsQoEConfiguration
  href: Remove-CsQoEConfiguration.yml
- text: Get-CsQoEConfiguration
  href: Get-CsQoEConfiguration.yml
syntaxes:
- >-
  Set-CsQoEConfiguration [[-Identity] <XdsIdentity>] [-EnableExternalConsumer <Boolean>]

   [-EnablePurging <Boolean>] [-EnableQoE <Boolean>] [-ExternalConsumerIssuedCertId <IssuedCertId>]

   [-ExternalConsumerName <String>] [-ExternalConsumerURL <String>] [-KeepQoEDataForDays <UInt32>]

   [-PurgeHourOfDay <UInt32>] [-Force] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Set-CsQoEConfiguration [-Instance <PSObject>] [-EnableExternalConsumer <Boolean>] [-EnablePurging <Boolean>]

   [-EnableQoE <Boolean>] [-ExternalConsumerIssuedCertId <IssuedCertId>] [-ExternalConsumerName <String>]

   [-ExternalConsumerURL <String>] [-KeepQoEDataForDays <UInt32>] [-PurgeHourOfDay <UInt32>] [-Force] [-WhatIf]

   [-Confirm] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Set-CsQoEConfiguration -Identity site:Redmond -EnableQoE $False
  description: |-
    The command in Example 1 uses the `Set-CsQoEConfiguration` cmdlet to modify the Quality of Experience settings for the Redmond site (-Identity site:Redmond).
    The new settings turn off QoE by setting the EnableQoE parameter to False.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Set-CsQoEConfiguration -Identity site:Dublin -KeepQoEDataForDays 45 -PurgeHourOfDay 4
  description: |-
    This command modifies QoE settings that apply to the Dublin site.
    In this example we've set the KeepQoEDataForDays parameter to 45, so QoE data will be purged from the database after 45 days.
    In addition, we've set the PurgeHourOfDay parameter to 4, meaning any data older than the 45 days we just specified will be purged at 4:00 AM.

    Note: If you have enabled QoE and call detail recording (CDR), for performance reasons it's a good idea to make sure the PurgeHourOfDay setting is different for QoE than for CDR.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableExternalConsumer
  description: |+
    Specifies whether an external consumer is able to receive QoE reports.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnablePurging
  description: |+
    Specifies whether records will be purged after the duration defined in the KeepQoEDataForDays property has elapsed.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableQoE
  description: |+
    Specifies whether QoE records will be collected and saved to the monitoring database.

    Note that even if EnableQoE is set to True, QoE data will not be collected unless a Monitoring Server has been deployed and associated with a Registrar pool.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="IssuedCertId" data-throw-if-not-resolved="False" />
  name: ExternalConsumerIssuedCertId
  description: |+
    The certificate ID of the certificate that allows access to the external consumer web service.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ExternalConsumerName
  description: |+
    The friendly name of the external consumer of the QoE report.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ExternalConsumerURL
  description: |+
    The URL of the external consumer to which the QoE reports will be posted.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses any confirmation prompts that would otherwise be displayed before making changes.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    The unique identifier of the settings you want to modify.
    Possible values are global and site:\<site name\>, where \<site name\> is the name of the site in your Skype for Business Server deployment to which you want to apply the changes.


  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PSObject" data-throw-if-not-resolved="False" />
  name: Instance
  description: |+
    An object reference to a QoE configuration object.
    This object must be of type QoESettings and can be retrieved by calling the `Get-CsQoEConfiguration` cmdlet.


  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: KeepQoEDataForDays
  description: |+
    The number of days QoE data will be stored before being purged from the database.
    This value is ignored if EnablePurging is set to False.

    Must be a value from 1 through 2562.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: PurgeHourOfDay
  description: |+
    The hour of the day that QoE records that have exceeded the number of days specified in the KeepQoEDataForDays property will be purged.

    Must be a value 0 through 23, representing the hour of the day.
    For example, 0 would be midnight, 13 would be 1:00 PM.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Set-CsQoEConfiguration
name: Set-CsQoEConfiguration
description: |-
  QoE metrics track the quality of audio and video calls made in your organization, including such things as the number of network packets lost, background noise and the amount of "jitter" (differences in packet delay).
  These metrics are stored in a database apart from other data (such as call detail records), which allows you to enable and disable QoE independent of other data recording.
  Use this cmdlet to modify settings that configure QoE at the global or site level.

  QoE is part of the Monitoring Server role; therefore Monitoring Server must be deployed on your Skype for Business Server installation before QoE recording takes effect or any QoE data can be collected.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/set-csqoeconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Set-CsQoEConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
