### YamlMime:PowershellCmdlet
summary: |-
  Modifies a pool that contains the computers that host trusted applications.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.Rtc.Management.Xds.DisplayExternalServer object.
    Accepts pipelined input of trusted application pool objects.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    This cmdlet does not return a value.
    It modifies an object of type Microsoft.Rtc.Management.Xds.DisplayExternalServer.
links:
- text: New-CsTrustedApplicationPool
  href: New-CsTrustedApplicationPool.yml
- text: Remove-CsTrustedApplicationPool
  href: Remove-CsTrustedApplicationPool.yml
- text: Get-CsTrustedApplicationPool
  href: Get-CsTrustedApplicationPool.yml
- text: New-CsTrustedApplicationComputer
  href: New-CsTrustedApplicationComputer.yml
syntaxes:
- >-
  Set-CsTrustedApplicationPool [[-Identity] <XdsGlobalRelativeIdentity>] [-AppSharingPortCount <UInt16>]

   [-AppSharingPortStart <UInt16>] [-AudioPortCount <UInt16>] [-AudioPortStart <UInt16>]

   [-OutboundOnly <Boolean>] [-Registrar <String>] [-RequiresReplication <Boolean>] [-ThrottleAsServer <Boolean>]

   [-TreatAsAuthenticated <Boolean>] [-VideoPortCount <UInt16>] [-VideoPortStart <UInt16>] [-Force] [-WhatIf]

   [-Confirm] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 ------------------------'
  code: |-
    Set-CsTrustedApplicationPool -Identity TrustPool.litwareinc.com -OutboundOnly $True
  description: |-
    This example modifies the pool with the FQDN TrustPool.litwareinc.com.
    We use the Identity parameter to specify the FQDN of the pool we want to modify.
    This example modifies the OutboundOnly property of the pool by specifying a value of True ($True) for the parameter OutboundOnly.
    (The default value is False.)
  summary: ""
parameters:
- type: <xref href="UInt16" data-throw-if-not-resolved="False" />
  name: AppSharingPortCount
  description: |+
    The number of ports available in the port range for application sharing connections.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt16" data-throw-if-not-resolved="False" />
  name: AppSharingPortStart
  description: |+
    The number of the first port in the port range available for application sharing connections.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt16" data-throw-if-not-resolved="False" />
  name: AudioPortCount
  description: |+
    The number of ports available in the port range for audio connections.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt16" data-throw-if-not-resolved="False" />
  name: AudioPortStart
  description: |+
    The number of the first port in the port range available for audio connections.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses any confirmation prompts that would otherwise be displayed before making changes.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsGlobalRelativeIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    The fully qualified domain name (FQDN) or service ID of the pool whose settings you want to modify.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: OutboundOnly
  description: |+
    Specifies whether a trusted application can initiate a connection to a server within the pool.
    Set this value to True if you want all connections to be initiated by the server rather than the application.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Registrar
  description: |+
    The service ID or FQDN of the Registrar service for the pool.
    Note that changing the Registrar will orphan any contacts attached to the application.
    Those contacts must be moved by calling the `Move-CsApplicationEndpoint` cmdlet.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: RequiresReplication
  description: |+
    Determines whether replication is required for this pool.
    Set this value to False if replication is not required.
    You would ordinarily set this parameter to False for Microsoft Outlook Web Access and manually-provisioned applications.


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: ThrottleAsServer
  description: |+
    Set this parameter to false to throttle connections between the servers within the pool and trusted applications as clients.
    This places greater restrictions on the connections than the default True, which throttles connections as servers.
    Throttling a connection simply places restrictions on the number of transactions that can occur simultaneously.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: TreatAsAuthenticated
  description: |+
    Determines whether authentication is required for trusted applications connecting to servers within the pool.
    Set this parameter to False if you want to require trusted applications to be authenticated.
    The default value of True allows the trusted applications to connect under the assumption they've already been authenticated.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt16" data-throw-if-not-resolved="False" />
  name: VideoPortCount
  description: |+
    The number of ports available in the port range for video connections.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt16" data-throw-if-not-resolved="False" />
  name: VideoPortStart
  description: |+
    The number of the first port in the port range available for video connections.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Set-CsTrustedApplicationPool
name: Set-CsTrustedApplicationPool
description: |-
  We recommend that the computers that are running trusted applications within a Skype for Business Server deployment be added to a separate pool that is only for trusted applications.
  However, you can add trusted application computers to an existing pool that is also used for other purposes.
  The `Set-CsTrustedApplicationPool` cmdlet modifies the settings for an existing trusted application pool.
  Note that you can't modify the computers that are associated with a pool by using this cmdlet; you must use the CsTrustedApplicationComputer cmdlets to do that.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/set-cstrustedapplicationpool
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Set-CsTrustedApplicationPool
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
