### YamlMime:PowershellCmdlet
summary: |-
  This cmdlet modifies the specified user's call forwarding settings. This cmdlet returns the specified user's call forwarding settings as an object, and displays the same on the screen, in case of success. In case of failure, the appropriate error message is shown.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Set-CsUserCallForwardingSettings [-DisableForwarding] [-SettingsActiveWorkHours] [-UnansweredToVoicemail]

   [-UnansweredToOther <String>] [-UnansweredWaitTime <Int32>] [-User] <String> [-Force] [-WhatIf] [-Confirm]

   [<CommonParameters>]
- >-
  Set-CsUserCallForwardingSettings -EnableForwarding <String> [-SettingsActiveWorkHours]

   [-DelegateRingWaitTime <Int32>] [-Delegates <System.Management.Automation.PSListModifier`1[System.String]>]

   [-User] <String> [-Force] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Set-CsUserCallForwardingSettings -EnableSimulRing <String> [-SettingsActiveWorkHours] [-UnansweredToVoicemail]

   [-UnansweredToOther <String>] [-UnansweredWaitTime <Int32>] [-TeamDelegateRingWaitTime <Int32>]

   [-Delegates <System.Management.Automation.PSListModifier`1[System.String]>]

   [-Team <System.Management.Automation.PSListModifier`1[System.String]>] [-User] <String> [-Force] [-WhatIf]

   [-Confirm] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> Set-CsUserCallForwardingSettings -User user@contoso.com -DisableForwarding
  description: |-
    This example disables the user's call forwarding settings.
  summary: ""
- title: Example 2
  code: |-
    PS C:\> Set-CsUserCallForwardingSettings -User user@contoso.com -EnableForwarding +4721956666
  description: |-
    This example modifies the user's call forwarding settings, activating call forwarding to a specific phone number.
  summary: ""
- title: Example 3
  code: |-
    PS C:\> Set-CsUserCallForwardingSettings -User user1@contoso.com -EnableSimulRing Team -Team user2@contoso.com,user2@contoso.com -TeamDelegateRingWaitTime 5
  description: |-
    This example modifies the SimulRing settings, activating simultaneous ring for the users listed in the Team parameter.
  summary: ""
- title: Example 4
  code: |-
    PS C:\> Set-CsUserCallForwardingSettings -User user@contoso.com -DisableForwarding -UnansweredToVoicemail -UnansweredWaitTime 30
  description: |-
    This example sends unanswered calls to voicemail after 30 seconds.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Skype for Business Server 2019CU1
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: DelegateRingWaitTime
  description: |+
    Specifies the time, in seconds, to wait before ringing delegates. Acceptable inputs: 0, 5, 10, 15. The parameter DelegateWaitRingTime needs to be explicitly set to a positive value  to allow call forwarding to delegates.


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2019CU1
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.PSListModifier`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.String" data-throw-if-not-resolved="False" /><span>]</span>
  name: Delegates
  description: |+
    Specifies the list of delegates that calls will be forwarded to. This parameter can only be used with EnableForwarding and EnableSimulRing parameters.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2019CU1
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: DisableForwarding
  isRequired: true
  description: |+
    This is a switch parameter that disables forwarding. Cannot be used with the EnableSimulRing and EnableForwarding parameters.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2019CU1
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: EnableForwarding
  isRequired: true
  description: |+
    Enables forwarding to the specified destination. Cannot be used with the EnableSimulRing and DisableForwarding parameters.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2019CU1
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: EnableSimulRing
  isRequired: true
  description: |+
    This is a switch parameter that enables forwarding to the specified destination. Cannot be used along with the DisableForwarding and EnableForwarding parameters. SimulRingDestination can be a phone number, delegates, or team call group. Acceptable input formats: "\<phone number\>", Team, Delegates.


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2019CU1
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: SettingsActiveWorkHours
  description: |+
    Switch parameter that specifies that settings should apply during work hours defined in Outlook. When this is not specified, settings apply all the time by default.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2019CU1
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.PSListModifier`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.String" data-throw-if-not-resolved="False" /><span>]</span>
  name: Team
  description: |+
    Specifies list of team members that calls will be forwarded to. The add and remove switches will add and remove specified users from the Team Members list. The replace parameter will set the list to the specified list, wiping out the previous list. Add and remove can be used together, but neither of them can be used along with replace. Acceptable input formats for add/remove/replace list: The inputs can be a single user address (in one of the below formats), or a comma separated list of user addresses, in the 4 standard formats that Identity parameter accepts.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2019CU1
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: TeamDelegateRingWaitTime
  description: |+
    Specifies the time, in seconds, to wait before ringing team members.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2019CU1
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: UnansweredToOther
  description: |+
    Specifies that unanswered calls will be send to other user or phone number.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2019CU1
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: UnansweredToVoicemail
  description: |+
    Specifies that unanswered calls will be send to voicemail.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2019CU1
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: UnansweredWaitTime
  description: |+
    Specifies the time, in seconds, to wait before send unanswered calls to voicemail.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2019CU1
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: User
  isRequired: true
  description: |+
    Specifies the SIP address of the user whose call forwarding settings will be modified.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: DisplayName, SipAddress, Identity
  applicable:
  - Skype for Business Server 2019CU1
  parameterValueGroup: ""
applicable:
- Skype for Business Server 2019
uid: SkypeForBusiness.Set-CsUserCallForwardingSettings
name: Set-CsUserCallForwardingSettings
description: |-
  The feature enables the use of SEFAUtil functionality in PowerShell. SEFAUtil (Secondary Extension Feature Activation) enables Skype server administrators and helpdesk agents to configure delegate-ringing, call-forwarding and Group Call Pickup settings on behalf of a Skype server user. This tool also allows administrators to query the call-routing settings that are published for a particular user.

  The cmdlets introduced in this feature can only be run by members of the following groups for On-prem deployments, per the access level specified below:

  - CsAdministrator - Get and Set for all cmdlets
  - CsVoiceAdministrator - Get and Set for all cmdlets
  - CsServerAdministrator - Get and Set for all cmdlets
  - CsHelpDesk - Get for all cmdlets

  Server auto-discovery needs to be enabled. There are no additional licensing requirements for use of the cmdlets.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/set-csusercallforwardingsettings
  applicable: Skype for Business Server 2019
  title: Set-CsUserCallForwardingSettings
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
