### YamlMime:PowershellCmdlet
summary: |-
  Provide the topic introduction here.

  **Note**: This cmdlet will be deprecated from Teams PowerShell Module.
module: SkypeForBusiness
notes: ""
syntaxes:
- >-
  Set-CsCceApplianceDeploymentStatus -Action <HybridPstnApplianceAction>

   -Status <HybridPstnApplianceActionStatus> [-Version <String>] [-Error <String>]

   [-Identity] <XdsGlobalRelativeIdentity> [-Tenant <Guid>] [-Force] [-WhatIf] [-Confirm]

   [<CommonParameters>]
- >-
  Set-CsCceApplianceDeploymentStatus -Action <HybridPstnApplianceAction>

   -Status <HybridPstnApplianceActionStatus> [-Version <String>] [-Error <String>]

   [-Identity] <XdsGlobalRelativeIdentity> [-Tenant <Guid>] [-Instance <PSObject>] [-Force] [-WhatIf]

   [-Confirm] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Insert example commands for example 1.
  description: |-
    Insert descriptive text for example 1.
  summary: ""
parameters:
- type: <xref href="HybridPstnApplianceAction" data-throw-if-not-resolved="False" />
  name: Action
  description: |+
    PARAMVALUE: Deploy | BitsUpdate | OsUpdate | Remove

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    PARAMVALUE: SwitchParameter

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Error
  description: |+
    PARAMVALUE: String

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    PARAMVALUE: SwitchParameter

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="XdsGlobalRelativeIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    PARAMVALUE: XdsGlobalRelativeIdentity

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="PSObject" data-throw-if-not-resolved="False" />
  name: Instance
  description: |+
    PARAMVALUE: PSObject

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="HybridPstnApplianceActionStatus" data-throw-if-not-resolved="False" />
  name: Status
  description: |+
    PARAMVALUE: Started | Finished | Error

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="Guid" data-throw-if-not-resolved="False" />
  name: Tenant
  description: |+
    PARAMVALUE: Guid

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Version
  description: |+
    PARAMVALUE: String

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    PARAMVALUE: SwitchParameter

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
applicable:
- Skype for Business Online
uid: SkypeForBusiness.Set-CsCceApplianceDeploymentStatus
name: Set-CsCceApplianceDeploymentStatus
description: |-
  Provide the detailed description here.
metadata:
  external help file: Microsoft.Rtc.Management.Hosted.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/set-cscceappliancedeploymentstatus
  applicable: Skype for Business Online
  title: Set-CsCceApplianceDeploymentStatus
  schema: 2.0.0
  manager: bulenteg
  author: tomkau
  ms.author: tomkau
  ms.reviewer: williamlooney
