### YamlMime:PowershellCmdlet
summary: |-
  Modifies a test scenario you can use to test phone numbers against specified routes and rules.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.Rtc.Management.WritableConfig.Policy.Voice.TestConfiguration object.
    Accepts pipelined input of voice test configuration objects.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    This cmdlet returns an object of type Microsoft.Rtc.Management.WritableConfig.Policy.Voice.TestConfiguration.
links:
- text: New-CsVoiceTestConfiguration
  href: New-CsVoiceTestConfiguration.yml
- text: Remove-CsVoiceTestConfiguration
  href: Remove-CsVoiceTestConfiguration.yml
- text: Get-CsVoiceTestConfiguration
  href: Get-CsVoiceTestConfiguration.yml
- text: Test-CsVoiceTestConfiguration
  href: Test-CsVoiceTestConfiguration.yml
- text: Get-CsVoiceRoute
  href: Get-CsVoiceRoute.yml
- text: Get-CsPstnUsage
  href: Get-CsPstnUsage.yml
- text: Get-CsDialPlan
  href: Get-CsDialPlan.yml
- text: Get-CsVoicePolicy
  href: Get-CsVoicePolicy.yml
syntaxes:
- >-
  Set-CsVoiceTestConfiguration [[-Identity] <XdsGlobalRelativeIdentity>] [-DialedNumber <String>]

   [-ExpectedRoute <String>] [-ExpectedTranslatedNumber <String>] [-ExpectedUsage <String>]

   [-TargetDialplan <String>] [-TargetVoicePolicy <String>] [-Force] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Set-CsVoiceTestConfiguration [-Instance <PSObject>] [-DialedNumber <String>] [-ExpectedRoute <String>]

   [-ExpectedTranslatedNumber <String>] [-ExpectedUsage <String>] [-TargetDialplan <String>]

   [-TargetVoicePolicy <String>] [-Force] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Set-CsVoiceTestConfiguration -Identity TestConfig1 -DialedNumber 14255551212
  description: |-
    This example sets the dialed number of the voice test configuration for TestConfig1 to 14255551212.
    This is the number that will be checked against the voice policy and route to ensure normalization occurs as expected, as well as to ensure the correct routes and dial plans are being applied.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Set-CsVoiceTestConfiguration -Identity TestConfig1 -TargetDialPlan site:Redmond1 -ExpectedTranslatedNumber "+912065551212"
  description: |-
    This example modifies settings for the voice test configuration TestConfig1.
    The command sets the TargetDialPlan to the dial plan for site:Redmond1.
    Because a change in dial plan could mean a change in normalization rules, the ExpectedTranslationNumber has also been changed to reflect what is expected from the normalization rules for that dial plan.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DialedNumber
  description: |+
    The phone number you want to use to test the policies, usages, and so on.

    Must be 512 characters or fewer.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ExpectedRoute
  description: |+
    The name of the voice route expected to be used during the configuration test.
    If a different route is used, based on the target dial plan and voice policy, the test will fail.
    You can retrieve available voice routes by calling the `Get-CsVoiceRoute` cmdlet.

    Must be 256 characters or fewer.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ExpectedTranslatedNumber
  description: |+
    The phone number in the format you expect to see it in after translation.
    This is the value of the DialedNumber parameter after normalization.
    If you run the `Test-CsVoiceTestConfiguration` cmdlet and the DialedNumber does not result in the value in ExpectedTranslatedNumber, the test will report as Fail.

    Must be 512 characters or fewer.


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ExpectedUsage
  description: |+
    The name of the PSTN usage expected to be used during the configuration test.
    If a different PSTN usage is used, based on the target dial plan and voice policy, the test will fail.
    You can retrieve available usages by calling the `Get-CsPstnUsage` cmdlet.

    Must be 256 characters or fewer.


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses any confirmation prompts that would otherwise be displayed before making changes.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsGlobalRelativeIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    A string uniquely identifying the test scenario you want to modify.

    The value of this parameter does not include scope because this object can be created only at the global scope.
    Therefore only a name is required.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PSObject" data-throw-if-not-resolved="False" />
  name: Instance
  description: |+
    An object of type Microsoft.Rtc.Management.WritableConfig.Policy.Voice.TestConfiguration that contains an existing voice test configuration with the changes you'd like to make to that configuration.
    An object of this type can be retrieved by calling the `Get-CsVoiceTestConfiguration` cmdlet.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: TargetDialplan
  description: |+
    The Identity of the dial plan to be used for this test.
    Dial plans can be retrieved by calling the `Get-CsDialPlan` cmdlet.

    Must be 40 characters or fewer.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: TargetVoicePolicy
  description: |+
    The Identity of the voice policy against which to run this test.
    Voice policies can be retrieved by calling the `Get-CsVoicePolicy` cmdlet.

    Must be 40 characters or fewer.


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Set-CsVoiceTestConfiguration
name: Set-CsVoiceTestConfiguration
description: |-
  Before implementing voice routes and voice policies, it's a good idea to test them out on various phone numbers to ensure the results are what you're expecting.
  You can do this by modifying test scenarios with this cmdlet.

  The `Set-CsVoiceTestConfiguration` cmdlet modifies the voice route, usage, dial plan and voice policy against which to test a specified phone number.
  All of this information can be defined and retrieved using other cmdlets, as specified in the parameter descriptions for this topic.

  The configurations modified with this cmdlet are tested using the `Test-CsVoiceTestConfiguration` cmdlet.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/set-csvoicetestconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Set-CsVoiceTestConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
