### YamlMime:PowershellCmdlet
summary: |-
  Enables you to modify configuration settings for computers running the A/V Edge service (these computers are also known as A/V Edge servers).
  An A/V Edge server enables internal users to share audio and video data with external users (that is, users who are not logged on to your internal network), as well as exchange files and participate in desktop sharing sessions.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.Rtc.Management.WritableConfig.Settings.Edge.MediaRelaySettings object.
    The `Set-CsAVEdgeConfiguration` cmdlet accepts pipelined input of media relay settings objects.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The `Set-CsAVEdgeConfiguration` cmdlet does not return a value or object.
    Instead, the cmdlet configures instances of the Microsoft.Rtc.Management.WritableConfig.Settings.Edge.MediaRelaySettings object.
links:
- text: Get-CsAVEdgeConfiguration
  href: Get-CsAVEdgeConfiguration.yml
- text: New-CsAVEdgeConfiguration
  href: New-CsAVEdgeConfiguration.yml
- text: Remove-CsAVEdgeConfiguration
  href: Remove-CsAVEdgeConfiguration.yml
syntaxes:
- >-
  Set-CsAVEdgeConfiguration [[-Identity] <XdsIdentity>] [-MaxTokenLifetime <TimeSpan>] [-Force] [-WhatIf]

   [-Confirm] [-MaxBandwidthPerPortKb <UInt32>] [-MaxBandwidthPerUserKb <UInt32>] [<CommonParameters>]
- >-
  Set-CsAVEdgeConfiguration [-Instance <PSObject>] [-MaxTokenLifetime <TimeSpan>] [-Force] [-WhatIf] [-Confirm]

   [-MaxBandwidthPerPortKb <UInt32>] [-MaxBandwidthPerUserKb <UInt32>] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 ------------------------'
  code: |-
    Set-CsAVEdgeConfiguration -Identity global -MaxTokenLifetime "04:00:00"
  description: |-
    In Example 1, the command modifies the MaxTokenLifetime property for the global A/V Edge configuration settings.
    In this example, the maximum token lifetime is set to 4 hours (04 hours : 00 minutes : 00 seconds).
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error message that might occur when running the command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Unique identifier for the collection of A/V Edge configuration settings to be modified.
    To modify the global collection, use the following syntax: `-Identity global`.
    To modify a site collection use syntax similar to this: `-Identity site:Redmond`.
    Settings configured at the service scope should be referred to using syntax similar to this: `-Identity service:EdgeServer:atl-cs-001.litwareinc.com`.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PSObject" data-throw-if-not-resolved="False" />
  name: Instance
  description: |+
    Allows you to pass a reference to an object to the cmdlet rather than set individual parameter values.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: MaxBandwidthPerPortKb
  description: |+
    Indicates the maximum amount of bandwidth (in kilobits per second) that can be allocated to a single port.
    The maximum bandwidth can be set to any integer value between 1 and 4294967296 (4096 gigabits) per second; the default value is 3000.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: MaxBandwidthPerUserKb
  description: |+
    Indicates the maximum amount of bandwidth (in kilobits per second) that can be allocated to any one user.
    The maximum bandwidth can be set to any integer value between 1 and 4294967296 (4096 gigabits) per second; the default value is 10000.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="TimeSpan" data-throw-if-not-resolved="False" />
  name: MaxTokenLifetime
  description: |+
    The maximum amount of time that an authentication token can be used before it expires and must be renewed.
    Token lifetimes are expressed using the following format: Days.Hours:Minutes:Seconds.
    For example, 13 days must be expressed like this, with a period (.) following the number of days, and colons (:) used to separate the hours, minutes, and seconds:

    13.00:00:00

    The default value of 8 hours must be expressed like this:

    08:00:00

    The minimum allowed token lifetime is 1 minute (00:01:00); the maximum allowed lifetime is 180 days (180.00:00:00).

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Set-CsAVEdgeConfiguration
name: Set-CsAVEdgeConfiguration
description: |-
  An A/V Edge server provides a way for audio and video traffic to be exchanged across an organization's firewall.
  Among other things, this enables users to use Skype for Business Server across the Internet and then exchange audio and video data with users who have logged onto the system from inside the firewall.
  Edge Server configuration settings can be assigned at the global scope, the site scope and the service scope.
  These configuration settings enable administrators to do such things as manage the amount of time that user authentication is valid before it must be renewed and to limit the amount of bandwidth that can be used by a single user or a single port.

  The `Set-CsAVEdgeConfiguration` cmdlet provides a way for you to modify the A/V Edge configuration settings currently in use in your organization.
  However, unless instructed by Microsoft support personnel, it is recommended that administrators do not modify the default A/V Edge settings.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/set-csavedgeconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Set-CsAVEdgeConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
