### YamlMime:PowershellCmdlet
summary: |-
  Modifies an existing endpoint contact for a trusted application.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.Rtc.Management.ADConnect.Schema.OCSADApplicationContact object.
    Accepts pipelined input of trusted application endpoint objects.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    This cmdlet does not return a value.
    It modifies an object of type Microsoft.Rtc.Management.ADConnect.Schema.OCSADApplicationContact.
links:
- text: New-CsTrustedApplicationEndpoint
  href: New-CsTrustedApplicationEndpoint.yml
- text: Remove-CsTrustedApplicationEndpoint
  href: Remove-CsTrustedApplicationEndpoint.yml
- text: Get-CsTrustedApplicationEndpoint
  href: Get-CsTrustedApplicationEndpoint.yml
syntaxes:
- >-
  Set-CsTrustedApplicationEndpoint [-Identity] <UserIdParameter> [-DisplayName <String>]

   [-DisplayNumber <String>] [-Enabled <Boolean>] [-EnabledForFederation <Boolean>]

   [-EnterpriseVoiceEnabled <Boolean>] [-LineURI <String>] [-PrimaryLanguage <String>]

   [-SecondaryLanguages <Microsoft.Rtc.Management.ADConnect.Core.MultiValuedProperty`1[System.String]>]

   [-SipAddress <String>] [-Type <String>] [-PassThru] [-WhatIf] [-Confirm]

   [-ExchangeArchivingPolicy <ExchangeArchivingPolicyOptionsEnum>] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 ------------------------'
  code: |-
    Set-CsTrustedApplicationEndpoint -Identity "sip:endpoint1@litwareinc.com" -DisplayName "Endpoint 1"
  description: |-
    This example modifies the application endpoint contact object with the SIP address endpoint1@litwareinc.com.
    Notice that the Identity value begins with the string sip: followed by the SIP address.
    The next parameter, DisplayName, is given a value of "Endpoint 1", which changes the display name of the contact to that value.
  summary: ""
- title: '-------------------------- Example 2 ------------------------'
  code: |-
    Get-CsTrustedApplicationEndpoint -Identity "Endpoint 1" | Set-CsTrustedApplicationEndpoint -DisplayNumber "(425)555-1212"
  description: |-
    This example modifies the display number of the endpoint application with the display name Endpoint 1.
    The command begins with a call to the `Get-CsTrustedApplicationEndpoint` cmdlet with an Identity of Endpoint 1.
    This retrieves the endpoint contact object with that display name.
    This object is then piped to the `Set-CsTrustedApplicationEndpoint` cmdlet, which modifies the DisplayNumber to the value, in this case, (425)555-1212.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DisplayName
  description: |+
    The display name of the endpoint contact object.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DisplayNumber
  description: |+
    The telephone number of the contact as it will appear in the Address Book.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: Enabled
  description: |+
    Determines whether the contact is enabled for Skype for Business Server.

    Default: True


  defaultValue: None
  position: Named
  aliases: CsEnabled
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnabledForFederation
  description: |+
    Determines whether federated users have access to this contact.

    Default: False

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnterpriseVoiceEnabled
  description: |+
    Determines whether the contact is enabled for Enterprise Voice.

    Default: True

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="ExchangeArchivingPolicyOptionsEnum" data-throw-if-not-resolved="False" />
  name: ExchangeArchivingPolicy
  description: |+
    Indicates where the contact's instant messaging sessions are archived.
    Allowed values are:

    * Uninitialized
    * UseLyncArchivingPolicy
    * ArchivingToExchange
    * NoArchiving

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UserIdParameter" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    The Identity (the distinguished name) or the SIP address of the application endpoint to be modified.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: LineURI
  description: |+
    The phone number of the contact.
    Must be in the format TEL:\<number\>, for example TEL:+14255551212.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PassThru
  description: |+
    Including this parameter will cause the cmdlet to not only modify the contact object but will return the new object as output.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: PrimaryLanguage
  description: |+
    The primary language used for the trusted application.
    The language must be configured using a valid language code, such as en-US (U.S.
    English), fr-FR (French), etc.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Microsoft.Rtc.Management.ADConnect.Core.MultiValuedProperty`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.String" data-throw-if-not-resolved="False" /><span>]</span>
  name: SecondaryLanguages
  description: |+
    A collection of languages that can also be used for trusted applications.
    Values must be configured as a comma-separated values list of language codes.
    For example, the following syntax sets French Canadian and French as secondary languages: `-SecondaryLanguages "fr-CA","fr-FR"`.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SipAddress
  description: |+
    You cannot modify the SIP address of a contact.
    The SIP address is assigned when the application endpoint is created.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Type
  description: |+
    This parameter is not used with this cmdlet.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Set-CsTrustedApplicationEndpoint
name: Set-CsTrustedApplicationEndpoint
description: |-
  A trusted application endpoint is an Active Directory contact object that enables routing of calls to a trusted application.
  This cmdlet modifies an existing endpoint contact object in Active Directory Domain Services.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/set-cstrustedapplicationendpoint
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Set-CsTrustedApplicationEndpoint
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
