### YamlMime:PowershellCmdlet
summary: |-
  Modifies settings that provide public switched telephone network (PSTN) phone numbers to access Exchange Subscriber Access and Auto Attendant features.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.Rtc.Management.WritableConfig.Settings.ExumRouting.VoicemailReroutingConfiguration object.
    Accepts pipelined input of voice mail rerouting configuration objects.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    This cmdlet does not return a value.
    It modifies an object of type Microsoft.Rtc.Management.WritableConfig.Settings.ExumRouting.VoicemailReroutingConfiguration.
links:
- text: New-CsVoicemailReroutingConfiguration
  href: New-CsVoicemailReroutingConfiguration.yml
- text: Remove-CsVoicemailReroutingConfiguration
  href: Remove-CsVoicemailReroutingConfiguration.yml
- text: Get-CsVoicemailReroutingConfiguration
  href: Get-CsVoicemailReroutingConfiguration.yml
syntaxes:
- >-
  Set-CsVoicemailReroutingConfiguration [[-Identity] <XdsIdentity>] [-AutoAttendantNumber <String>]

   [-Enabled <Boolean>] [-SubscriberAccessNumber <String>] [-Force] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Set-CsVoicemailReroutingConfiguration [-Instance <PSObject>] [-AutoAttendantNumber <String>]

   [-Enabled <Boolean>] [-SubscriberAccessNumber <String>] [-Force] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Set-CsVoicemailReroutingConfiguration -Identity site:Redmond1 -Enabled $True
  description: |-
    This example enables the voice mail rerouting configuration settings for the site Redmond1.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Set-CsVoicemailReroutingConfiguration -Identity site:Redmond1 -SubscriberAccessNumber "+14255551213"
  description: |-
    This example modifies the voice mail rerouting settings that apply to the site Redmond1, setting the phone number for Subscriber Access to +14255551213.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AutoAttendantNumber
  description: |+
    Phone number of the Auto Attendant to which the voice mail deposit attempts should be re-routed.

    The number supplied to this parameter must be a LineUri of an existing contact object.

    Value must be a number beginning with a digit 1 through 9, optionally preceded by a plus (+), followed by any number of digits.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: Enabled
  description: |+
    Indicates whether attempts to access voice mail should be re-routed through PSTN when IP connectivity is down.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses any confirmation prompts that would otherwise be displayed before making changes.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    The unique identifier of the configuration you want to modify.
    For this cmdlet the Identity will be either Global or Site:\<site name\>, where \<site name\> is the name of the site to which the settings are applied.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PSObject" data-throw-if-not-resolved="False" />
  name: Instance
  description: |+
    Allows you to pass a reference to an object to the cmdlet rather than set individual parameter values.

    This object must be of type Microsoft.Rtc.Management.WritableConfig.Settings.ExumRouting.VoicemailReroutingConfiguration (which can be retrieved by calling the `Get-CsVoicemailReroutingConfiguration` cmdlet).


  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SubscriberAccessNumber
  description: |+
    Subscriber Access number to which the voice mail retrieval attempts should be re-routed.

    The number supplied to this parameter must be a LineUri of an existing contact object.

    Value must be a number beginning with a digit 1 through 9, optionally preceded by a plus (+), followed by any number of digits.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Set-CsVoicemailReroutingConfiguration
name: Set-CsVoicemailReroutingConfiguration
description: |-
  This cmdlet allows you to modify settings that determine where Auto Attendant and Subscriber Access calls are rerouted to when IP connectivity to an Exchange server is lost.

  Auto Attendant and Subscriber Access are features of Exchange.
  The Auto Attendant feature provides voice recognition and touch-tone control (dual-tone multifrequency, or DTMF) for outside callers to navigate a company's phone system to reach the desired department or employee or, in Message Taking Mode, to accept messages for users.
  (Voice rerouting for Message Taking Mode is recommended.) Subscriber Access allows internal users to access their Microsoft Outlook mailbox from a phone.
  The numbers provided by these settings allow callers to leave voice mail messages for Enterprise Voice users (the AutoAttendantNumber setting) and for those users to retrieve voice mail even if the IP connectivity from the Skype for Business Server deployment at a remote site to Exchange in the data center is unavailable (the SubscriberAccessNumber setting).

  Note that these settings are not available unless the Enabled property has been set to True.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/set-csvoicemailreroutingconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Set-CsVoicemailReroutingConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
