### YamlMime:PowershellCmdlet
summary: |-
  Modifies a list of voice test configurations.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.Rtc.Management.WritableConfig.Policy.Voice.VoiceConfiguration object.
    The `Set-CsVoiceConfiguration` cmdlet accepts pipelined input of a voice configuration object.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The `Set-CsVoiceConfiguration` cmdlet does not return a value or object.
    Instead, the cmdlet configures instances of the Microsoft.Rtc.Management.WritableConfig.Policy.Voice.VoiceConfiguration object.
links:
- text: Remove-CsVoiceConfiguration
  href: Remove-CsVoiceConfiguration.yml
- text: Get-CsVoiceConfiguration
  href: Get-CsVoiceConfiguration.yml
- text: New-CsVoiceTestConfiguration
  href: New-CsVoiceTestConfiguration.yml
- text: Set-CsVoiceTestConfiguration
  href: Set-CsVoiceTestConfiguration.yml
- text: Get-CsVoiceTestConfiguration
  href: Get-CsVoiceTestConfiguration.yml
syntaxes:
- >-
  Set-CsVoiceConfiguration [[-Identity] <XdsIdentity>] [-VoiceTestConfigurations <PSListModifier>] [-Force]

   [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Set-CsVoiceConfiguration [-Instance <PSObject>] [-VoiceTestConfigurations <PSListModifier>] [-Force] [-WhatIf]

   [-Confirm] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    $a = Get-CsVoiceConfiguration

    $b = $a.VoiceTestConfigurations | Where-Object {$_.Name -eq "TestConfig2"}

    $b.DialedNumber = "5551212"

    $b.ExpectedTranslatedNumber = "+5551212"

    Set-CsVoiceConfiguration -Instance $a
  description: |-
    It takes several steps to modify a test voice configuration within a voice configuration.
    In this example, we start by retrieving the voice configuration object by calling the `Get-CsVoiceConfiguration` cmdlet.
    We assign the object retrieved (there will be only one) to the variable $a.

    In line 2 of this example we retrieve the contents of the VoiceTestConfigurations property, which is a collection of voice test configuration objects, from variable $a.
    We then pipe that collection to the `Where-Object` cmdlet, where we search the collection for the voice test configuration object with a Name equal to the string TestConfig2.
    We assign that object to the variable $b.

    Next, we modify the TestConfig2 voice test configuration object by assigning new values to the properties DialedNumber and ExpectedTranslatedNumber.
    By updating that object we've updated the object in variable $a.
    However, that object is still only in memory.
    As a final step, we need to save those changes by passing $a to the Instance parameter of the `Set-CsVoiceConfiguration` cmdlet.

    This is not the recommended way of modifying a voice configuration.
    To modify a voice configuration, simply change the individual voice test configurations with the `Set-CsVoiceTestConfiguration` cmdlet, as shown here:

    `Set-CsVoiceTestConfiguration -Identity TestConfig2 -DialedNumber 5551212 -ExpectedTranslatedNumber +5551212`

    That one line will accomplish the same task shown in Example 1.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses any confirmation prompts that would otherwise be displayed before making changes.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    The scope of this object.
    The only value possible for this parameter is Global.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PSObject" data-throw-if-not-resolved="False" />
  name: Instance
  description: |+
    A reference to a voice configuration (Microsoft.Rtc.Management.WritableConfig.Policy.Voice.VoiceConfiguration) object.
    An object of this type can be retrieved by calling the `Get-CsVoiceConfiguration` cmdlet.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PSListModifier" data-throw-if-not-resolved="False" />
  name: VoiceTestConfigurations
  description: |+
    A list of all voice test configurations (Microsoft.Rtc.Management.WritableConfig.Policy.Voice.TestConfiguration objects) defined for the Skype for Business Server deployment.

    You should modify individual voice test configuration objects by using the `Set-CsVoiceTestConfiguration` cmdlet.
    That is the recommended way of modifying configurations in this list.


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Set-CsVoiceConfiguration
name: Set-CsVoiceConfiguration
description: |-
  Voice test configurations are used to test a phone number against a specific voice policy, route and dial plan.
  This cmdlet can be used to modify voice test configurations from a list containing all the voice test configurations for a Skype for Business Server deployment.

  This cmdlet modifies an object of type VoiceConfiguration.
  This object is simply a container object for voice test configurations.
  Therefore, the use of this cmdlet is not recommended.
  To modify voice configurations, modify the individual voice test configurations by calling the `Set-CsVoiceTestConfiguration` cmdlet.

  Who can run this cmdlet: By default, members of the following groups are authorized to run the `Set-CsVoiceConfiguration` cmdlet locally: RTCUniversalServerAdmins.
  To return a list of all the role-based access control (RBAC) roles this cmdlet has been assigned to (including any custom RBAC roles you have created yourself), run the following command from the Windows PowerShell prompt:

  `Get-CsAdminRole | Where-Object {$_.Cmdlets -match "Set-CsVoiceConfiguration"}`
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/set-csvoiceconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Set-CsVoiceConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
