### YamlMime:PowershellCmdlet
summary: |-
  Use the `Set-CsVideoInteropServerConfiguration` cmdlet to modify an existing collection of Video Interop Server (VIS) configuration settings.
  VIS settings are scoped to appropriate VIS instances, and will govern the behavior of those instances.
  The Video Interop Server (VIS) enables you to incorporate 3rd party video teleconferencing systems (VTCs) into your Skype for Business infrastructure.
  VIS is a Skype for Business service that runs on a standalone pool and cannot be co-located on an FE pool.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The `Set-CsVideoInteropServerConfiguration` cmdlet accepts pipelined instances of the Microsoft.Rtc.Management.WritableConfig.Settings.VideoInteropServer.VideoInteropServerConfiguration object.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
    The `Set-CsVideoInteropServerConfiguration` cmdlet modifies existing instances of the Microsoft.Rtc.Management.WritableConfig.Settings.VideoInteropServer.VideoInteropServerConfiguration object.
links:
- text: Get-CsVideoInteropServerConfiguration
  href: Get-CsVideoInteropServerConfiguration.yml
- text: New-CsVideoInteropServerConfiguration
  href: New-CsVideoInteropServerConfiguration.yml
- text: Remove-CsVideoInteropServerConfiguration
  href: Remove-CsVideoInteropServerConfiguration.yml
syntaxes:
- >-
  Set-CsVideoInteropServerConfiguration [[-Identity] <XdsIdentity>] [-Confirm]

   [-EnableEnhancedVideoExperience <Boolean>] [-Force] [-WhatIf] [<CommonParameters>]
- >-
  Set-CsVideoInteropServerConfiguration [-Confirm] [-EnableEnhancedVideoExperience <Boolean>] [-Force]

   [-Instance <PSObject>] [-WhatIf] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Set-CsVideoInteropServerConfiguration -Identity "site:Redmond" -EnableEnhancedVideoExperience $False
  description: |-
    This example disables enhanced video experience for the collection of VIS settings assigned to the Redmond site.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Get-CsVideoInteropServerConfiguration | Set-CsVideoInteropServerConfiguration -EnableEnhancedVideoExperience $False
  description: |-
    This example disables all enhanced video experience settings in the organization.
    The command uses the `Get-CsVideoInteropServerConfiguration` cmdlet to return a collection of all the available VIS settings.
    That collection is piped to the `Set-CsVideoInteropServerConfiguration` cmdlet, which disables the enhanced video experience for each item in the collection.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableEnhancedVideoExperience
  description: |+
    When set to True ($True) the single video stream coming from a third party video system will be converted to multiple streams in order to meet the needs of devices using different video resolutions or frame rates. The default value is True ($True).

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error messages and completes the cmdlet operation.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Unique identifier for the video server configuration settings to be modified.
    To modify the global settings, use this syntax:

    `-Identity "global"`

    To manage settings at the site scope use syntax like the following:

    `-Identity "site:Redmond"`

    To modify settings configured at the service scope, use syntax similar to this:

    `-Identity "service:VideoInteropServer:atl-edge-001.litwareinc.com"`

    If this parameter is not included, the `Set-CsVideoInteropServerConfiguration` cmdlet will automatically modify the global settings.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PSObject" data-throw-if-not-resolved="False" />
  name: Instance
  description: |+
    Allows you to pass a reference to an object to the cmdlet rather than set individual parameter values.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Set-CsVideoInteropServerConfiguration
name: Set-CsVideoInteropServerConfiguration
description: |-
  The Video Interop Server (VIS) enables you to incorporate 3rd party video teleconferencing systems (VTCs) into your Skype for Business infrastructure.
  VIS is a Skype for Business service that runs on a standalone pool and cannot be co-located on an FE pool.

  To enable the Video Interop Server (VIS) you must use Topology Builder to define at least one VIS instance.
  Each VIS instance will typically be associated with one or more Video Gateways.
  Video Gateways route traffic between internal and external video devices such as an internal Skype for Business endpoint receiving video from an external PBX supporting 3rd party video teleconferencing systems (VTCs).
  The Video Gateway and a VIS use a Session Initiation Protocol (SIP) trunk to connect video calls between external VTCs and internal endpoints.

  You can manage the Video Interop Server (VIS) by using VIS configuration settings and the CsVideoInteropServerConfiguration cmdlets.
  These settings are used to enable or disable the enhanced video experience (in which a single video stream is converted to multiple streams in order to accommodate the needs of devices that use different frame rates or video resolutions).

  By default, Skype for Business Server ships with a single, global collection of video interop configuration settings.
  However, administrators can use the `New-CsVideoInteropServerConfiguration` cmdlet to create additional settings at the site or the service scope (for the Video Interop server service only.) Both the global collection of settings and any custom settings that you create can be modified by using the `Set-CsVideoInteropServerConfiguration` cmdlet.

  To return a list of all the Role-Based Access Control (RBAC) roles a cmdlet has been assigned to (including any custom RBAC roles you have created), run the following command from the Windows PowerShell prompt.

  `Get-CsAdminRole | Where-Object {$_.Cmdlets -Match "\<DesiredCmdletName\>"}`
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/set-csvideointeropserverconfiguration
  applicable: Skype for Business Server 2015, Skype for Business Server 2019
  title: Set-CsVideoInteropServerConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
