### YamlMime:PowershellCmdlet
summary: |-
  Use the `Set-CsBroadcastMeetingConfiguration` cmdlet to modify the settings of your global (and only) broadcast meeting configuration.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None
syntaxes:
- >-
  Set-CsBroadcastMeetingConfiguration [-Tenant <Guid>] [-EnableBroadcastMeeting <Boolean>]

   [-EnableOpenBroadcastMeeting <Boolean>] [-EnableBroadcastMeetingRecording <Boolean>]

   [-EnableAnonymousBroadcastMeeting <Boolean>] [-EnforceBroadcastMeetingRecording <Boolean>]

   [-BroadcastMeetingSupportUrl <String>] [-EnableSdnProviderForBroadcastMeeting <Boolean>]

   [-SdnFallbackAttendeeThresholdCountForBroadcastMeeting <UInt32>] [-EnableTechPreviewFeatures <Boolean>]

   [[-Identity] <XdsIdentity>] [-Force] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Set-CsBroadcastMeetingConfiguration -SdnProviderName <String> [-SdnLicenseId <String>]

   [-SdnAzureSubscriptionId <String>] -SdnApiTemplateUrl <String> [-SdnApiToken <String>] [-Tenant <Guid>]

   [-EnableBroadcastMeeting <Boolean>] [-EnableOpenBroadcastMeeting <Boolean>]

   [-EnableBroadcastMeetingRecording <Boolean>] [-EnableAnonymousBroadcastMeeting <Boolean>]

   [-EnforceBroadcastMeetingRecording <Boolean>] [-BroadcastMeetingSupportUrl <String>]

   [-EnableSdnProviderForBroadcastMeeting <Boolean>]

   [-SdnFallbackAttendeeThresholdCountForBroadcastMeeting <UInt32>] [-EnableTechPreviewFeatures <Boolean>]

   [-Force] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Set-CsBroadcastMeetingConfiguration [-Tenant <Guid>] [-EnableBroadcastMeeting <Boolean>]

   [-EnableOpenBroadcastMeeting <Boolean>] [-EnableBroadcastMeetingRecording <Boolean>]

   [-EnableAnonymousBroadcastMeeting <Boolean>] [-EnforceBroadcastMeetingRecording <Boolean>]

   [-BroadcastMeetingSupportUrl <String>] [-EnableSdnProviderForBroadcastMeeting <Boolean>]

   [-SdnFallbackAttendeeThresholdCountForBroadcastMeeting <UInt32>] [-EnableTechPreviewFeatures <Boolean>]

   [-Instance <PSObject>] [-Force] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Set-CsBroadcastMeetingConfiguration -Identity Global -EnableAnonymousBroadcastMeeting $true -EnableBroadcastMeetingRecording $true
  description: |-
    This example sets the global configuration to enable unauthenticated attendees and recorded meetings.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Set-CsBroadcastMeetingConfiguration -EnableSdnProviderForBroadcastMeeting $true -SdnProviderName "SDNCo" -SdnLicenseId 24030-38291-39042-2048-253904 -SdnApiTemplateUrl "https://api.SDNCo.com/template?auth={0}" -SdnFallbackAttendeeThresholdCountForBroadcastMeeting 1000
  description: |-
    This example enables Software Defined Network (SDN) management of broadcast meetings and provides all the required and optional settings to enable SDN support.
  summary: ""
- title: '-------------------------- Example 3 --------------------------'
  code: |-
    Set-CsBroadcastMeetingConfiguration -SdnFallbackAttendeeThresholdCountForBroadcastMeeting 500
  description: |-
    This example adjusts the broadcast meeting configuration to set the number of meeting attendees who can fall back from a Software Defined Network (SDN) to the content delivery network to 500.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: BroadcastMeetingSupportUrl
  description: |+
    Specifies a URL where broadcast meeting attendees can find support information or FAQs specific to that meeting.
    The URL will be displayed during the broadcast meeting.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    The Confirm switch causes the command to pause processing and requires confirmation to proceed.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableAnonymousBroadcastMeeting
  description: |+
    Specifies whether non-authenticated attendees are allowed to join and view the web-based portion of the meeting.
    Valid input for this parameter is $true or $false.
    The default value is $true.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableBroadcastMeeting
  description: |+
    Specifies whether broadcast meetings are enabled.
    Valid input for this parameter is $true or $false.
    The default value is $false.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableBroadcastMeetingRecording
  description: |+
    Specifies whether broadcast meetings can be recorded at the server level.
    Valid input for this parameter is $true or $false.
    The default value is $true.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableOpenBroadcastMeeting
  description: |+
    Specifies if the organizer is allowed to create broadcast meetings that allows anyone in the organizer's organization to attend.
    The default and only setting is $true.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableSdnProviderForBroadcastMeeting
  description: |+
    If set to $true, broadcast meeting streams are enabled to take advantage of the network and bandwidth management capabilities of your Software Defined Network (SDN) provider.
    The default is $false.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableTechPreviewFeatures
  description: |+
    Set to $true to enable use of features available in a technical preview program.
    Set to $false to disable the technical preview features.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnforceBroadcastMeetingRecording
  description: |+
    Specifies whether all meetings will be recorded.
    Valid input for this parameter is $true or $false.
    The default value is $false.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    The Force switch specifies whether to suppress warning and confirmation messages.
    It can be useful in scripting to suppress interactive prompts.
    If the Force switch isn't provided in the command, you're prompted for administrative input if required.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    This parameter is reserved for internal Microsoft use.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="PSObject" data-throw-if-not-resolved="False" />
  name: Instance
  description: |+
    Allows you to pass a reference to an object to the cmdlet rather than set individual parameter values.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SdnApiTemplateUrl
  description: |+
    Specifies the Software Defined Network (SDN) provider's HTTP API endpoint.
    This information is provided to you by the SDN provider.
    This parameter is only required if EnableSdnProviderForBroadcastMeeting is set to $true.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SdnApiToken
  description: |+
    Specifies the Software Defined Network (SDN) provider's authentication token which is required to use their SDN license.
    This is required by some SDN providers who will give you the required token.
    This parameter is only required if EnableSdnProviderForBroadcastMeeting is set to $true.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SdnAzureSubscriptionId
  description: |+
    Specifies your Microsoft Azure subscription id which is required by some providers to access the Software Defined Network (SDN) provider's services.

    The SdnAzureSubscriptionId parameter is not currently supported.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SdnFallbackAttendeeThresholdCountForBroadcastMeeting
  description: |+
    Specifies the number of broadcast meeting attendees that are allowed to fallback from a Software Defined Network (SDN) connection to the standard content delivery network.
    If this number is exceeded, additional meeting attendees who are not able to use the SDN service will not be allowed to join the meeting.

    The SdnFallbackAttendeeThresholdCountForBroadcastMeeting parameter is not currently supported.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SdnLicenseId
  description: |+
    Specifies the Software Defined Network (SDN) license identifier.
    This is required and provided by some SDN providers.
    This parameter is only required if EnableSdnProviderForBroadcastMeeting is set to $true.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SdnProviderName
  description: |+
    Specifies the Software Defined Network (SDN) provider's name.
    This parameter is only required if EnableSdnProviderForBroadcastMeeting is set to $true.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="Guid" data-throw-if-not-resolved="False" />
  name: Tenant
  description: |+
    This parameter is reserved for internal Microsoft use.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    The WhatIf switch causes the command to simulate its results.
    By using this switch, you can view what changes would occur without having to commit those changes.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
applicable:
- Skype for Business Online
uid: SkypeForBusiness.Set-CsBroadcastMeetingConfiguration
name: Set-CsBroadcastMeetingConfiguration
description: |-
  Use the `Set-CsBroadcastMeetingConfiguration` cmdlet to modify the settings of your global (and only) broadcast meeting configuration.

  To return a list of all the Role-Based Access Control (RBAC) roles a cmdlet has been assigned to (including any custom RBAC roles you have created), run the following command:

  `Get-CsAdminRole | Where-Object {$_.Cmdlets -Match "\<DesiredCmdletName\>"}`
metadata:
  external help file: Microsoft.Rtc.Management.Hosted.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/set-csbroadcastmeetingconfiguration
  applicable: Skype for Business Online
  title: Set-CsBroadcastMeetingConfiguration
  schema: 2.0.0
  manager: bulenteg
  author: tomkau
  ms.author: tomkau
  ms.reviewer: williamlooney
