### YamlMime:PowershellCmdlet
summary: |-
  Modifies the property values in an existing collection of Registrar configuration settings.
  Registrars are used to authenticate logon requests and to maintain information about user status and availability.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.Rtc.Management.WritableConfig.Settings.Registrar.RegistrarSettings object.
    The `Set-CsRegistrarConfiguration` cmdlet accepts pipelined instances of the Registrar settings object.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The `Set-CsRegistrarConfiguration` cmdlet does not return a value or object.
    Instead, the cmdlet configures instances of the Microsoft.Rtc.Management.WritableConfig.Settings.Registrar.RegistrarSettings object.
links:
- text: Get-CsRegistrarConfiguration
  href: Get-CsRegistrarConfiguration.yml
- text: New-CsRegistrarConfiguration
  href: New-CsRegistrarConfiguration.yml
- text: Remove-CsRegistrarConfiguration
  href: Remove-CsRegistrarConfiguration.yml
syntaxes:
- >-
  Set-CsRegistrarConfiguration [[-Identity] <XdsIdentity>] [-DefaultEndpointExpiration <Int32>]

   [-EnableDHCPServer <Boolean>] [-MaxEndpointExpiration <Int32>] [-MaxEndpointsPerUser <UInt16>]

   [-MinEndpointExpiration <Int32>] [-Force] [-WhatIf] [-Confirm] [-BackupStoreUnavailableThreshold <TimeSpan>]

   [-MaxUserCount <UInt64>] [-PoolState <PoolState>] [-EnableWinFabLogUpload <Boolean>]

   [-UserCertificateReplicationThreshold <UInt64>] [-WinFabMaxLogsSizeMb <Int32>] [<CommonParameters>]
- >-
  Set-CsRegistrarConfiguration [-Instance <PSObject>] [-DefaultEndpointExpiration <Int32>]

   [-EnableDHCPServer <Boolean>] [-MaxEndpointExpiration <Int32>] [-MaxEndpointsPerUser <UInt16>]

   [-MinEndpointExpiration <Int32>] [-Force] [-WhatIf] [-Confirm] [-BackupStoreUnavailableThreshold <TimeSpan>]

   [-MaxUserCount <UInt64>] [-PoolState <PoolState>] [-EnableWinFabLogUpload <Boolean>]

   [-UserCertificateReplicationThreshold <UInt64>] [-WinFabMaxLogsSizeMb <Int32>] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Set-CsRegistrarConfiguration -Identity site:Redmond -EnableDHCPServer $True
  description: |-
    Example 1 modifies the Registrar configuration settings applied to the Redmond site (-Identity site:Redmond).
    In this example, the value of the EnableDHCPServer property is set to True.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Get-CsRegistrarConfiguration | Where-Object {$_.MaxEndpointsPerUser -gt 8} | Set-CsRegistrarConfiguration -MaxEndpointsPerUser 8
  description: |-
    In Example 2, any Registrar configuration settings that allow users more than 8 endpoints are modified.
    To accomplish this, the command first calls the `Get-CsRegistrarConfiguration` cmdlet without any parameters; this returns a collection of all the Registrar configuration settings used in the organization.
    This collection is then piped to the `Where-Object` cmdlet, which picks out only those settings where the MaxEndpointsPerUser property is greater than (-gt) 8.
    Finally, the filtered collection is piped to the `Set-CsRegistrarConfiguration` cmdlet, which sets the maximum number of endpoints for each item in that collection to 8.
  summary: ""
- title: '-------------------------- Example 3 --------------------------'
  code: |-
    Get-CsRegistrarConfiguration -Filter "site:*"| Set-CsRegistrarConfiguration -EnableDHCPServer $False
  description: |-
    The command shown in Example 3 disables client registration via DHCP for each site in the organization that hosts a collection of Registrar configuration settings.
    To do this, the command calls the `Get-CsRegistrarConfiguration` cmdlet along with the Filter parameter; the parameter value "site:*" limits the returned data to settings that have been configured at the site scope.
    This collection is then piped to the `Set-CsRegistrarConfiguration` cmdlet, which uses the EnableDHCPServer parameter and the parameter value $False to prevent clients from using a DHCP server to locate a Registrar.
  summary: ""
parameters:
- type: <xref href="TimeSpan" data-throw-if-not-resolved="False" />
  name: BackupStoreUnavailableThreshold
  description: |+
    Specifies the amount of time the system will wait before determining that the backup store is unavailable; at that point, users will be placed in survivability mode.
    The default value is 30 minutes (00:30:00).

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: DefaultEndpointExpiration
  description: |+
    When endpoints log on they have the option of requesting an expiration timeout; this specifies the time interval that an endpoint can remain logged onto the system before it must contact the server and request an extension.
    The DefaultEndpointExpiration property represents the expiration timeout interval for clients that do not request a specific timeout value.

    The DefaultEndpointExpiration must be between 300 (5 minutes) and 900 (15 minutes).
    The default value is 600 (10 minutes).

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableDHCPServer
  description: |+
    Indicates whether endpoints can use DHCP servers to locate a Registrar.
    If True, clients will send a DHCP Inform message when they first start; the DHCP server will respond by sending the fully qualified domain name (FQDN) of a Registrar that can be used to log on the user.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableWinFabLogUpload
  description: |+
    PARAMVALUE: $true | $false

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error message that might occur when running the command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Unique identifier for the Registrar configuration settings to be modified.
    To modify the global settings, use this syntax:

    `-Identity global`

    To modify settings configured at the site scope, use syntax similar to this:

    `-Identity site:Redmond`

    To modify settings at the service level, use syntax like this:

    `-Identity service:Registrar:atl-cs-001.litwareinc.com`

    Note that Registrar settings can only be applied to the Registrar service.
    An error message will occur if you try to apply these settings to any other service.


  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PSObject" data-throw-if-not-resolved="False" />
  name: Instance
  description: |+
    Allows you to pass a reference to an object to the cmdlet rather than set individual parameter values.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: MaxEndpointExpiration
  description: |+
    When endpoints log on they have the option of requesting an expiration timeout; this specifies the time interval that an endpoint can remain logged onto the system before it must contact the server and request an extension.
    The MaxEndpointExpiration property represents the maximum amount of time that clients can be granted.
    For example, if the maximum time is set to 600 seconds and a client requests a timeout interval of 800 seconds, the client will be given the maximum allowed expiration period: 600 seconds.

    The MaxEndpointExpiration must be between 300 (5 minutes) and 900 (15 minutes).
    The default value is 900.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt16" data-throw-if-not-resolved="False" />
  name: MaxEndpointsPerUser
  description: |+
    Indicates the maximum number of endpoints a user can simultaneously have connected to the system.
    For example, a user who is logged on to Skype for Business Server with both a computer and a mobile phone would be using two endpoints.
    MaxEndPointsPerUser must be set to a value between 1 and 64, inclusive.
    The default value is 8.

    Although it is possible to allow a user as many as 64 endpoints, it is recommended that the maximum number of endpoints not exceed 8.
    Values of 9 or more are used for backwards compatibility and, in rare cases, when suggested by Microsoft support personnel.
    For new deployments, the maximum number of endpoints should be no more than 8.

    Note, too, that the maximum number of endpoints is intended to give individual users multiple points of presence.
    As such, this setting is designed for individual users and not for groups of users (such as an entire department.)


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt64" data-throw-if-not-resolved="False" />
  name: MaxUserCount
  description: |+
    Indicates the maximum number of users that can simultaneously be logged on to a Registrar.
    MaxUserCount can be set to any integer value between 2000 and 100000, inclusive.
    The default value is 12000.


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: MinEndpointExpiration
  description: |+
    When endpoints log on they have the option of requesting an expiration timeout; this specifies the time interval that an endpoint can remain logged onto the system before it must contact the server and request an extension.
    The MinEndpointExpiration property represents the minimum amount of time that clients can be granted.
    For example, if the minimum time is set to 600 seconds and a client requests a timeout interval of 200 seconds, the client will be given the minimum allowed expiration period: 600 seconds.

    The MinEndpointExpiration must be between 300 (5 minutes) and 900 (15 minutes).
    The default value is 300.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PoolState" data-throw-if-not-resolved="False" />
  name: PoolState
  description: |+
    Current state for the Registrar pool.
    Allowed values are:

    * Active
    * FailedOver
    * FailingOver
    * FailedBack

    The default value is Active.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt64" data-throw-if-not-resolved="False" />
  name: UserCertificateReplicationThreshold
  description: |+
    PARAMVALUE: UInt64

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: WinFabMaxLogsSizeMb
  description: |+
    PARAMVALUE: Int32

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Set-CsRegistrarConfiguration
name: Set-CsRegistrarConfiguration
description: |-
  The Registrar is perhaps the most important component in Skype for Business Server; after all, without a Registrar, users would not be able to log on to the system and Skype for Business Server would not be able to keep track of users and their current status.
  When a user logs on to Skype for Business Server, the endpoint the user is logging on from sends a REGISTER request to the Registrar; in turn, the server responds by challenging the client device for authentication credentials.
  If the client passes the challenge (that is, if the client presents a valid set of credentials), then the user is authenticated and endpoint information such as IP address, port, and user name is logged in the registration database.
  When a user logs off, this information is then removed from the database.
  In between log on and log off, the Registrar keeps status information up-to-date and helps to route messages to and from the user.

  Registrar configuration settings are used to help manage endpoints and endpoint subscriptions; these settings can be applied at the global, site, or service scope.
  (Service scoped-settings are only used with the Registrar service.) The `Set-CsRegistrarConfiguration` cmdlet can be used to modify any (or all) of the Registrar configuration collections currently in use in your organization.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/set-csregistrarconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Set-CsRegistrarConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
