### YamlMime:PowershellCmdlet
summary: |-
  Retrieves the backup service configuration settings for Skype for Business Server.
  These settings include information about the maximum number of simultaneous Windows Communication Framework calls that can be made to the backup service as well as the backup service synchronization interval.
  This cmdlet was introduced in Lync Server 2013.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The `Set-CsBackupServiceConfiguration` cmdlet accepts piped instances of the Microsoft.Rtc.Management.WritableConfig.Settings.BackupService.BackupServiceConfiguration object.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
    Instead, the `Set-CsBackupServiceConfiguration` cmdlet modifies existing instances of the Microsoft.Rtc.Management.WritableConfig.Settings.BackupService.BackupServiceConfiguration object.
links:
- text: Get-CsBackupServiceConfiguration
  href: Get-CsBackupServiceConfiguration.yml
- text: Remove-CsBackupServiceConfiguration
  href: Remove-CsBackupServiceConfiguration.yml
syntaxes:
- >-
  Set-CsBackupServiceConfiguration [[-Identity] <XdsIdentity>] [-AuthorizedLocalAccounts <String>]

   [-AuthorizedUniversalGroups <String>] [-Confirm] [-Force] [-MaxBatchesPerCmsSync <Int32>]

   [-MaxBatchesPerUserStoreSync <Int32>] [-MaxConcurrentCalls <Int32>] [-MaxDataConfPackageSizeKB <Int32>]

   [-SyncInterval <TimeSpan>] [-WhatIf] [-MaxHighPriQueuePercentagePerUserStoreSync <Int32>] [-EnableRgsBackupService <Boolean>]  [<CommonParameters>]
- >-
  Set-CsBackupServiceConfiguration [-AuthorizedLocalAccounts <String>] [-AuthorizedUniversalGroups <String>]

   [-Confirm] [-Force] [-Instance <PSObject>] [-MaxBatchesPerCmsSync <Int32>]

   [-MaxBatchesPerUserStoreSync <Int32>] [-MaxConcurrentCalls <Int32>] [-MaxDataConfPackageSizeKB <Int32>]

   [-SyncInterval <TimeSpan>] [-WhatIf] [-MaxHighPriQueuePercentagePerUserStoreSync <Int32>] [-EnableRgsBackupService <Boolean>] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Set-CsBackupServiceConfiguration -Identity "global" -AuthorizedUniversalGroups "Schema Admins"
  description: |-
    The command shown in Example 1 assigns the Active Directory security group Schema Admins to the AuthorizedUniversalGroups property for the global collection of backup service settings.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Set-CsBackupServiceConfiguration -Identity "global" -MaxConcurrentCalls 12
  description: |-
    In Example 2, the MaxConcurrentCalls property of the global collection of backup service settings is set to 12.
  summary: ""
- title: '-------------------------- Example 3 --------------------------'
  code: |-
    Set-CsBackupServiceConfiguration -Identity "global" -SyncInterval "00:10:00"
  description: |-
    Example 3 modifies the SyncInterval property of the global collection of backup service settings.
    In this example, SyncInterval is set to 10 minutes: 00 hours : 10 minutes : 00 seconds.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AuthorizedLocalAccounts
  description: |+
    Names of the local users/local groups that are authorized to run the backup service.
    The default value is Network Service.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AuthorizedUniversalGroups
  description: |+
    Names of the universal groups authorized to run the backup service.
    The default value is Schema admins.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableRgsBackupService
  description: |+
    Indicates whether the backup service for RGS has been enabled or not. If it is set to true RGSBackupService will start syncing RGS data on paired pools

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error message that might occur when running the command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Unique identifier for the backup service configuration settings.
    Because you can only have a single, global instance of these settings, you do not need to specify an Identity when calling the `Set-CsBackupServiceConfiguration` cmdlet.
    If you prefer, however, you can use the following syntax to reference the global settings:

    `-Identity global`


  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PSObject" data-throw-if-not-resolved="False" />
  name: Instance
  description: |+
    Allows you to pass a reference to an object to the cmdlet rather than set individual parameter values.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: MaxBatchesPerCmsSync
  description: |+
    Maximum number of batches that the CMS backup module will export during each export cycle.
    The default value is 500.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: MaxBatchesPerUserStoreSync
  description: |+
    Maximum number of batches that the User Store backup module will export during each export cycle.
    The default value is 500.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: MaxConcurrentCalls
  description: |+
    The maximum number of Windows Communication Foundation (WCF) calls that can be made to the backup service at the same time.
    The default value is 10.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: MaxDataConfPackageSizeKB
  description: |+
    Maximum size of the data package (in kilobytes) that the Data Conference module will export during each export cycle.
    The default value is 102400.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: MaxHighPriQueuePercentagePerUserStoreSync
  description: |+
    PARAMVALUE: Int32

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="TimeSpan" data-throw-if-not-resolved="False" />
  name: SyncInterval
  description: |+
    Specifies the amount of time that the service waits before synchronizing a pool with its backup pool.
    The default value is 2 minutes (00:02:00, or 00 hours, 02 minutes, 00 seconds).
    The SyncInterval can be configured to any value between 5 seconds (00:00:05) and 3 hours (03:00:00), inclusive.


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Set-CsBackupServiceConfiguration
name: Set-CsBackupServiceConfiguration
description: |-
  The backup service configuration settings are used to manage pool backups in Skype for Business Server.
  Note that Skype for Business Server allows only for a single, global collection of backup configuration settings.
  Among other things, that means that all your pools must be backed up using the same synchronization schedule and that users and groups authorized to backup Pool A are also allowed to backup Pools B, C, D and E.

  Skype for Business Server Control Panel: The functions carried out by the `Set-CsBackupServiceConfiguration` cmdlet are not available in the Skype for Business Server Control Panel.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/set-csbackupserviceconfiguration
  applicable: Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Set-CsBackupServiceConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
