### YamlMime:PowershellCmdlet
summary: |-
  Modifies a list of voice routes.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.Rtc.WritableConfig.Management.Policy.Voice.PSTNRoutingSettings object.
    Accepts pipelined input of a routing configuration object.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The `Set-CsRoutingConfiguration` cmdlet does not return a value or object.
    Instead, the cmdlet configures instances of the Microsoft.Rtc.Management.WritableConfig.Policy.Voice.PstnRoutingSettings object.
links:
- text: New-CsRoutingConfiguration
  href: New-CsRoutingConfiguration.yml
- text: Remove-CsRoutingConfiguration
  href: Remove-CsRoutingConfiguration.yml
- text: Get-CsRoutingConfiguration
  href: Get-CsRoutingConfiguration.yml
- text: Set-CsVoiceRoute
  href: Set-CsVoiceRoute.yml
- text: Get-CsVoiceRoute
  href: Get-CsVoiceRoute.yml
- text: New-CsCallViaWorkPolicy
  href: New-CsCallViaWorkPolicy.yml
syntaxes:
- >-
  Set-CsRoutingConfiguration [[-Identity] <XdsIdentity>] [-Route <PSListModifier>] [-Force] [-WhatIf] [-Confirm]

   [-CallViaWorkCallerId <String>] [-EnableLocationBasedRouting <Boolean>] [<CommonParameters>]
- >-
  Set-CsRoutingConfiguration [-Instance <PSObject>] [-Route <PSListModifier>] [-Force] [-WhatIf] [-Confirm]

   [-CallViaWorkCallerId <String>] [-EnableLocationBasedRouting <Boolean>] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    $a = Get-CsRoutingConfiguration

    $b = $a.Route | Where-Object {$_.Name -match "LocalRoute"}

    $b.SuppressCallerId = $False

    Set-CsRoutingConfiguration -Instance $a
  description: |-
    It takes several steps to modify a voice route within a routing configuration.
    In this example, we start by retrieving the routing configuration object by calling the `Get-CsRoutingConfiguration` cmdlet.
    We assign the object retrieved (there will be only one) to the variable $a.

    In line 2 of this example we retrieve the contents of the Route property from variable $a, which is a collection of voice route objects.
    We then pipe that collection to the `Where-Object` cmdlet, where we search the collection for all voice route objects with a Name matching the string LocalRoute.
    We assign that object to the variable $b.

    Next, we modify the LocalRoute voice route object by assigning the value $False to the property SuppressCallerId.
    By updating that object we've updated the object in variable $a.
    However, that object is still only in memory.
    As a final step, we need to save those changes by passing $a to the Instance parameter of the `Set-CsRoutingConfiguration` cmdlet.

    This is not the recommended way of modifying a routing configuration.
    To modify a routing configuration, simply change the individual voice routes with the `Set-CsVoiceRoute` cmdlet, as shown here:

    `Set-CsVoiceRoute -Identity LocalRoute -SuppressCallerId $False`

    That one line will accomplish the same task shown in Example 1.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: CallViaWorkCallerId
  description: |+
    The number the system will display for the callback portion of an external call.
    External calls first connect the user making the call by calling a specified number (typically the user's desk phone), once connected to the user, the system dials the outside number.
    The CallViaWorkCallerId parameter specifies the number that will be displayed during the first leg, or callback segment, of the call via work external call.
    For more information, see `New-CsCallViaWorkPolicy`.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableLocationBasedRouting
  description: |+
    When set to True, voice routing will be managed by taking into account the location of both the user placing the call and the user receiving the call.
    The default value is False.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses any confirmation prompts that would otherwise be displayed before making changes.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    The scope of the routing configuration.
    This must be Global.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PSObject" data-throw-if-not-resolved="False" />
  name: Instance
  description: |+
    A routing configuration (Microsoft.Rtc.Management.WritablConfig.Policy.Voice.PstnRoutingSettings) object.
    An object of this type can be retrieved by calling the `Get-CsRoutingConfiguration` cmdlet.


  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PSListModifier" data-throw-if-not-resolved="False" />
  name: Route
  description: |+
    A list of all voice routes (Microsoft.Rtc.Management.WritableConfig.Policy.Voice.Route objects) defined for the Skype for Business Server deployment.

    You should modify individual voice route objects by using the `Set-CsVoiceRoute` cmdlet.
    That is the recommended way of modifying routes in this list.


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Set-CsRoutingConfiguration
name: Set-CsRoutingConfiguration
description: |-
  Voice routes contain instructions that tell Skype for Business Server how to route calls from Enterprise Voice users to phone numbers on the public switched telephone network (PSTN) or a private branch exchange (PBX).
  With this cmdlet you can modify the settings of any voice route defined within a Skype for Business Server deployment.

  The use of this cmdlet is not recommended.
  To modify routing configurations, modify the individual voice routes by calling the `Set-CsVoiceRoute` cmdlet.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/set-csroutingconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Set-CsRoutingConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
