### YamlMime:PowershellCmdlet
summary: |-
  Modifies an existing collection of watcher node configuration settings.
  Watcher nodes are computers that periodically use Microsoft System Center Operations Manager and Skype for Business Server synthetic transactions to verify that Skype for Business Server components are working as expected.
  This cmdlet was introduced in Lync Server 2013.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The `Set-CsWatcherNodeConfiguration` cmdlet accepts pipelined instances of the Microsoft.Rtc.Management.WritableConfig.Settings.WatcherNode.TargetPool#Decorated object.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
    Instead, the `Set-CsWatcherNodeConfiguration` cmdlet modifies existing instances of the Microsoft.Rtc.Management.WritableConfig.Settings.WatcherNode.TargetPool#Decorated object.
links:
- text: Get-CsWatcherNodeConfiguration
  href: Get-CsWatcherNodeConfiguration.yml
- text: New-CsWatcherNodeConfiguration
  href: New-CsWatcherNodeConfiguration.yml
- text: Remove-CsWatcherNodeConfiguration
  href: Remove-CsWatcherNodeConfiguration.yml
- text: Test-CsWatcherNodeConfiguration
  href: Test-CsWatcherNodeConfiguration.yml
syntaxes:
- >-
  Set-CsWatcherNodeConfiguration [[-Identity] <XdsGlobalRelativeIdentity>] [-Confirm] [-Enabled <Boolean>]

   [-ExtendedTests <PSListModifier>] [-Force] [-PortNumber <UInt16>] [-Tests <PSListModifier>]

   [-TestUsers <PSListModifier>] [-UseInternalWebUrls <Boolean>] [-WhatIf]

   [-XmppTestReceiverMailAddress <String>] [-UseAutoDiscovery <Boolean>] [<CommonParameters>]
- >-
  Set-CsWatcherNodeConfiguration [-Confirm] [-Enabled <Boolean>] [-ExtendedTests <PSListModifier>] [-Force]

   [-Instance <PSObject>] [-PortNumber <UInt16>] [-Tests <PSListModifier>] [-TestUsers <PSListModifier>]

   [-UseInternalWebUrls <Boolean>] [-WhatIf] [-XmppTestReceiverMailAddress <String>]

   [-UseAutoDiscovery <Boolean>] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    $x = New-CsExtendedTest -TestUsers "sip:kenmyer@litwareinc.com", "sip:pilar@litwareinc.com" -Name "Audio Conferencing Test" -TestType "AudioConferencingProvider"

    Set-CsWatcherNodeConfiguration -Identity "atl-cs-001.litwareinc.com" -ExtendedTests @{Add=$x}
  description: |-
    The commands shown in Example 1 add a new audio conferencing provider test to the watcher node configuration settings applied to the pool `atl-cs-001.litwareinc.com`.
    To do this, the first command in the example uses the `New-CsExtendedTest` cmdlet to create the new test; this in-memory-only test is stored in a variable $x.
    In the second command, the `Set-CsWatcherNodeConfiguration` cmdlet adds the new test to the watcher node configuration settings; this is done by using the ExtendedTests parameter and the syntax `@{Add=$x}`.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    $x = Get-CsWatcherNodeConfiguration -Identity "atl-cs-001.litwareinc.com"

    $x.ExtendedTests.RemoveAt(0)

    Set-CsWatcherNodeConfiguration -Instance $x
  description: |-
    The commands in Example 2 show how you can remove an extended test from a collection of watcher node configuration settings.
    To carry out this task, the first command in the example uses the `Get-CsWatcherNodeConfiguration` cmdlet to return an object reference to the watcher node settings for the pool `atl-cs-001.litwareinc.com`; this object reference is stored in a variable named $x.

    In the second command, the RemoveAt() method is used to remove the first extended test in the object reference $x.
    Extended tests are stored as items in an array, with the first item being given the index number 0, the second item being given the index number 1, and so on.
    The syntax RemoveAt(0) removes the item with the index number 0: the first item in the set of extended tests.
    To remove the second extended test, use the syntax `RemoveAt(1)`.

    After the object reference has been updated, the final command uses the `Set-CsWatcherNodeConfiguration` cmdlet and the Instance parameter to write the changes made to the object reference back to the actual watcher node settings for the pool `atl-cs-001.litwareinc.com`.
  summary: ""
- title: '-------------------------- Example 3 --------------------------'
  code: |-
    Set-CsWatcherNodeConfiguration -Identity "atl-cs-001.litwareinc.com" -ExtendedTests $Null
  description: |-
    In Example 3, all the extended tests configured for the `atl-cs-001.litwareinc.com` watcher node are removed.
    This task is performed by including the ExtendedTests parameter and the parameter value $Null.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: Enabled
  description: |+
    Enables or disables the watcher node.
    The default value is True ($True).

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PSListModifier" data-throw-if-not-resolved="False" />
  name: ExtendedTests
  description: |+
    Object reference to one or more instances of the ExtendedTest object.
    These objects must be created using the `New-CsExtendedTest` cmdlet.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error message that might occur when running the command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsGlobalRelativeIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Fully qualified domain name of the pool associated with the watcher node configuration settings.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PSObject" data-throw-if-not-resolved="False" />
  name: Instance
  description: |+
    Allows you to pass a reference to an object to the cmdlet rather than set individual parameter values.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt16" data-throw-if-not-resolved="False" />
  name: PortNumber
  description: |+
    SIP port used by the Registrar service.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PSListModifier" data-throw-if-not-resolved="False" />
  name: Tests
  description: |+
    Synthetic transactions to be run by the watcher node.
    Allowed values are:

    Registration

    IM

    GroupIM

    P2PAV

    AvConference

    Presence

    ABS

    ABWQ

    MCXP2PIM

    ExumConnectivity

    JoinLauncher

    PersistentChatMessage

    DataConference

    XmppIM

    UnifiedContactStore

    AVEdgeConnectivity

    To enable additional tests for a watcher node use syntax similar to this:

    `-Tests @{Add="ExumConnectivity","JoinLauncher","UnifiedContactStore"}`

    To disable one or more tests from a watcher node use syntax like this:

    `-Tests @{Remove="ABS","ABWQ"}`

    To disable all the tests for a watcher node, set the value of the Tests parameter to $Null:

    `-Tests $Null`


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PSListModifier" data-throw-if-not-resolved="False" />
  name: TestUsers
  description: |+
    SIP addresses of the test users employed by the watcher node.
    To add additional test users to the node use syntax similar to this:

    `-TestUsers @{Add="sip:aidan@litwareinc.com"}`

    To remove a test user from the watcher node user syntax like this:

    `-TestUsers @{Remove="sip:aidan@litwareinc.com"`

    To replace an existing user with a new user, use the Replace method.
    For example, this syntax replaces the user sip:pilar@litwareinc.com with the new user sip:aidan@litwareinc.com:

    `-TestUsers @{Replace="sip:pilar@litwareinc.com","sip:aidan@litwareinc.com"}`

    You must always have at least two test users per watcher node.
    If you have two users and try to remove one of those users (ostensibly leaving the node with just one test user) your command will fail.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: UseAutoDiscovery
  description: |+
    When set to True ($True), watcher nodes will use the Autodiscover service locate the target pool.
    When set to False (the default value), watcher nodes will use the pool FQDN and SRV records to locate pools.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: UseInternalWebUrls
  description: |+
    When set to True ($True), instructs the watcher node to use the internal Web URLs rather than the external Web URLs.
    This provides a way to way to verify URL validity for users located behind the organization's firewall.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: XmppTestReceiverMailAddress
  description: |+
    XMPP email address to be used when testing the XMPP gateway.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Set-CsWatcherNodeConfiguration
name: Set-CsWatcherNodeConfiguration
description: |-
  If you are using Microsoft System Center Operations Manager to monitor Skype for Business Server then you have the option of setting up "watcher nodes": computers that periodically and automatically, run synthetic transactions in order to verify that Skype for Business Server is working as expected.
  Watcher nodes are assigned to pools, and are managed using the CsWatcherNodeConfiguration cmdlets.
  Note that you do not need to install watcher nodes if you are using System Center Operations Manager.
  You can still monitor your system without using watcher nodes; the only difference is that any synthetic transactions you want to run will need to be invoked manually rather than automatically invoked by Operations Manager.

  Skype for Business Server Control Panel: The functions carried out by the `Set-CsWatcherNodeConfiguration` cmdlet are not available in the Skype for Business Server Control Panel.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/set-cswatchernodeconfiguration
  applicable: Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Set-CsWatcherNodeConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
