### YamlMime:PowershellCmdlet
summary: |-
  Modifies an existing set of privacy configuration settings.
  Privacy configuration settings help determine how much information users make available to other users.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.Rtc.Management.WritableConfig.Settings.UserServices.PrivacyConfiguration object.
    The `Set-CsPrivacyConfiguration` cmdlet accepts pipelined input of the privacy configuration object.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The `Set-CsPrivacyConfiguration` cmdlet does not return any objects or values.
    Instead, the cmdlet modifies existing instances of the Microsoft.Rtc.Management.WritableConfig.Settings.UserServices.PrivacyConfiguration object.
links:
- text: Get-CsPrivacyConfiguration
  href: Get-CsPrivacyConfiguration.yml
- text: New-CsPrivacyConfiguration
  href: New-CsPrivacyConfiguration.yml
- text: Remove-CsPrivacyConfiguration
  href: Remove-CsPrivacyConfiguration.yml
syntaxes:
- >-
  Set-CsPrivacyConfiguration [-EnablePrivacyMode <Boolean>]

   [-AutoInitiateContacts <Boolean>] [-PublishLocationDataDefault <Boolean>]

   [-DisplayPublishedPhotoDefault <Boolean>] [[-Identity] <XdsIdentity>] [-Force] [-WhatIf] [-Confirm]

   [<CommonParameters>]
- >-
  Set-CsPrivacyConfiguration [-EnablePrivacyMode <Boolean>]

   [-AutoInitiateContacts <Boolean>] [-PublishLocationDataDefault <Boolean>]

   [-DisplayPublishedPhotoDefault <Boolean>] [-Instance <PSObject>] [-Force] [-WhatIf] [-Confirm]

   [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 ------------------------'
  code: |-
    Set-CsPrivacyConfiguration -Identity site:Redmond -EnablePrivacyMode $False -AutoInitiateContacts $True -PublishLocationDataDefault $True -DisplayPublishedPhotoDefault $True
  description: |-
    The command shown in Example 1 modifies three property values for the privacy configuration settings with the Identity site:Redmond.
    The three property values modified are AutoInitiateContacts, PublishLocationDataDefault and DisplayPublishedPhotoDefault.
  summary: ""
- title: '-------------------------- Example 2 ------------------------'
  code: |-
    Get-CsPrivacyConfiguration | Set-CsPrivacyConfiguration -EnablePrivacyMode $True
  description: |-
    Example 2 enables privacy mode for all the privacy configuration settings currently in use in the organization.
    To do this, the command first calls the `Get-CsPrivacyConfiguration` cmdlet without any parameters; this returns the complete collection of privacy settings.
    This collection is then piped to the `Set-CsPrivacyConfiguration` cmdlet, which takes each item in the collection and sets the EnablePrivacyMode property to True.
  summary: ""
- title: '-------------------------- Example 3 ------------------------'
  code: |-
    Get-CsPrivacyConfiguration | Where-Object {$_.EnablePrivacyMode -eq $False} | Set-CsPrivacyConfiguration -AutoInitiateContacts $True -PublishLocationDataDefault $True -DisplayPublishedPhotoDefault $True
  description: |-
    In Example 3, modifications are made to all the privacy configuration settings that are not currently using privacy mode.
    To carry out this task, the `Get-CsPrivacyConfiguration` cmdlet is first used in order to return a collection of all the privacy configuration settings.
    This collection is piped to the `Where-Object` cmdlet, which selects only those settings where the EnablePrivacyMode property is equal to False.
    The filtered collection is then piped to the `Set-CsPrivacyConfiguration` cmdlet, which assigns values to the AutoInitiateContacts, PublishLocationDataDefault, and DisplayPublishedPhotoDefault properties for each item in the collection.
  summary: ""
parameters:
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AutoInitiateContacts
  description: |+
    If True, Skype for Business will automatically add your manager and your direct reports to your Contacts list.
    The default value is True.


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Online
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.


  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Online
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: DisplayPublishedPhotoDefault
  description: |+
    If True, the user's photo will automatically be published in Skype for Business.
    If False, the user's photo will not be available unless he or she explicitly selects the option Let others see my photo.
    The default value is True.


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Online
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnablePrivacyMode
  description: |+
    If True, gives users the opportunity to enable the advanced privacy mode.
    In advanced privacy mode, only people on your Contacts list will be allowed to view your presence information.
    If False, your presence information will be available to anyone in your organization.
    The default value is False.

    For information about privacy mode in Microsoft Teams, see [User presence in Teams](/microsoftteams/presence-admins).

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Online
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error message that might occur when running the command.


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Online
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Unique identifier for the privacy configuration settings to be modified.
    To modify the global settings, use this syntax:

    `-Identity global`

    To modify settings configured at the site scope, use syntax similar to this:

    `-Identity site:Redmond`

    To modify settings at the service level, use syntax like this:

    `-Identity service:Redmond-UserServices-1`

    Note that privacy settings can only be applied to the User Server service.
    An error will occur if you try to apply these settings to any other service.

    If this parameter is not specified then the global settings will be updated when you call the `Set-CsPrivacyConfiguration` cmdlet.


  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Online
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PSObject" data-throw-if-not-resolved="False" />
  name: Instance
  description: |+
    Allows you to pass a reference to an object to the cmdlet rather than set individual parameter values.


  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Online
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: PublishLocationDataDefault
  description: |+
    If True, location data will automatically be published in Skype for Business.
    If False, location data will not be available unless the user explicitly selects the option Show Contacts My Location.
    The default value is True.


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Online
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.


  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Online
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Online
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Set-CsPrivacyConfiguration
name: Set-CsPrivacyConfiguration
description: |-
  Skype for Business Server gives users the opportunity to share a wealth of presence information with other people: they can publish a photograph of themselves; they can provide detailed location information; they can have presence information automatically made available to everyone in the organization (as opposed to having this information available only to people on their Contacts list).

  Some users will welcome the opportunity to make this information available to their colleagues; other users might be more reluctant to share this data.
  (For example, many people might be hesitant about having their photo included in their presence data.) As a general rule, users have control over what information they will (or will not) share; for example, users can select or clear a check box in order to control whether or not their location information is shared with others.
  In addition, the privacy configuration cmdlets enable administrators to manage privacy settings for their users.
  In some cases, administrators can enable or disable settings; for example, if the property AutoInitiateContacts is set to True, then team members will automatically be added to each user's Contacts list; if set to False, team members will not be automatically be added to each user's Contacts list.

  In other cases, administrators can configure the default values in Skype for Business while still giving users the right to change these values.
  For example, by default location data is published for users, although users do have the right to stop location publication.
  By setting the PublishLocationDataByDefault property to False, administrators can change this behavior: in that case, location data will not be published by default, although users will still have the right to publish this data if they choose.

  Privacy configuration settings can be applied at the global scope, the site scope, and at the service scope (albeit only for the User Server service).
  The `Set-CsPrivacyConfiguration` cmdlet enables you to modify any of the privacy configuration settings currently in use in your organization.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/set-csprivacyconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Online, Skype for Business Server 2015, Skype for Business Server 2019
  title: Set-CsPrivacyConfiguration
  schema: 2.0.0
  manager: bulenteg
  author: tomkau
  ms.author: tomkau
  ms.reviewer: rogupta
