### YamlMime:PowershellCmdlet
summary: |-
  Modifies an existing collection of call detail recording (CDR) settings.
  CDR enables you to track usage of such things as peer-to-peer instant messaging sessions, Voice over Internet Protocol (VoIP) phone calls and conferencing calls.
  This usage data includes information about who called whom, when they called and how long they talked.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Microsoft.Rtc.Management.WritableConfig.Settings.CallDetailRecording.CdrSettings.
    The `Set-CsCdrConfiguration` cmdlet accepts pipelined input of call detail recording configuration objects.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The `Set-CsCdrConfiguration` cmdlet does not return a value or object.
    Instead, the cmdlet configures instances of the Microsoft.Rtc.Management.WritableConfig.Settings.CallDetailRecording.CDRSettings object.
links:
- text: Get-CsCdrConfiguration
  href: Get-CsCdrConfiguration.yml
- text: New-CsCdrConfiguration
  href: New-CsCdrConfiguration.yml
- text: Remove-CsCdrConfiguration
  href: Remove-CsCdrConfiguration.yml
syntaxes:
- >-
  Set-CsCdrConfiguration [[-Identity] <XdsIdentity>] [-EnableCDR <Boolean>] [-EnablePurging <Boolean>]

   [-KeepCallDetailForDays <UInt32>] [-KeepErrorReportForDays <UInt32>] [-PurgeHourOfDay <UInt32>] 

   [-EnableUdcLite <Boolean>] [-Force] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Set-CsCdrConfiguration [-Instance <PSObject>] [-EnableCDR <Boolean>] [-EnablePurging <Boolean>]

   [-KeepCallDetailForDays <UInt32>] [-KeepErrorReportForDays <UInt32>] [-PurgeHourOfDay <UInt32>]

   [-EnableUdcLite <Boolean>] [-Force] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Set-CsCdrConfiguration -Identity site:Redmond -PurgeHourOfDay 23
  description: |-
    Example 1 sets the time of day for purging old records.
    In this case the time is set to 23 (11:00 P.M. on a 24-hour clock).
    The Identity parameter is used to ensure that these changes are only made to the CDR settings that have the Identity site:Redmond.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Get-CsCdrConfiguration | Set-CsCdrConfiguration -PurgeHourOfDay 23
  description: |-
    Example 2 is a variation of the command shown in Example 1.
    In this case, the PurgeHourOfDay property is modified for each collection of CDR configuration settings currently in use in the organization.
    To do this, the command first calls the `Get-CsCdrConfiguration` cmdlet without any parameters in order to return a collection of all the CDR settings currently in use.
    This collection is then piped to the `Set-CsCdrConfiguration` cmdlet, which takes each item in the collection and changes the value of the PurgeHourOfDay property to 11:00 PM (23).
  summary: ""
- title: '-------------------------- Example 3 --------------------------'
  code: |-
    Get-CsCdrConfiguration -Filter "site:*"| Set-CsCdrConfiguration -PurgeHourOfDay 23
  description: |-
    Another variation of the command used in Example 1 is shown in Example 3.
    In this example, the PurgeHourOfDay property is changed for all the CDR settings that have been configured at the site scope.
    To perform this task, the command first calls the `Get-CsCdrConfiguration` cmdlet along with the Filter parameter; the filter value "site:*" ensures that only CDR settings that have an Identity that begins with the string value "site:" will be returned.
    The filtered collection is then piped to the `Set-CsCdrConfiguration` cmdlet, which changes the PurgeHourOfDay property for each item in that collection.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableCDR
  description: |+
    Indicates whether or not CDR is enabled.
    The default value is True.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnablePurging
  description: |+
    Indicates whether or not CDR records will periodically be deleted from the CDR database.
    If True (the default value), records will be deleted after the time period specified by the properties KeepCallDetailForDays (for CDR records) and KeepErrorReportForDays (for CDR errors).
    If False, CDR records will be maintained indefinitely.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableUdcLite
  description: |+
    This parameter is reserved for internal Microsoft use.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error message that might occur when running the command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Unique identifier assigned to the collection of CDR configuration settings.
    To refer to the global settings, use this syntax: `-Identity global`.
    To refer to a collection configured at the site scope, use syntax similar to this: `-Identity site:Redmond`.
    Note that you cannot use wildcard characters when specifying an Identity.

    If this parameter is omitted then the `Set-CsCdrConfiguration` cmdlet will modify the global settings.


  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PSObject" data-throw-if-not-resolved="False" />
  name: Instance
  description: |+
    Allows you to pass a reference to an object to the cmdlet rather than set individual parameter values.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: KeepCallDetailForDays
  description: |+
    Indicates the number of days that CDR records will be kept in the CDR database; any records older than the specified number of days will automatically be deleted.
    (Note that purging will take only place if the EnablePurging property has been set to true.)

    You can set this property to any integer value between 1 and 2562 days (approximately 7 years).
    The default value is 60.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: KeepErrorReportForDays
  description: |+
    Indicates the number of days that CDR error reports are kept; any reports older than the specified number of days will automatically be deleted.
    CDR error reports are diagnostic reports uploaded by client applications such as Skype for Business.

    You can set this property to any integer value between 1 and 2562 days (approximately 7 years).
    The default value is 60.


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: PurgeHourOfDay
  description: |+
    Indicates the local time of day when expired records are deleted from the CDR database.
    The time of day is specified using a 24-hour clock, with 0 representing midnight (12:00 A.M.) and 23 representing 11:00 P.M.
    Note that you can only specify the hour of the day; that means that you can schedule purging to take place at 4:00 A.M., but you cannot schedule it to take place at 4:30 A.M.
    or 4:15 A.M..
    The default value is 2 (2:00 A.M.).
    It is recommended that purging take place during non-working hours.

    Database purging takes place only if the EnablePurging property is set to True.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Set-CsCdrConfiguration
name: Set-CsCdrConfiguration
description: |-
  Call detail recording (CDR) provides a way for you to track usage of Skype for Business Server capabilities such as Voice over Internet Protocol (VoIP) phone calls; instant messaging (IM); file transfers; audio/video (A/V) conferencing and application sharing sessions.
  CDR (which is available only if you have deployed the Monitoring service) keeps usage information: it logs information such as the parties involved in the call; the length of the call; and whether or not any files were transferred.
  However, CDR does not make a recording of the call itself.

  CDR also keeps track of call error information: detailed diagnostic data for both peer-to-peer sessions and for conferencing calls.

  As an administrator, you can determine whether or not CDR is used in your organization; assuming that the Monitoring Service has been deployed, you can easily enable or disable CDR.
  In addition, you can make this decision globally (in which case CDR will either be enabled or disabled throughout the organization) or on a site-by-site basis.
  For example, you could use CDR in the Redmond site but not use CDR in the Paris site.

  Administrators can also manage the CDR database; for example, you can specify the number of days CDR records are maintained before they are purged from that database.
  Changes such as these can be made by using the `Set-CsCdrConfiguration` cmdlet.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/set-cscdrconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Set-CsCdrConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
