### YamlMime:PowershellCmdlet
summary: |-
  You can use Set-CsSlaConfiguration to create a new Shared Line Appearance (SLA) group or modify an existing one. SLA is an Enterprise Voice user that is capable of receiving multiple calls at a time and forwarding them to its delegates, who answer the call. This cmdlet was introduced in Skype for Business Server 2015, November 2015 Cumulative Update.
module: SkypeForBusiness
notes: ""
links:
- text: Get-CsSlaConfiguration
  href: https://learn.microsoft.com/powershell/module/skype/get-csslaconfiguration?view=skype-ps
- text: Remove-CsSlaConfiguration
  href: https://learn.microsoft.com/powershell/module/skype/remove-csslaconfiguration?view=skype-ps
syntaxes:
- >-
  Set-CsSlaConfiguration [-BusyOption <SlaBusyOption>] [-Target <Uri>]

   [-MissedCallOption <SlaUserMissedCallOption>] [-MissedCallForwardTarget <Uri>] [-MaxNumberOfCalls <UInt32>]

   [-Identity] <UserIdParameter> [-PassThru] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    PS C:\> Set-CsSlaConfiguration -Identity SLAGroup1 -MaxNumberOfCalls 3 -BusyOption BusyOnBusy
  description: |-
    This example creates an SLA group for an existing Enterprise Voice user, SLAGroup1, and uses the number assigned for SLAGroup1 as the SLA mainline number. Also It sets the maximum number of concurrent calls for the new SLA group to 3, and for calls in excess of that to hear a busy signal.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    PS C:\> Set-CsSlaConfiguration -Identity SLAGroup1 -BusyOption Forward -Target tel:+2025551234
  description: |-
    This example sets calls that exceed the maximum number of concurrent calls to be forwarded to the telephone number 202-555-1234.
  summary: ""
- title: '-------------------------- Example 3 --------------------------'
  code: |-
    PS C:\> Set-CsSlaConfiguration -Identity SLAGroup1 -MissedCallOption Forward -MissedCallForwardTarget sip:sla_forward_number@contoso.com -BusyOption Forward -MaxNumberOfCalls 2 -Target sip:sla_forward_number@contoso.com
  description: |-
    This example specifies that missed calls to be forwarded to the user named sla_forward_number and calls that exceed the maximum number of concurrent calls to be forwarded to the same user.
  summary: ""
parameters:
- type: <xref href="SlaBusyOption" data-throw-if-not-resolved="False" />
  name: BusyOption
  description: |+
    Specifies the action to take when the SLA group exceeds the maximum number of simultaneous calls. Possible values are:
    * Forward
    * BusyOnBusy
    * Voicemail

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UserIdParameter" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Indicates the Identity of the SLA group to be created or modified. User Identities can be specified by using one of four formats: 1) the user's SIP address; 2) the user's user principal name (UPN); 3) the user's domain name and logon name, in the form domain\logon (for example, litwareinc\kenmyer); and, 4) the user's Active Directory display name (for example, Ken Myer). You can also reference a user account by using the Active Directory distinguished name.

    You can use the asterisk (\*) wildcard character when using the Display Name as the user Identity. For example, the Identity "\*Smith" returns all the users who have a display name that ends with the string value "Smith".

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: MaxNumberOfCalls
  description: |+
    Sets the maximum number of concurrent calls to be allowed in the SLA group.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Uri" data-throw-if-not-resolved="False" />
  name: MissedCallForwardTarget
  description: |+
    Specifies the sip address of a user account or a telephone number to forward the call when you select `Forward` in the `MissedCallOption` parameter. The target could be a user in your organization or a phone number following next syntax:
    * tel:\<PhoneNumber\>
    * sip:\<NameofDelegate@domain\>

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SlaUserMissedCallOption" data-throw-if-not-resolved="False" />
  name: MissedCallOption
  description: |+
    Specifies the action to take when the SLA group delegates do not answer a call. Possible values are:
    * Disconnect
    * Forward
    * BusySignal
    * Voicemail

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PassThru
  description: |+
    Enables you to pass a user object through the pipeline that represents the SLA group being created or modified. By default, the Set-CsSlaConfiguration cmdlet does not pass objects through the pipeline.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Uri" data-throw-if-not-resolved="False" />
  name: Target
  description: |+
    Specifies the sip address of a user account or a telephone number to forward the call when you select `Forward` in the `BusyOption` parameter. The target could be a user in your organization or a phone number following next syntax:
    * tel:\<PhoneNumber\>
    * sip:\<NameofDelegate@domain\>

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Set-CsSlaConfiguration
name: Set-CsSlaConfiguration
description: |-
  Shared Line Appearance (SLA) is a feature in Skype for Business (SfB) for handling multiple calls on a specific number called a shared number. SLA can configure any enterprise voice enabled SfB user as a shared number with multiple lines to respond to multiple calls. The calls are not actually received on the shared number, instead they are forwarded to users that act as delegates for the shared number. Any one of the delegates can pick up the call while the rest of the delegates get a notification on their phone about who picked up the call and which line has become busy as a result. Both the number of lines and the delegates are configurable for a shared number in SLA. In addition, advanced options such as BusyOption (what happens in a situation when all lines are busy) and MissedCallOption (the case in which none of the delegates pick up a call) etc. can also be configured for a shared number. 

  The Set-CsSlaConfiguration cmdlet modifies the properties of an SLA configuration.

  Note: Logging in with the account created for the SLA number is not supported. Using the SLA number account with any device or Desktop Client can result in unpredictable behavior. It is not necessary to use that account for the Shared Line Appearance feature to function. By default, members of the RTCUniversalServerAdmins group are authorized to run the Set-CsSlaConfiguration cmdlet. To return a list of all the role-based access control (RBAC) roles this cmdlet has been assigned to (including any custom RBAC roles you have created yourself), run the following command from the Windows PowerShell prompt:

  Get-CsAdminRole | Where-Object {$_.Cmdlets -match "Set-CsSlaConfiguration"}
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/set-csslaconfiguration
  applicable: Skype for Business Server 2015, Skype for Business Server 2019
  title: Set-CsSlaConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
