### YamlMime:PowershellCmdlet
summary: |-
  Modifies the reporting URL for an existing collection of reporting configuration settings.
  Reporting configuration settings are used to specify the URL used to access Skype for Business Server Monitoring Reports.
  This cmdlet was introduced in Lync Server 2013.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The `Set-CsReportingConfiguration` cmdlet accepts pipelined instances of the Microsoft.Rtc.Management.WritableConfig.Settings.Reporting.ReportingConfiguration object.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
    Instead, the `Set-CsReportingConfiguration` cmdlet modifies existing instances of the Microsoft.Rtc.Management.WritableConfig.Settings.Reporting.ReportingConfiguration object.
links:
- text: Get-CsReportingConfiguration
  href: Get-CsReportingConfiguration.yml
- text: New-CsReportingConfiguration
  href: New-CsReportingConfiguration.yml
- text: Remove-CsReportingConfiguration
  href: Remove-CsReportingConfiguration.yml
syntaxes:
- >-
  Set-CsReportingConfiguration [[-Identity] <XdsIdentity>] [-Confirm] [-Force] [-ReportingUrl <String>] [-WhatIf]

   [<CommonParameters>]
- >-
  Set-CsReportingConfiguration [-Confirm] [-Force] [-Instance <PSObject>] [-ReportingUrl <String>] [-WhatIf]

   [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Set-CsReportingConfiguration -Identity "service:MonitoringDatabase:atl-sql-002.litwareinc.com" -ReportingURL "https://atl-sql-002.litwareinc.com/lync_reports"
  description: |-
    The command shown in Example 1 modifies the reporting URL for the reporting configuration settings with the Identity service:MonitoringDatabase:atl-sql-002.litwareinc.com.
    In this example, the reporting URL is changed to `https://atl-sql-002.litwareinc.com/lync_reports`.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error message that might occur when running the command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Service Identity of the monitoring database whose reporting configuration settings are being modified.
    For example:

    `-Identity "Service:MonitoringDatabase:atl-sql-001.litwareinc.com"`

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PSObject" data-throw-if-not-resolved="False" />
  name: Instance
  description: |+
    Allows you to pass a reference to an object to the cmdlet rather than set individual parameter values.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ReportingUrl
  description: |+
    URL for the Skype for Business Server Monitoring Reports.


  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Set-CsReportingConfiguration
name: Set-CsReportingConfiguration
description: |-
  Reporting configuration settings are used to specify the home page for the Skype for Business Server Monitoring Reports; if you are not using Monitoring Reports then there is no reason for you to modify the reporting configuration settings.

  If you do not know the URL for the Monitoring Reports home page you can determine that URL by doing the following:

  Open the SQL Server Reporting Services Configuration Manager for the SQL Server instance that contains your monitoring database.

  In the Configuration Manager, click Report Manager URL and then click the URL for your Monitoring Reports.
  If you see two URLs, click the one that uses the https protocol.

  In SQL Server Reporting Services, click LyncServerReports.

  On the LyncServerReports page, click Reports Home Page.
  That will take you to the home page for the Monitoring Reports.
  You can then copy the URL and use that URL in conjunction with the CsReportingConfiguration cmdlets.

  Skype for Business Server Control Panel: The functions carried out by the `Set-CsReportingConfiguration` cmdlet are not available in the Skype for Business Server Control Panel.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/set-csreportingconfiguration
  applicable: Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Set-CsReportingConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
