### YamlMime:PowershellCmdlet
summary: |-
  Removes the Location Information Server (LIS) configuration from the Central Management store.
  This cmdlet was introduced in Lync Server 2010.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    This cmdlet does not return a value.
links:
- text: Debug-CsLisConfiguration
  href: Debug-CsLisConfiguration.yml
- text: Publish-CsLisConfiguration
  href: Publish-CsLisConfiguration.yml
- text: Import-CsLisConfiguration
  href: Import-CsLisConfiguration.yml
- text: Export-CsLisConfiguration
  href: Export-CsLisConfiguration.yml
- text: Test-CsLisConfiguration
  href: Test-CsLisConfiguration.yml
syntaxes:
- Unpublish-CsLisConfiguration [-Force] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: '-------------------------- EXAMPLE 1 --------------------------'
  code: |-
    Unpublish-CsLisConfiguration
  description: |-
    This command removes the LIS configuration from the Central Management store.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses any confirmation prompts that would otherwise be displayed before making changes.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2010
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2010
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Unpublish-CsLisConfiguration
name: Unpublish-CsLisConfiguration
description: |-
  In order to implement Enhanced 9-1-1 (E9-1-1) in Skype for Business Server, you must create a location mapping (called a wiremap).
  This mapping includes matching physical addresses to ports, subnets, switches, and wireless access points so emergency calls made over an Enterprise Voice connection will reach the nearest emergency operator and provide that operator with the correct location of the caller.
  This mapping configuration, created by calling cmdlets such as the `Set-CsLisPort` cmdlet and the `Set-CsLisSubnet` cmdlet, is stored in the location configuration database.
  A configuration can be committed from the location configuration database to the Central Management store by calling the `Publish-CsLisConfiguration` cmdlet, which allows for replication of the data to the Location Information Server.
  The `Unpublish-CsLisConfiguration` cmdlet removes the LIS configuration from the Central Management store.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/unpublish-cslisconfiguration
  applicable: Lync Server 2010, Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Unpublish-CsLisConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
