### YamlMime:PowershellCmdlet
summary: |-
  Clears environment-specific configurations from the local machine set by running Set-TeamsEnvironmentConfig.
module: MicrosoftTeamsPowerShell
notes: |-
  We do not recommend using Clear-TeamsEnvironmentConfig in Commercial, GCC, GCC High, or DoD environments. This cmdlet is available in Microsoft Teams PowerShell module from version 5.2.0-GA.
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- Clear-TeamsEnvironmentConfig [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> Clear-TeamsEnvironmentConfig
  description: |-
    Clears environment-specific configurations from the local machine set by running Set-TeamsEnvironmentConfig.
  summary: ""
uid: MicrosoftTeamsPowerShell.Clear-TeamsEnvironmentConfig
name: Clear-TeamsEnvironmentConfig
description: |-
  This cmdlet clears environment-specific configurations from the local machine set by running Set-TeamsEnvironmentConfig. This helps in clearing and rectifying any wrong information set in Set-TeamsEnvironmentConfig.
metadata:
  external help file: Microsoft.TeamsCmdlets.PowerShell.Connect.dll-Help.xml
  Module Name: MicrosoftTeams
  online version: ""
  schema: 2.0.0
  author: VikneshMSFT
  ms.author: vimohan
  ms.reviewer: pbafna
  manager: vinelap
