### YamlMime:PowershellCmdlet
summary: |-
  Returns information about the application instances of policy-based recording applications that have been configured for administering automatic policy-based recording in your tenant.
  Automatic policy-based recording is only applicable to Microsoft Teams users.
module: MicrosoftTeamsPowerShell
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-CsTeamsComplianceRecordingPolicy
  href: Get-CsTeamsComplianceRecordingPolicy.yml
- text: New-CsTeamsComplianceRecordingPolicy
  href: New-CsTeamsComplianceRecordingPolicy.yml
- text: Set-CsTeamsComplianceRecordingPolicy
  href: Set-CsTeamsComplianceRecordingPolicy.yml
- text: Grant-CsTeamsComplianceRecordingPolicy
  href: Grant-CsTeamsComplianceRecordingPolicy.yml
- text: Remove-CsTeamsComplianceRecordingPolicy
  href: Remove-CsTeamsComplianceRecordingPolicy.yml
- text: New-CsTeamsComplianceRecordingApplication
  href: New-CsTeamsComplianceRecordingApplication.yml
- text: Set-CsTeamsComplianceRecordingApplication
  href: Set-CsTeamsComplianceRecordingApplication.yml
- text: Remove-CsTeamsComplianceRecordingApplication
  href: Remove-CsTeamsComplianceRecordingApplication.yml
- text: New-CsTeamsComplianceRecordingPairedApplication
  href: New-CsTeamsComplianceRecordingPairedApplication.yml
syntaxes:
- >-
  Get-CsTeamsComplianceRecordingApplication [-Tenant <System.Guid>] [-Identity <XdsIdentity>]

   [-LocalStore] [<CommonParameters>]
- >-
  Get-CsTeamsComplianceRecordingApplication [-Tenant <System.Guid>] [-Filter <String>]

   [-LocalStore] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> Get-CsTeamsComplianceRecordingApplication
  description: |-
    The command shown in Example 1 returns information for all the application instances of policy-based recording applications associated with Teams recording policies.
  summary: ""
- title: Example 2
  code: |-
    PS C:\> Get-CsTeamsComplianceRecordingApplication -Identity 'Tag:ContosoPartnerComplianceRecordingPolicy/39dc3ede-c80e-4f19-9153-417a65a1f144'
  description: |-
    In Example 2, information is returned for a single application instance of a policy-based recording application with the Identity Tag:ContosoPartnerComplianceRecordingPolicy/39dc3ede-c80e-4f19-9153-417a65a1f144.
  summary: ""
- title: Example 3
  code: |-
    PS C:\> Get-CsTeamsComplianceRecordingApplication -Filter 'Tag:*'
  description: |-
    The command shown in Example 3 returns all the application instances associated with Teams recording policies at the per-user scope.
    To do this, the command uses the Filter parameter and the filter value "Tag:\*"; that filter value limits the returned data to policies that have an Identity that begins with the string value "Tag:".
  summary: ""
- title: Example 4
  code: |-
    PS C:\> Get-CsTeamsComplianceRecordingApplication -Filter 'Tag:ContosoPartnerComplianceRecordingPolicy*'
  description: |-
    The command shown in Example 4 returns all the application instances associated with Teams recording policy with Identity ContosoPartnerComplianceRecordingPolicy.
    To do this, the command uses the Filter parameter and the filter value "Tag:ContosoPartnerComplianceRecordingPolicy\*"; that filter value limits the returned data to policies that have an Identity that begins with the string value "Tag:ContosoPartnerComplianceRecordingPolicy".
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Enables you to use wildcards when retrieving one or more application instances of policy-based recording applications.
    For example, to return all the application instances associated with Teams recording policies at the per-user scope, use this syntax:

    -Filter "Tag:\*"

  defaultValue: None
  acceptWildcardCharacters: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Unique identifier of the application instance of a policy-based recording application to be retrieved.

    You cannot use wildcard characters when specifying the Identity.

    Note that application instances of policy-based recording applications must be associated with a Teams recording policy using the CsTeamsComplianceRecordingApplication cmdlets.
    Once the association is done, the Identity of these application instances becomes \<Identity of the associated Teams recording policy\>/\<ObjectId of the application instance\>.
    For example, the Identity of an application instance can be \"Tag:ContosoPartnerComplianceRecordingPolicy/39dc3ede-c80e-4f19-9153-417a65a1f144\", which indicates that the application instance with ObjectId 39dc3ede-c80e-4f19-9153-417a65a1f144 is associated with the Teams recording policy with Identity ContosoPartnerComplianceRecordingPolicy.

  defaultValue: None
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: LocalStore
  description: |+
    This parameter is reserved for internal Microsoft use.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Guid" data-throw-if-not-resolved="False" />
  name: Tenant
  description: |+
    Globally unique identifier (GUID) of the tenant account whose Teams recording policies are being queried.
    For example:

    -Tenant "38aad667-af54-4397-aaa7-e94c79ec2308"

    You can return your tenant ID by running this command:

    Get-CsTenant | Select-Object DisplayName, TenantID

    If you are using a remote session of Windows PowerShell and are connected only to Skype for Business Online you do not have to include the Tenant parameter.
    Instead, the tenant ID will automatically be filled in for you based on your connection information.
    The Tenant parameter is primarily for use in a hybrid deployment.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
applicable:
- Microsoft Teams
uid: MicrosoftTeamsPowerShell.Get-CsTeamsComplianceRecordingApplication
name: Get-CsTeamsComplianceRecordingApplication
description: |-
  Policy-based recording applications are used in automatic policy-based recording scenarios.
  When Microsoft Teams users participate in meetings or make or receive calls, the policy-based recording applications i.e. bots associated with the user's Teams recording policy are invited into the call or meeting to enforce compliance with the administrative set policy.

  Instances of these applications are created using CsOnlineApplicationInstance cmdlets and are then associated with Teams recording policies.

  Note that application instances of policy-based recording applications must be associated with a Teams recording policy using the CsTeamsComplianceRecordingApplication cmdlets.
  Once the association is done, the Identity of these application instances becomes \<Identity of the associated Teams recording policy\>/\<ObjectId of the application instance\>.
  For example, the Identity of an application instance can be \"Tag:ContosoPartnerComplianceRecordingPolicy/39dc3ede-c80e-4f19-9153-417a65a1f144\", which indicates that the application instance with ObjectId 39dc3ede-c80e-4f19-9153-417a65a1f144 is associated with the Teams recording policy with Identity ContosoPartnerComplianceRecordingPolicy.

  Note that if neither the Identity nor the Filter parameters are specified, then Get-CsTeamsComplianceRecordingApplication returns all application instances of policy-based recording applications that are associated with a Teams recording policy.

  Please work with your Microsoft certified policy-based recording application provider to obtain an instance of their recording application.
  Please refer to the documentation of the CsOnlineApplicationInstance cmdlets for information on how to create an application instance of a policy-based recording application.
  Please also refer to the documentation of CsTeamsComplianceRecordingPolicy cmdlets for further information.
metadata:
  external help file: Microsoft.Rtc.Management.Hosted.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/teams/get-csteamscompliancerecordingapplication
  applicable: Microsoft Teams
  title: Get-CsTeamsComplianceRecordingApplication
  schema: 2.0.0
  manager: nakumar
  author: aditdalvi
  ms.author: aditd
  ms.reviewer: ""
