### YamlMime:PowershellCmdlet
summary: |-
  This cmdlet fetches the first-party meeting templates stored on the tenant.
module: MicrosoftTeamsPowerShell
links:
- text: Get-CsTeamsMeetingTemplateConfiguration
  href: Get-CsTeamsMeetingTemplateConfiguration.yml
syntaxes:
- Get-CsTeamsFirstPartyMeetingTemplateConfiguration [[-Identity] <string>] [<CommonParameters>]
examples:
- title: Example 1 - Fetching all first party meeting templates on the tenant
  code: |-
    Get-CsTeamsFirstPartyMeetingTemplateConfiguration

    Identity              : Global
    TeamsMeetingTemplates : {default, firstparty_30d773c0-1b4e-4bf6-970b-73f544c054bb,
                            firstparty_399f69a3-c482-41bf-9cf7-fcdefe269ce6,
                            firstparty_64c92390-c8a2-471e-96d9-4ee8f6080155...}
    Description           : The `TeamsMeetingTemplates` property contains the meeting template details:


    TeamsMeetingOptions : {SelectedSensitivityLabel, AutoAdmittedUsers, AllowPstnUsersToBypassLobby,
                          EntryExitAnnouncementsEnabled...}
    Description         : Townhall
    Name                : firstparty_21f91ef7-6265-4064-b78b-41ab66889d90
    Category            :

    TeamsMeetingOptions : {AutoRecordingEnabled, AllowMeetingChat, PresenterOption}
    Description         : Virtual appointment
    Name                : firstparty_e514e598-fba6-4e1f-b8b3-138dd3bca748
    Category            :
  description: |-
    Fetches all the first-party templates on the tenant.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    This parameter can be used to fetch a specific instance of the configuration.

    Note: This configuration is read only and will only have the Global instance.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
uid: MicrosoftTeamsPowerShell.Get-CsTeamsFirstPartyMeetingTemplateConfiguration
name: Get-CsTeamsFirstPartyMeetingTemplateConfiguration
description: |-
  Fetches the list of first-party templates on the tenant. Each template object contains its list of meeting options, the name of the template, and its ID.

  This is a read-only configuration.
metadata:
  external help file: Microsoft.Teams.Policy.Administration.Cmdlets.Core.dll-Help.xml
  Module Name: MicrosoftTeams
  title: Get-CsTeamsFirstPartyMeetingTemplateConfiguration
  author: boboPD
  ms.author: pradas
  online version: https://learn.microsoft.com/powershell/module/teams/Get-CsTeamsFirstPartyMeetingTemplateConfiguration
  schema: 2.0.0
