### YamlMime:PowershellCmdlet
summary: |-
  Note: This cmdlet is deprecated as of our 1.0 PowerShell release, and is not supported in our 1.0 release.  To retrieve a Team's fun settings, run Get-Team.

  Gets a team's fun settings.
module: MicrosoftTeamsPowerShell
notes: ""
syntaxes:
- Get-TeamFunSettings -GroupId <String>
examples:
- title: '--------------------------  Example 1  --------------------------'
  code: |-
    Get-TeamFunSettings -GroupId 2f162b0e-36d2-4e15-8ba3-ba229cecdccf
  description: ""
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: GroupId
  isRequired: true
  description: |+
    GroupId of the team

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
applicable:
- Microsoft Teams
uid: MicrosoftTeamsPowerShell.Get-TeamFunSettings
name: Get-TeamFunSettings
description: ""
metadata:
  external help file: Microsoft.TeamsCmdlets.PowerShell.Custom.dll-Help.xml
  Module Name: MicrosoftTeams
  applicable: Microsoft Teams
  title: Get-TeamFunSettings
  online version: https://learn.microsoft.com/powershell/module/teams/get-teamfunsettings
  schema: 2.0.0
  author: serdarsoysal
  ms.author: serdars
  ms.reviewer: ""
