### YamlMime:PowershellCmdlet
summary: |-
  Designates what meeting features guests using Microsoft Teams will have available.
module: MicrosoftTeamsPowerShell
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Get-CsTeamsGuestMeetingConfiguration [-Tenant <Guid>] [[-Identity] <XdsIdentity>] [-LocalStore]

   [<CommonParameters>]
- >-
  Get-CsTeamsGuestMeetingConfiguration [-Tenant <Guid>] [-Filter <String>] [-LocalStore]

   [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    Get-CsTeamsGuestMeetingConfiguration
  description: |-
    Returns the TeamsGuestMeetingConfiguration set in your organization.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Internal Microsoft use.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    The only value accepted is Global

  defaultValue: None
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: LocalStore
  description: |+
    Internal Microsoft use

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Guid" data-throw-if-not-resolved="False" />
  name: Tenant
  description: |+
    Internal Microsoft use

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
applicable:
- Microsoft Teams
uid: MicrosoftTeamsPowerShell.Get-CsTeamsGuestMeetingConfiguration
name: Get-CsTeamsGuestMeetingConfiguration
description: |-
  The TeamsGuestMeetingConfiguration designates which meeting features guests leveraging Microsoft Teams will have available.  This configuration will apply to all guests utilizing Microsoft Teams.  Use the Get-CsTeamsGuestMeetingConfiguration cmdlet to return what values are set for your organization.
metadata:
  external help file: Microsoft.Rtc.Management.Hosted.dll-help.xml
  Module Name: MicrosoftTeams
  online version: https://learn.microsoft.com/powershell/module/teams/get-csteamsguestmeetingconfiguration
  applicable: Microsoft Teams
  title: Get-CsTeamsGuestMeetingConfiguration
  schema: 2.0.0
  manager: bulenteg
  author: tomkau
  ms.author: tomkau
  ms.reviewer: williamlooney
