### YamlMime:PowershellCmdlet
summary: |-
  Get-CsTeamsMeetingBroadcastConfiguration \[\[-Identity\] \<XdsIdentity\>\] \[-Tenant \<guid\>\] \[-ExposeSDNConfigurationJsonBlob \<bool\>\] \[-LocalStore\] \[\<CommonParameters\>\]

  Get-CsTeamsMeetingBroadcastConfiguration \[-Tenant \<guid\>\] \[-ExposeSDNConfigurationJsonBlob \<bool\>\] \[-Filter \<string\>\] \[-LocalStore\] \[\<CommonParameters\>\]
module: MicrosoftTeamsPowerShell
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Get-CsTeamsMeetingBroadcastConfiguration [-Tenant <Guid>] [-ExposeSDNConfigurationJsonBlob <Boolean>]

   [[-Identity] <XdsIdentity>] [-LocalStore] [<CommonParameters>]
- >-
  Get-CsTeamsMeetingBroadcastConfiguration [-Tenant <Guid>] [-ExposeSDNConfigurationJsonBlob <Boolean>]

   [-Filter <String>] [-LocalStore] [<CommonParameters>]
parameters:
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: ExposeSDNConfigurationJsonBlob
  description: |+
    Extract SDN properties as a Json Blob in get.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Not applicable to online service - you can only have one configuration.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    You can only have one configuration - "Global"

  defaultValue: None
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: LocalStore
  description: |+
    Not applicable to online service.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Guid" data-throw-if-not-resolved="False" />
  name: Tenant
  description: |+
    Not applicable to online service

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
applicable:
- Microsoft Teams
uid: MicrosoftTeamsPowerShell.Get-CsTeamsMeetingBroadcastConfiguration
name: Get-CsTeamsMeetingBroadcastConfiguration
description: |-
  Tenant level configuration for broadcast events in Teams
metadata:
  external help file: Microsoft.Rtc.Management.Hosted.dll-help.xml
  Module Name: MicrosoftTeams
  online version: https://learn.microsoft.com/powershell/module/teams/get-csteamsmeetingbroadcastconfiguration
  applicable: Microsoft Teams
  title: Get-CsTeamsMeetingBroadcastConfiguration
  schema: 2.0.0
  manager: bulenteg
  author: tomkau
  ms.author: tomkau
  ms.reviewer: williamlooney
