### YamlMime:PowershellCmdlet
summary: |-
  Assigns a per-user application access policy to one or more users. After assigning an application access policy to a user, the applications configured in the policy will be authorized to access online meetings on behalf of that user.
module: MicrosoftTeamsPowerShell
notes: ""
links:
- text: New-CsApplicationAccessPolicy
  href: New-CsApplicationAccessPolicy.yml
- text: Get-CsApplicationAccessPolicy
  href: Get-CsApplicationAccessPolicy.yml
- text: Set-CsApplicationAccessPolicy
  href: Set-CsApplicationAccessPolicy.yml
- text: Remove-CsApplicationAccessPolicy
  href: Remove-CsApplicationAccessPolicy.yml
syntaxes:
- Grant-CsApplicationAccessPolicy [-Identity <UserIdParameter>] [-PolicyName <String>] [-Global]
- >-
  Grant-CsApplicationAccessPolicy [-Global] [-PassThru] [-PolicyName <String>]

   [-MsftInternalProcessingMode <String>] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Grant-CsApplicationAccessPolicy [-PassThru] [-PolicyName <String>] [-MsftInternalProcessingMode <String>]

   -Group <String> [-Rank <Int32>] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: Assign an application access policy to a user
  code: |-
    PS C:\> Grant-CsApplicationAccessPolicy -Identity "dc17674c-81d9-4adb-bfb2-8f6a442e4624" -PolicyName "ASimplePolicy"
  description: |-
    The command shown above assigns the per-user application access policy "ASimplePolicy" to the user with object ID "dc17674c-81d9-4adb-bfb2-8f6a442e4624".
  summary: ""
- title: Unassign an application access policy from a user
  code: |-
    PS C:\> Grant-CsApplicationAccessPolicy -Identity "dc17674c-81d9-4adb-bfb2-8f6a442e4624" -PolicyName $Null
  description: |-
    In the command shown above, any per-user application access policy previously assigned to the user with user (object) ID "dc17674c-81d9-4adb-bfb2-8f6a442e4624" is unassigned from that user; as a result, applications configured in the policy can no longer access online meetings on behalf of that user. To unassign a per-user policy, set the PolicyName to a null value ($Null).
  summary: ""
- title: Assign an application access policy to all users in the tenant
  code: |-
    PS C:\> Get-CsOnlineUser | Grant-CsApplicationAccessPolicy -PolicyName "ASimplePolicy"
  description: |-
    The command shown above assigns the per-user application access policy ASimplePolicy to all the users in the tenant. To do this, the command first calls the `Get-CsOnlineUser` cmdlet to get all user accounts enabled for Microsoft Teams or Skype for Business Online. Those user accounts are then piped to the `Grant-CsApplicationAccessPolicy` cmdlet, which assigns each user the application access policy "ASimplePolicy".
  summary: ""
- title: Assign an application access policy to users who have not been assigned one
  code: |-
    PS C:\> Grant-CsApplicationAccessPolicy -PolicyName "ASimplePolicy" -Global
  description: |-
    The command shown above assigns the per-user application access policy "ASimplePolicy" to all the users in the tenant, except any that have an explicit policy assignment.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Global
  description: |+
    When you use this cmdlet without specifying a user identity, the policy applies to all users in your tenant, except any that have an explicit policy assignment. For example, if the user already have application access policy "A" assigned, and tenant admin assigns "B" globally, then application access policy "A" will take effect for the user.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Group
  isRequired: true
  description: |+
    Specifies the group used for the group policy assignment.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="UserIdParameter" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Indicates the user (object) ID of the user account to be assigned the per-user application access policy.

  defaultValue: None
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="PSListModifier" data-throw-if-not-resolved="False" />
  name: PolicyName
  description: |+
    Name of the policy to be assigned. The PolicyName is simply the policy Identity without the policy scope (the "tag:" prefix). For example, a policy with the Identity tag:ASimplePolicy has a PolicyName equal to ASimplePolicy.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: Rank
  description: |+
    The rank of the policy assignment, relative to other group policy assignments for the same policy type.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
applicable:
- Microsoft Teams
uid: MicrosoftTeamsPowerShell.Grant-CsApplicationAccessPolicy
name: Grant-CsApplicationAccessPolicy
description: |-
  This cmdlet assigns a per-user application access policy to one or more users. After assigning an application access policy to a user, the applications configured in the policy will be authorized to access online meetings on behalf of that user.**Note:** You can assign only 1 application access policy at a time to a particular user. Assigning a new application access policy to a user will override the existing application access policy if any.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/teams/grant-csapplicationaccesspolicy
  applicable: Microsoft Teams
  title: Grant-CsApplicationAccessPolicy
  schema: 2.0.0
  manager: zhengni
  author: frankpeng7
  ms.author: frpeng
  ms.reviewer: ""
