### YamlMime:PowershellCmdlet
summary: |-
  Assigns a per-user Teams voice applications policy to one or more users. TeamsVoiceApplications policy governs what permissions the supervisors/users have over auto attendants and call queues.
module: MicrosoftTeamsPowerShell
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-CsTeamsVoiceApplicationsPolicy
  href: Get-CsTeamsVoiceApplicationsPolicy.yml
- text: Set-CsTeamsVoiceApplicationsPolicy
  href: Set-CsTeamsVoiceApplicationsPolicy.yml
- text: Remove-CsTeamsVoiceApplicationsPolicy
  href: Remove-CsTeamsVoiceApplicationsPolicy.yml
- text: New-CsTeamsVoiceApplicationsPolicy
  href: New-CsTeamsVoiceApplicationsPolicy.yml
syntaxes:
- >-
  Grant-CsTeamsVoiceApplicationsPolicy [[-Identity] <String>] [-PassThru] [[-PolicyName] <String>]

   [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Grant-CsTeamsVoiceApplicationsPolicy [-PassThru] [[-PolicyName] <String>]

   [-Global] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Grant-CsTeamsVoiceApplicationsPolicy [-PassThru] [[-PolicyName] <String>]

   -Group <String> [-Rank <Int32>] [-WhatIf] [-Confirm]

   [<CommonParameters>]
examples:
- title: EXAMPLE 1
  code: |-
    Grant-CsTeamsVoiceApplicationsPolicy -Identity "Ken Myer" -PolicyName "SDA-Allow-All"
  description: |-
    The command shown in Example 1 assigns the per-user Teams voice applications policy SDA-Allow-All to the user with the display name "Ken Myer".
  summary: ""
- title: EXAMPLE 2
  code: |-
    Grant-CsTeamsVoiceApplicationsPolicy -PolicyName "SDA-Allow-All" -Global
  description: |-
    Example 2 assigns the per-user online voice routing policy "SDA-Allow-All to all the users in the tenant, except any that have an explicit policy assignment.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Global
  description: |+
    When you use this cmdlet without specifying a user identity, the policy applies to all users in your tenant, except any that have an explicit policy assignment. To skip a warning when you do this operation, specify this parameter.

  defaultValue: "False"
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Group
  isRequired: true
  description: |+
    Specifies the group used for the group policy assignment.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Indicates the Identity of the user account to be assigned the per-user Teams voice applications policy. User Identities can be specified using one of the following formats: the user's SIP address, the user's user principal name (UPN), or the user's Active Directory display name (for example, Ken Myer).

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PassThru
  description: |+
    Enables you to pass a user object through the pipeline that represents the user account being assigned the Teams voice applications policy. By default, the Grant-CsTeamsVoiceApplicationsPolicy cmdlet does not pass objects through the pipeline.

  defaultValue: "False"
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: PolicyName
  description: |+
    "Name" of the policy to be assigned. The PolicyName is simply the policy Identity minus the policy scope (the "tag:" prefix). For example, a policy with the Identity tag:Redmond has a PolicyName equal to Redmond; likewise, a policy with the Identity tag:SDAAllowAllTeamsVoiceApplicationsPolicy has a PolicyName equal to SDAAllowAllTeamsVoiceApplicationsPolicy.

    To unassign a per-user policy previously assigned to a user, set the PolicyName to a null value ($Null).

  defaultValue: None
  position: "2"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: Rank
  description: |+
    The rank of the policy assignment, relative to other group policy assignments for the same policy type.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: MicrosoftTeamsPowerShell.Grant-CsTeamsVoiceApplicationsPolicy
name: Grant-CsTeamsVoiceApplicationsPolicy
description: |-
  TeamsVoiceApplicationsPolicy is used for Supervisor Delegated Administration which allows tenant admins to permit certain users to make changes to auto attendant and call queue configurations.
metadata:
  external help file: MicrosoftTeams-help.xml
  Module Name: MicrosoftTeams
  online version: https://learn.microsoft.com/powershell/module/teams/grant-csteamsvoiceapplicationspolicy
  schema: 2.0.0
