### YamlMime:PowershellCmdlet
summary: |-
  Creates a new application access policy. Application access policy contains a list of application (client) IDs. When granted to a user, those applications will be authorized to access online meetings on behalf of that user.
module: MicrosoftTeamsPowerShell
notes: ""
links:
- text: Grant-CsApplicationAccessPolicy
  href: Grant-CsApplicationAccessPolicy.yml
- text: Get-CsApplicationAccessPolicy
  href: Get-CsApplicationAccessPolicy.yml
- text: Set-CsApplicationAccessPolicy
  href: Set-CsApplicationAccessPolicy.yml
- text: Remove-CsApplicationAccessPolicy
  href: Remove-CsApplicationAccessPolicy.yml
syntaxes:
- New-CsApplicationAccessPolicy [-Identity <XdsIdentity>] [-AppIds <PSListModifier>] [-Description <String>]
examples:
- title: Create a new application access policy with one app ID
  code: |-
    PS C:\> New-CsApplicationAccessPolicy -Identity "ASimplePolicy" -AppIds "d39597bf-8407-40ca-92ef-1ec26b885b7b" -Description "Some description"
  description: |-
    The command shown above shows how to create a new policy with one app IDs configured.
  summary: ""
- title: Create a new application access policy with multiple app IDs
  code: |-
    PS C:\> New-CsApplicationAccessPolicy -Identity "ASimplePolicy" -AppIds "d39597bf-8407-40ca-92ef-1ec26b885b71", "57caaef9-5ed0-48d5-8862-e5abfa71b3e1", "dc17674c-81d9-4adb-bfb2-8f6a442e4620" -Description "Some description"
  description: |-
    The command shown above shows how to create a new policy with a list of (three) app IDs configured.
  summary: ""
parameters:
- type: <xref href="PSListModifier" data-throw-if-not-resolved="False" />
  name: AppIds
  description: |+
    A list of application (client) IDs. For details of application (client) ID, refer to: [Get tenant and app ID values for signing in](https://learn.microsoft.com/azure/active-directory/develop/howto-create-service-principal-portal#get-tenant-and-app-id-values-for-signing-in).

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Description
  description: |+
    Specifies the description of the policy.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Unique identifier assigned to the policy when it was created.

  defaultValue: None
  position: "1"
  aliases: ""
  parameterValueGroup: ""
applicable:
- Microsoft Teams
uid: MicrosoftTeamsPowerShell.New-CsApplicationAccessPolicy
name: New-CsApplicationAccessPolicy
description: |-
  This cmdlet creates a new application access policy. Application access policy contains a list of application (client) IDs. When granted to a user, those applications will be authorized to access online meetings on behalf of that user.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/teams/new-csapplicationaccesspolicy
  applicable: Microsoft Teams
  title: New-CsApplicationAccessPolicy
  schema: 2.0.0
  manager: zhengni
  author: frankpeng7
  ms.author: frpeng
  ms.reviewer: ""
