### YamlMime:PowershellCmdlet
summary: |-
  Use the `Remove-CsOnlineDialInConferencingTenantSettings` cmdlet to revert the tenant level dial-in conferencing settings to their original defaults.
module: MicrosoftTeamsPowerShell
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None
syntaxes:
- >-
  Remove-CsOnlineDialInConferencingTenantSettings [-Tenant <Guid>] [-Identity] <XdsIdentity> [-Force]

   [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Remove-CsOnlineDialInConferencingTenantSettings
  description: |-
    This example reverts the tenant level dial-in conferencing settings to their original defaults.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    The Confirm switch causes the command to pause processing and requires confirmation to proceed.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    The Force switch specifies whether to suppress warning and confirmation messages.
    It can be useful in scripting to suppress interactive prompts.
    If the Force switch isn't provided in the command, you're prompted for administrative input if required.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    This parameter is reserved for internal Microsoft use.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
- type: <xref href="Guid" data-throw-if-not-resolved="False" />
  name: Tenant
  description: |+
    This parameter is reserved for internal Microsoft use.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    The WhatIf switch causes the command to simulate its results.
    By using this switch, you can view what changes would occur without having to commit those changes.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
applicable:
- Microsoft Teams
uid: MicrosoftTeamsPowerShell.Remove-CsOnlineDialInConferencingTenantSettings
name: Remove-CsOnlineDialInConferencingTenantSettings
description: |-
  There is always a single instance of the dial-in conferencing settings per tenant.
  You can modify the settings using `Set-CsOnlineDialInConferencingTenantSettings` and revert those settings to their defaults by using `Remove-CsOnlineDialInConferencingTenantSettings`.
metadata:
  external help file: Microsoft.Rtc.Management.Hosted.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/teams/remove-csonlinedialinconferencingtenantsettings
  applicable: Microsoft Teams
  title: Remove-CsOnlineDialInConferencingTenantSettings
  schema: 2.0.0
  manager: bulenteg
  author: tomkau
  ms.author: tomkau
  ms.reviewer: williamlooney
