### YamlMime:PowershellCmdlet
summary: |-
  Note: This cmdlet is deprecated as of our 1.0 PowerShell release, and is not supported in our 1.0 release.  To set a Team's settings, run Set-Team.

  Update Giphy, Stickers and Memes settings.
module: MicrosoftTeamsPowerShell
notes: ""
inputs:
- name: <xref href="GroupId, AllowGiphy, GiphyContentRating, AllowStickersAndMemes, AllowCustomMemes" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Set-TeamFunSettings -GroupId <String> [-AllowGiphy <String>] [-GiphyContentRating <String>]

   [-AllowStickersAndMemes <String>] [-AllowCustomMemes <String>]
examples:
- title: '--------------------------  Example 1  --------------------------'
  code: |-
    Set-TeamFunSettings -GroupId 0ebb500c-f5f3-44dd-b155-cc8c4f383e2d -AllowGiphy true -GiphyContentRating Strict
  description: ""
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AllowCustomMemes
  description: |+
    Allow custom memes to be uploaded

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AllowGiphy
  description: |+
    Setting to enable giphy for team

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AllowStickersAndMemes
  description: |+
    Enable Stickers and memes

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: GiphyContentRating
  description: |+
    Settings to set content rating for giphy.
    Can be "Strict" or "Moderate"

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: GroupId
  isRequired: true
  description: |+
    GroupId of the team

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
applicable:
- Microsoft Teams
uid: MicrosoftTeamsPowerShell.Set-TeamFunSettings
name: Set-TeamFunSettings
description: ""
metadata:
  external help file: Microsoft.TeamsCmdlets.PowerShell.Custom.dll-Help.xml
  Module Name: MicrosoftTeams
  applicable: Microsoft Teams
  title: Set-TeamFunSettings
  online version: https://learn.microsoft.com/powershell/module/teams/set-teamfunsettings
  schema: 2.0.0
  author: serdarsoysal
  ms.author: serdars
  ms.reviewer: ""
