### YamlMime:PowershellCmdlet
summary: |-
  Note: This cmdlet is deprecated as of our 1.0 PowerShell release, and is not supported in our 1.0 release.  To set a Team's settings, run Set-Team.

  Updates team messaging settings.
module: MicrosoftTeamsPowerShell
notes: ""
inputs:
- name: <xref href="GroupId" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="AllowUserEditMessages" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="AllowUserDeleteMessages" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="AllowOwnerDeleteMessages" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="AllowTeamMentions" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="AllowChannelMentions" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Set-TeamMessagingSettings -GroupId <String> [-AllowUserEditMessages <String>]

   [-AllowUserDeleteMessages <String>] [-AllowOwnerDeleteMessages <String>] [-AllowTeamMentions <String>]

   [-AllowChannelMentions <String>]
examples:
- title: '--------------------------  Example 1  --------------------------'
  code: |-
    Set-TeamMessagingSettings -GroupId 4ba546e6-e28d-4645-8cc1-d3575ef9d266 -AllowUserEditMessages true
  description: ""
  summary: ""
- title: '--------------------------  Example 2  --------------------------'
  code: |-
    Set-TeamMessagingSettings -GroupId 4ba546e6-e28d-4645-8cc1-d3575ef9d266 -AllowUserDeleteMessages false -AllowChannelMentions true
  description: ""
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AllowChannelMentions
  description: |+
    Allow @channel or @\[channel name\] mentions.
    This wil notify members who've favorited that channel

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AllowOwnerDeleteMessages
  description: |+
    Setting to allow owner to Delete messages

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AllowTeamMentions
  description: |+
    Allow @team or @\[team name\] mentions.
    This will notify everyone in the team

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AllowUserDeleteMessages
  description: |+
    Setting to allow user to delete messages

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AllowUserEditMessages
  description: |+
    Setting to allow user to edit messages

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: GroupId
  isRequired: true
  description: |+
    GroupId of the team

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
applicable:
- Microsoft Teams
uid: MicrosoftTeamsPowerShell.Set-TeamMessagingSettings
name: Set-TeamMessagingSettings
description: ""
metadata:
  external help file: Microsoft.TeamsCmdlets.PowerShell.Custom.dll-Help.xml
  Module Name: MicrosoftTeams
  applicable: Microsoft Teams
  title: Set-TeamMessagingSettings
  online version: https://learn.microsoft.com/powershell/module/teams/set-teammessagingsettings
  schema: 2.0.0
  author: serdarsoysal
  ms.author: serdars
  ms.reviewer: ""
