### YamlMime:PowershellCmdlet
summary: |-
  Modifies an existing association between an application instance of a policy-based recording application and a Teams recording policy for administering automatic policy-based recording in your tenant.
  Automatic policy-based recording is only applicable to Microsoft Teams users.
module: MicrosoftTeamsPowerShell
inputs:
- name: <xref href="System.Management.Automation.PSObject" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-CsTeamsComplianceRecordingPolicy
  href: Get-CsTeamsComplianceRecordingPolicy.yml
- text: New-CsTeamsComplianceRecordingPolicy
  href: New-CsTeamsComplianceRecordingPolicy.yml
- text: Set-CsTeamsComplianceRecordingPolicy
  href: Set-CsTeamsComplianceRecordingPolicy.yml
- text: Grant-CsTeamsComplianceRecordingPolicy
  href: Grant-CsTeamsComplianceRecordingPolicy.yml
- text: Remove-CsTeamsComplianceRecordingPolicy
  href: Remove-CsTeamsComplianceRecordingPolicy.yml
- text: Get-CsTeamsComplianceRecordingApplication
  href: Get-CsTeamsComplianceRecordingApplication.yml
- text: New-CsTeamsComplianceRecordingApplication
  href: New-CsTeamsComplianceRecordingApplication.yml
- text: Remove-CsTeamsComplianceRecordingApplication
  href: Remove-CsTeamsComplianceRecordingApplication.yml
- text: New-CsTeamsComplianceRecordingPairedApplication
  href: New-CsTeamsComplianceRecordingPairedApplication.yml
syntaxes:
- >-
  Set-CsTeamsComplianceRecordingApplication [-Tenant <System.Guid>] [-Identity <XdsIdentity>]

   [-RequiredBeforeMeetingJoin <Boolean>] [-RequiredDuringMeeting <Boolean>]

   [-RequiredBeforeCallEstablishment <Boolean>] [-RequiredDuringCall <Boolean>]

   [-ConcurrentInvitationCount <UInt32>] [-ComplianceRecordingPairedApplications <ComplianceRecordingPairedApplication[]>]

   [-Priority <Int32>] [-Force] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Set-CsTeamsComplianceRecordingApplication [-Tenant <System.Guid>] [-Instance <PSObject>]

   [-RequiredBeforeMeetingJoin <Boolean>] [-RequiredDuringMeeting <Boolean>]

   [-RequiredBeforeCallEstablishment <Boolean>] [-RequiredDuringCall <Boolean>]

   [-ConcurrentInvitationCount <UInt32>] [-ComplianceRecordingPairedApplications <ComplianceRecordingPairedApplication[]>]

   [-Priority <Int32>] [-Force] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> Set-CsTeamsComplianceRecordingApplication -Identity 'Tag:ContosoPartnerComplianceRecordingPolicy/d93fefc7-93cc-4d44-9a5d-344b0fff2899' -RequiredBeforeMeetingJoin $false -RequiredDuringMeeting $false
  description: |-
    The command shown in Example 1 modifies an existing association between an application instance of a policy-based recording application with ObjectId d93fefc7-93cc-4d44-9a5d-344b0fff2899 and a Teams recording policy with the Identity ContosoPartnerComplianceRecordingPolicy.

    In this example, the application is made optional for meetings.
    Please refer to the documentation of the RequiredBeforeMeetingJoin and RequiredDuringMeeting parameters for more information.
  summary: ""
- title: Example 2
  code: |-
    PS C:\> Set-CsTeamsComplianceRecordingApplication -Identity 'Tag:ContosoPartnerComplianceRecordingPolicy/d93fefc7-93cc-4d44-9a5d-344b0fff2899' -RequiredBeforeCallEstablishment $false -RequiredDuringCall $false
  description: |-
    The command shown in Example 2 modifies an existing association between an application instance of a policy-based recording application with ObjectId d93fefc7-93cc-4d44-9a5d-344b0fff2899 and a Teams recording policy with the Identity ContosoPartnerComplianceRecordingPolicy.

    In this example, the application is made optional for calls.
    Please refer to the documentation of the RequiredBeforeCallEstablishment and RequiredDuringCall parameters for more information.
  summary: ""
- title: Example 3
  code: |-
    PS C:\> Set-CsTeamsComplianceRecordingApplication -Identity 'Tag:ContosoPartnerComplianceRecordingPolicy/d93fefc7-93cc-4d44-9a5d-344b0fff2899' -ConcurrentInvitationCount 2
  description: |-
    The command shown in Example 3 modifies an existing association between an application instance of a policy-based recording application with ObjectId d93fefc7-93cc-4d44-9a5d-344b0fff2899 and a Teams recording policy with the Identity ContosoPartnerComplianceRecordingPolicy.

    In this example, the application is made resilient by specifying that two invites must be sent to the same application for the same call or meeting.
    Please refer to the documentation of the ConcurrentInvitationCount parameter for more information.
  summary: ""
- title: Example 4
  code: |-
    PS C:\> Set-CsTeamsComplianceRecordingApplication -Identity 'Tag:ContosoPartnerComplianceRecordingPolicy/d93fefc7-93cc-4d44-9a5d-344b0fff2899' -ComplianceRecordingPairedApplications @(New-CsTeamsComplianceRecordingPairedApplication -Id '39dc3ede-c80e-4f19-9153-417a65a1f144')
  description: |-
    The command shown in Example 4 modifies an existing association between an application instance of a policy-based recording application with ObjectId d93fefc7-93cc-4d44-9a5d-344b0fff2899 and a Teams recording policy with the Identity ContosoPartnerComplianceRecordingPolicy.

    In this example, the application is made resilient by pairing it with another application instance of a policy-based recording application with ObjectId 39dc3ede-c80e-4f19-9153-417a65a1f144.
    Separate invites are sent to the paired applications for the same call or meeting.
    Please refer to the documentation of the ComplianceRecordingPairedApplications parameter for more information.
  summary: ""
- title: Example 5
  code: |-
    PS C:\> Set-CsTeamsComplianceRecordingApplication -Identity 'Tag:ContosoPartnerComplianceRecordingPolicy/d93fefc7-93cc-4d44-9a5d-344b0fff2899' -ComplianceRecordingPairedApplications $null
  description: |-
    The command shown in Example 5 modifies an existing association between an application instance of a policy-based recording application with ObjectId d93fefc7-93cc-4d44-9a5d-344b0fff2899 and a Teams recording policy with the Identity ContosoPartnerComplianceRecordingPolicy.

    In this example, the application's resiliency is removed by removing the pairing it had with the application instance of a policy-based recording application with ObjectId 39dc3ede-c80e-4f19-9153-417a65a1f144.
    Please refer to the documentation of the ComplianceRecordingPairedApplications parameter for more information.
  summary: ""
- title: Example 6
  code: |-
    PS C:\> Get-CsTeamsComplianceRecordingApplication | Set-CsTeamsComplianceRecordingApplication -RequiredBeforeMeetingJoin $false -RequiredDuringMeeting $false
  description: |-
    The command shown in Example 6 modifies all existing associations between application instances of policy-based recording applications and their corresponding Teams recording policy.

    In this example, all applications are made optional for meetings.
    Please refer to the documentation of the RequiredBeforeMeetingJoin and RequiredDuringMeeting parameters for more information.
  summary: ""
parameters:
- type: <xref href="ComplianceRecordingPairedApplication" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: ComplianceRecordingPairedApplications
  description: |+
    Determines the other policy-based recording applications to pair with this application to achieve application resiliency. Can only have one paired application.

    In situations where application resiliency is a necessity, invites can be sent to separate paired applications for the same call or meeting.
    If multiple such invites are accepted, then it means that multiple instances of this application are in the call or meeting and each of those instances can record independent of the others.

    If all of the invites are rejected, the application invitation process is deemed a failure and the other flags for this application control what happens next.
    Please refer to the documentation of the RequiredBeforeMeetingJoin and RequiredBeforeCallEstablishment parameters.

    If at least one of the invites is accepted and the others are rejected, the application invitation process is still deemed a success.

    If multiple invites are accepted and all of the instances leave or get dropped from the call or meeting, then the application is no longer in the call or meeting and the other flags for this application control what happens next.
    Please refer to the documentation of the RequiredDuringMeeting and RequiredDuringCall parameters.

    If multiple invites are accepted and at least one of the instances remains in the call or meeting, then the application is in the call or meeting.

    Note that application resiliency can be achieved either by sending multiple invites to the same application using ConcurrentInvitationCount or by sending invites to separate paired applications using ComplianceRecordingPairedApplications.
    However, you cannot do both.
    Please work with your Microsoft certified policy-based recording application provider to determine if application resiliency is needed for your workflows and how best to achieve application resiliency.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: ConcurrentInvitationCount
  description: |+
    Determines the number of invites to send out to the application instance of the policy-based recording application. Can be set to 1 or 2 only. 

    In situations where application resiliency is a necessity, multiple invites can be sent to the same application for the same call or meeting.
    If multiple such invites are accepted, then it means that multiple instances of this application are in the call or meeting and each of those instances can record independent of the others.

    If all of the invites are rejected, the application invitation process is deemed a failure and the other flags for this application control what happens next.
    Please refer to the documentation of the RequiredBeforeMeetingJoin and RequiredBeforeCallEstablishment parameters.

    If at least one of the invites is accepted and the others are rejected, the application invitation process is still deemed a success.

    If multiple invites are accepted and all of the instances leave or get dropped from the call or meeting, then the application is no longer in the call or meeting and the other flags for this application control what happens next.
    Please refer to the documentation of the RequiredDuringMeeting and RequiredDuringCall parameters.

    If multiple invites are accepted and at least one of the instances remains in the call or meeting, then the application is in the call or meeting.

    Note that application resiliency can be achieved either by sending multiple invites to the same application using ConcurrentInvitationCount or by sending invites to separate paired applications using ComplianceRecordingPairedApplications.
    However, you cannot do both.
    Please work with your Microsoft certified policy-based recording application provider to determine if application resiliency is needed for your workflows and how best to achieve application resiliency.

  defaultValue: "1"
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error message that might arise when running the command.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    A name that uniquely identifies the application instance of the policy-based recording application.

    Application instances of policy-based recording applications must be associated with a Teams recording policy using the CsTeamsComplianceRecordingApplication cmdlets.
    To do this association correctly, the Identity of these application instances must be \<Identity of the associated Teams recording policy\>/\<ObjectId of the application instance\>.
    For example, the Identity of an application instance can be \"Tag:ContosoPartnerComplianceRecordingPolicy/39dc3ede-c80e-4f19-9153-417a65a1f144\", which indicates that the application instance with ObjectId 39dc3ede-c80e-4f19-9153-417a65a1f144 is associated with the Teams recording policy with Identity ContosoPartnerComplianceRecordingPolicy.

  defaultValue: None
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="PSObject" data-throw-if-not-resolved="False" />
  name: Instance
  description: |+
    Allows you to pass a reference to an object to the cmdlet rather than set individual parameter values.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: Priority
  description: |+
    This priority determines the order in which the policy-based recording applications are displayed in the output of the Get-CsTeamsComplianceRecordingPolicy cmdlet.

    All policy-based recording applications are invited in parallel to ensure low call setup and meeting join latencies.
    So this parameter does not affect the order of invitations to the applications, or any other routing.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: RequiredBeforeCallEstablishment
  description: |+
    Indicates whether the policy-based recording application must be in the call before the call is allowed to establish.

    If this is set to True, the call will be cancelled if the policy-based recording application fails to join the call.

    If this is set to False, call establishment will proceed normally if the policy-based recording application fails to join the call.

  defaultValue: "True"
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: RequiredBeforeMeetingJoin
  description: |+
    Indicates whether the policy-based recording application must be in the meeting before the user is allowed to join the meeting.

    If this is set to True, the user will not be allowed to join the meeting if the policy-based recording application fails to join the meeting.
    The meeting will still continue for users who are in the meeting.

    If this is set to False, the user will be allowed to join the meeting even if the policy-based recording application fails to join the meeting.

  defaultValue: "True"
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: RequiredDuringCall
  description: |+
    Indicates whether the policy-based recording application must be in the call while the call is active.

    If this is set to True, the call will be cancelled if the policy-based recording application leaves the call or is dropped from the call.

    If this is set to False, call establishment will proceed normally if the policy-based recording application leaves the call or is dropped from the call.

  defaultValue: "True"
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: RequiredDuringMeeting
  description: |+
    Indicates whether the policy-based recording application must be in the meeting while the user is in the meeting.

    If this is set to True, the user will be ejected from the meeting if the policy-based recording application leaves the meeting or is dropped from the meeting.
    The meeting will still continue for users who are in the meeting.

    If this is set to False, the user will not be ejected from the meeting if the policy-based recording application leaves the meeting or is dropped from the meeting.

  defaultValue: "True"
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Guid" data-throw-if-not-resolved="False" />
  name: Tenant
  description: |+
    Globally unique identifier (GUID) of the tenant account whose Teams recording policies are being queried.
    For example:

    -Tenant "38aad667-af54-4397-aaa7-e94c79ec2308"

    You can return your tenant ID by running this command:

    Get-CsTenant | Select-Object DisplayName, TenantID

    If you are using a remote session of Windows PowerShell and are connected only to Skype for Business Online you do not have to include the Tenant parameter.
    Instead, the tenant ID will automatically be filled in for you based on your connection information.
    The Tenant parameter is primarily for use in a hybrid deployment.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
applicable:
- Microsoft Teams
uid: MicrosoftTeamsPowerShell.Set-CsTeamsComplianceRecordingApplication
name: Set-CsTeamsComplianceRecordingApplication
description: |-
  Policy-based recording applications are used in automatic policy-based recording scenarios.
  When Microsoft Teams users participate in meetings or make or receive calls, the policy-based recording applications i.e. bots associated with the user's Teams recording policy are invited into the call or meeting to enforce compliance with the administrative set policy.

  Instances of these applications are created using CsOnlineApplicationInstance cmdlets and are then associated with Teams recording policies.

  Note that application instances of policy-based recording applications must be associated with a Teams recording policy using the CsTeamsComplianceRecordingApplication cmdlets.
  Once the association is done, the Identity of these application instances becomes \<Identity of the associated Teams recording policy\>/\<ObjectId of the application instance\>.
  For example, the Identity of an application instance can be \"Tag:ContosoPartnerComplianceRecordingPolicy/39dc3ede-c80e-4f19-9153-417a65a1f144\", which indicates that the application instance with ObjectId 39dc3ede-c80e-4f19-9153-417a65a1f144 is associated with the Teams recording policy with Identity ContosoPartnerComplianceRecordingPolicy.

  Please work with your Microsoft certified policy-based recording application provider to obtain an instance of their recording application.
  Please refer to the documentation of the CsOnlineApplicationInstance cmdlets for information on how to create an application instance of a policy-based recording application.
  Please also refer to the documentation of CsTeamsComplianceRecordingPolicy cmdlets for further information.
metadata:
  external help file: Microsoft.Rtc.Management.Hosted.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/teams/set-csteamscompliancerecordingapplication
  applicable: Microsoft Teams
  title: Set-CsTeamsComplianceRecordingApplication
  schema: 2.0.0
  manager: nakumar
  author: aditdalvi
  ms.author: aditd
  ms.reviewer: ""
