### YamlMime:PowershellCmdlet
summary: |-
  Note: This cmdlet is deprecated as of our 1.0 PowerShell release, and is not supported in our 1.0 release.  To set a Team's settings, run Set-Team.

  Updates team guest settings.
module: MicrosoftTeamsPowerShell
notes: ""
inputs:
- name: <xref href="GroupId" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="AllowCreateUpdateChannels" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="AllowDeleteChannels" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- Set-TeamGuestSettings -GroupId <String> [-AllowCreateUpdateChannels <String>] [-AllowDeleteChannels <String>]
examples:
- title: '--------------------------  Example 1  --------------------------'
  code: |-
    Set-TeamGuestSettings -GroupId a61f5a96-a0cf-43db-a7c8-cec05f8a8fc4 -AllowCreateUpdateChannels true
  description: ""
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AllowCreateUpdateChannels
  description: |+
    Settings to create and update channels

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AllowDeleteChannels
  description: |+
    Settings to Delete channels

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: GroupId
  isRequired: true
  description: |+
    GroupId of the team

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
applicable:
- Microsoft Teams
uid: MicrosoftTeamsPowerShell.Set-TeamGuestSettings
name: Set-TeamGuestSettings
description: ""
metadata:
  external help file: Microsoft.TeamsCmdlets.PowerShell.Custom.dll-Help.xml
  Module Name: MicrosoftTeams
  applicable: Microsoft Teams
  title: Set-TeamGuestSettings
  online version: https://learn.microsoft.com/powershell/module/teams/set-teamguestsettings
  schema: 2.0.0
  author: serdarsoysal
  ms.author: serdars
  ms.reviewer: ""
