### YamlMime:PowershellCmdlet
summary: |-
  This cmdlet is used to manage the organization-wide Teams SIP devices configuration.
module: MicrosoftTeamsPowerShell
links:
- text: Get-CsTeamsSipDevicesConfiguration
  href: Get-CsTeamsSipDevicesConfiguration.yml
syntaxes:
- >-
  Set-CsTeamsSipDevicesConfiguration

     [-BulkSignIn <String>]

     [-WhatIf]

     [-Confirm]

     [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    Set-CsTeamsSipDevicesConfiguration -BulkSignIn "Enabled"
  description: |-
    In this example, Bulk SignIn is set to Enabled across the organization.
  summary: ""
- title: Example 2
  code: |-
    Set-CsTeamsSipDevicesConfiguration -BulkSignIn "Disabled"
  description: |-
    In this example, Bulk SignIn is set to Disabled across the organization.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: BulkSignIn
  description: |+
    Indicates whether Bulk SingIn into Teams SIP devices is enabled or disabled for the common area phone (CAP) accounts across the organization. Possible values are **Enabled** and '**Disabled**.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: MicrosoftTeamsPowerShell.Set-CsTeamsSipDevicesConfiguration
name: Set-CsTeamsSipDevicesConfiguration
description: |-
  This cmdlet is used to manage the organization-wide Teams SIP devices configuration which contains settings that are applicable to SIP devices connected to Teams using Teams Sip Gateway.

  To execute the cmdlet, you need to hold a role within your organization such as Global Administrator, Teams Administrator, or Teams Communication Administrator.
metadata:
  external help file: Microsoft.TeamsCmdlets.PowerShell.Custom.dll-Help.xml
  Module Name: MicrosoftTeams
  title: Set-CsTeamsSipDevicesConfiguration
  author: anmandav
  ms.author: anmandav
  online version: https://learn.microsoft.com/powershell/module/teams/set-csteamssipdevicesconfiguration
  schema: 2.0.0
