### YamlMime:PowershellCmdlet
summary: |-
  Set-CsTeamsMeetingBroadcastConfiguration \[\[-Identity\] \<XdsIdentity\>\] \[-Tenant \<guid\>\] \[-SupportURL \<string\>\] \[-AllowSdnProviderForBroadcastMeeting \<bool\>\] \[-Force\] \[-WhatIf\] \[-Confirm\] \[\<CommonParameters\>\]

  Set-CsTeamsMeetingBroadcastConfiguration -SdnProviderName \<string\> -SdnApiTemplateUrl \<string\> \[-Tenant \<guid\>\] \[-SupportURL \<string\>\] \[-AllowSdnProviderForBroadcastMeeting \<bool\>\] \[-SdnLicenseId \<string\>\] \[-SdnApiToken \<string\>\] \[-Force\] \[-WhatIf\] \[-Confirm\] \[\<CommonParameters\>\]

  Set-CsTeamsMeetingBroadcastConfiguration \[-Tenant \<guid\>\] \[-SupportURL \<string\>\] \[-AllowSdnProviderForBroadcastMeeting \<bool\>\] \[-Instance \<psobject\>\] \[-Force\] \[-WhatIf\] \[-Confirm\] \[\<CommonParameters\>\]
module: MicrosoftTeamsPowerShell
notes: ""
inputs:
- name: <xref href="System.Management.Automation.PSObject" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Set-CsTeamsMeetingBroadcastConfiguration [-Tenant <Guid>] [-SupportURL <String>]

   [-AllowSdnProviderForBroadcastMeeting <Boolean>] [-SdnProviderName <String>] [-SdnLicenseId <String>]

   [-SdnApiTemplateUrl <String>] [-SdnApiToken <String>] [[-Identity] <XdsIdentity>] [-Force] [-WhatIf]

   [-Confirm] [<CommonParameters>]
- >-
  Set-CsTeamsMeetingBroadcastConfiguration [-Tenant <Guid>] [-SupportURL <String>]

   [-AllowSdnProviderForBroadcastMeeting <Boolean>] [-SdnProviderName <String>] [-SdnLicenseId <String>]

   [-SdnApiTemplateUrl <String>] [-SdnApiToken <String>] [-Instance <PSObject>] [-Force] [-WhatIf] [-Confirm]

   [<CommonParameters>]
parameters:
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AllowSdnProviderForBroadcastMeeting
  description: |+
    If set to $true,  Teams meeting broadcast streams are enabled to take advantage of the network and bandwidth management capabilities of your Software Defined Network (SDN) provider. 

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppress all non-fatal errors

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    You can only have one configuration - "Global"

  defaultValue: None
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="PSObject" data-throw-if-not-resolved="False" />
  name: Instance
  description: |+
    You can pass in the output from Get-CsTeamsMeetingBroadcastConfiguration as input to this cmdlet (instead of Identity)

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SdnApiTemplateUrl
  description: |+
    Specifies the Software Defined Network (SDN) provider's HTTP API endpoint. This information is provided to you by the SDN provider. This parameter is only required if AllowSdnProviderForBroadcastMeeting is set to $true. 

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SdnApiToken
  description: |+
    Specifies the Software Defined Network (SDN) provider's authentication token which is required to use their SDN license. This is required by some SDN providers who will give you the required token. This parameter is only required if AllowSdnProviderForBroadcastMeeting is set to $true. 

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SdnLicenseId
  description: |+
    Specifies the Software Defined Network (SDN) license identifier. This is required and provided by some SDN providers. This parameter is only required if AllowSdnProviderForBroadcastMeeting is set to $true. 

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SdnProviderName
  description: |+
    Specifies the Software Defined Network (SDN) provider's name. This parameter is only required if AllowSdnProviderForBroadcastMeeting is set to $true. 

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SupportURL
  description: |+
    Specifies a URL where broadcast event attendees can find support information or FAQs specific to that event. The URL will be displayed to the attendees during the broadcast. 

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Guid" data-throw-if-not-resolved="False" />
  name: Tenant
  description: |+
    Not applicable to online service.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
applicable:
- Microsoft Teams
uid: MicrosoftTeamsPowerShell.Set-CsTeamsMeetingBroadcastConfiguration
name: Set-CsTeamsMeetingBroadcastConfiguration
description: |-
  Tenant level configuration for broadcast events in Teams
metadata:
  external help file: Microsoft.Rtc.Management.Hosted.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/teams/set-csteamsmeetingbroadcastconfiguration
  applicable: Microsoft Teams
  title: Set-CsTeamsMeetingBroadcastConfiguration
  schema: 2.0.0
  manager: bulenteg
  author: tomkau
  ms.author: tomkau
  ms.reviewer: williamlooney
