### YamlMime:PowershellCmdlet
summary: |-
  Sets environment-specific configurations on the local machine and is used to connect to the right environment when running Connect-MicrosoftTeams.
module: MicrosoftTeamsPowerShell
notes: |-
  Set-TeamsEnvironmentConfig should not be used in Commercial, GCC, GCC High, or DoD environments.
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Set-TeamsEnvironmentConfig [-EndpointUris <Hashtable>] [-TeamsEnvironmentName <String>] [-WhatIf] [-Confirm]

   [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> Set-TeamsEnvironmentConfig -TeamsEnvironmentName TeamsChina
  description: |-
    Sets the environment as Gallatin China on a local machine and when Connect-MicrosoftTeams is run, authentication will happen in the Gallatin China cloud and Microsoft Teams module will connect to the Gallatin environment.
  summary: ""
- title: Example 2
  code: |-
    $endPointUriDict = @{ActiveDirectory = 'https://login.microsoftonline.us/';MsGraphEndpointResourceId = 'https://graph.microsoft.us'}
    Set-TeamsEnvironmentConfig -TeamsEnvironmentName $endPointUriDict
  description: |-
    Sets endpoint URIs required for special clouds.
  summary: ""
- title: Example 3
  code: |-
    Set-TeamsEnvironmentConfig -TeamsEnvironmentName TeamsChina

    $cred=get-credential
    Move-CsUser -Identity "PilarA@contoso.com" -Target "sipfed.online.lync.com" -Credential $cred
  description: "This cmdlet is mainly introduced to support Skype for Business to Microsoft Teams user migration using Move-CsUser. \r\n\r\nThis example shows how tenant admins can run Move-CsUser in Gallatin and other special clouds after setting the environment configuration using Set-TeamsEnvironmentConfig.\r\n \r\nNote that Set-TeamsEnvironmentConfig needs to be run only once for each machine. There is no need to run it each time before running Move-CsUser."
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="Hashtable" data-throw-if-not-resolved="False" />
  name: EndpointUris
  description: |+
    Provides custom endpoints.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: TeamsEnvironmentName
  description: |+
    Provides a Teams environment to connect to, for example, Teams GCCH or Teams DoD.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: MicrosoftTeamsPowerShell.Set-TeamsEnvironmentConfig
name: Set-TeamsEnvironmentConfig
description: "This cmdlet sets environment-specific configurations like endpoint URIs(such as Microsoft Entra ID and Microsoft Graph) and Teams environment (such as GCCH and DOD) on the local machine.\r\n  \r\nWhen running Connect-MicrosoftTeams, environment-specific information set in this cmdlet will be considered unless overridden by Connect-MicrosoftTeams parameters.\r\n\r\nParameters passed to Connect-MicrosoftTeams will take precedence over the information set by this cmdlet. \r\n\r\nClear-TeamsEnvironmentConfig should not be used in Commercial, GCC, GCC High, or DoD environments."
metadata:
  external help file: Microsoft.TeamsCmdlets.PowerShell.Connect.dll-Help.xml
  Module Name: MicrosoftTeams
  online version: ""
  schema: 2.0.0
  author: VikneshMSFT
  ms.author: vimohan
  ms.reviewer: pbafna
  manager: vinelap
