### YamlMime:PowershellCmdlet
summary: |-
  Modifies an existing application access policy.
module: MicrosoftTeamsPowerShell
notes: ""
links:
- text: New-CsApplicationAccessPolicy
  href: New-CsApplicationAccessPolicy.yml
- text: Grant-CsApplicationAccessPolicy
  href: Grant-CsApplicationAccessPolicy.yml
- text: Get-CsApplicationAccessPolicy
  href: Get-CsApplicationAccessPolicy.yml
- text: Remove-CsApplicationAccessPolicy
  href: Remove-CsApplicationAccessPolicy.yml
syntaxes:
- Set-CsApplicationAccessPolicy [-Identity <XdsIdentity>] [-AppIds <PSListModifier>]
examples:
- title: Add new app ID to the policy
  code: |-
    PS C:\> Set-CsApplicationAccessPolicy -Identity "ASimplePolicy" -AppIds @{Add="5817674c-81d9-4adb-bfb2-8f6a442e4622"}
  description: |-
    The command shown above adds a new app ID "5817674c-81d9-4adb-bfb2-8f6a442e4622" to the per-user application access policy ASimplePolicy.
  summary: ""
- title: Remove app IDs from the policy
  code: |-
    PS C:\> Set-CsApplicationAccessPolicy -Identity "ASimplePolicy" -AppIds @{Remove="5817674c-81d9-4adb-bfb2-8f6a442e4622"}
  description: |-
    The command shown above removes the app ID "5817674c-81d9-4adb-bfb2-8f6a442e4622" from the per-user application access policy ASimplePolicy.
  summary: ""
parameters:
- type: <xref href="PSListModifier" data-throw-if-not-resolved="False" />
  name: AppIds
  description: |+
    A list of application (client) IDs. For details of application (client) ID, refer to: [Get tenant and app ID values for signing in](https://learn.microsoft.com/azure/active-directory/develop/howto-create-service-principal-portal#get-tenant-and-app-id-values-for-signing-in).

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Unique identifier assigned to the policy when it was created.

  defaultValue: None
  position: "1"
  aliases: ""
  parameterValueGroup: ""
applicable:
- Microsoft Teams
uid: MicrosoftTeamsPowerShell.Set-CsApplicationAccessPolicy
name: Set-CsApplicationAccessPolicy
description: |-
  This cmdlet modifies an existing application access policy.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/teams/set-csapplicationaccesspolicy
  applicable: Microsoft Teams
  title: Set-CsApplicationAccessPolicy
  schema: 2.0.0
  manager: zhengni
  author: frankpeng7
  ms.author: frpeng
  ms.reviewer: ""
