name: (Scheduled) Publish to live

permissions:
  contents: write
  pull-requests: write
  checks: read

on:
  schedule:
    - cron: "25 2,5,8,11,14,17,20,22 * * *" # Times are UTC based on Daylight Saving Time (~Mar-Nov). Scheduling at :25 to account for queuing lag.
    # - cron: "25 3,6,9,12,15,18,21,23 * * *" # Times are UTC based on Standard Time (~Nov-Mar). Scheduling at :25 to account for queuing lag.

  workflow_dispatch:

jobs:

  config:
    if: github.repository_owner == 'MicrosoftDocs' && contains(github.event.repository.topics, 'build')
    runs-on: ubuntu-latest
    outputs:
      EnableAutoPublish: ${{ steps.read.outputs.EnableAutoPublish }}
      EnableAutoMerge: ${{ steps.read.outputs.EnableAutoMerge }}
    steps:
      - uses: actions/checkout@v5
        with:
          sparse-checkout: .github/workflow-config.json
          sparse-checkout-cone-mode: false
      - id: read
        shell: pwsh
        run: |
          $Config = (Get-Content '.github/workflow-config.json' | ConvertFrom-Json).AutoPublish
          "EnableAutoPublish=$("$($Config.EnableAutoPublish)".ToLower())" >> $Env:GITHUB_OUTPUT
          "EnableAutoMerge=$("$($Config.EnableAutoMerge)".ToLower())" >> $Env:GITHUB_OUTPUT

  auto-publish:
    if: github.repository_owner == 'MicrosoftDocs' && contains(github.event.repository.topics, 'build')
    needs: config
    uses: MicrosoftDocs/tcp-workflows/.github/workflows/Shared-AutoPublishV2.yml@workflows-prod
    with:
        PayloadJson: ${{ toJSON(github) }}
        EnableAutoPublish: ${{ fromJSON(needs.config.outputs.EnableAutoPublish) }}
        EnableAutoMerge: ${{ fromJSON(needs.config.outputs.EnableAutoMerge) }}
    secrets:
        AccessToken: ${{ secrets.GITHUB_TOKEN }}
        PrivateKey: ${{ secrets.M365_APP_PRIVATE_KEY }}
        ClientId: ${{ secrets.M365_APP_CLIENT_ID }}
